
// TOMB

export const tomb_adjective = [
    ['Empty', [], 1],
    ['False', [], 1],
    ['Burial', [], 1],
    ['Haunted', [], 1],
    ['Trapped', [], 1],
    ['Ceremonial', [], 1],
    ['Entry', [], 1],
    ['Sealed', [], 1],
    ['Upper', [], 1],
    ['Lower', [], 1],
];

export const tomb_objects = [
    ['Sepulcher', [], 1],
    ['Bone', [], 1],
    ['Skeleton', [], 1],
    ['Darkness', [], 1],
    ['Skull', [], 1],
    ['Remains', [], 1],
    ['Offering', [], 1],
    ['Armored Skeleton', [], 1],
    ['Buried Treasure', [], 1],
    ['Sleeping Kings', [], 1],
    ['Sarcophagus', [], 1],
    ['Pit', [], 1],
];

export const tomb_possessive = [
    ['Ghoul', [], 1],
    ['Spectre', [], 1],
];

// TEMPLE

export const temple_adjective = [
    ['Waiting', [], 1],
    ['Violet', [], 1],
    ['Torture', [], 1],
    ['Terraced', [], 1],
    ['Tapestry', [], 1],
    ['Storage', [], 1],
    ['Robing', [], 1],
    ['Reception', [], 1],
    ['Pillared', [], 1],
    ['Meditation', [], 1],
    ['Marble', [], 1],
    ['Large', [], 1],
    ['Inner', [], 1],
    ['Outer', [], 1],
    ['Vaulted', [], 1],
    ['Divination', [], 1],
    ['Domed', [], 1],
    ['Augury', [], 1],
    ['Audience', [], 1],
    ['Arched', [], 1],
    ['Abandoned', [], 1],
    ['Columned', [], 1],
    ['Ancestral', [], 1],
    ['Processional', [], 1],
];

export const temple_objects = [
    ['Ziggarut', [], 1],
    ['Wine', [], 1],
    ['Treasure', [], 1],
    ['Stupa', [], 1],
    ['Statueary', [], 1],
    ['Statue', [], 1],
    ['Pyramid', [], 1],
    ['Pool', [], 1],
    ['Pipe Organ', [], 1],
    ['Obelisk', [], 1],
    ['Incense', [], 1],
    ['Idol', [], 1],
    ['Mosaic', [], 1],
    ['Dome', [], 1],
    ['Dolmen', [], 1],
    ['Distillary', [], 1],
    ['Silver Chains', [], 1],
    ['Candle', [], 1],
    ['Arch', [], 1],
    ['Alter', [], 1],
    ['Hundred Candles', [], 1],
];

export const temple_possessive = [
    ['Special Guest', [], 1],
    ['Guest', [], 1],
    ['Shamen', [], 1],
    ['Scribe', [], 1],
    ['Priest', [], 1],
    ['Gargoyle', [], 1],
    ['Adept', [], 1],
    ['Acolyte', [], 1],
];

export const temple_special_rooms = [
    ['Vestibule', [], 1],
    ['Vestry', [], 1],
    ['Sanctuary', [], 1],
    ['Shrine', [], 1],
    ['Refectory', [], 1],
    ['Promenade', [], 1],
    ['Transept', [], 1],
    ['Offeratorium', [], 1],
    ['Office', [], 1],
    ['Oratorium', [], 1],
    ['Pavillion', [], 1],
    ['Nave', [], 1],
    ['Court', [], 1],
    ['Library', [], 1],
    ['Hall', [], 1],
    ['Sanctum', [], 1],
    ['Herbarium', [], 1],
    ['Foyer', [], 1],
    ['Chantry', [], 1],
    ['Choir Loft', [], 1],
    ['Balcony', [], 1],
    ['Beastiary', [], 1],
    ['Archives', [], 1],
    ['Annex', [], 1],
    ['Antechamber', [], 1],
    ['Apse', [], 1],
    ['Arcade (of Pillars)', [], 1],
    ['Alcove', [], 1],
    ['Cloister', [], 1],
    ['Chapel', [], 1],
];

// CAVERNS


export const cavern_possessive = [
    ['Ant', [], 1],
    ['Bat', [], 1],
    ['Bear', [], 1],
    ['Carrion Crawlers', [], 1],
    ['Minotaur', [], 1],
    ['Spider', [], 1],
    ['Devil', [], 1],
    ['Hobgoblin', [], 1],
    ['Hydra', [], 1],
    ['Ogre', [], 1],
    ['Piercer', [], 1],
    ['Special Visitor', [], 1],
    ['Stirge', [], 1],
    ['Troglodyte', [], 1],
    ['Troll', [], 1],
];

export const cavern_materials = [
    ['Coral', [], 1],
    ['Algae', [], 1],
    ['Basalt', [], 1],
    ['Bone', [], 1],
    ['Carnelian', [], 1],
    ['Clay', [], 1],
    ['Crystal', [], 1],
    ['Ice', [], 1],
    ['Flowstone', [], 1],
    ['Fungus', [], 1],
    ['Gypsum', [], 1],
    ['Sand', [], 1],
    ['Slate', [], 1],
    ['Steam', [], 1],
    ['Water', [], 1],
];

export const cavern_objects = [
    ['Minaret', [], 1],
    ['Waterfall', [], 1],
    ['Spring', [], 1],
    ['Bridge', [], 1],
    ['Artifact', [], 1],
    ['Bone', [], 1],
    ['Boulder', [], 1],
    ['Many Candles', [], 1],
    ['Glowing Skull', [], 1],
    ['Skull', [], 1],
    ['Corpse', [], 1],
    ['Cave Pearl', [], 1],
    ['Coffin', [], 1],
    ['Crystal', [], 1],
    ['Distillery', [], 1],
    ['Engraving', [], 1],
    ['Formation', [], 1],
    ['Gem', [], 1],
    ['Demon Idol', [], 1],
    ['Magic Pool', [], 1],
    ['Moat', [], 1],
    ['Pit', [], 1],
    ['Pool', [], 1],
    ['Ice Cube', [], 1],
    ['Rune', [], 1],
    ['Sewer', [], 1],
    ['Sinkhole', [], 1],
    ['Stream', [], 1],
    ['Trapdoor', [], 1],
    ['Volcano', [], 1],
    ['Weapon', [], 1],
];

export const cavern_adjective = [
    ['Winding', [], 1],
    ['Wide', [], 1],
    ['Wet', [], 1],
    ['Water Filled', [], 1],
    ['Upper', [], 1],
    ['Splendid', [], 1],
    ['Narrow', [], 1],
    ['Monotonous', [], 1],
    ['Lower', [], 1],
    ['Inclined', [], 1],
    ['Gothic', [], 1],
    ['Forgotten', [], 1],
    ['Dark', [], 1],
    ['Collapsed', [], 1],
    ['Grinding', [], 1],
    ['Dripping', [], 1],
    ['Frostwork', [], 1],
    ['Arched', [], 1],
    ['Attic', [], 1],
    ['Blast', [], 1],
    ['Blue Sky', [], 1],
    ['Blue Velvet', [], 1],
    ['Burrowed', [], 1],
    ['Cascade', [], 1],
    ['Cathedral', [], 1],
    ['Charred and Burned', [], 1],
    ['Communal', [], 1],
    ['Damp', [], 1],
    ['Deserted', [], 1],
    ['Dismal', [], 1],
    ['Secret', [], 1],
    ['Deep', [], 1],
    ['Domed', [], 1],
    ['Vaulted', [], 1],
    ['Dry', [], 1],
    ['Empty', [], 1],
    ['Engraved', [], 1],
    ['Entry', [], 1],
    ['Exit', [], 1],
    ['Fire', [], 1],
    ['Flooding', [], 1],
    ['Frescoed', [], 1],
    ['Glittering', [], 1],
    ['Glowing', [], 1],
    ['Grey', [], 1],
    ['Guard', [], 1],
    ['Hidden', [], 1],
    ['Huge', [], 1],
    ['Vast', [], 1],
    ['Infernal', [], 1],
    ['Irregular', [], 1],
    ['Jagged', [], 1],
    ['Jeweled', [], 1],
    ['Littered', [], 1],
    ['Long', [], 1],
    ['Low Cieling', [], 1],
    ['Misty', [], 1],
    ['Mouning', [], 1],
    ['Mudslide', [], 1],
    ['Narrow', [], 1],
    ['Pillared', [], 1],
    ['Rotunda', [], 1],
    ['Scar', [], 1],
    ['Sealed', [], 1],
    ['Shattered', [], 1],
    ['Side', [], 1],
    ['Singing', [], 1],
    ['Slippery', [], 1],
    ['Small', [], 1],
    ['Smoke Filled', [], 1],
    ['Smooth', [], 1],
    ['Spur', [], 1],
    ['Statueary', [], 1],
    ['Stinking', [], 1],
    ['Storage', [], 1],
    ['Streaked', [], 1],
    ['Sunken', [], 1],
    ['Terraced', [], 1],
    ['Wind', [], 1],
    ['Wishbone', [], 1],
];

export const cavern_abstract = [
    ['Fatique', [], 1],
];

export const cavern_special_rooms = [
    ['Culvert', [], 1],
    ['Catacombs', [], 1],
    ['Rift', [], 1],
    ['Labyrinth', [], 1],
    ['Crawlway', [], 1],
    ['Corkscrew', [], 1],
    ['Alcove', [], 1],
    ['Antecavern', [], 1],
    ['Barrow', [], 1],
    ['Cavity', [], 1],
    ['Chasm', [], 1],
    ['Crevasse', [], 1],
    ['Hollow', [], 1],
    ['Grotto', [], 1],
    ['Loft', [], 1],
    ['Attic', [], 1],
    ['Cellar', [], 1],
    ['Balcony', [], 1],
    ['Ballroom', [], 1],
    ['Ravine', [], 1],
    ['Sewers', [], 1],
    ['Gallery', [], 1],
];

export const cavern_room_unique = [
    //"Yellow Brick Road', [], 1],
    ['The Button Hole', [], 1],
    ['Rathole', [], 1],
    ['Escape Tunnel', [], 1],
    ['Exhaust Pipe', [], 1],
    ['Borehole', [], 1],
    ['Belfry', [], 1],
    ['Chandelier Ballroom', [], 1],
    ['Natural Bridge', [], 1],
    ['Virgin Forest', [], 1],
    ['Ammonia Cave (Bat Colony)', [], 1],
    ['Boneyard', [], 1],
    ['Boulder Choke', [], 1],
    ['Boulder Heap', [], 1],
    ['Cave Warrens', [], 1],
    ['Cavern Barracks', [], 1],
    ['Cavern Hall', [], 1],
    ['Cave Chamber', [], 1],
    ['Cavern Temple', [], 1],
    ['Coral Grove', [], 1],
    ['Crystal Gardens', [], 1],
    ['Crystal Grotto', [], 1],
    ['Crystal Pool', [], 1],
    ['Death Valley', [], 1],
    ['Deep Sea Room', [], 1],
    ['Deep Secrets', [], 1],
    ['Devils Ice Box', [], 1],
    ['Dismal Hollow', [], 1],
    ['Eastern Eerie', [], 1],
    ['Elfin Forest', [], 1],
    ['Fairy Grotto', [], 1],
    ['Firecaverns', [], 1],
    ['Ghost Town', [], 1],
    ['Giants Hallway', [], 1],
    ['Glacier Way', [], 1],
    ['Grand Entry', [], 1],
    ['Great Beyond', [], 1],
    ['Helictite Hall', [], 1],
    ['Hidden Loft', [], 1],
    ['Infernal Regions', [], 1],
    ['Jungle Room', [], 1],
    ['Kennel Cave', [], 1],
    ['Kitchen Cave', [], 1],
    ['Land of Awes', [], 1],
    ['Lava Pool', [], 1],
    ['Lost Wax Room', [], 1],
    ['Lost World Cave', [], 1],
    ['Menagerie', [], 1],
    ['Mummys Niche', [], 1],
    ['Nirvana', [], 1],
    ['North Rift', [], 1],
    ['Oasis', [], 1],
    ['Prison Cave', [], 1],
    ['Rainbow Cavern', [], 1],
    ['Seleotherm Gallery', [], 1],
    ['South Rift', [], 1],
    ['Spillway', [], 1],
    ['Stalagmite Forest', [], 1],
    ['Storm Shelter', [], 1],
    ['Stream Crossing', [], 1],
    ['Stream View', [], 1],
    ['Whales Stomach', [], 1],
];


export const cavern_water_special_rooms = [
    ['Waterfall', [], 1],
    ['Spring', [], 1],
    ['Falls', [], 1],
];

export const cavern_water_unique = [
    ['Underground River', [], 1],
    ['Echo River', [], 1],
    ['Boulder Falls', [], 1],
    ['Noisy Water Cave', [], 1],
    ['Bridal Veil Falls', [], 1],
    ['Underground Lake', [], 1],
    ['Underground Reservoir', [], 1],
    ['Lake of the Blue Giants', [], 1],
    ['Lake of the Lost Marbles', [], 1],
    ['Lake Purity', [], 1],
    ['Oasis Pool', [], 1],
    ['Pearlsian Gulf', [], 1],
    ['Rimstone Pool', [], 1],
    ['Sulfur Pool', [], 1],
    ['Sump', [], 1],
    ['Epsom Salts', [], 1],
    ['Glacier Bay', [], 1],
    ['Acid Lake Basin', [], 1],
    ['Bitter Water Pool', [], 1],
];

export const cavern_formation_unique = [
    ['The Leaning Tower', [], 1],
    ['The Marble Temple', [], 1],
    ['Wizards Staff', [], 1],
    ['The Giants Coffin', [], 1],
    ['Emperors Throne"', [], 1],
];

export const cavern_pit_unique = [
    ['The Commode', [], 1],
    ['Blowholes', [], 1],
    ['Dragon Pit', [], 1],
    ['Dry Cistern', [], 1],
    ['Esophagus', [], 1],
    ['Lava Tube', [], 1],
    ['Shower Shaft', [], 1],
    ['Slippery Chimney', [], 1],
    ['The Chimneys', [], 1],
    ['Vent Shaft', [], 1],
    ['Well Cave', [], 1],
];

// DUNGEON


export const dungeon_possessive = [
    ['Minstrel', [], 1],
    ['Halfling', [], 1],
    ['Dead Man', [], 1],
    ['Troll', [], 1],
    ['Servant', [], 1],
    ['Maid', [], 1],
    ['Lord', [], 1],
    ['Guardian', [], 1],
    ['Giant', [], 1],
    ['Dragon', [], 1],
    ['Cook', [], 1],
    ['Archer', [], 1],
];

export const dungeon_materials = [
    ['Teak', [], 1],
    ['Cedar', [], 1],
    ['Red Marble', [], 1],
    ['Sand', [], 1],
    ['Steam', [], 1],
    ['Moss', [], 1],
    ['Lava', [], 1],
    ['Ice', [], 1],
    ['Granite', [], 1],
    ['Geode', [], 1],
    ['Dust', [], 1],
    ['Coal', [], 1],
    ['Amber', [], 1],
];

export const dungeon_objects = [
    ['Well', [], 1],
    ['Hot Spring', [], 1],
    ['Mud Pit', [], 1],
    ['Vaulted Skylight', [], 1],
    ['Sparkling Stone', [], 1],
    ['Boiler', [], 1],
    ['Spyhole', [], 1],
    ['Pit', [], 1],
    ['Rat', [], 1],
    ['Antler', [], 1],
    ['Winch', [], 1],
    ['Weapon', [], 1],
    ['Waterfall', [], 1],
    ['Sword', [], 1],
    ['Valve', [], 1],
    ['Trophy', [], 1],
    ['Treasure', [], 1],
    ['Trap', [], 1],
    ['Torch', [], 1],
    ['Time Machine', [], 1],
    ['Throne', [], 1],
    ['Slippery Floor', [], 1],
    ['Rope', [], 1],
    ['Crowned Skull', [], 1],
    ['Refuse', [], 1],
    ['Quicksand', [], 1],
    ['Pump', [], 1],
    ['Provisions', [], 1],
    ['Pottery', [], 1],
    ['Moat', [], 1],
    ['Lodestone', [], 1],
    ['Ladder', [], 1],
    ['Junk', [], 1],
    ['Black Helm', [], 1],
    ['Garbage', [], 1],
    ['Crossbow', [], 1],
    ['Fountain', [], 1],
    ['Cube', [], 1],
    ['Compass Rose', [], 1],
    ['Cobweb', [], 1],
    ['Stone Head', [], 1],
    ['Barrel', [], 1],
    ['Ballistae', [], 1],
    ['Arsenal', [], 1],
    ['Water Clock', [], 1],
];

export const dungeon_adjective = [
    ['Sewage', [], 1],
    ['Sundered', [], 1],
    ['Greased', [], 1],
    ['Muttering', [], 1],
    ['Unfinished', [], 1],
    ['Training', [], 1],
    ['Toll', [], 1],
    ['Timber', [], 1],
    ['Theives', [], 1],
    ['Secret', [], 1],
    ['Rubble-Filled', [], 1],
    ['Round', [], 1],
    ['Rough Hewn', [], 1],
    ['Polished', [], 1],
    ['Partially Collapsed', [], 1],
    ['Padlocked', [], 1],
    ['Mud-Filled', [], 1],
    ['Mouning', [], 1],
    ['Opulent', [], 1],
    ['Odd-Angled', [], 1],
    ['Misty', [], 1],
    ['Meeting', [], 1],
    ['Maintenance', [], 1],
    ['Loud', [], 1],
    ['Locked', [], 1],
    ['Littered', [], 1],
    ['Jumbled', [], 1],
    ['Inky', [], 1],
    ['Echo', [], 1],
    ['Guard', [], 1],
    ['Grim', [], 1],
    ['Grand', [], 1],
    ['Forsaken', [], 1],
    ['Forgotten', [], 1],
    ['Foggy', [], 1],
    ['Flooding', [], 1],
    ['Empty', [], 1],
    ['Earth-floored', [], 1],
    ['Dusty and Moldy', [], 1],
    ['Dusty', [], 1],
    ['Moldy', [], 1],
    ['Drainage', [], 1],
    ['Deserted', [], 1],
    ['Damp', [], 1],
    ['Cool', [], 1],
    ['Common', [], 1],
    ['Collapsed', [], 1],
    ['Bricked Up', [], 1],
    ['Boarded Up', [], 1],
    ['Bloodstained', [], 1],
    ['Barred', [], 1],
    ['Banquet', [], 1],
    ['Audience', [], 1],
    ['Arched', [], 1],
];

export const dungeon_abstract = [
    ['Merriment', [], 1],
    ['Echoes', [], 1],
];

export const dungeon_special_rooms = [
    ['Oubliette', [], 1],
    ['Maze', [], 1],
    ['Cove', [], 1],
    ['Cistern', [], 1],
    ['Smithy', [], 1],
    ['Forge', [], 1],
    ['Wellroom', [], 1],
    ['Storeroom', [], 1],
    ['Ballroom', [], 1],
    ['Bedchamber', [], 1],
    ['Compartment', [], 1],
    ['Prison', [], 1],
    ['Pantry', [], 1],
    ['Nusery', [], 1],
    ['Elevator', [], 1],
    ['Arena', [], 1],
    ['Armory', [], 1],
    ['Kennels', [], 1],
    ['Niche', [], 1],
    ['Dormitory', [], 1],
    ['Recess', [], 1],
    ['Scullery (Dish Washing Room)', [], 1],
    ['Latrine', [], 1],
    ['Kitchen', [], 1],
    ['Coliseum', [], 1],
    ['Cellar', [], 1],
    ['Cesspool', [], 1],
    ['Closet', [], 1],
    ['Barracks', [], 1],
    ['Barroom', [], 1],
    ['Bank', [], 1],
    ['Aquaduct', [], 1],
    ['Snuggery', [], 1],
];

export const dungeon_unique = [
    ['Tight Squeeze', [], 1],
    ['Vent Shaft', [], 1],
    ['Swill Pit', [], 1],
    ['Mine Shaft', [], 1],
    ['Tool Shed', [], 1],
    ['Strong Room', [], 1],
    ['Boat Dock (Row Boat)', [], 1],
    ['Slippery Slide', [], 1],
    ['Shooting Gallery', [], 1],
    ['Dressing Room', [], 1],
    ['Dining Room', [], 1],
    ['Living Room', [], 1],
    ['Root Cellar', [], 1],
    ['Nusery Room', [], 1],
    ['Gas Chamber', [], 1],
    ['Food Storage', [], 1],
    ['Fuel Storage', [], 1],
    ['Oaken Cabinet', [], 1],
    ['Bridal Chamber', [], 1],
    ['Firing Range', [], 1],
    ['Linen Closet', [], 1],
    ['Harem/Seraglio', [], 1],
    ['Underground Bridge', [], 1],
];

// DUNGEON BRIDGE

export const dungeon_bridge_adjective = [
    ['Collapsing', [], 1],
    ['Rope', [], 1],
    ['Rotting', [], 1],
    ['Stone', [], 1],
];

// DUNGEON CORRIDOR

export const dungeon_corridor_adjective = [
    ['Blocked', [], 1],
    ['Cobweb', [], 1],
    ['Collapsed', [], 1],
    ['Crooked', [], 1],
    ['Flooded', [], 1],
    ['Junction', [], 1],
    ['Plain', [], 1],
    ['Round', [], 1],
    ['Royal', [], 1],
    ['Trapped', [], 1],
    ['Verdigris', [], 1],
];

// DUNGEON PORTAL

export const dungeon_portal_adjective = [
    ['Great Iron', [], 1],
    ['Heavy Barred', [], 1],
    ['Reinforced', [], 1],
    ['Secret', [], 1],
    ['One-way', [], 1],
    ['Metal', [], 1],
    ['Stone', [], 1],
    ['Circular', [], 1],
    ['False', [], 1],
    ['Double', [], 1],
    ['Revolving', [], 1],
];

export const cavern_portal_special_rooms = [
    ['Keyhole', [], 1],
];

// DUNGEON STAIRWAY

export const dungeon_stairway_adjective = [
    ['Main', [], 1],
    ['Marble', [], 1],
    ['Moving', [], 1],
    ['Ruined', [], 1],
    ['Sinister', [], 1],
    ['Trapped', [], 1],
];

// DUNGEON PIT

export const dungeon_pit_adjective = [
    ['Circular', [], 1],
    ['Drainage', [], 1],
    ['Locking', [], 1],
    ['Flooding', [], 1],
    ['Spiked', [], 1],
    ['Spear', [], 1],
    ['Poison Spike', [], 1],
    ['Teleporting', [], 1],
    ['Crossbow', [], 1],
    ['Slime', [], 1],
    ['Gas', [], 1],
    ['Water Filled', [], 1],
    ['Acid', [], 1],
    ['Sulfur', [], 1],
    ['Rat', [], 1],
    ['Snake', [], 1],
];

// MAGICAL

export const magical_unique = [
    ['Underground Garden', [], 1],
    ['Treasure Vault', [], 1],
    ['Wind Tunnel', [], 1],
    ['Storage Space', [], 1],
    ['Scenic Vista', [], 1],
    ['Fish Tank', [], 1],
    ['Echo Chamber', [], 1],
    ['Game Room', [], 1],
    ['Display Room', [], 1],
    ['Control Room', [], 1],
    ['Cloak Room', [], 1],
    ['Classroom', [], 1],
    ['Card Room', [], 1],
    ['Beam Room', [], 1],
    ['Council Chamber', [], 1],
    ['Curtain of Beads', [], 1],
    ['Art Studio', [], 1],
];

export const magical_materials = [
    ['Jade', [], 1],
    ['Glass', [], 1],
    ['Crystal', [], 1],
    ['Marble and Gold', [], 1],
    ['Mist', [], 1],
    ['Mithril', [], 1],
];

export const magical_objects = [
    ['Floating Bones', [], 1],
    ['Treasure', [], 1],
    ['Fountain', [], 1],
    ['Throne', [], 1],
    ['Tea', [], 1],
    ['Star', [], 1],
    ['Sphere', [], 1],
    ['Scroll', [], 1],
    ['Spell', [], 1],
    ['Rosette', [], 1],
    ['Green Glow', [], 1],
    ['Deadly Marble', [], 1],
    ['Red Carpet', [], 1],
    ['Puzzle', [], 1],
    ['Prism', [], 1],
    ['Pillar', [], 1],
    ['Pentacle', [], 1],
    ['Pearl', [], 1],
    ['Mushroom', [], 1],
    ['Mosaic', [], 1],
    ['Mirror', [], 1],
    ['Menhir', [], 1],
    ['Magic Mouth', [], 1],
    ['Machine', [], 1],
    ['Lantern', [], 1],
    ['Key', [], 1],
    ['Jewelry', [], 1],
    ['Illusion', [], 1],
    ['Mirror', [], 1],
    ['Floating Hat', [], 1],
    ['Grim Statue', [], 1],
    ['Gem', [], 1],
    ['Gargoyle', [], 1],
    ['Talking Painting', [], 1],
    ['Shield', [], 1],
    ['Painting', [], 1],
    ['Living Sculpture', [], 1],
    ['Fungus', [], 1],
    ['Fresco', [], 1],
    ['Engraving', [], 1],
    ['Echo', [], 1],
    ['Egg', [], 1],
    ['Dome', [], 1],
    ['Pedestal', [], 1],
    ['Compass', [], 1],
    ['Collection', [], 1],
    ['Clock', [], 1],
    ['Cloak', [], 1],
    ['Talking Skull', [], 1],
    ['Floating Corpse', [], 1],
    ['Dancing Swords', [], 1],
    ['Sword', [], 1],
    ['Potion', [], 1],
    ['Portal', [], 1],
    ['Pool', [], 1],
    ['Map', [], 1],
    ['Lever', [], 1],
    ['Floating Skull', [], 1],
    ['Eye', [], 1],
    ['Chest', [], 1],
    ['Cauldron', [], 1],
    ['Balloon', [], 1],
    ['Cage', [], 1],
    ['Artifact', [], 1],
    ['Armor', [], 1],
    ['Abacus', [], 1],
    ['Floating Candles', [], 1],
    ['Guardian', [], 1],
];

export const magical_adjective = [
    ['Wondrous', [], 1],
    ['Weird', [], 1],
    ['Viewing', [], 1],
    ['Tiny', [], 1],
    ['Terraced', [], 1],
    ['Teleportation', [], 1],
    ['Sunken', [], 1],
    ['Summoning', [], 1],
    ['Striated', [], 1],
    ['Storage', [], 1],
    ['Stasis', [], 1],
    ['Spinning', [], 1],
    ['Smoking', [], 1],
    ['Secret', [], 1],
    ['Scrying', [], 1],
    ['Reflecting', [], 1],
    ['Radiation', [], 1],
    ['Pleasure', [], 1],
    ['Pearlescent', [], 1],
    ['Opulent', [], 1],
    ['Luxurious', [], 1],
    ['Locked', [], 1],
    ['Lavish', [], 1],
    ['Inner', [], 1],
    ['Elemental', [], 1],
    ['Domed', [], 1],
    ['Conjuring', [], 1],
    ['Carousel', [], 1],
    ['Billiards', [], 1],
    ['Purple', [], 1],
    ['Muraled', [], 1],
    ['Glowing', [], 1],
];

export const magical_abstract = [
    ['Distortion', [], 1],
    ['Eternal Returns', [], 1],
];

export const magical_possessive = [
    ['Wizard', [], 1],
    ['Sorceror', [], 1],
    ['Apprentice', [], 1],
    ['Alchemist', [], 1],
    ['Advisor', [], 1],
];

export const magical_special_rooms = [
    ['Salon', [], 1],
    ['Registary', [], 1],
    ['Privy', [], 1],
    ['Planetarium', [], 1],
    ['Museum', [], 1],
    ['Menagerie', [], 1],
    ['Lounge', [], 1],
    ['Librarium', [], 1],
    ['Laboratory', [], 1],
    ['Workroom', [], 1],
    ['Sphere', [], 1],
    ['Greenhouse', [], 1],
    ['Cubicle', [], 1],
    ['Closet', [], 1],
    ['Gallery', [], 1],
    ['Aviary', [], 1],
    ['Atrium', [], 1],
    ['Maze', [], 1],
    ['Beastiary', [], 1],
];


