import { Gender, SocialClass, Alignment } from './Character';
import { TaggedItem } from '../shared/types';

export const { Male, Female, Neutral } = Gender
export const gender = [...Object.values(Gender)]

export const {
  Servant,
  Labor,
  Merchant,
  Artisan,
  Elite,
  Military,
  Ecclesiastical,
  Royal,
  Criminal,
  Administration
  // Academic
  // Magical
} = SocialClass

// export const socialClass = [...Object.values(SocialClass)]
export const socialClass: TaggedItem[] = [
  [Servant, [], 2],
  [Labor, [], 3],
  [Merchant, [], 3],
  [Artisan, [], 1],
  [Elite, [], 1],
  [Military, [], 2],
  [Ecclesiastical, [], 1],
  [Royal, [], 1],
  [Criminal, [], 3],
  [Administration, [], 2],
]

export const alignment = [...Object.values(Alignment)]

export const ageTuple: TaggedItem[] = [
  ['Child', [], 1],
  ['Adolescent', [], 2],
  ['Young adult', [], 2],
  ['Middle-aged', [], 3],
  ['Aged', [], 2],
  ['Elderly', [], 1],
  ['Ancient', [], 1]
]

export const wealthTuple: TaggedItem[] = [
  ['Destitute', [], 1],
  ['in debt', [], 2],
  ['Impoverished', [], 3],
  ['Working class', [], 3],
  ['Middle class', [], 2],
  ['Prosperous', [], 1],
  ['Decadent', [], 1]
]

export const flawTuple: TaggedItem[] = [
  ['Arrogance', [], 1],
  ['Drunkenness', [], 1],
  ['Paranoia', [], 1],
  ['Gluttony', [], 1],
  ['Sloth', [], 1],
  ['Cruelty', [], 1],
  ['Cowardice', [], 1],
  ['Wrath', [], 1],
  ['Greed', [], 1],
  ['Lust', [], 1],
]

export const titleTuple: TaggedItem[] = [
  ['Master', [Neutral, Artisan], 1],
  ['Apprentice', [Neutral, Artisan], 1],
  ['Chamberlain', [Neutral, Royal], 1],
  ['Sheriff', [Neutral, Royal], 1],
  ['Alderman', [Neutral, Royal], 1],
  ['Lord Mayor', [Neutral, Royal], 1],
  ['Burgomaster', [Neutral, Royal], 1],
  ['Chancellor', [Neutral, Royal], 1],
  ['Governor', [Neutral, Royal], 1],
  ['Minister', [Neutral, Royal], 1],
  ['Magistrate', [Neutral, Royal], 1],
  ['Bishop', [Neutral, Ecclesiastical], 1],
  ['Curate', [Neutral, Ecclesiastical], 1],
  ['Vicar', [Male, Ecclesiastical], 1],
  ['Brother', [Male, Ecclesiastical], 1],
  ['Abbot', [Male, Ecclesiastical], 1],
  ['Prior', [Male, Ecclesiastical], 1],
  ['Friar', [Male, Ecclesiastical], 1],
  ['Lord', [Male, Royal], 1],
  ['King', [Male, Royal], 1],
  ['Prince', [Male, Royal], 1],
  ['Duke', [Male, Royal], 1],
  ['Marquis', [Male, Royal], 1],
  ['Earl/Count', [Male, Royal], 1],
  ['Baron', [Male, Royal], 1],
  ['Lady', [Female, Royal], 1],
  ['Queen', [Female, Royal], 1],
  ['Princess', [Female, Royal], 1],
  ['Duchess', [Female, Royal], 1],
  ['Marchioness', [Female, Royal], 1],
  ['Countess', [Female, Royal], 1],
  ['Baroness', [Female, Royal], 1],
  ['Sister', [Female, Ecclesiastical], 1],
  ['Abbess', [Female, Ecclesiastical], 1],
  ['Prioress', [Female, Ecclesiastical], 1],
]

export const occupationTuple: TaggedItem[] = [
  ['Gravedigger', [Labor], 1],
  ['Plague Doctor', [Artisan], 1],
  ['Inquisitor', [Ecclesiastical], 1],
  ['Hangman', [Labor], 1],
  ['Smuggler', [Criminal], 1],
  ['Tax collector', [Administration], 1],
  ['Scrivener', [Administration], 1],
  ['Scribe', [Ecclesiastical], 1],
  ['Barrelmaker', [Artisan], 1],
  ['Cheesemaker', [Artisan], 1],
  ['Fishmonger', [Merchant], 1],
  ['Butcher', [Merchant], 1],
  ['Apothecary', [Merchant], 1],
  ['Mason', [Artisan], 1],
  ['Carpenter', [Artisan], 1],
  ['Weaver', [Artisan], 1],
  ['Farmer', [Labor], 1],
  ['Fisherman', [Labor], 1],
  ['Armorer', [Artisan], 1],
  ['Baker', [Artisan], 1],
  ['Barrister', [Administration], 1],
  ['Basketweaver', [Artisan], 1],
  ['Barber', [Labor], 1],
  ['Beekeeper', [Labor], 1],
  ['Blacksmith', [Artisan], 1],
  ['Bookbinder', [Artisan], 1],
  ['Bowyer', [Artisan], 1],
  ['Brewer', [Artisan], 1],
  ['Dyer', [Artisan], 1],
  ['Embroiderer', [Artisan], 1],
  ['Engraver', [Artisan], 1],
  ['Fletcher', [Artisan], 1],
  ['Lamplighter', [Labor], 1],
  ['Laundress', [Labor], 1],
  ['Leatherworker', [Artisan], 1],
  ['Locksmith', [Artisan], 1],
  ['Midwife', [Female, Labor], 1],
  ['Miller', [Labor], 1],
  ['Moneychanger', [Administration], 1],
  ['Needleworker', [Labor], 1],
  ['Candlemaker', [Artisan], 1],
  ['Cartwright', [Artisan], 1],
  ['Chimney sweep', [Labor], 1],
  ['Clerk', [Administration], 1],
  ['Clothier', [Merchant], 1],
  ['Cobbler', [Artisan], 1],
  ['Cooper', [Artisan], 1],
  ['Coppersmith', [Artisan], 1],
  ['Crier', [Labor], 1],
  ['Glassblower', [Artisan], 1],
  ['Goldsmith', [Artisan], 1],
  ['Haberdasher', [Merchant], 1],
  ['Herbalist', [Merchant], 1],
  ['Innkeeper', [Labor], 1],
  ['Jailer', [Administration], 1],
  ['Jester', [Labor], 1],
  ['Jeweler', [Artisan], 1],
  ['Lacemaker', [Artisan], 1],
  ['Limner', [Artisan], 1],
  ['Perfumemaker', [Artisan], 1],
  ['Porter', [Labor], 1],
  ['Potter', [Artisan], 1],
  ['Ropemaker', [Artisan], 1],
  ['Sailor', [Labor], 1],
  ['Seamstress', [Labor], 1],
  ['Shipwright', [Labor], 1],
  ['Shoemaker', [Artisan], 1],
  ['Silversmith', [Artisan], 1],
  ['Soapmaker', [Artisan], 1],
  ['Stonecarver', [Artisan], 1],
  ['Storyteller', [Labor], 1],
  ['Tailor', [Artisan], 1],
  ['Tanner', [Labor], 1],
  ['Tavernkeeper', [Labor], 1],
  ['Taxidermist', [Artisan], 1],
  ['Thatcher', [Labor], 1],
  ['Rat catcher', [Labor], 1],
  ['Vintner', [Labor], 1],
  ['Wainwright', [Artisan], 1],
  ['Weaponsmith', [Artisan], 1],
  ['Wheelwright', [Artisan], 1],
  ['Woodcarver', [Artisan], 1],
]

export const demeanorTuple: TaggedItem[] = [
  ['Abrasive', [], 1],
  ['Arrogant', [], 1],
  ['Calm', [], 1],
  ['Confident', [], 1],
  ['Courteous', [], 1],
  ['Eccentric', [], 1],
  ['Flamboyant', [], 1],
  ['Friendly', [], 1],
  ['Humble', [], 1],
  ['Naive', [], 1],
  ['Nervous', [], 1],
  ['Reserved', [], 1],
  ['Stubborn', [], 1],
  ['Suspicious', [], 1],
  ['Impatient', [], 1],
  ['Absent-minded', [], 1],
  ['Judgemental', [], 1],
  ['Cantankerous', [], 1],
  ['Curmudgeonly', [], 1],
  ['Clumsy', [], 1],
  ['Fidgety', [], 1],
  ['Glib', [], 1],
  ['Ornery', [], 1],
  ['Pompous', [], 1],
  ['Fretful', [], 1],
  ['Silent', [], 1],
  ['Jovial', [], 1],
  ['Snooty', [], 1],
  ['Lazy', [], 1],
  ['Bitter', [], 1],
  ['Vindictive', [], 1],
  ['Conflicted', [], 1],
  ['Sullen', [], 1]
]
