import { Gender, SocialClass, Alignment } from './Character';
import { d_name_male, d_name_female } from '../lists/deity_lists';
import { Generic, TaggedItem } from '../shared/types';

export const { All } = Generic
export const { Male, Female, Neutral } = Gender
export const gender = [...Object.values(Gender)]

export const {
  Servant,
  Labor,
  Merchant,
  Artisan,
  Elite,
  Military,
  Ecclesiastical,
  Royal,
  Criminal,
  Administration
} = SocialClass

export const socialClass = [...Object.values(SocialClass)]
export const alignment = [...Object.values(Alignment)]

// export const age = [
//   'Child',
//   'Adolescent',
//   'Young adult',
//   'Middle-aged',
//   'Aged',
//   'Elderly',
//   'Ancient'
// ]
export const ageTuple: TaggedItem[] = [
  ['Child', [], 1],
  ['Adolescent', [], 2],
  ['Young adult', [], 2],
  ['Middle-aged', [], 3],
  ['Aged', [], 2],
  ['Elderly', [], 1],
  ['Ancient', [], 1]
]

// export const wealth = [
//   'in debt',
//   'Destitute',
//   'Impoverished',
//   'Working class',
//   'Middle class',
//   'Prosperous',
//   'Decadent'
// ]

export const wealthTuple: TaggedItem[] = [
  ['Destitute', [], 1],
  ['in debt', [], 2],
  ['Impoverished', [], 3],
  ['Working class', [], 3],
  ['Middle class', [], 2],
  ['Prosperous', [], 1],
  ['Decadent', [], 1]
]

export const titleTuple: TaggedItem[] = [
  ['Master', [Neutral, Artisan, All], 1],
  ['Apprentice', [Neutral, Artisan, All], 1],
  ['Chamberlain', [Neutral, Royal, All], 1],
  ['Sheriff', [Neutral, Royal, All], 1],
  ['Alderman', [Neutral, Royal, All], 1],
  ['Lord Mayor', [Neutral, Royal, All], 1],
  ['Burgomaster', [Neutral, Royal, All], 1],
  ['Chancellor', [Neutral, Royal, All], 1],
  ['Governor', [Neutral, Royal, All], 1],
  ['Minister', [Neutral, Royal, All], 1],
  ['Magistrate', [Neutral, Royal, All], 1],
  ['Bishop', [Neutral, Ecclesiastical, All], 1],
  ['Curate', [Neutral, Ecclesiastical, All], 1],
  ['Vicar', [Male, Ecclesiastical, All], 1],
  ['Brother', [Male, Ecclesiastical, All], 1],
  ['Abbot', [Male, Ecclesiastical, All], 1],
  ['Prior', [Male, Ecclesiastical, All], 1],
  ['Friar', [Male, Ecclesiastical, All], 1],
  ['Lord', [Male, Royal, All], 1],
  ['King', [Male, Royal, All], 1],
  ['Prince', [Male, Royal, All], 1],
  ['Duke', [Male, Royal, All], 1],
  ['Marquis', [Male, Royal, All], 1],
  ['Earl/Count', [Male, Royal, All], 1],
  ['Baron', [Male, Royal, All], 1],
  ['Lady', [Female, Royal, All], 1],
  ['Queen', [Female, Royal, All], 1],
  ['Princess', [Female, Royal, All], 1],
  ['Duchess', [Female, Royal, All], 1],
  ['Marchioness', [Female, Royal, All], 1],
  ['Countess', [Female, Royal, All], 1],
  ['Baroness', [Female, Royal, All], 1],
  ['Sister', [Female, Ecclesiastical, All], 1],
  ['Abbess', [Female, Ecclesiastical, All], 1],
  ['Prioress', [Female, Ecclesiastical, All], 1],
]

export const occupationTuple: TaggedItem[] = [
  ['Gravedigger', [Labor, All], 1],
  ['Plague Doctor', [Artisan, All], 1],
  ['Inquisitor', [Ecclesiastical, All], 1],
  ['Hangman', [Labor, All], 1],
  ['Smuggler', [Criminal, All], 1],
  ['Tax collector', [Administration, All], 1],
  ['Scrivener', [Administration, All], 1],
  ['Scribe', [Ecclesiastical, All], 1],
  ['Barrelmaker', [Artisan, All], 1],
  ['Cheesemaker', [Artisan, All], 1],
  ['Fishmonger', [Merchant, All], 1],
  ['Butcher', [Merchant, All], 1],
  ['Apothecary', [Merchant, All], 1],
  ['Mason', [Artisan, All], 1],
  ['Carpenter', [Artisan, All], 1],
  ['Weaver', [Artisan, All], 1],
  ['Farmer', [Labor, All], 1],
  ['Fisherman', [Labor, All], 1],
  ['Armorer', [Artisan, All], 1],
  ['Baker', [Artisan, All], 1],
  ['Barrister', [Administration, All], 1],
  ['Basketweaver', [Artisan, All], 1],
  ['Barber', [Labor, All], 1],
  ['Beekeeper', [Labor, All], 1],
  ['Blacksmith', [Artisan, All], 1],
  ['Bookbinder', [Artisan, All], 1],
  ['Bowyer', [Artisan, All], 1],
  ['Brewer', [Artisan, All], 1],
  ['Dyer', [Artisan, All], 1],
  ['Embroiderer', [Artisan, All], 1],
  ['Engraver', [Artisan, All], 1],
  ['Fletcher', [Artisan, All], 1],
  ['Lamplighter', [Labor, All], 1],
  ['Laundress', [Labor, All], 1],
  ['Leatherworker', [Artisan, All], 1],
  ['Locksmith', [Artisan, All], 1],
  ['Midwife', [Female, Labor, All], 1],
  ['Miller', [Labor, All], 1],
  ['Moneychanger', [Administration, All], 1],
  ['Needleworker', [Labor, All], 1],
  ['Candlemaker', [Artisan, All], 1],
  ['Cartwright', [Artisan, All], 1],
  ['Chimney sweep', [Labor, All], 1],
  ['Clerk', [Administration, All], 1],
  ['Clothier', [Merchant, All], 1],
  ['Cobbler', [Artisan, All], 1],
  ['Cooper', [Artisan, All], 1],
  ['Coppersmith', [Artisan, All], 1],
  ['Crier', [Labor, All], 1],
  ['Glassblower', [Artisan, All], 1],
  ['Goldsmith', [Artisan, All], 1],
  ['Haberdasher', [Merchant, All], 1],
  ['Herbalist', [Merchant, All], 1],
  ['Innkeeper', [Labor, All], 1],
  ['Jailer', [Administration, All], 1],
  ['Jester', [Labor, All], 1],
  ['Jeweler', [Artisan, All], 1],
  ['Lacemaker', [Artisan, All], 1],
  ['Limner', [Artisan, All], 1],
  ['Perfumemaker', [Artisan, All], 1],
  ['Porter', [Labor, All], 1],
  ['Potter', [Artisan, All], 1],
  ['Ropemaker', [Artisan, All], 1],
  ['Sailor', [Labor, All], 1],
  ['Seamstress', [Labor, All], 1],
  ['Shipwright', [Labor, All], 1],
  ['Shoemaker', [Artisan, All], 1],
  ['Silversmith', [Artisan, All], 1],
  ['Soapmaker', [Artisan, All], 1],
  ['Stonecarver', [Artisan, All], 1],
  ['Storyteller', [Labor, All], 1],
  ['Tailor', [Artisan, All], 1],
  ['Tanner', [Labor, All], 1],
  ['Tavernkeeper', [Labor, All], 1],
  ['Taxidermist', [Artisan, All], 1],
  ['Thatcher', [Labor, All], 1],
  ['Rat catcher', [Labor, All], 1],
  ['Vintner', [Labor, All], 1],
  ['Wainwright', [Artisan, All], 1],
  ['Weaponsmith', [Artisan, All], 1],
  ['Wheelwright', [Artisan, All], 1],
  ['Woodcarver', [Artisan, All], 1],
]

// export const demeanor = [
//   'Abrasive',
//   'Arrogant',
//   'Calm',
//   'Confident',
//   'Courteous',
//   'Eccentric',
//   'Flamboyant',
//   'Friendly',
//   'Humble',
//   'Naive',
//   'Nervous',
//   'Reserved',
//   'Stubborn',
//   'Suspicious',
//   'Impatient',
//   'Absent-minded',
//   'Judgemental',
//   'Cantankerous',
//   'Curmudgeonly',
//   'Clumsy',
//   'Fidgety',
//   'Glib',
//   'Ornery',
//   'Pompous',
//   'Fretful',
//   'Silent',
//   'Jovial',
//   'Snooty',
//   'Lazy',
//   'Bitter',
//   'Vindictive',
//   'Conflicted',
//   'Sullen'
// ]

export const demeanorTuple: TaggedItem[] = [
  ['Abrasive', [], 1],
  ['Arrogant', [], 1],
  ['Calm', [], 1],
  ['Confident', [], 1],
  ['Courteous', [], 1],
  ['Eccentric', [], 1],
  ['Flamboyant', [], 1],
  ['Friendly', [], 1],
  ['Humble', [], 1],
  ['Naive', [], 1],
  ['Nervous', [], 1],
  ['Reserved', [], 1],
  ['Stubborn', [], 1],
  ['Suspicious', [], 1],
  ['Impatient', [], 1],
  ['Absent-minded', [], 1],
  ['Judgemental', [], 1],
  ['Cantankerous', [], 1],
  ['Curmudgeonly', [], 1],
  ['Clumsy', [], 1],
  ['Fidgety', [], 1],
  ['Glib', [], 1],
  ['Ornery', [], 1],
  ['Pompous', [], 1],
  ['Fretful', [], 1],
  ['Silent', [], 1],
  ['Jovial', [], 1],
  ['Snooty', [], 1],
  ['Lazy', [], 1],
  ['Bitter', [], 1],
  ['Vindictive', [], 1],
  ['Conflicted', [], 1],
  ['Sullen', [], 1]
]

export const names = {
  male: [...d_name_male],
  female: [...d_name_female],
  neutral: [...d_name_male, ...d_name_female]
}
