// Epithets
//   the Lesser
//   the Greater
//   the Bald
//   the Impure
//   the Unready
//   the Grim
//   The Mad
//   the First, Second, Third, etc
//   the Miserable
//   the Fat
//   the Unreliable
//   the Forgotten
//   the Incompetent
//   the Slippery
//   the Inconsistent


export enum Epithets {
    Bestial = 'Bestial',
    Bold = 'Bold',
    Charming = 'Charming',
    Devious = 'Devious',
    Dextrous = 'Dextrous',
    Epithet = 'Epithet',
    Evil = 'Evil',
    Fast = 'Fast',
    Fierce = 'Fierce',
    Good = 'Good',
    Infirm = 'Infirm',
    Noble = 'Noble',
    Personality = 'Personality',
    Physical = 'Physical',
    Strong = 'Strong',
    Tough = 'Tough',
    Wise = 'Wise'
}

const {
    Bestial,
    Bold,
    Charming,
    Devious,
    Dextrous,
    Epithet,
    Evil,
    Fast,
    Fierce,
    Good,
    Infirm,
    Noble,
    Personality,
    Physical,
    Strong,
    Tough,
    Wise
} = Epithets


const CommonList = [
    ['Bald', [Epithet,], 1],
    ['Eighth', [Epithet,], 1],
    ['Fat', [Epithet,], 1],
    ['Fifth', [Epithet,], 1],
    ['First', [Epithet,], 1],
    ['Forgotten', [Epithet,], 1],
    ['Fourth', [Epithet,], 1],
    ['Great', [Epithet,], 1],
    ['Greater', [Epithet,], 1],
    ['Grim', [Epithet,], 1],
    ['Impure', [Epithet,], 1],
    ['Incompetent', [Epithet,], 1],
    ['Inconsistent', [Epithet,], 1],
    ['Lesser', [Epithet,], 1],
    ['Mad', [Epithet,], 1],
    ['Miserable', [Epithet,], 1],
    ['Ninth', [Epithet,], 1],
    ['Second', [Epithet,], 1],
    ['Seventh', [Epithet,], 1],
    ['Sixth', [Epithet,], 1],
    ['Slippery', [Epithet,], 1],
    ['Tenth', [Epithet,], 1],
    ['Third', [Epithet,], 1],
    ['Unclean', [Epithet,], 1],
    ['Unready', [Epithet,], 1],
    ['Unreliable', [Epithet,], 1],
]

const PhysicalList = [
    ["big", [Epithet, Physical], 1],
    ["comely", [Epithet, Physical], 1],
    ["dark", [Epithet, Physical], 1],
    ["fair", [Epithet, Physical], 1],
    ["fast", [Epithet, Physical], 1],
    ["fat", [Epithet, Physical], 1],
    ["feeble", [Epithet, Physical], 1],
    ["hardy", [Epithet, Physical], 1],
    ["healthy", [Epithet, Physical], 1],
    ["lank", [Epithet, Physical], 1],
    ["lean", [Epithet, Physical], 1],
    ["old", [Epithet, Physical], 1],
    ["short", [Epithet, Physical], 1],
    ["sick", [Epithet, Physical], 1],
    ["slow", [Epithet, Physical], 1],
    ["small", [Epithet, Physical], 1],
    ["squat", [Epithet, Physical], 1],
    ["stout", [Epithet, Physical], 1],
    ["strong", [Epithet, Physical], 1],
    ["tall", [Epithet, Physical], 1],
    ["thin", [Epithet, Physical], 1],
    ["ugly", [Epithet, Physical], 1],
    ["unwell", [Epithet, Physical], 1],
    ["weak", [Epithet, Physical], 1],
    ["young", [Epithet, Physical], 1],
]

const PersonalityList = [
    ["aloof", [Epithet, Personality], 1],
    ["ardent", [Epithet, Personality], 1],
    ["ascetic", [Epithet, Personality], 1],
    ["bad", [Epithet, Personality], 1],
    ["benign", [Epithet, Personality], 1],
    ["boastful", [Epithet, Personality], 1],
    ["bold", [Epithet, Personality], 1],
    ["brave", [Epithet, Personality], 1],
    ["capricious", [Epithet, Personality], 1],
    ["chaste", [Epithet, Personality], 1],
    ["clever", [Epithet, Personality], 1],
    ["courteous", [Epithet, Personality], 1],
    ["craven", [Epithet, Personality], 1],
    ["cruel", [Epithet, Personality], 1],
    ["cunning", [Epithet, Personality], 1],
    ["despairing", [Epithet, Personality], 1],
    ["dull", [Epithet, Personality], 1],
    ["dutiful", [Epithet, Personality], 1],
    ["faithless", [Epithet, Personality], 1],
    ["false", [Epithet, Personality], 1],
    ["fierce", [Epithet, Personality], 1],
    ["foolish", [Epithet, Personality], 1],
    ["gallant", [Epithet, Personality], 1],
    ["genial", [Epithet, Personality], 1],
    ["gentle", [Epithet, Personality], 1],
    ["good", [Epithet, Personality], 1],
    ["guileless", [Epithet, Personality], 1],
    ["happy", [Epithet, Personality], 1],
    ["honest", [Epithet, Personality], 1],
    ["hopeful", [Epithet, Personality], 1],
    ["humble", [Epithet, Personality], 1],
    ["impious", [Epithet, Personality], 1],
    ["impure", [Epithet, Personality], 1],
    ["insolent", [Epithet, Personality], 1],
    ["irresolute", [Epithet, Personality], 1],
    ["just", [Epithet, Personality], 1],
    ["kind", [Epithet, Personality], 1],
    ["lawful", [Epithet, Personality], 1],
    ["lax", [Epithet, Personality], 1],
    ["lewd", [Epithet, Personality], 1],
    ["listless", [Epithet, Personality], 1],
    ["loyal", [Epithet, Personality], 1],
    ["malign", [Epithet, Personality], 1],
    ["merciful", [Epithet, Personality], 1],
    ["modest", [Epithet, Personality], 1],
    ["neglectful", [Epithet, Personality], 1],
    ["peaceful", [Epithet, Personality], 1],
    ["pious", [Epithet, Personality], 1],
    ["proud", [Epithet, Personality], 1],
    ["pure", [Epithet, Personality], 1],
    ["rash", [Epithet, Personality], 1],
    ["resolute", [Epithet, Personality], 1],
    ["ruthless", [Epithet, Personality], 1],
    ["sad", [Epithet, Personality], 1],
    ["saint", [Epithet, Personality], 1],
    ["selfish", [Epithet, Personality], 1],
    ["selfless", [Epithet, Personality], 1],
    ["sensual", [Epithet, Personality], 1],
    ["servile", [Epithet, Personality], 1],
    ["severe", [Epithet, Personality], 1],
    ["sinner", [Epithet, Personality], 1],
    ["spiritless", [Epithet, Personality], 1],
    ["stubborn", [Epithet, Personality], 1],
    ["stupid", [Epithet, Personality], 1],
    ["timid", [Epithet, Personality], 1],
    ["unjust", [Epithet, Personality], 1],
    ["vain", [Epithet, Personality], 1],
    ["warlike", [Epithet, Personality], 1],
    ["wary", [Epithet, Personality], 1],
    ["wise", [Epithet, Personality], 1],
    ["witty", [Epithet, Personality], 1],
    ["yielding", [Epithet, Personality], 1],
]

const GeneralList = [
    ["admirable", [Epithet,], 1],
    ["beloved", [Epithet,], 1],
    ["benighted", [Epithet,], 1],
    ["clumsy", [Epithet,], 1],
    ["coarse", [Epithet,], 1],
    ["cultured", [Epithet,], 1],
    ["despised", [Epithet,], 1],
    ["drunk", [Epithet,], 1],
    ["elegant", [Epithet,], 1],
    ["esteemed", [Epithet,], 1],
    ["fair", [Epithet,], 1],
    ["famous", [Epithet,], 1],
    ["flawed", [Epithet,], 1],
    ["foppish", [Epithet,], 1],
    ["foul", [Epithet,], 1],
    ["great", [Epithet,], 1],
    ["hated", [Epithet,], 1],
    ["inept", [Epithet,], 1],
    ["knavish", [Epithet,], 1],
    ["lavish", [Epithet,], 1],
    ["learned", [Epithet,], 1],
    ["loser", [Epithet,], 1],
    ["lucky", [Epithet,], 1],
    ["mean", [Epithet,], 1],
    ["noble", [Epithet,], 1],
    ["obscure", [Epithet,], 1],
    ["paltry", [Epithet,], 1],
    ["perfect", [Epithet,], 1],
    ["poor", [Epithet,], 1],
    ["refined", [Epithet,], 1],
    ["rich", [Epithet,], 1],
    ["ridiculous", [Epithet,], 1],
    ["rough", [Epithet,], 1],
    ["skilful", [Epithet,], 1],
    ["sober", [Epithet,], 1],
    ["tasteful", [Epithet,], 1],
    ["uncouth", [Epithet,], 1],
    ["unlucky", [Epithet,], 1],
    ["victor", [Epithet,], 1],
    ["vulgar", [Epithet,], 1],
]

const EvilList = [
    ["bad", [Epithet, Evil], 1],
    ["base", [Epithet, Evil], 1],
    ["brutal", [Epithet, Evil], 1],
    ["corrupt", [Epithet, Evil], 1],
    ["depraved", [Epithet, Evil], 1],
    ["evil", [Epithet, Evil], 1],
    ["foul", [Epithet, Evil], 1],
    ["gross", [Epithet, Evil], 1],
    ["hateful", [Epithet, Evil], 1],
    ["horrid", [Epithet, Evil], 1],
    ["ignoble", [Epithet, Evil], 1],
    ["impure", [Epithet, Evil], 1],
    ["loathsome", [Epithet, Evil], 1],
    ["malevolent", [Epithet, Evil], 1],
    ["mean", [Epithet, Evil], 1],
    ["nasty", [Epithet, Evil], 1],
    ["spiteful", [Epithet, Evil], 1],
    ["squalid", [Epithet, Evil], 1],
    ["sullen", [Epithet, Evil], 1],
    ["surly", [Epithet, Evil], 1],
    ["ugly", [Epithet, Evil], 1],
    ["vicious", [Epithet, Evil], 1],
    ["vile", [Epithet, Evil], 1],
    ["vulgar", [Epithet, Evil], 1],
    ["wicked", [Epithet, Evil], 1],
    ["worthless", [Epithet, Evil], 1],
    ["cur", [Epithet, Evil], 1],
    ["slug", [Epithet, Evil], 1],
    ["reptile", [Epithet, Evil], 1],
    ["snake", [Epithet, Evil], 1],
    ["toad", [Epithet, Evil], 1],
    ["worm", [Epithet, Evil], 1],
]

const BestialList = [
    ["bestial", [Epithet, Bestial], 1],
    ["bloodthirsty", [Epithet, Bestial], 1],
    ["brutish", [Epithet, Bestial], 1],
    ["coarse", [Epithet, Bestial], 1],
    ["crude", [Epithet, Bestial], 1],
    ["cruel", [Epithet, Bestial], 1],
    ["ferocious", [Epithet, Bestial], 1],
    ["heartless", [Epithet, Bestial], 1],
    ["inhuman", [Epithet, Bestial], 1],
    ["merciless", [Epithet, Bestial], 1],
    ["pitiless", [Epithet, Bestial], 1],
    ["rapacious", [Epithet, Bestial], 1],
    ["ravening", [Epithet, Bestial], 1],
    ["remorseless", [Epithet, Bestial], 1],
    ["ruthless", [Epithet, Bestial], 1],
    ["savage", [Epithet, Bestial], 1],
    ["uncivilized", [Epithet, Bestial], 1],
    ["beast", [Epithet, Bestial], 1],
    ["shark", [Epithet, Bestial], 1],
    ["wolf", [Epithet, Bestial], 1],
]

const BoldList = [
    ["adventurous", [Epithet, Bold], 1],
    ["audacious", [Epithet, Bold], 1],
    ["bold", [Epithet, Bold], 1],
    ["brave", [Epithet, Bold], 1],
    ["courageous", [Epithet, Bold], 1],
    ["daring", [Epithet, Bold], 1],
    ["dauntless", [Epithet, Bold], 1],
    ["fearless", [Epithet, Bold], 1],
    ["gallant", [Epithet, Bold], 1],
    ["heroic", [Epithet, Bold], 1],
    ["intrepid", [Epithet, Bold], 1],
    ["keen", [Epithet, Bold], 1],
    ["manly", [Epithet, Bold], 1],
    ["plucky", [Epithet, Bold], 1],
    ["valiant", [Epithet, Bold], 1],
    ["lion", [Epithet, Bold], 1],
    ["hawk", [Epithet, Bold], 1],
]

const CharmingList = [
    ["agreeable", [Epithet, Charming], 1],
    ["beautiful", [Epithet, Charming], 1],
    ["charming", [Epithet, Charming], 1],
    ["comely", [Epithet, Charming], 1],
    ["easy", [Epithet, Charming], 1],
    ["elegant", [Epithet, Charming], 1],
    ["fair", [Epithet, Charming], 1],
    ["fine", [Epithet, Charming], 1],
    ["gentle", [Epithet, Charming], 1],
    ["gorgeous", [Epithet, Charming], 1],
    ["graceful", [Epithet, Charming], 1],
    ["handsome", [Epithet, Charming], 1],
    ["lovely", [Epithet, Charming], 1],
    ["pleasing", [Epithet, Charming], 1],
    ["pretty", [Epithet, Charming], 1],
    ["radiant", [Epithet, Charming], 1],
    ["flower", [Epithet, Charming], 1],
    ["jewel", [Epithet, Charming], 1],
    ["rose", [Epithet, Charming], 1],
    ["swan", [Epithet, Charming], 1],
]

const DeviousList = [
    ["artful", [Epithet, Devious], 1],
    ["canny", [Epithet, Devious], 1],
    ["clever", [Epithet, Devious], 1],
    ["crafty", [Epithet, Devious], 1],
    ["cunning", [Epithet, Devious], 1],
    ["guileful", [Epithet, Devious], 1],
    ["riddling", [Epithet, Devious], 1],
    ["scheming", [Epithet, Devious], 1],
    ["sharp", [Epithet, Devious], 1],
    ["shifty", [Epithet, Devious], 1],
    ["shrewd", [Epithet, Devious], 1],
    ["slippery", [Epithet, Devious], 1],
    ["sly", [Epithet, Devious], 1],
    ["smooth", [Epithet, Devious], 1],
    ["stealthy", [Epithet, Devious], 1],
    ["subtle", [Epithet, Devious], 1],
    ["tricky", [Epithet, Devious], 1],
    ["two-faced", [Epithet, Devious], 1],
    ["wily", [Epithet, Devious], 1],
    ["eel", [Epithet, Devious], 1],
    ["fox", [Epithet, Devious], 1],
    ["rat", [Epithet, Devious], 1],
    ["spider", [Epithet, Devious], 1],
]

const DextrousList = [
    ["adept", [Epithet, Dextrous], 1],
    ["adroit", [Epithet, Dextrous], 1],
    ["agile", [Epithet, Dextrous], 1],
    ["deft", [Epithet, Dextrous], 1],
    ["nimble", [Epithet, Dextrous], 1],
    ["spry", [Epithet, Dextrous], 1],
    ["supple", [Epithet, Dextrous], 1],
    ["cat", [Epithet, Dextrous], 1],
    ["lizard", [Epithet, Dextrous], 1],
    ["monkey", [Epithet, Dextrous], 1],
    ["ambidextrous", [Epithet, Dextrous], 1],
]

const FastList = [
    ["active", [Epithet, Fast], 1],
    ["alert", [Epithet, Fast], 1],
    ["brisk", [Epithet, Fast], 1],
    ["fast", [Epithet, Fast], 1],
    ["fleet", [Epithet, Fast], 1],
    ["hasty", [Epithet, Fast], 1],
    ["lively", [Epithet, Fast], 1],
    ["quick", [Epithet, Fast], 1],
    ["rapid", [Epithet, Fast], 1],
    ["ready", [Epithet, Fast], 1],
    ["smart", [Epithet, Fast], 1],
    ["speedy", [Epithet, Fast], 1],
    ["sprightly", [Epithet, Fast], 1],
    ["swift", [Epithet, Fast], 1],
    ["yare", [Epithet, Fast], 1],
    ["yauld", [Epithet, Fast], 1],
    ["bird", [Epithet, Fast], 1],
    ["deer", [Epithet, Fast], 1],
    ["hare", [Epithet, Fast], 1],
]

const FierceList = [
    ["berserk", [Epithet, Fierce], 1],
    ["brutal", [Epithet, Fierce], 1],
    ["dire", [Epithet, Fierce], 1],
    ["eager", [Epithet, Fierce], 1],
    ["ferocious", [Epithet, Fierce], 1],
    ["fervent", [Epithet, Fierce], 1],
    ["fierce", [Epithet, Fierce], 1],
    ["fiery", [Epithet, Fierce], 1],
    ["forcible", [Epithet, Fierce], 1],
    ["furious", [Epithet, Fierce], 1],
    ["headstrong", [Epithet, Fierce], 1],
    ["raging", [Epithet, Fierce], 1],
    ["rash", [Epithet, Fierce], 1],
    ["reckless", [Epithet, Fierce], 1],
    ["savage", [Epithet, Fierce], 1],
    ["violent", [Epithet, Fierce], 1],
    ["wild", [Epithet, Fierce], 1],
    ["zealous", [Epithet, Fierce], 1],
    ["boar", [Epithet, Fierce], 1],
    ["dragon", [Epithet, Fierce], 1],
    ["tiger", [Epithet, Fierce], 1],
    ["wolf", [Epithet, Fierce], 1],
]

const GoodList = [
    ["admirable", [Epithet, Good], 1],
    ["blameless", [Epithet, Good], 1],
    ["decent", [Epithet, Good], 1],
    ["estimable", [Epithet, Good], 1],
    ["ethical", [Epithet, Good], 1],
    ["excellent", [Epithet, Good], 1],
    ["exemplary", [Epithet, Good], 1],
    ["fair", [Epithet, Good], 1],
    ["fine", [Epithet, Good], 1],
    ["good", [Epithet, Good], 1],
    ["honest", [Epithet, Good], 1],
    ["honorable", [Epithet, Good], 1],
    ["humane", [Epithet, Good], 1],
    ["impartial", [Epithet, Good], 1],
    ["just", [Epithet, Good], 1],
    ["lawful", [Epithet, Good], 1],
    ["moral", [Epithet, Good], 1],
    ["pleasant", [Epithet, Good], 1],
    ["pure", [Epithet, Good], 1],
    ["right", [Epithet, Good], 1],
    ["righteous", [Epithet, Good], 1],
    ["true", [Epithet, Good], 1],
    ["upright", [Epithet, Good], 1],
    ["virtuous", [Epithet, Good], 1],
    ["worthy", [Epithet, Good], 1],
    ["golden", [Epithet, Good], 1],
]

const InfirmList = [
    ["bald", [Epithet, Infirm], 1],
    ["bandy", [Epithet, Infirm], 1],
    ["blind", [Epithet, Infirm], 1],
    ["club-foot", [Epithet, Infirm], 1],
    ["crippled", [Epithet, Infirm], 1],
    ["crooked", [Epithet, Infirm], 1],
    ["cross-eyed", [Epithet, Infirm], 1],
    ["deaf", [Epithet, Infirm], 1],
    ["dumb", [Epithet, Infirm], 1],
    ["fat", [Epithet, Infirm], 1],
    ["gouty", [Epithet, Infirm], 1],
    ["hunchback", [Epithet, Infirm], 1],
    ["knock-kneed", [Epithet, Infirm], 1],
    ["lame", [Epithet, Infirm], 1],
    ["mad", [Epithet, Infirm], 1],
    ["one-eyed", [Epithet, Infirm], 1],
    ["pockmarked", [Epithet, Infirm], 1],
    ["sickly", [Epithet, Infirm], 1],
    ["simple", [Epithet, Infirm], 1],
    ["sluggard", [Epithet, Infirm], 1],
    ["stammering", [Epithet, Infirm], 1],
    ["toothless", [Epithet, Infirm], 1],
    ["wall-eyed", [Epithet, Infirm], 1],
]

const NobleList = [
    ["august", [Epithet, Noble], 1],
    ["dignified", [Epithet, Noble], 1],
    ["distinguished", [Epithet, Noble], 1],
    ["elevated", [Epithet, Noble], 1],
    ["eminent", [Epithet, Noble], 1],
    ["generous", [Epithet, Noble], 1],
    ["grand", [Epithet, Noble], 1],
    ["great", [Epithet, Noble], 1],
    ["honorable", [Epithet, Noble], 1],
    ["imposing", [Epithet, Noble], 1],
    ["impressive", [Epithet, Noble], 1],
    ["lofty", [Epithet, Noble], 1],
    ["magnificent", [Epithet, Noble], 1],
    ["majestic", [Epithet, Noble], 1],
    ["noble", [Epithet, Noble], 1],
    ["proud", [Epithet, Noble], 1],
    ["splendid", [Epithet, Noble], 1],
    ["stately", [Epithet, Noble], 1],
    ["superior", [Epithet, Noble], 1],
    ["upright", [Epithet, Noble], 1],
    ["virtuous", [Epithet, Noble], 1],
    ["worthy", [Epithet, Noble], 1],
    ["lion", [Epithet, Noble], 1],
    ["eagle", [Epithet, Noble], 1],
]

const StrongList = [
    ["able", [Epithet, Strong], 1],
    ["brawny", [Epithet, Strong], 1],
    ["burly", [Epithet, Strong], 1],
    ["forceful", [Epithet, Strong], 1],
    ["hale", [Epithet, Strong], 1],
    ["hardy", [Epithet, Strong], 1],
    ["healthy", [Epithet, Strong], 1],
    ["lusty", [Epithet, Strong], 1],
    ["manly", [Epithet, Strong], 1],
    ["mighty", [Epithet, Strong], 1],
    ["powerful", [Epithet, Strong], 1],
    ["robust", [Epithet, Strong], 1],
    ["stalwart", [Epithet, Strong], 1],
    ["stout", [Epithet, Strong], 1],
    ["strapping", [Epithet, Strong], 1],
    ["strong", [Epithet, Strong], 1],
    ["sturdy", [Epithet, Strong], 1],
    ["tough", [Epithet, Strong], 1],
    ["virile", [Epithet, Strong], 1],
    ["ape", [Epithet, Strong], 1],
    ["bear", [Epithet, Strong], 1],
    ["bull", [Epithet, Strong], 1],
]

const ToughList = [
    ["bleak", [Epithet, Tough], 1],
    ["doughty", [Epithet, Tough], 1],
    ["dread", [Epithet, Tough], 1],
    ["firm", [Epithet, Tough], 1],
    ["grim", [Epithet, Tough], 1],
    ["hard", [Epithet, Tough], 1],
    ["hardy", [Epithet, Tough], 1],
    ["harsh", [Epithet, Tough], 1],
    ["resolute", [Epithet, Tough], 1],
    ["rugged", [Epithet, Tough], 1],
    ["severe", [Epithet, Tough], 1],
    ["stalwart", [Epithet, Tough], 1],
    ["stark", [Epithet, Tough], 1],
    ["staunch", [Epithet, Tough], 1],
    ["steadfast", [Epithet, Tough], 1],
    ["stern", [Epithet, Tough], 1],
    ["tough", [Epithet, Tough], 1],
    ["unyielding", [Epithet, Tough], 1],
    ["oak", [Epithet, Tough], 1],
    ["iron", [Epithet, Tough], 1],
    ["flint", [Epithet, Tough], 1],
    ["steel", [Epithet, Tough], 1],
    ["stone", [Epithet, Tough], 1],
]

const WiseList = [
    ["acute", [Epithet, Wise], 1],
    ["astute", [Epithet, Wise], 1],
    ["clever", [Epithet, Wise], 1],
    ["deep", [Epithet, Wise], 1],
    ["discerning", [Epithet, Wise], 1],
    ["judicious", [Epithet, Wise], 1],
    ["perceptive", [Epithet, Wise], 1],
    ["sage", [Epithet, Wise], 1],
    ["sapient", [Epithet, Wise], 1],
    ["sensible", [Epithet, Wise], 1],
    ["shrewd", [Epithet, Wise], 1],
    ["wise", [Epithet, Wise], 1],
    ["owl", [Epithet, Wise], 1],
]