import { TaggedItem } from "../shared/types"
import { NameTags, NounGroup, WordPosition, WordType, MaterialGroup, AdjectiveGroups } from "./enums"

const { Prefix, Suffix } = WordPosition
const { Anatomical, Fluid, Armor, Weapon, Animal, Material } = NounGroup
const { Agentive, Gerund, PastParticiple } = WordType
const { Color, Silly, Grim, Gross } = NameTags
const { Metal, Wood, Mineral, Stone } = MaterialGroup
const { Effect, Condition, Quality } = AdjectiveGroups

export const twoTagSets = [
	[Weapon, Fluid],
	[Color, Anatomical],
	[Gerund, Animal],
	[Material, Armor],
	[Grim, Silly],
	// [Prefix, Suffix]
]


export const colors: TaggedItem[] = [
	["Azure", [Color], 1],
	["Cobalt", [Color], 1],
	["Verdigris", [Color], 1],
	["Pale", [Color], 1],
	["Dark", [Color], 1],
	["Dim", [Color], 1],
	["Umber", [Color], 1],
	["Amber", [Color], 1],
	["Burgundy", [Color], 1],
	["Crimson", [Color], 1],
	["Ocher", [Color], 1],
	["Rainbow", [Color], 1],
	["Magenta", [Color], 1],
	["Cyan", [Color], 1],
	["Gray", [Color], 1],
	["Black", [Color], 1],
	["White", [Color], 1],
	["Red", [Color], 1],
	["Blue", [Color], 1],
	["Green", [Color], 1],
	["Orange", [Color], 1],
	["Violet", [Color], 1],
	["Yellow", [Color], 1],
	["Sepia", [Color], 1],
	["Cerulean", [Color], 1],
	["Alizerin", [Color], 1],
	["Ebon", [Color], 1],
	["Veridian", [Color], 1],
	["Dun", [Color], 1]
]

export const silly: TaggedItem[] = [
	["Beard", [Silly], 1],
	["Biscuit", [Silly], 1],
	["Bobble", [Silly], 1],
	["Bong", [Silly], 1],
	["Bottom", [Silly], 1],
	["Brew", [Silly], 1],
	["Bucket", [Silly], 1],
	["Bucket", [Silly], 1],
	["Button", [Silly], 1],
	["Clump", [Silly], 1],
	["Crumble", [Silly], 1],
	["Doodle", [Silly], 1],
	["Fidget", [Silly], 1],
	["Finger", [Silly], 1],
	["Fluff", [Silly], 1],
	["Foot", [Silly], 1],
	["Fork", [Silly], 1],
	["Freckle", [Silly], 1],
	["Funnel", [Silly], 1],
	["Gizzard", [Silly], 1],
	["Glob", [Silly], 1],
	["Glum", [Silly], 1],
	["Gobble", [Silly], 1],
	["Google", [Silly], 1],
	["Grizzle", [Silly], 1],
	["Grumble", [Silly], 1],
	["Guzzle", [Silly], 1],
	["Hobble", [Silly], 1],
	["Ladle", [Silly], 1],
	["Loaf", [Silly], 1],
	["Lump", [Silly], 1],
	["Muffin", [Silly], 1],
	["Nose", [Silly], 1],
	["Nozzle", [Silly], 1],
	["Pants", [Silly], 1],
	["Piddle", [Silly], 1],
	["Plug", [Silly], 1],
	["Pocket", [Silly], 1],
	["Prickle", [Silly], 1],
	["Prong", [Silly], 1],
	["Puddle", [Silly], 1],
	["Puppet", [Silly], 1],
	["Sock", [Silly], 1],
	["Socks", [Silly], 1],
	["Spackle", [Silly], 1],
	["Speckle", [Silly], 1],
	["Spigot", [Silly], 1],
	["Spoon", [Silly], 1],
	["Stubble", [Silly], 1],
	["Stumble", [Silly], 1],
	["Tickle", [Silly], 1],
	["Toes", [Silly], 1],
	["Tooth", [Silly], 1],
	["Trouser", [Silly], 1],
	["Wart", [Silly], 1],
	["Water", [Silly], 1],
	["Weasel", [Silly], 1],
	["Weevil", [Silly], 1],
	["Whisker", [Silly], 1],
	["Widget", [Silly], 1],
	["Wood", [Silly], 1],
	["Worth", [Silly], 1],
	["Long", [Silly], 1],
	["Scurvy", [Silly], 1],
	["Scruffy", [Silly], 1],
	["Grumble", [Silly], 1],
	["Nose", [Silly], 1],
	["Knees", [Silly], 1],
	["Ears", [Silly], 1],
	["Trousers", [Silly], 1],
	["Beard", [Silly], 1],
	["Wart", [Silly], 1]
]

export const grim: TaggedItem[] = [
	["Ash", [Grim], 1],
	["Axe", [Grim], 1],
	["Bag", [Grim], 1],
	["Bane", [Grim], 1],
	["Beast", [Grim], 1],
	["Beetle", [Grim], 1],
	["Belch", [Grim], 1],
	["Bend", [Grim], 1],
	["Bender", [Grim], 1],
	["Bile", [Grim], 1],
	["Bite", [Grim], 1],
	["Black", [Grim], 1],
	["Blade", [Grim], 1],
	["Blast", [Grim], 1],
	["Blight", [Grim], 1],
	["Blister", [Grim], 1],
	["Blood", [Grim], 1],
	["Blue", [Grim], 1],
	["Blunt", [Grim], 1],
	["Bog", [Grim], 1],
	["Bone", [Grim], 1],
	["Bowel", [Grim], 1],
	["Break", [Grim], 1],
	["Brow", [Grim], 1],
	["Brute", [Grim], 1],
	["Burble", [Grim], 1],
	["Burn", [Grim], 1],
	["Cackle", [Grim], 1],
	["Call", [Grim], 1],
	["Canker", [Grim], 1],
	["Chaos", [Grim], 1],
	["Chew", [Grim], 1],
	["Clap", [Grim], 1],
	["Claw", [Grim], 1],
	["Cloud", [Grim], 1],
	["Cold", [Grim], 1],
	["Crab", [Grim], 1],
	["Crawler", [Grim], 1],
	["Craze", [Grim], 1],
	["Crow", [Grim], 1],
	["Crush", [Grim], 1],
	["Cry", [Grim], 1],
	["Cut", [Grim], 1],
	["Death", [Grim], 1],
	["Devil", [Grim], 1],
	["Dire", [Grim], 1],
	["Dog", [Grim], 1],
	["Doom", [Grim], 1],
	["Dragon", [Grim], 1],
	["Dread", [Grim], 1],
	["Dreg", [Grim], 1],
	["Drink", [Grim], 1],
	["Drinker", [Grim], 1],
	["Drool", [Grim], 1],
	["Dung", [Grim], 1],
	["Eat", [Grim], 1],
	["Eater", [Grim], 1],
	["Eye", [Grim], 1],
	["Eye", [Grim], 1],
	["Face", [Grim], 1],
	["Fang", [Grim], 1],
	["Fat", [Grim], 1],
	["Feast", [Grim], 1],
	["Fester", [Grim], 1],
	["Fiddle", [Grim], 1],
	["Fiend", [Grim], 1],
	["Filth", [Grim], 1],
	["Fire", [Grim], 1],
	["Fist", [Grim], 1],
	["Flame", [Grim], 1],
	["Flesh", [Grim], 1],
	["Flush", [Grim], 1],
	["Flux", [Grim], 1],
	["Foam", [Grim], 1],
	["Foul", [Grim], 1],
	["Froth", [Grim], 1],
	["Fume", [Grim], 1],
	["Fury", [Grim], 1],
	["Gall", [Grim], 1],
	["Gibber", [Grim], 1],
	["Gloom", [Grim], 1],
	["Glop", [Grim], 1],
	["Glut", [Grim], 1],
	["Glutton", [Grim], 1],
	["Gnash", [Grim], 1],
	["Gnaw", [Grim], 1],
	["Gob", [Grim], 1],
	["Gobble", [Grim], 1],
	["Gore", [Grim], 1],
	["Grab", [Grim], 1],
	["Grasp", [Grim], 1],
	["Gray", [Grim], 1],
	["Green", [Grim], 1],
	["Grief", [Grim], 1],
	["Grim", [Grim], 1],
	["Grin", [Grim], 1],
	["Grin", [Grim], 1],
	["Grind", [Grim], 1],
	["Gristle", [Grim], 1],
	["Gross", [Grim, Gross], 1],
	["Growler", [Grim], 1],
	["Grue", [Grim], 1],
	["Grumble", [Grim], 1],
	["Grunt", [Grim], 1],
	["Gut", [Grim], 1],
	["Hack", [Grim], 1],
	["Hammer", [Grim], 1],
	["Hate", [Grim], 1],
	["Hawk", [Grim], 1],
	["Haze", [Grim], 1],
	["Head", [Grim], 1],
	["Heart", [Grim], 1],
	["Helm", [Grim], 1],
	["Horn", [Grim], 1],
	["Hot", [Grim], 1],
	["Howl", [Grim], 1],
	["Ice", [Grim], 1],
	["Ichor", [Grim], 1],
	["Jade", [Grim], 1],
	["Kill", [Grim], 1],
	["Killer", [Grim], 1],
	["Lash", [Grim], 1],
	["Leper", [Grim], 1],
	["Lick", [Grim], 1],
	["Lip", [Grim], 1],
	["Liver", [Grim], 1],
	["Loath", [Grim], 1],
	["Loose", [Grim], 1],
	["Lust", [Grim], 1],
	["Mad", [Grim], 1],
	["Maggot", [Grim], 1],
	["Maim", [Grim], 1],
	["Mange", [Grim], 1],
	["Mark", [Grim], 1],
	["Maul", [Grim], 1],
	["Maw", [Grim], 1],
	["Mildew", [Grim], 1],
	["Mind", [Grim], 1],
	["Mire", [Grim], 1],
	["Mold", [Grim], 1],
	["Moon", [Grim], 1],
	["Moulder", [Grim], 1],
	["Mucus", [Grim, Gross], 1],
	["Nibble", [Grim], 1],
	["Night", [Grim], 1],
	["Offal", [Grim], 1],
	["Ooze", [Grim], 1],
	["Pain", [Grim], 1],
	["Pest", [Grim], 1],
	["Pierce", [Grim], 1],
	["Pile", [Grim], 1],
	["Pinch", [Grim], 1],
	["Pit", [Grim], 1],
	["Plague", [Grim], 1],
	["Poison", [Grim], 1],
	["Pox", [Grim], 1],
	["Puke", [Grim], 1],
	["Pulse", [Grim], 1],
	["Pus", [Grim], 1],
	["Putrid", [Grim], 1],
	["Quake", [Grim], 1],
	["Quiver", [Grim], 1],
	["Rabid", [Grim], 1],
	["Raven", [Grim], 1],
	["Razor", [Grim], 1],
	["Reap", [Grim], 1],
	["Red", [Grim], 1],
	["Rend", [Grim], 1],
	["Rip", [Grim], 1],
	["Ripper", [Grim], 1],
	["Rot", [Grim], 1],
	["Rotten", [Grim], 1],
	["Rust", [Grim], 1],
	["Sate", [Grim], 1],
	["Scab", [Grim], 1],
	["Scrape", [Grim], 1],
	["Scratch", [Grim], 1],
	["Screech", [Grim], 1],
	["Scum", [Grim], 1],
	["Seethe", [Grim], 1],
	["Shadow", [Grim], 1],
	["Shank", [Grim], 1],
	["Shard", [Grim], 1],
	["Sharp", [Grim], 1],
	["Shield", [Grim], 1],
	["Shifter", [Grim], 1],
	["Shine", [Grim], 1],
	["Shout", [Grim], 1],
	["Sin", [Grim], 1],
	["Sinew", [Grim], 1],
	["Skin", [Grim], 1],
	["Skull", [Grim], 1],
	["Skull", [Grim], 1],
	["Slake", [Grim], 1],
	["Slash", [Grim], 1],
	["Slice", [Grim], 1],
	["Slime", [Grim], 1],
	["Slob", [Grim], 1],
	["Slobber", [Grim], 1],
	["Sludge", [Grim], 1],
	["Slug", [Grim], 1],
	["Snarl", [Grim], 1],
	["Snot", [Grim], 1],
	["Sore", [Grim], 1],
	["Soul", [Grim], 1],
	["Spasm", [Grim], 1],
	["Spawn", [Grim], 1],
	["Spell", [Grim], 1],
	["Spew", [Grim], 1],
	["Spider", [Grim], 1],
	["Spike", [Grim], 1],
	["Spine", [Grim], 1],
	["Spirit", [Grim], 1],
	["Spite", [Grim], 1],
	["Spittle", [Grim], 1],
	["Spore", [Grim], 1],
	["Spot", [Grim], 1],
	["Star", [Grim], 1],
	["Stare", [Grim], 1],
	["Steel", [Grim], 1],
	["Sting", [Grim], 1],
	["Stone", [Grim], 1],
	["Storm", [Grim], 1],
	["Suck", [Grim], 1],
	["Sweat", [Grim], 1],
	["Sword", [Grim], 1],
	["Taint", [Grim], 1],
	["Tear", [Grim], 1],
	["Thigh", [Grim], 1],
	["Thirst", [Grim], 1],
	["Thorn", [Grim], 1],
	["Thrash", [Grim], 1],
	["Thrust", [Grim], 1],
	["Toad", [Grim], 1],
	["Tongue", [Grim], 1],
	["Touch", [Grim], 1],
	["Tremble", [Grim], 1],
	["Twist", [Grim], 1],
	["Venom", [Grim], 1],
	["Vex", [Grim], 1],
	["Vile", [Grim], 1],
	["Viper", [Grim], 1],
	["Vomit", [Grim], 1],
	["Wail", [Grim], 1],
	["War", [Grim], 1],
	["Warp", [Grim], 1],
	["Wart", [Grim], 1],
	["Water", [Grim], 1],
	["Weaver", [Grim], 1],
	["Web", [Grim], 1],
	["Whine", [Grim], 1],
	["Whip", [Grim], 1],
	["Widow", [Grim], 1],
	["Wight", [Grim], 1],
	["Wind", [Grim], 1],
	["Wing", [Grim], 1],
	["Wither", [Grim], 1],
	["Wolf", [Grim], 1],
	["Worm", [Grim], 1],
	["Worship", [Grim], 1],
	["Wound", [Grim], 1],
	["Wrack", [Grim], 1],
	["Wrath", [Grim], 1],
	["Wraith", [Grim], 1]
]


export const anatomical: TaggedItem[] = [
	['hand', [Anatomical], 1],
	['nose', [Anatomical], 1],
	['eye', [Anatomical], 1],
	['heart', [Anatomical], 1],
	['foot', [Anatomical], 1],
	['tongue', [Anatomical], 1],
	['beard', [Anatomical], 1],
	['toe', [Anatomical], 1],
	['finger', [Anatomical], 1],
	['claw', [Anatomical], 1],
	['fang', [Anatomical], 1],
	['tooth', [Anatomical], 1],
	['fist', [Anatomical], 1],
	['tusk', [Anatomical], 1],
	['talon', [Anatomical], 1],
	['bone', [Anatomical], 1]
]

export const fluid: TaggedItem[] = [
	['puss', [Fluid, Gross], 1],
	['drool', [Fluid, Gross], 1],
	['blood', [Fluid], 1],
	['bile', [Fluid, Gross], 1],
	['ichor', [Fluid], 1],
	['snot', [Fluid, Gross], 1],
	['ale', [Fluid], 1],
	['wine', [Fluid], 1],
	['mead', [Fluid], 1],
	['brew', [Fluid], 1],
	['water', [Fluid], 1],
	['brine', [Fluid], 1]
]

export const weapon: TaggedItem[] = [
	['hammer', [Weapon], 1],
	['sword', [Weapon], 1],
	['flail', [Weapon], 1],
	['dagger', [Weapon], 1],
	['staff', [Weapon], 1],
	['axe', [Weapon], 1]
]

export const armor: TaggedItem[] = [
	['shield', [Armor], 1],
	['mail', [Armor], 1],
	['greaves', [Armor], 1],
	['helm', [Armor], 1],
	['cloak', [Armor], 1],
	['gauntlet', [Armor], 1]
]
export const animal: TaggedItem[] = [
	['raven', [Animal], 1],
	['viper', [Animal], 1],
	['crow', [Animal], 1],
	['wolf', [Animal], 1],
	['badger', [Animal], 1],
	['shrew', [Animal], 1],
	['spider', [Animal], 1],
	['toad', [Animal], 1],
	['sloth', [Animal], 1],
	['weasel', [Animal], 1]
]
export const material: TaggedItem[] = [
	['iron', [Material, Metal], 1],
	['salt', [Material, Mineral], 1],
	['oak', [Material, Wood], 1],
	['silver', [Material, Metal], 1],
	['ash', [Material], 1]
]
export const agentive: TaggedItem[] = [
	['eater', [Agentive, Suffix], 1],
	['crawler', [Agentive, Suffix], 1],
	['drinker', [Agentive, Suffix], 1],
	['slayer', [Agentive, Suffix], 1],
	['gutter', [Agentive, Suffix], 1],
	['monger', [Agentive, Suffix], 1],
	['stalker', [Agentive, Suffix], 1],
	['weaver', [Agentive, Suffix], 1]
]
export const gerund: TaggedItem[] = [
	['festering', [Gerund], 1],
	['withering', [Gerund], 1],
	['dwindling', [Gerund], 1],
	['fizzling', [Gerund], 1],
	['glimmering', [Gerund], 1],
	['shimmering', [Gerund], 1]
]

export const condition: TaggedItem[] = [
	['Grand', [Condition], 1],
	['Pristine', [Condition], 1],
	['Terraced', [Condition], 1],
	['Shattered', [Condition], 1],
	['Broken', [Condition], 1],
	['Fallen', [Condition], 1],
	['Crumbling', [Condition], 1],
	['Splintered', [Condition], 1],
	['Worn', [Condition], 1],
	['Collapsed', [Condition], 1],
	['Scorched', [Condition], 1],
	['Unstable', [Condition], 1],
	['Weathered', [Condition], 1],
	['Warped', [Condition], 1],
	['Rusty', [Condition], 1],
	['Sunken', [Condition], 1],
	['Tangled', [Condition], 1],
	['Twisted', [Condition], 1],
	['Tarnished', [Condition], 1],
	['Sinking', [Condition], 1],
	['Smoldering', [Condition], 1],
	['Odious', [Condition], 1],
	['Moldy', [Condition], 1],
	['Eroded', [Condition], 1],
	['Overgrown', [Condition], 1],
	['Lost', [Condition], 1],
	['Ancient', [Condition], 1],
	['Bald', [Condition], 1],
	['Hollow', [Condition], 1],
	['Forgotten', [Condition], 1],
	['Jagged', [Condition], 1],
	['Cloudy', [Condition], 1],
	['Foggy', [Condition], 1],
	['Wrinkled', [Condition], 1],
	['Mossy', [Condition], 1],
	['Drifting', [Condition], 1],
	['Looming', [Condition], 1],
	['Lurking', [Condition], 1],
	['Remote', [Condition], 1],
	['Barbed', [Condition], 1],
	['Shrouded', [Condition], 1],
	['Thermal', [Condition], 1],
	['Crested', [Condition], 1],
	['Spined', [Condition], 1],
	['Serrated', [Condition], 1],
	['Forsaken', [Condition], 1],
	['Dormant', [Condition], 1],
]

export const effect: TaggedItem[] = [
	['Glowing', [Effect], 1],
	['Shimmering', [Effect], 1],
	['Levitating', [Effect], 1],
	['Wandering', [Effect], 1],
	['Endless', [Effect], 1],
	['Drifting', [Effect], 1],
	['Radiant', [Effect], 1],
	['Howling', [Effect], 1],
	['Screaming', [Effect], 1],
	['Inverted', [Effect], 1],
	['Whispering', [Effect], 1],
	['Frozen', [Effect], 1],
	['Colossal', [Effect], 1],
	['Cursed', [Effect], 1],
	['Haunted', [Effect], 1],
	['Withering', [Effect], 1],
	['Creeping', [Effect], 1],
	['Magnetic', [Effect], 1],
	['Luminous', [Effect], 1],
	['Irridescent', [Effect], 1],
	['Jeweled', [Effect], 1],
	['Ghostly', [Effect], 1],
	['Caustic', [Effect], 1],
	['Shifting', [Effect], 1],
	['Whirling', [Effect], 1],
	['Spiraling', [Effect], 1],
]

export const nameWords: TaggedItem[] = [
	...colors,
	...silly,
	...grim,
	...anatomical,
	...animal,
	...weapon,
	...armor,
	...fluid,
	...material,
	...gerund

]