import { TaggedItem } from '../types/types'
import { filterByTag } from '../types/types'
import {
  ADJECTIVE, PARTICIPLE, CREATURE, UNDEAD, GOBLINOID, ANIMAL, INSECT, NONHUMAN,
  SMALL, MEDIUM, BIG, UNDERGROUND,
  EVIL, GOOD, NEUTRAL_TONE, MAGICAL, MUNDANE,
  MATERIAL_STONE, MATERIAL_METAL, MATERIAL_WOOD, MATERIAL_GEMSTONE, MATERIAL_MISC,
  MOUNTAIN, RIVER, FOREST, SWAMP, CAVE, DUNGEON, TEMPLE, TOMB, TAVERN,
  CITY, TOWER, OCEAN, HILLS, MINE, CANYON, BRIDGE, STONE,
  CONDITION, EFFECT,
} from './tags'
import {
  dungeon_materials, dungeon_objects, dungeon_adjective,
  dungeon_bridge_adjective, dungeon_corridor_adjective, dungeon_portal_adjective,
  dungeon_stairway_adjective, dungeon_pit_adjective,
  tomb_objects, tomb_adjective,
  temple_objects, temple_adjective,
  cavern_materials, cavern_objects, cavern_adjective,
  magical_materials, magical_objects, magical_adjective,
} from './dungeon_rooms'

// CREATURES (used as adjective modifiers and possessives)

export const creatures: TaggedItem[] = [
  // Small
  ["Imp",             [ADJECTIVE, CREATURE, SMALL], 2],
  ["Spore",           [ADJECTIVE, CREATURE, SMALL], 2],
  ["Stirge",          [ADJECTIVE, CREATURE, SMALL], 1],
  // Big
  ["Dragon",          [ADJECTIVE, CREATURE, BIG], 2],
  ["Wyrm",            [ADJECTIVE, CREATURE, BIG], 2],
  ["Sphinx",          [ADJECTIVE, CREATURE, BIG], 1],
  ["Hydra",           [ADJECTIVE, CREATURE, BIG], 2],
  ["Griffon",         [ADJECTIVE, CREATURE, BIG], 2],
  ["Giant",           [ADJECTIVE, CREATURE, BIG], 2],
  // Medium
  ["Gargoyle",        [ADJECTIVE, CREATURE, MEDIUM], 2],
  ["Golem",           [ADJECTIVE, CREATURE, MEDIUM], 2],
  ["Demon",           [ADJECTIVE, CREATURE, MEDIUM], 2],
  ["Devil",           [ADJECTIVE, CREATURE, MEDIUM], 2],
  // Insect / Animal
  ["Spider",          [ADJECTIVE, CREATURE, ANIMAL, INSECT], 2],
  ["Ant",             [ADJECTIVE, CREATURE, ANIMAL, INSECT], 2],
  ["Rat",             [ADJECTIVE, CREATURE, ANIMAL], 3],
  ["Raven",           [ADJECTIVE, CREATURE, ANIMAL], 2],
  ["Frog",            [ADJECTIVE, CREATURE, ANIMAL], 2],
  ["Serpent",         [ADJECTIVE, CREATURE, ANIMAL], 2],
  ["Leech",           [ADJECTIVE, CREATURE, ANIMAL], 2],
  ["Bat",             [ADJECTIVE, CREATURE, ANIMAL], 2],
  ["Bear",            [ADJECTIVE, CREATURE, ANIMAL], 2],
  // Goblinoid
  ["Troll",           [ADJECTIVE, CREATURE, GOBLINOID], 2],
  ["Ogre",            [ADJECTIVE, CREATURE, GOBLINOID], 2],
  ["Gnoll",           [ADJECTIVE, CREATURE, GOBLINOID], 2],
  ["Bugbear",         [ADJECTIVE, CREATURE, GOBLINOID], 2],
  ["Hobgoblin",       [ADJECTIVE, CREATURE, GOBLINOID], 2],
  ["Orc",             [ADJECTIVE, CREATURE, GOBLINOID], 3],
  ["Goblin",          [ADJECTIVE, CREATURE, GOBLINOID], 3],
  ["Kobold",          [ADJECTIVE, CREATURE, GOBLINOID], 2],
  ["Cyclops",         [ADJECTIVE, CREATURE, GOBLINOID], 2],
  ["Minotaur",        [ADJECTIVE, CREATURE, GOBLINOID], 2],
  ["Troglodyte",      [ADJECTIVE, CREATURE, GOBLINOID, UNDERGROUND], 2],
  // Nonhuman
  ["Dwarf",           [ADJECTIVE, CREATURE, NONHUMAN], 2],
  ["Elf",             [ADJECTIVE, CREATURE, NONHUMAN], 2],
  ["Gnome",           [ADJECTIVE, CREATURE, NONHUMAN], 2],
  ["Halfling",        [ADJECTIVE, CREATURE, NONHUMAN], 2],
  ["Drow",            [ADJECTIVE, CREATURE, NONHUMAN, UNDERGROUND], 2],
  // Undead
  ["Skeleton",        [ADJECTIVE, CREATURE, UNDEAD], 3],
  ["Zombie",          [ADJECTIVE, CREATURE, UNDEAD], 3],
  ["Ghoul",           [ADJECTIVE, CREATURE, UNDEAD], 2],
  ["Ghost",           [ADJECTIVE, CREATURE, UNDEAD], 2],
  ["Wight",           [ADJECTIVE, CREATURE, UNDEAD], 2],
  ["Wraith",          [ADJECTIVE, CREATURE, UNDEAD], 2],
  ["Spectre",         [ADJECTIVE, CREATURE, UNDEAD], 2],
  // Underground (non-undead, non-goblinoid)
  ["Carrion Crawler", [ADJECTIVE, CREATURE, UNDERGROUND, MEDIUM], 1],
  ["Piercer",         [ADJECTIVE, CREATURE, UNDERGROUND, SMALL], 1],
]

// COLORS

export const color: TaggedItem[] = [
  ["Azure",    [ADJECTIVE, MUNDANE], 2],
  ["Cobalt",   [ADJECTIVE, MUNDANE], 2],
  ["Verdigris",[ADJECTIVE, MUNDANE], 1],
  ["Pale",     [ADJECTIVE, MUNDANE], 2],
  ["Dark",     [ADJECTIVE, MUNDANE], 3],
  ["Dim",      [ADJECTIVE, MUNDANE], 2],
  ["Umber",    [ADJECTIVE, MUNDANE], 2],
  ["Amber",    [ADJECTIVE, MUNDANE], 2],
  ["Burgundy", [ADJECTIVE, MUNDANE], 2],
  ["Crimson",  [ADJECTIVE, MUNDANE], 2],
  ["Ocher",    [ADJECTIVE, MUNDANE], 2],
  ["Rainbow",  [ADJECTIVE, MUNDANE], 2],
  ["Magenta",  [ADJECTIVE, MUNDANE], 2],
  ["Cyan",     [ADJECTIVE, MUNDANE], 2],
  ["Gray",     [ADJECTIVE, MUNDANE], 3],
  ["Black",    [ADJECTIVE, MUNDANE], 3],
  ["White",    [ADJECTIVE, MUNDANE], 3],
  ["Red",      [ADJECTIVE, MUNDANE], 3],
  ["Blue",     [ADJECTIVE, MUNDANE], 3],
  ["Green",    [ADJECTIVE, MUNDANE], 3],
  ["Orange",   [ADJECTIVE, MUNDANE], 2],
  ["Violet",   [ADJECTIVE, MUNDANE], 2],
  ["Yellow",   [ADJECTIVE, MUNDANE], 2],
  ["Sepia",    [ADJECTIVE, MUNDANE], 2],
  ["Cerulean", [ADJECTIVE, MUNDANE], 1],
  ["Alizerin", [ADJECTIVE, MUNDANE], 1],
  ["Ebon",     [ADJECTIVE, MUNDANE], 2],
  ["Veridian", [ADJECTIVE, MUNDANE], 2],
  ["Dun",      [ADJECTIVE, MUNDANE], 2],
]

// EMOTIVE

export const emotives: TaggedItem[] = [
  // Good
  ["Celestial",   [ADJECTIVE, GOOD], 2],
  ["Holy",        [ADJECTIVE, GOOD], 3],
  ["Sacred",      [ADJECTIVE, GOOD], 2],
  ["Consecrated", [ADJECTIVE, GOOD], 2],
  ["Pure",        [ADJECTIVE, GOOD], 2],
  ["Great",       [ADJECTIVE, GOOD], 3],
  ["Angelic",     [ADJECTIVE, GOOD], 2],
  ["Regal",       [ADJECTIVE, GOOD], 2],
  ["Heraldic",    [ADJECTIVE, GOOD], 2],
  ["Imperial",    [ADJECTIVE, GOOD], 2],
  ["Royal",       [ADJECTIVE, GOOD], 2],
  ["Blessed",     [ADJECTIVE, GOOD], 2],
  ["Ancestral",   [ADJECTIVE, GOOD], 2],
  ["Mystic",      [ADJECTIVE, GOOD], 2],
  ["Tranquil",    [ADJECTIVE, GOOD], 2],
  // Neutral
  ["Weird",        [ADJECTIVE, NEUTRAL_TONE], 2],
  ["Mysterious",   [ADJECTIVE, NEUTRAL_TONE], 2],
  ["Cryptic",      [ADJECTIVE, NEUTRAL_TONE], 2],
  ["Lunar",        [ADJECTIVE, NEUTRAL_TONE], 2],
  ["Elder",        [ADJECTIVE, NEUTRAL_TONE], 2],
  ["Fey",          [ADJECTIVE, NEUTRAL_TONE], 2],
  ["Eldritch",     [ADJECTIVE, NEUTRAL_TONE], 2],
  ["Lonely",       [ADJECTIVE, NEUTRAL_TONE], 2],
  ["Strange",      [ADJECTIVE, NEUTRAL_TONE], 2],
  ["Wonderous",    [ADJECTIVE, NEUTRAL_TONE], 2],
  ["Arcane",       [ADJECTIVE, NEUTRAL_TONE, MAGICAL], 2],
  ["Enchanted",    [ADJECTIVE, NEUTRAL_TONE, MAGICAL], 2],
  ["Eerie",        [ADJECTIVE, NEUTRAL_TONE], 2],
  ["Quiet",        [ADJECTIVE, NEUTRAL_TONE], 2],
  ["Obscure",      [ADJECTIVE, NEUTRAL_TONE], 2],
  ["Disenchanted", [ADJECTIVE, NEUTRAL_TONE], 2],
  ["Ingenious",    [ADJECTIVE, NEUTRAL_TONE], 2],
  // Evil
  ["Creepy",       [ADJECTIVE, EVIL], 2],
  ["Vile",         [ADJECTIVE, EVIL], 2],
  ["Cursed",       [ADJECTIVE, EVIL], 3],
  ["Toxic",        [ADJECTIVE, EVIL], 2],
  ["Noxious",      [ADJECTIVE, EVIL], 2],
  ["Putrid",       [ADJECTIVE, EVIL], 2],
  ["Pitch Black",  [ADJECTIVE, EVIL], 2],
  ["Desecrated",   [ADJECTIVE, EVIL], 2],
  ["Awful",        [ADJECTIVE, EVIL], 2],
  ["Demonic",      [ADJECTIVE, EVIL], 2],
  ["Infernal",     [ADJECTIVE, EVIL], 2],
  ["Dire",         [ADJECTIVE, EVIL], 2],
  ["Grim",         [ADJECTIVE, EVIL], 3],
  ["Rancid",       [ADJECTIVE, EVIL], 2],
  ["Foul",         [ADJECTIVE, EVIL], 2],
  ["Dreary",       [ADJECTIVE, EVIL], 2],
  ["Abyssal",      [ADJECTIVE, EVIL], 1],
  ["Corrupted",    [ADJECTIVE, EVIL], 2],
  ["Contaminated", [ADJECTIVE, EVIL], 2],
  ["Diabolic",     [ADJECTIVE, EVIL], 2],
  ["Cruel",        [ADJECTIVE, EVIL], 2],
  ["Wretched",     [ADJECTIVE, EVIL], 2],
  ["Fetid",        [ADJECTIVE, EVIL], 2],
  ["Unnatural",    [ADJECTIVE, EVIL], 2],
  ["Infested",     [ADJECTIVE, EVIL], 2],
  ["Sinister",     [ADJECTIVE, EVIL], 2],
  ["Suspicious",   [ADJECTIVE, EVIL], 2],
  ["Defiled",      [ADJECTIVE, EVIL], 2],
  ["Insidious",    [ADJECTIVE, EVIL], 2],
  ["Blackflame",   [ADJECTIVE, EVIL], 1],
  ["Dismal",       [ADJECTIVE, EVIL], 2],
  ["Gloomy",       [ADJECTIVE, EVIL], 2],
  ["Murky",        [ADJECTIVE, EVIL], 2],
]

// MATERIAL

export const materials: TaggedItem[] = [
  // Wood
  ["Oaken",    [ADJECTIVE, MATERIAL_WOOD], 2],
  ["Cedar",    [ADJECTIVE, MATERIAL_WOOD], 2],
  ["Ash",      [ADJECTIVE, MATERIAL_WOOD], 2],
  ["Wooden",   [ADJECTIVE, MATERIAL_WOOD], 3],
  ["Redwood",  [ADJECTIVE, MATERIAL_WOOD], 2],
  ["Mahogany", [ADJECTIVE, MATERIAL_WOOD], 2],
  // Gemstone
  ["Emerald",    [ADJECTIVE, MATERIAL_GEMSTONE], 2],
  ["Jade",       [ADJECTIVE, MATERIAL_GEMSTONE], 2],
  ["Onyx",       [ADJECTIVE, MATERIAL_GEMSTONE], 2],
  ["Ruby",       [ADJECTIVE, MATERIAL_GEMSTONE], 2],
  ["Topaz",      [ADJECTIVE, MATERIAL_GEMSTONE], 2],
  ["Crystal",    [ADJECTIVE, MATERIAL_GEMSTONE], 2],
  ["Sapphire",   [ADJECTIVE, MATERIAL_GEMSTONE], 2],
  ["Amethyst",   [ADJECTIVE, MATERIAL_GEMSTONE], 2],
  ["Garnet",     [ADJECTIVE, MATERIAL_GEMSTONE], 2],
  ["Coral",      [ADJECTIVE, MATERIAL_GEMSTONE, OCEAN], 2],
  ["Beryl",      [ADJECTIVE, MATERIAL_GEMSTONE], 2],
  ["Lapis",      [ADJECTIVE, MATERIAL_GEMSTONE], 2],
  ["Ivory",      [ADJECTIVE, MATERIAL_GEMSTONE, OCEAN], 2],
  ["Turquoise",  [ADJECTIVE, MATERIAL_GEMSTONE, OCEAN], 2],
  ["Ambergris",  [ADJECTIVE, MATERIAL_GEMSTONE], 1],
  ["Opal",       [ADJECTIVE, MATERIAL_GEMSTONE, OCEAN], 2],
  ["Greenstone", [ADJECTIVE, MATERIAL_GEMSTONE], 2],
  ["Bloodstone", [ADJECTIVE, MATERIAL_GEMSTONE], 2],
  // Metal
  ["Brass",      [ADJECTIVE, MATERIAL_METAL], 2],
  ["Copper",     [ADJECTIVE, MATERIAL_METAL], 2],
  ["Iron",       [ADJECTIVE, MATERIAL_METAL], 3],
  ["Silver",     [ADJECTIVE, MATERIAL_METAL, OCEAN], 2],
  ["Mithril",    [ADJECTIVE, MATERIAL_METAL], 1],
  ["Platinum",   [ADJECTIVE, MATERIAL_METAL], 2],
  ["Bronze",     [ADJECTIVE, MATERIAL_METAL], 2],
  ["Steel",      [ADJECTIVE, MATERIAL_METAL], 2],
  ["Gold",       [ADJECTIVE, MATERIAL_METAL], 2],
  ["Lead",       [ADJECTIVE, MATERIAL_METAL], 2],
  ["Alloy",      [ADJECTIVE, MATERIAL_METAL], 2],
  ["Adamantite", [ADJECTIVE, MATERIAL_METAL], 1],
  // Stone
  ["Obsidian",   [ADJECTIVE, MATERIAL_STONE], 2],
  ["Granite",    [ADJECTIVE, MATERIAL_STONE], 2],
  ["Marble",     [ADJECTIVE, MATERIAL_STONE], 2],
  ["Flint",      [ADJECTIVE, MATERIAL_STONE], 2],
  ["Flowstone",  [ADJECTIVE, MATERIAL_STONE], 2],
  ["Limestone",  [ADJECTIVE, MATERIAL_STONE], 2],
  ["Sandstone",  [ADJECTIVE, MATERIAL_STONE], 2],
  ["Basalt",     [ADJECTIVE, MATERIAL_STONE], 2],
  ["Concrete",   [ADJECTIVE, MATERIAL_STONE], 2],
  ["Igneous",    [ADJECTIVE, MATERIAL_STONE], 2],
  ["Greenstone", [ADJECTIVE, MATERIAL_STONE], 2],
  // Misc
  ["Alabaster",  [ADJECTIVE, MATERIAL_MISC], 2],
  ["Bone",       [ADJECTIVE, MATERIAL_MISC], 2],
  ["Dung",       [ADJECTIVE, MATERIAL_MISC], 2],
  ["Sand",       [ADJECTIVE, MATERIAL_MISC], 2],
  ["Salt",       [ADJECTIVE, MATERIAL_MISC, OCEAN], 2],
  ["Glass",      [ADJECTIVE, MATERIAL_MISC, OCEAN], 2],
  ["Brimstone",  [ADJECTIVE, MATERIAL_MISC], 2],
  ["Sulpher",    [ADJECTIVE, MATERIAL_MISC], 2],
  ["Brine",      [ADJECTIVE, MATERIAL_MISC, OCEAN], 2],
  ["Ambergris",  [ADJECTIVE, MATERIAL_MISC], 1],
  ["Fungal",     [ADJECTIVE, MATERIAL_MISC], 2],
  ["Mud",        [ADJECTIVE, MATERIAL_MISC], 3],
  ["Pitch",      [ADJECTIVE, MATERIAL_MISC], 2],
  ["Sludge",     [ADJECTIVE, MATERIAL_MISC], 2],
  ["Parchment",  [ADJECTIVE, MATERIAL_MISC], 2],
  ["Woven",      [ADJECTIVE, MATERIAL_MISC], 2],
  ["Silk",       [ADJECTIVE, MATERIAL_MISC], 2],
  ["Wax",        [ADJECTIVE, MATERIAL_MISC], 2],
  ["Brick",      [ADJECTIVE, MATERIAL_MISC], 2],
  ["Ash",        [ADJECTIVE, MATERIAL_MISC], 2],
  ["Thatch",     [ADJECTIVE, MATERIAL_MISC], 2],
  ["Tar",        [ADJECTIVE, MATERIAL_MISC], 2],
  ["Porcelain",  [ADJECTIVE, MATERIAL_MISC], 2],
  ["Leather",    [ADJECTIVE, MATERIAL_MISC], 2],
  ["Slag",       [ADJECTIVE, MATERIAL_MISC], 2],
  ["Shale",      [ADJECTIVE, MATERIAL_MISC], 2],
  ["Coal",       [ADJECTIVE, MATERIAL_MISC], 2],
  ["Plaster",    [ADJECTIVE, MATERIAL_MISC], 2],
  ["Clay",       [ADJECTIVE, MATERIAL_MISC], 2],
  ["Straw",      [ADJECTIVE, MATERIAL_MISC], 2],
  ["Tephra",     [ADJECTIVE, MATERIAL_MISC], 1],
  ["Charcoal",   [ADJECTIVE, MATERIAL_MISC], 2],
  ["Lotus",      [ADJECTIVE, MATERIAL_MISC], 2],
  ["Papyrus",    [ADJECTIVE, MATERIAL_MISC], 2],
  ["Muck",       [ADJECTIVE, MATERIAL_MISC], 2],
  ["Steam",      [ADJECTIVE, MATERIAL_MISC], 2],
  ["Smog",       [ADJECTIVE, MATERIAL_MISC], 2],
  ["Blood",      [ADJECTIVE, MATERIAL_MISC, OCEAN], 2],
  ["Fog",        [ADJECTIVE, MATERIAL_MISC, OCEAN], 2],
  ["Ice",        [ADJECTIVE, MATERIAL_MISC, OCEAN], 2],
]

// CONDITIONS — tagged by terrain context; generic items have no terrain tag

export const conditions: TaggedItem[] = [
  // Generic excellent
  ["Fine",        [ADJECTIVE, CONDITION], 2],
  ["Grand",       [ADJECTIVE, CONDITION], 2],
  ["Pristine",    [ADJECTIVE, CONDITION], 2],
  ["Ornate",      [ADJECTIVE, CONDITION], 2],
  ["Engraved",    [ADJECTIVE, CONDITION], 2],
  ["Warded",      [ADJECTIVE, CONDITION], 2],
  ["Sturdy",      [ADJECTIVE, CONDITION], 2],
  ["Bright",      [ADJECTIVE, CONDITION], 2],
  ["Concentric",  [ADJECTIVE, CONDITION], 2],
  ["Terraced",    [ADJECTIVE, CONDITION], 2],
  ["Geometric",   [ADJECTIVE, CONDITION], 2],
  ["Gilded",      [ADJECTIVE, CONDITION], 2],
  ["Sealed",      [ADJECTIVE, CONDITION], 2],
  // Generic broken
  ["Shattered",   [ADJECTIVE, CONDITION], 2],
  ["Broken",      [ADJECTIVE, CONDITION], 2],
  ["Fallen",      [ADJECTIVE, CONDITION], 2],
  ["Crumbling",   [ADJECTIVE, CONDITION], 2],
  ["Flawed",      [ADJECTIVE, CONDITION], 2],
  ["Faulty",      [ADJECTIVE, CONDITION], 2],
  ["Splintered",  [ADJECTIVE, CONDITION], 2],
  ["Chipped",     [ADJECTIVE, CONDITION], 2],
  ["Worn",        [ADJECTIVE, CONDITION], 2],
  ["Collapsed",   [ADJECTIVE, CONDITION], 2],
  ["Scorched",    [ADJECTIVE, CONDITION], 2],
  ["Unstable",    [ADJECTIVE, CONDITION], 2],
  ["Decayed",     [ADJECTIVE, CONDITION], 2],
  ["Defaced",     [ADJECTIVE, CONDITION], 2],
  ["Weathered",   [ADJECTIVE, CONDITION], 2],
  ["Warped",      [ADJECTIVE, CONDITION], 2],
  ["Rotting",     [ADJECTIVE, CONDITION], 2],
  ["Rusty",       [ADJECTIVE, CONDITION], 2],
  ["Sunken",      [ADJECTIVE, CONDITION], 2],
  ["Tangled",     [ADJECTIVE, CONDITION], 2],
  ["Twisted",     [ADJECTIVE, CONDITION], 2],
  ["Tarnished",   [ADJECTIVE, CONDITION], 2],
  ["Sinking",     [ADJECTIVE, CONDITION], 2],
  ["Smoldering",  [ADJECTIVE, CONDITION], 2],
  ["Flooded",     [ADJECTIVE, CONDITION], 2],
  ["Pilfered",    [ADJECTIVE, CONDITION], 2],
  ["Odious",      [ADJECTIVE, CONDITION], 2],
  ["Moldy",       [ADJECTIVE, CONDITION], 2],
  ["Eroded",      [ADJECTIVE, CONDITION], 2],
  ["Rusting",     [ADJECTIVE, CONDITION], 2],
  ["Overgrown",   [ADJECTIVE, CONDITION], 2],
  ["Leaking",     [ADJECTIVE, CONDITION], 2],
  ["Drained",     [ADJECTIVE, CONDITION], 2],
  // Generic misc
  ["Dusty",       [ADJECTIVE, CONDITION], 2],
  ["Lost",        [ADJECTIVE, CONDITION], 2],
  ["Mottled",     [ADJECTIVE, CONDITION], 2],
  ["Ancient",     [ADJECTIVE, CONDITION], 3],
  ["Bald",        [ADJECTIVE, CONDITION], 2],
  ["Hollow",      [ADJECTIVE, CONDITION], 2],
  ["Balanced",    [ADJECTIVE, CONDITION], 2],
  ["Forgotten",   [ADJECTIVE, CONDITION], 2],
  ["Abandoned",   [ADJECTIVE, CONDITION], 2],
  ["Jagged",      [ADJECTIVE, CONDITION], 2],
  ["Dull",        [ADJECTIVE, CONDITION], 2],
  ["Viscous",     [ADJECTIVE, CONDITION], 2],
  ["Cloudy",      [ADJECTIVE, CONDITION], 2],
  ["Greasy",      [ADJECTIVE, CONDITION], 2],
  ["Unfinished",  [ADJECTIVE, CONDITION], 2],
  ["Renovated",   [ADJECTIVE, CONDITION], 2],
  ["Repaired",    [ADJECTIVE, CONDITION], 2],
  ["Foggy",       [ADJECTIVE, CONDITION], 2],
  ["Speckled",    [ADJECTIVE, CONDITION], 2],
  ["Wrinkled",    [ADJECTIVE, CONDITION], 2],
  ["Veiled",      [ADJECTIVE, CONDITION], 2],
  ["Rebuilt",     [ADJECTIVE, CONDITION], 2],
  ["Mossy",       [ADJECTIVE, CONDITION], 2],
  ["Slippery",    [ADJECTIVE, CONDITION], 2],
  ["Drifting",    [ADJECTIVE, CONDITION], 2],
  ["Looming",     [ADJECTIVE, CONDITION], 2],
  ["Lurking",     [ADJECTIVE, CONDITION], 2],
  ["Remote",      [ADJECTIVE, CONDITION], 2],
  ["Dry",         [ADJECTIVE, CONDITION], 2],
  ["Squirming",   [ADJECTIVE, CONDITION], 2],
  ["False",       [ADJECTIVE, CONDITION], 2],
  ["Barbed",      [ADJECTIVE, CONDITION], 2],
  ["Shrouded",    [ADJECTIVE, CONDITION], 2],
  ["Thermal",     [ADJECTIVE, CONDITION], 2],
  ["Crested",     [ADJECTIVE, CONDITION], 2],
  ["Spined",      [ADJECTIVE, CONDITION], 2],
  ["Spiked",      [ADJECTIVE, CONDITION], 2],
  ["Serrated",    [ADJECTIVE, CONDITION], 2],
  ["Scaled",      [ADJECTIVE, CONDITION], 2],
  ["Shallow",     [ADJECTIVE, CONDITION], 2],
  ["Forsaken",    [ADJECTIVE, CONDITION], 2],
  ["Dormant",     [ADJECTIVE, CONDITION], 2],
  ["Nocturnal",   [ADJECTIVE, CONDITION], 2],
  ["Cyclopean",   [ADJECTIVE, CONDITION], 2],
  // Mountain
  ["Grand",       [ADJECTIVE, CONDITION, MOUNTAIN], 2],
  ["Terraced",    [ADJECTIVE, CONDITION, MOUNTAIN], 2],
  ["Shattered",   [ADJECTIVE, CONDITION, MOUNTAIN], 2],
  ["Broken",      [ADJECTIVE, CONDITION, MOUNTAIN], 2],
  ["Fallen",      [ADJECTIVE, CONDITION, MOUNTAIN], 2],
  ["Crumbling",   [ADJECTIVE, CONDITION, MOUNTAIN], 2],
  ["Splintered",  [ADJECTIVE, CONDITION, MOUNTAIN], 2],
  ["Worn",        [ADJECTIVE, CONDITION, MOUNTAIN], 2],
  ["Collapsed",   [ADJECTIVE, CONDITION, MOUNTAIN], 2],
  ["Scorched",    [ADJECTIVE, CONDITION, MOUNTAIN], 2],
  ["Unstable",    [ADJECTIVE, CONDITION, MOUNTAIN], 2],
  ["Weathered",   [ADJECTIVE, CONDITION, MOUNTAIN], 2],
  ["Warped",      [ADJECTIVE, CONDITION, MOUNTAIN], 2],
  ["Rusty",       [ADJECTIVE, CONDITION, MOUNTAIN], 2],
  ["Sunken",      [ADJECTIVE, CONDITION, MOUNTAIN], 2],
  ["Tangled",     [ADJECTIVE, CONDITION, MOUNTAIN], 2],
  ["Twisted",     [ADJECTIVE, CONDITION, MOUNTAIN], 2],
  ["Tarnished",   [ADJECTIVE, CONDITION, MOUNTAIN], 2],
  ["Sinking",     [ADJECTIVE, CONDITION, MOUNTAIN], 2],
  ["Smoldering",  [ADJECTIVE, CONDITION, MOUNTAIN], 2],
  ["Odious",      [ADJECTIVE, CONDITION, MOUNTAIN], 2],
  ["Moldy",       [ADJECTIVE, CONDITION, MOUNTAIN], 2],
  ["Eroded",      [ADJECTIVE, CONDITION, MOUNTAIN], 2],
  ["Overgrown",   [ADJECTIVE, CONDITION, MOUNTAIN], 2],
  ["Lost",        [ADJECTIVE, CONDITION, MOUNTAIN], 2],
  ["Ancient",     [ADJECTIVE, CONDITION, MOUNTAIN], 3],
  ["Bald",        [ADJECTIVE, CONDITION, MOUNTAIN], 2],
  ["Hollow",      [ADJECTIVE, CONDITION, MOUNTAIN], 2],
  ["Forgotten",   [ADJECTIVE, CONDITION, MOUNTAIN], 2],
  ["Jagged",      [ADJECTIVE, CONDITION, MOUNTAIN], 2],
  ["Cloudy",      [ADJECTIVE, CONDITION, MOUNTAIN], 2],
  ["Foggy",       [ADJECTIVE, CONDITION, MOUNTAIN], 2],
  ["Wrinkled",    [ADJECTIVE, CONDITION, MOUNTAIN], 2],
  ["Mossy",       [ADJECTIVE, CONDITION, MOUNTAIN], 2],
  ["Drifting",    [ADJECTIVE, CONDITION, MOUNTAIN], 2],
  ["Looming",     [ADJECTIVE, CONDITION, MOUNTAIN], 2],
  ["Lurking",     [ADJECTIVE, CONDITION, MOUNTAIN], 2],
  ["Remote",      [ADJECTIVE, CONDITION, MOUNTAIN], 2],
  ["Barbed",      [ADJECTIVE, CONDITION, MOUNTAIN], 2],
  ["Shrouded",    [ADJECTIVE, CONDITION, MOUNTAIN], 2],
  ["Thermal",     [ADJECTIVE, CONDITION, MOUNTAIN], 2],
  ["Crested",     [ADJECTIVE, CONDITION, MOUNTAIN], 2],
  ["Spined",      [ADJECTIVE, CONDITION, MOUNTAIN], 2],
  ["Serrated",    [ADJECTIVE, CONDITION, MOUNTAIN], 2],
  ["Forsaken",    [ADJECTIVE, CONDITION, MOUNTAIN], 2],
  ["Dormant",     [ADJECTIVE, CONDITION, MOUNTAIN], 2],
  ["Pristine",    [ADJECTIVE, CONDITION, MOUNTAIN], 2],
  // Forest
  ["Pristine",   [ADJECTIVE, CONDITION, FOREST], 2],
  ["Shattered",  [ADJECTIVE, CONDITION, FOREST], 2],
  ["Fallen",     [ADJECTIVE, CONDITION, FOREST], 2],
  ["Splintered", [ADJECTIVE, CONDITION, FOREST], 2],
  ["Scorched",   [ADJECTIVE, CONDITION, FOREST], 2],
  ["Decayed",    [ADJECTIVE, CONDITION, FOREST], 2],
  ["Warped",     [ADJECTIVE, CONDITION, FOREST], 2],
  ["Rotting",    [ADJECTIVE, CONDITION, FOREST], 2],
  ["Sunken",     [ADJECTIVE, CONDITION, FOREST], 2],
  ["Tangled",    [ADJECTIVE, CONDITION, FOREST], 2],
  ["Twisted",    [ADJECTIVE, CONDITION, FOREST], 2],
  ["Tarnished",  [ADJECTIVE, CONDITION, FOREST], 2],
  ["Sinking",    [ADJECTIVE, CONDITION, FOREST], 2],
  ["Smoldering", [ADJECTIVE, CONDITION, FOREST], 2],
  ["Flooded",    [ADJECTIVE, CONDITION, FOREST], 2],
  ["Moldy",      [ADJECTIVE, CONDITION, FOREST], 2],
  ["Eroded",     [ADJECTIVE, CONDITION, FOREST], 2],
  ["Overgrown",  [ADJECTIVE, CONDITION, FOREST], 2],
  ["Lost",       [ADJECTIVE, CONDITION, FOREST], 2],
  ["Mottled",    [ADJECTIVE, CONDITION, FOREST], 2],
  ["Ancient",    [ADJECTIVE, CONDITION, FOREST], 3],
  ["Forgotten",  [ADJECTIVE, CONDITION, FOREST], 2],
  ["Abandoned",  [ADJECTIVE, CONDITION, FOREST], 2],
  ["Jagged",     [ADJECTIVE, CONDITION, FOREST], 2],
  ["Cloudy",     [ADJECTIVE, CONDITION, FOREST], 2],
  ["Foggy",      [ADJECTIVE, CONDITION, FOREST], 2],
  ["Mossy",      [ADJECTIVE, CONDITION, FOREST], 2],
  ["Barbed",     [ADJECTIVE, CONDITION, FOREST], 2],
  ["Shrouded",   [ADJECTIVE, CONDITION, FOREST], 2],
  ["Spined",     [ADJECTIVE, CONDITION, FOREST], 2],
  ["Serrated",   [ADJECTIVE, CONDITION, FOREST], 2],
  ["Forsaken",   [ADJECTIVE, CONDITION, FOREST], 2],
  ["Nocturnal",  [ADJECTIVE, CONDITION, FOREST], 2],
  // Swamp
  ["Decayed",    [ADJECTIVE, CONDITION, SWAMP], 2],
  ["Rotting",    [ADJECTIVE, CONDITION, SWAMP], 2],
  ["Sunken",     [ADJECTIVE, CONDITION, SWAMP], 2],
  ["Tangled",    [ADJECTIVE, CONDITION, SWAMP], 2],
  ["Twisted",    [ADJECTIVE, CONDITION, SWAMP], 2],
  ["Sinking",    [ADJECTIVE, CONDITION, SWAMP], 2],
  ["Smoldering", [ADJECTIVE, CONDITION, SWAMP], 2],
  ["Flooded",    [ADJECTIVE, CONDITION, SWAMP], 2],
  ["Odious",     [ADJECTIVE, CONDITION, SWAMP], 2],
  ["Moldy",      [ADJECTIVE, CONDITION, SWAMP], 2],
  ["Overgrown",  [ADJECTIVE, CONDITION, SWAMP], 2],
  ["Drained",    [ADJECTIVE, CONDITION, SWAMP], 2],
  ["Lost",       [ADJECTIVE, CONDITION, SWAMP], 2],
  ["Ancient",    [ADJECTIVE, CONDITION, SWAMP], 2],
  ["Forgotten",  [ADJECTIVE, CONDITION, SWAMP], 2],
  ["Foggy",      [ADJECTIVE, CONDITION, SWAMP], 2],
  ["Veiled",     [ADJECTIVE, CONDITION, SWAMP], 2],
  ["Mossy",      [ADJECTIVE, CONDITION, SWAMP], 2],
  ["Slippery",   [ADJECTIVE, CONDITION, SWAMP], 2],
  ["Remote",     [ADJECTIVE, CONDITION, SWAMP], 2],
  ["Dry",        [ADJECTIVE, CONDITION, SWAMP], 2],
  ["Squirming",  [ADJECTIVE, CONDITION, SWAMP], 2],
  ["Shrouded",   [ADJECTIVE, CONDITION, SWAMP], 2],
  ["Shallow",    [ADJECTIVE, CONDITION, SWAMP], 2],
  ["Forsaken",   [ADJECTIVE, CONDITION, SWAMP], 2],
  ["Nocturnal",  [ADJECTIVE, CONDITION, SWAMP], 2],
  ["Peat",       [ADJECTIVE, CONDITION, SWAMP], 2],
  ["Pitch",      [ADJECTIVE, CONDITION, SWAMP], 2],
  ["Mud",        [ADJECTIVE, CONDITION, SWAMP], 2],
  ["Sludge",     [ADJECTIVE, CONDITION, SWAMP], 2],
  ["Muddy",      [ADJECTIVE, CONDITION, SWAMP], 2],
  ["Stump",      [ADJECTIVE, CONDITION, SWAMP], 2],
  // Hills
  ["Terraced",   [ADJECTIVE, CONDITION, HILLS], 2],
  ["Crumbling",  [ADJECTIVE, CONDITION, HILLS], 2],
  ["Splintered", [ADJECTIVE, CONDITION, HILLS], 2],
  ["Worn",       [ADJECTIVE, CONDITION, HILLS], 2],
  ["Scorched",   [ADJECTIVE, CONDITION, HILLS], 2],
  ["Decayed",    [ADJECTIVE, CONDITION, HILLS], 2],
  ["Weathered",  [ADJECTIVE, CONDITION, HILLS], 2],
  ["Rotting",    [ADJECTIVE, CONDITION, HILLS], 2],
  ["Sunken",     [ADJECTIVE, CONDITION, HILLS], 2],
  ["Twisted",    [ADJECTIVE, CONDITION, HILLS], 2],
  ["Sinking",    [ADJECTIVE, CONDITION, HILLS], 2],
  ["Smoldering", [ADJECTIVE, CONDITION, HILLS], 2],
  ["Moldy",      [ADJECTIVE, CONDITION, HILLS], 2],
  ["Eroded",     [ADJECTIVE, CONDITION, HILLS], 2],
  ["Overgrown",  [ADJECTIVE, CONDITION, HILLS], 2],
  ["Dusty",      [ADJECTIVE, CONDITION, HILLS], 2],
  ["Lost",       [ADJECTIVE, CONDITION, HILLS], 2],
  ["Bald",       [ADJECTIVE, CONDITION, HILLS], 2],
  ["Hollow",     [ADJECTIVE, CONDITION, HILLS], 2],
  ["Forgotten",  [ADJECTIVE, CONDITION, HILLS], 2],
  ["Jagged",     [ADJECTIVE, CONDITION, HILLS], 2],
  ["Foggy",      [ADJECTIVE, CONDITION, HILLS], 2],
  ["Wrinkled",   [ADJECTIVE, CONDITION, HILLS], 2],
  ["Mossy",      [ADJECTIVE, CONDITION, HILLS], 2],
  ["Slippery",   [ADJECTIVE, CONDITION, HILLS], 2],
  ["Remote",     [ADJECTIVE, CONDITION, HILLS], 2],
  ["Dry",        [ADJECTIVE, CONDITION, HILLS], 2],
  ["Shrouded",   [ADJECTIVE, CONDITION, HILLS], 2],
  ["Crested",    [ADJECTIVE, CONDITION, HILLS], 2],
  ["Forsaken",   [ADJECTIVE, CONDITION, HILLS], 2],
  // Tower / Fortification
  ["Grand",       [ADJECTIVE, CONDITION, TOWER], 2],
  ["Ornate",      [ADJECTIVE, CONDITION, TOWER], 2],
  ["Engraved",    [ADJECTIVE, CONDITION, TOWER], 2],
  ["Warded",      [ADJECTIVE, CONDITION, TOWER], 2],
  ["Concentric",  [ADJECTIVE, CONDITION, TOWER], 2],
  ["Gilded",      [ADJECTIVE, CONDITION, TOWER], 2],
  ["Sealed",      [ADJECTIVE, CONDITION, TOWER], 2],
  ["Shattered",   [ADJECTIVE, CONDITION, TOWER], 2],
  ["Broken",      [ADJECTIVE, CONDITION, TOWER], 2],
  ["Fallen",      [ADJECTIVE, CONDITION, TOWER], 2],
  ["Crumbling",   [ADJECTIVE, CONDITION, TOWER], 2],
  ["Splintered",  [ADJECTIVE, CONDITION, TOWER], 2],
  ["Collapsed",   [ADJECTIVE, CONDITION, TOWER], 2],
  ["Scorched",    [ADJECTIVE, CONDITION, TOWER], 2],
  ["Decayed",     [ADJECTIVE, CONDITION, TOWER], 2],
  ["Weathered",   [ADJECTIVE, CONDITION, TOWER], 2],
  ["Warped",      [ADJECTIVE, CONDITION, TOWER], 2],
  ["Rotting",     [ADJECTIVE, CONDITION, TOWER], 2],
  ["Rusty",       [ADJECTIVE, CONDITION, TOWER], 2],
  ["Sunken",      [ADJECTIVE, CONDITION, TOWER], 2],
  ["Tangled",     [ADJECTIVE, CONDITION, TOWER], 2],
  ["Twisted",     [ADJECTIVE, CONDITION, TOWER], 2],
  ["Tarnished",   [ADJECTIVE, CONDITION, TOWER], 2],
  ["Sinking",     [ADJECTIVE, CONDITION, TOWER], 2],
  ["Smoldering",  [ADJECTIVE, CONDITION, TOWER], 2],
  ["Flooded",     [ADJECTIVE, CONDITION, TOWER], 2],
  ["Pilfered",    [ADJECTIVE, CONDITION, TOWER], 2],
  ["Moldy",       [ADJECTIVE, CONDITION, TOWER], 2],
  ["Rusting",     [ADJECTIVE, CONDITION, TOWER], 2],
  ["Dusty",       [ADJECTIVE, CONDITION, TOWER], 2],
  ["Lost",        [ADJECTIVE, CONDITION, TOWER], 2],
  ["Ancient",     [ADJECTIVE, CONDITION, TOWER], 3],
  ["Forgotten",   [ADJECTIVE, CONDITION, TOWER], 2],
  ["Abandoned",   [ADJECTIVE, CONDITION, TOWER], 2],
  ["Jagged",      [ADJECTIVE, CONDITION, TOWER], 2],
  ["Unfinished",  [ADJECTIVE, CONDITION, TOWER], 2],
  ["Renovated",   [ADJECTIVE, CONDITION, TOWER], 2],
  ["Repaired",    [ADJECTIVE, CONDITION, TOWER], 2],
  ["Foggy",       [ADJECTIVE, CONDITION, TOWER], 2],
  ["Veiled",      [ADJECTIVE, CONDITION, TOWER], 2],
  ["Rebuilt",     [ADJECTIVE, CONDITION, TOWER], 2],
  ["Mossy",       [ADJECTIVE, CONDITION, TOWER], 2],
  ["Drifting",    [ADJECTIVE, CONDITION, TOWER], 2],
  ["Looming",     [ADJECTIVE, CONDITION, TOWER], 2],
  ["Remote",      [ADJECTIVE, CONDITION, TOWER], 2],
  ["Barbed",      [ADJECTIVE, CONDITION, TOWER], 2],
  ["Shrouded",    [ADJECTIVE, CONDITION, TOWER], 2],
  ["Crested",     [ADJECTIVE, CONDITION, TOWER], 2],
  ["Spined",      [ADJECTIVE, CONDITION, TOWER], 2],
  ["Spiked",      [ADJECTIVE, CONDITION, TOWER], 2],
  ["Serrated",    [ADJECTIVE, CONDITION, TOWER], 2],
  ["Scaled",      [ADJECTIVE, CONDITION, TOWER], 2],
  ["Forsaken",    [ADJECTIVE, CONDITION, TOWER], 2],
  ["Cyclopean",   [ADJECTIVE, CONDITION, TOWER], 2],
  // Ocean
  ["Sunken",    [ADJECTIVE, CONDITION, OCEAN], 2],
  ["Squirming", [ADJECTIVE, CONDITION, OCEAN], 2],
  ["Shallow",   [ADJECTIVE, CONDITION, OCEAN], 2],
  // River / Lake
  ["Pristine",   [ADJECTIVE, CONDITION, RIVER], 2],
  ["Rotting",    [ADJECTIVE, CONDITION, RIVER], 2],
  ["Sunken",     [ADJECTIVE, CONDITION, RIVER], 2],
  ["Sinking",    [ADJECTIVE, CONDITION, RIVER], 2],
  ["Smoldering", [ADJECTIVE, CONDITION, RIVER], 2],
  ["Flooded",    [ADJECTIVE, CONDITION, RIVER], 2],
  ["Moldy",      [ADJECTIVE, CONDITION, RIVER], 2],
  ["Eroded",     [ADJECTIVE, CONDITION, RIVER], 2],
  ["Overgrown",  [ADJECTIVE, CONDITION, RIVER], 2],
  ["Lost",       [ADJECTIVE, CONDITION, RIVER], 2],
  ["Forgotten",  [ADJECTIVE, CONDITION, RIVER], 2],
  ["Foggy",      [ADJECTIVE, CONDITION, RIVER], 2],
  ["Veiled",     [ADJECTIVE, CONDITION, RIVER], 2],
  ["Mossy",      [ADJECTIVE, CONDITION, RIVER], 2],
  ["Remote",     [ADJECTIVE, CONDITION, RIVER], 2],
  ["Dry",        [ADJECTIVE, CONDITION, RIVER], 2],
  ["Shrouded",   [ADJECTIVE, CONDITION, RIVER], 2],
  ["Thermal",    [ADJECTIVE, CONDITION, RIVER], 2],
  ["Shallow",    [ADJECTIVE, CONDITION, RIVER], 2],
  ["Forsaken",   [ADJECTIVE, CONDITION, RIVER], 2],
  ["Grand",      [ADJECTIVE, CONDITION, RIVER], 2],
  ["Warped",     [ADJECTIVE, CONDITION, RIVER], 2],
  ["Twisted",    [ADJECTIVE, CONDITION, RIVER], 2],
  ["Drained",    [ADJECTIVE, CONDITION, RIVER], 2],
  ["Drifting",   [ADJECTIVE, CONDITION, RIVER], 2],
  ["Squirming",  [ADJECTIVE, CONDITION, RIVER], 2],
  // Cave
  ["Grand",      [ADJECTIVE, CONDITION, CAVE], 2],
  ["Pristine",   [ADJECTIVE, CONDITION, CAVE], 2],
  ["Terraced",   [ADJECTIVE, CONDITION, CAVE], 2],
  ["Sealed",     [ADJECTIVE, CONDITION, CAVE], 2],
  ["Fallen",     [ADJECTIVE, CONDITION, CAVE], 2],
  ["Crumbling",  [ADJECTIVE, CONDITION, CAVE], 2],
  ["Worn",       [ADJECTIVE, CONDITION, CAVE], 2],
  ["Collapsed",  [ADJECTIVE, CONDITION, CAVE], 2],
  ["Scorched",   [ADJECTIVE, CONDITION, CAVE], 2],
  ["Unstable",   [ADJECTIVE, CONDITION, CAVE], 2],
  ["Defaced",    [ADJECTIVE, CONDITION, CAVE], 2],
  ["Weathered",  [ADJECTIVE, CONDITION, CAVE], 2],
  ["Warped",     [ADJECTIVE, CONDITION, CAVE], 2],
  ["Rotting",    [ADJECTIVE, CONDITION, CAVE], 2],
  ["Rusty",      [ADJECTIVE, CONDITION, CAVE], 2],
  ["Sunken",     [ADJECTIVE, CONDITION, CAVE], 2],
  ["Twisted",    [ADJECTIVE, CONDITION, CAVE], 2],
  ["Sinking",    [ADJECTIVE, CONDITION, CAVE], 2],
  ["Smoldering", [ADJECTIVE, CONDITION, CAVE], 2],
  ["Flooded",    [ADJECTIVE, CONDITION, CAVE], 2],
  ["Moldy",      [ADJECTIVE, CONDITION, CAVE], 2],
  ["Eroded",     [ADJECTIVE, CONDITION, CAVE], 2],
  ["Rusting",    [ADJECTIVE, CONDITION, CAVE], 2],
  ["Overgrown",  [ADJECTIVE, CONDITION, CAVE], 2],
  ["Leaking",    [ADJECTIVE, CONDITION, CAVE], 2],
  ["Drained",    [ADJECTIVE, CONDITION, CAVE], 2],
  ["Dusty",      [ADJECTIVE, CONDITION, CAVE], 2],
  ["Lost",       [ADJECTIVE, CONDITION, CAVE], 2],
  ["Forgotten",  [ADJECTIVE, CONDITION, CAVE], 2],
  ["Abandoned",  [ADJECTIVE, CONDITION, CAVE], 2],
  ["Foggy",      [ADJECTIVE, CONDITION, CAVE], 2],
  ["Speckled",   [ADJECTIVE, CONDITION, CAVE], 2],
  ["Veiled",     [ADJECTIVE, CONDITION, CAVE], 2],
  ["Mossy",      [ADJECTIVE, CONDITION, CAVE], 2],
  ["Slippery",   [ADJECTIVE, CONDITION, CAVE], 2],
  ["Remote",     [ADJECTIVE, CONDITION, CAVE], 2],
  ["Dry",        [ADJECTIVE, CONDITION, CAVE], 2],
  ["Shrouded",   [ADJECTIVE, CONDITION, CAVE], 2],
  ["Thermal",    [ADJECTIVE, CONDITION, CAVE], 2],
  ["Shallow",    [ADJECTIVE, CONDITION, CAVE], 2],
  ["Forsaken",   [ADJECTIVE, CONDITION, CAVE], 2],
  // Mine
  ["Sealed",     [ADJECTIVE, CONDITION, MINE], 2],
  ["Crumbling",  [ADJECTIVE, CONDITION, MINE], 2],
  ["Collapsed",  [ADJECTIVE, CONDITION, MINE], 2],
  ["Scorched",   [ADJECTIVE, CONDITION, MINE], 2],
  ["Unstable",   [ADJECTIVE, CONDITION, MINE], 2],
  ["Decayed",    [ADJECTIVE, CONDITION, MINE], 2],
  ["Defaced",    [ADJECTIVE, CONDITION, MINE], 2],
  ["Rotting",    [ADJECTIVE, CONDITION, MINE], 2],
  ["Sunken",     [ADJECTIVE, CONDITION, MINE], 2],
  ["Twisted",    [ADJECTIVE, CONDITION, MINE], 2],
  ["Sinking",    [ADJECTIVE, CONDITION, MINE], 2],
  ["Smoldering", [ADJECTIVE, CONDITION, MINE], 2],
  ["Flooded",    [ADJECTIVE, CONDITION, MINE], 2],
  ["Moldy",      [ADJECTIVE, CONDITION, MINE], 2],
  ["Overgrown",  [ADJECTIVE, CONDITION, MINE], 2],
  ["Leaking",    [ADJECTIVE, CONDITION, MINE], 2],
  ["Dusty",      [ADJECTIVE, CONDITION, MINE], 2],
  ["Lost",       [ADJECTIVE, CONDITION, MINE], 2],
  ["Ancient",    [ADJECTIVE, CONDITION, MINE], 2],
  ["Forgotten",  [ADJECTIVE, CONDITION, MINE], 2],
  ["Abandoned",  [ADJECTIVE, CONDITION, MINE], 2],
  ["Unfinished", [ADJECTIVE, CONDITION, MINE], 2],
  ["Renovated",  [ADJECTIVE, CONDITION, MINE], 2],
  ["Repaired",   [ADJECTIVE, CONDITION, MINE], 2],
  ["Veiled",     [ADJECTIVE, CONDITION, MINE], 2],
  ["Slippery",   [ADJECTIVE, CONDITION, MINE], 2],
  ["Remote",     [ADJECTIVE, CONDITION, MINE], 2],
  ["Dry",        [ADJECTIVE, CONDITION, MINE], 2],
  ["False",      [ADJECTIVE, CONDITION, MINE], 2],
  ["Shrouded",   [ADJECTIVE, CONDITION, MINE], 2],
  ["Shallow",    [ADJECTIVE, CONDITION, MINE], 2],
  ["Forsaken",   [ADJECTIVE, CONDITION, MINE], 2],
  // Temple / Religious
  ["Grand",      [ADJECTIVE, CONDITION, TEMPLE], 2],
  ["Ornate",     [ADJECTIVE, CONDITION, TEMPLE], 2],
  ["Engraved",   [ADJECTIVE, CONDITION, TEMPLE], 2],
  ["Gilded",     [ADJECTIVE, CONDITION, TEMPLE], 2],
  ["Sealed",     [ADJECTIVE, CONDITION, TEMPLE], 2],
  ["Shattered",  [ADJECTIVE, CONDITION, TEMPLE], 2],
  ["Broken",     [ADJECTIVE, CONDITION, TEMPLE], 2],
  ["Fallen",     [ADJECTIVE, CONDITION, TEMPLE], 2],
  ["Crumbling",  [ADJECTIVE, CONDITION, TEMPLE], 2],
  ["Splintered", [ADJECTIVE, CONDITION, TEMPLE], 2],
  ["Collapsed",  [ADJECTIVE, CONDITION, TEMPLE], 2],
  ["Scorched",   [ADJECTIVE, CONDITION, TEMPLE], 2],
  ["Decayed",    [ADJECTIVE, CONDITION, TEMPLE], 2],
  ["Defaced",    [ADJECTIVE, CONDITION, TEMPLE], 2],
  ["Weathered",  [ADJECTIVE, CONDITION, TEMPLE], 2],
  ["Warped",     [ADJECTIVE, CONDITION, TEMPLE], 2],
  ["Rotting",    [ADJECTIVE, CONDITION, TEMPLE], 2],
  ["Rusty",      [ADJECTIVE, CONDITION, TEMPLE], 2],
  ["Sunken",     [ADJECTIVE, CONDITION, TEMPLE], 2],
  ["Tangled",    [ADJECTIVE, CONDITION, TEMPLE], 2],
  ["Twisted",    [ADJECTIVE, CONDITION, TEMPLE], 2],
  ["Tarnished",  [ADJECTIVE, CONDITION, TEMPLE], 2],
  ["Sinking",    [ADJECTIVE, CONDITION, TEMPLE], 2],
  ["Smoldering", [ADJECTIVE, CONDITION, TEMPLE], 2],
  ["Flooded",    [ADJECTIVE, CONDITION, TEMPLE], 2],
  ["Moldy",      [ADJECTIVE, CONDITION, TEMPLE], 2],
  ["Rusting",    [ADJECTIVE, CONDITION, TEMPLE], 2],
  ["Overgrown",  [ADJECTIVE, CONDITION, TEMPLE], 2],
  ["Lost",       [ADJECTIVE, CONDITION, TEMPLE], 2],
  ["Ancient",    [ADJECTIVE, CONDITION, TEMPLE], 3],
  ["Forgotten",  [ADJECTIVE, CONDITION, TEMPLE], 2],
  ["Abandoned",  [ADJECTIVE, CONDITION, TEMPLE], 2],
  ["Unfinished", [ADJECTIVE, CONDITION, TEMPLE], 2],
  ["Renovated",  [ADJECTIVE, CONDITION, TEMPLE], 2],
  ["Repaired",   [ADJECTIVE, CONDITION, TEMPLE], 2],
  ["Veiled",     [ADJECTIVE, CONDITION, TEMPLE], 2],
  ["Rebuilt",    [ADJECTIVE, CONDITION, TEMPLE], 2],
  ["Remote",     [ADJECTIVE, CONDITION, TEMPLE], 2],
  ["Shrouded",   [ADJECTIVE, CONDITION, TEMPLE], 2],
  ["Forsaken",   [ADJECTIVE, CONDITION, TEMPLE], 2],
  // Canyon
  ["Crumbling",  [ADJECTIVE, CONDITION, CANYON], 2],
  ["Weathered",  [ADJECTIVE, CONDITION, CANYON], 2],
  ["Rotting",    [ADJECTIVE, CONDITION, CANYON], 2],
  ["Rusty",      [ADJECTIVE, CONDITION, CANYON], 2],
  ["Sunken",     [ADJECTIVE, CONDITION, CANYON], 2],
  ["Twisted",    [ADJECTIVE, CONDITION, CANYON], 2],
  ["Sinking",    [ADJECTIVE, CONDITION, CANYON], 2],
  ["Smoldering", [ADJECTIVE, CONDITION, CANYON], 2],
  ["Flooded",    [ADJECTIVE, CONDITION, CANYON], 2],
  ["Moldy",      [ADJECTIVE, CONDITION, CANYON], 2],
  ["Eroded",     [ADJECTIVE, CONDITION, CANYON], 2],
  ["Overgrown",  [ADJECTIVE, CONDITION, CANYON], 2],
  ["Dusty",      [ADJECTIVE, CONDITION, CANYON], 2],
  ["Lost",       [ADJECTIVE, CONDITION, CANYON], 2],
  ["Forgotten",  [ADJECTIVE, CONDITION, CANYON], 2],
  ["Veiled",     [ADJECTIVE, CONDITION, CANYON], 2],
  ["Mossy",      [ADJECTIVE, CONDITION, CANYON], 2],
  ["Slippery",   [ADJECTIVE, CONDITION, CANYON], 2],
  ["Remote",     [ADJECTIVE, CONDITION, CANYON], 2],
  ["Dry",        [ADJECTIVE, CONDITION, CANYON], 2],
  ["Shrouded",   [ADJECTIVE, CONDITION, CANYON], 2],
  ["Shallow",    [ADJECTIVE, CONDITION, CANYON], 2],
  ["Forsaken",   [ADJECTIVE, CONDITION, CANYON], 2],
]

// EFFECTS — tagged by terrain context; generic items have no terrain tag

export const effects: TaggedItem[] = [
  // Generic
  ["Clockwork",   [ADJECTIVE, EFFECT, MAGICAL], 2],
  ["Glowing",     [ADJECTIVE, EFFECT, MAGICAL], 2],
  ["Shimmering",  [ADJECTIVE, EFFECT, MAGICAL], 2],
  ["Hidden",      [ADJECTIVE, EFFECT, MAGICAL], 2],
  ["Secret",      [ADJECTIVE, EFFECT, MAGICAL], 2],
  ["Invisible",   [ADJECTIVE, EFFECT, MAGICAL], 1],
  ["Ethereal",    [ADJECTIVE, EFFECT, MAGICAL], 2],
  ["Floating",    [ADJECTIVE, EFFECT, MAGICAL], 2],
  ["Levitating",  [ADJECTIVE, EFFECT, MAGICAL], 2],
  ["Prismatic",   [ADJECTIVE, EFFECT, MAGICAL], 2],
  ["Wandering",   [ADJECTIVE, EFFECT, MAGICAL], 2],
  ["Singing",     [ADJECTIVE, EFFECT, MAGICAL], 2],
  ["Endless",     [ADJECTIVE, EFFECT, MAGICAL], 2],
  ["Drifting",    [ADJECTIVE, EFFECT, MAGICAL], 2],
  ["Blinking",    [ADJECTIVE, EFFECT, MAGICAL], 2],
  ["Jumping",     [ADJECTIVE, EFFECT, MAGICAL], 2],
  ["Radiant",     [ADJECTIVE, EFFECT, MAGICAL], 2],
  ["Giant",       [ADJECTIVE, EFFECT, MAGICAL], 2],
  ["Howling",     [ADJECTIVE, EFFECT, MAGICAL], 2],
  ["Screaming",   [ADJECTIVE, EFFECT, MAGICAL], 2],
  ["Chromatic",   [ADJECTIVE, EFFECT, MAGICAL], 2],
  ["Burning",     [ADJECTIVE, EFFECT, MAGICAL], 2],
  ["Blazing",     [ADJECTIVE, EFFECT, MAGICAL], 2],
  ["Charged",     [ADJECTIVE, EFFECT, MAGICAL], 2],
  ["Fiery",       [ADJECTIVE, EFFECT, MAGICAL], 2],
  ["Electric",    [ADJECTIVE, EFFECT, MAGICAL], 2],
  ["Acidic",      [ADJECTIVE, EFFECT, MAGICAL], 2],
  ["Poison",      [ADJECTIVE, EFFECT, MAGICAL], 2],
  ["Spinning",    [ADJECTIVE, EFFECT, MAGICAL], 2],
  ["Secure",      [ADJECTIVE, EFFECT, MAGICAL], 2],
  ["Locked",      [ADJECTIVE, EFFECT, MAGICAL], 2],
  ["Inverted",    [ADJECTIVE, EFFECT, MAGICAL], 1],
  ["Whispering",  [ADJECTIVE, EFFECT, MAGICAL], 2],
  ["Corrosive",   [ADJECTIVE, EFFECT, MAGICAL], 2],
  ["Frozen",      [ADJECTIVE, EFFECT, MAGICAL], 2],
  ["Colossal",    [ADJECTIVE, EFFECT, MAGICAL], 2],
  ["Cursed",      [ADJECTIVE, EFFECT, MAGICAL], 2],
  ["Haunted",     [ADJECTIVE, EFFECT, MAGICAL], 2],
  ["Dancing",     [ADJECTIVE, EFFECT, MAGICAL], 2],
  ["Withering",   [ADJECTIVE, EFFECT, MAGICAL], 2],
  ["Creeping",    [ADJECTIVE, EFFECT, MAGICAL], 2],
  ["Magnetic",    [ADJECTIVE, EFFECT, MAGICAL], 2],
  ["Albino",      [ADJECTIVE, EFFECT, MAGICAL], 2],
  ["Luminous",    [ADJECTIVE, EFFECT, MAGICAL], 2],
  ["Molten",      [ADJECTIVE, EFFECT, MAGICAL], 2],
  ["Polluted",    [ADJECTIVE, EFFECT, MAGICAL], 2],
  ["Iridescent",  [ADJECTIVE, EFFECT, MAGICAL], 2],
  ["Hovering",    [ADJECTIVE, EFFECT, MAGICAL], 2],
  ["Phantasmal",  [ADJECTIVE, EFFECT, MAGICAL], 2],
  ["Jeweled",     [ADJECTIVE, EFFECT, MAGICAL], 2],
  ["Trapped",     [ADJECTIVE, EFFECT, MAGICAL], 2],
  ["Voltaic",     [ADJECTIVE, EFFECT, MAGICAL], 2],
  ["Psionic",     [ADJECTIVE, EFFECT, MAGICAL], 1],
  ["Masterwork",  [ADJECTIVE, EFFECT, MAGICAL], 2],
  ["Temporal",    [ADJECTIVE, EFFECT, MAGICAL], 1],
  ["Ghostly",     [ADJECTIVE, EFFECT, MAGICAL], 2],
  ["Shrinking",   [ADJECTIVE, EFFECT, MAGICAL], 2],
  ["Bottomless",  [ADJECTIVE, EFFECT, MAGICAL], 2],
  ["Blinding",    [ADJECTIVE, EFFECT, MAGICAL], 2],
  ["Caustic",     [ADJECTIVE, EFFECT, MAGICAL], 2],
  ["Boiling",     [ADJECTIVE, EFFECT, MAGICAL], 2],
  ["Primordial",  [ADJECTIVE, EFFECT, MAGICAL], 2],
  ["Eternal",     [ADJECTIVE, EFFECT, MAGICAL], 2],
  ["Animated",    [ADJECTIVE, EFFECT, MAGICAL], 2],
  ["Spectral",    [ADJECTIVE, EFFECT, MAGICAL], 2],
  ["Shifting",    [ADJECTIVE, EFFECT, MAGICAL], 2],
  ["Hypnotic",    [ADJECTIVE, EFFECT, MAGICAL], 2],
  ["Explosive",   [ADJECTIVE, EFFECT, MAGICAL], 2],
  ["Blurry",      [ADJECTIVE, EFFECT, MAGICAL], 2],
  ["Shrunken",    [ADJECTIVE, EFFECT, MAGICAL], 2],
  ["Whirling",    [ADJECTIVE, EFFECT, MAGICAL], 2],
  ["Flickering",  [ADJECTIVE, EFFECT, MAGICAL], 2],
  ["Spiraling",   [ADJECTIVE, EFFECT, MAGICAL], 2],
  ["Concealed",   [ADJECTIVE, EFFECT, MAGICAL], 2],
  // Mountain
  ["Glowing",     [ADJECTIVE, EFFECT, MAGICAL, MOUNTAIN], 2],
  ["Shimmering",  [ADJECTIVE, EFFECT, MAGICAL, MOUNTAIN], 2],
  ["Levitating",  [ADJECTIVE, EFFECT, MAGICAL, MOUNTAIN], 1],
  ["Wandering",   [ADJECTIVE, EFFECT, MAGICAL, MOUNTAIN], 2],
  ["Endless",     [ADJECTIVE, EFFECT, MAGICAL, MOUNTAIN], 2],
  ["Drifting",    [ADJECTIVE, EFFECT, MAGICAL, MOUNTAIN], 2],
  ["Radiant",     [ADJECTIVE, EFFECT, MAGICAL, MOUNTAIN], 2],
  ["Howling",     [ADJECTIVE, EFFECT, MAGICAL, MOUNTAIN], 2],
  ["Screaming",   [ADJECTIVE, EFFECT, MAGICAL, MOUNTAIN], 2],
  ["Inverted",    [ADJECTIVE, EFFECT, MAGICAL, MOUNTAIN], 1],
  ["Whispering",  [ADJECTIVE, EFFECT, MAGICAL, MOUNTAIN], 2],
  ["Frozen",      [ADJECTIVE, EFFECT, MAGICAL, MOUNTAIN], 2],
  ["Colossal",    [ADJECTIVE, EFFECT, MAGICAL, MOUNTAIN], 2],
  ["Cursed",      [ADJECTIVE, EFFECT, MAGICAL, MOUNTAIN], 2],
  ["Haunted",     [ADJECTIVE, EFFECT, MAGICAL, MOUNTAIN], 2],
  ["Withering",   [ADJECTIVE, EFFECT, MAGICAL, MOUNTAIN], 2],
  ["Creeping",    [ADJECTIVE, EFFECT, MAGICAL, MOUNTAIN], 2],
  ["Magnetic",    [ADJECTIVE, EFFECT, MAGICAL, MOUNTAIN], 2],
  ["Luminous",    [ADJECTIVE, EFFECT, MAGICAL, MOUNTAIN], 2],
  ["Irridescent", [ADJECTIVE, EFFECT, MAGICAL, MOUNTAIN], 2],
  ["Jeweled",     [ADJECTIVE, EFFECT, MAGICAL, MOUNTAIN], 2],
  ["Ghostly",     [ADJECTIVE, EFFECT, MAGICAL, MOUNTAIN], 2],
  ["Caustic",     [ADJECTIVE, EFFECT, MAGICAL, MOUNTAIN], 2],
  ["Shifting",    [ADJECTIVE, EFFECT, MAGICAL, MOUNTAIN], 2],
  ["Whirling",    [ADJECTIVE, EFFECT, MAGICAL, MOUNTAIN], 2],
  ["Spiraling",   [ADJECTIVE, EFFECT, MAGICAL, MOUNTAIN], 2],
  // Forest
  ["Shimmering",  [ADJECTIVE, EFFECT, MAGICAL, FOREST], 2],
  ["Hidden",      [ADJECTIVE, EFFECT, MAGICAL, FOREST], 2],
  ["Ethereal",    [ADJECTIVE, EFFECT, MAGICAL, FOREST], 2],
  ["Floating",    [ADJECTIVE, EFFECT, MAGICAL, FOREST], 2],
  ["Wandering",   [ADJECTIVE, EFFECT, MAGICAL, FOREST], 2],
  ["Endless",     [ADJECTIVE, EFFECT, MAGICAL, FOREST], 2],
  ["Howling",     [ADJECTIVE, EFFECT, MAGICAL, FOREST], 2],
  ["Screaming",   [ADJECTIVE, EFFECT, MAGICAL, FOREST], 2],
  ["Poison",      [ADJECTIVE, EFFECT, MAGICAL, FOREST], 2],
  ["Whispering",  [ADJECTIVE, EFFECT, MAGICAL, FOREST], 2],
  ["Frozen",      [ADJECTIVE, EFFECT, MAGICAL, FOREST], 2],
  ["Cursed",      [ADJECTIVE, EFFECT, MAGICAL, FOREST], 2],
  ["Haunted",     [ADJECTIVE, EFFECT, MAGICAL, FOREST], 2],
  ["Withering",   [ADJECTIVE, EFFECT, MAGICAL, FOREST], 2],
  ["Creeping",    [ADJECTIVE, EFFECT, MAGICAL, FOREST], 2],
  ["Luminous",    [ADJECTIVE, EFFECT, MAGICAL, FOREST], 2],
  ["Polluted",    [ADJECTIVE, EFFECT, MAGICAL, FOREST], 2],
  ["Phantasmal",  [ADJECTIVE, EFFECT, MAGICAL, FOREST], 2],
  ["Ghostly",     [ADJECTIVE, EFFECT, MAGICAL, FOREST], 2],
  ["Primordial",  [ADJECTIVE, EFFECT, MAGICAL, FOREST], 2],
  ["Spectral",    [ADJECTIVE, EFFECT, MAGICAL, FOREST], 2],
  // Swamp
  ["Glowing",    [ADJECTIVE, EFFECT, MAGICAL, SWAMP], 2],
  ["Shimmering", [ADJECTIVE, EFFECT, MAGICAL, SWAMP], 2],
  ["Endless",    [ADJECTIVE, EFFECT, MAGICAL, SWAMP], 2],
  ["Howling",    [ADJECTIVE, EFFECT, MAGICAL, SWAMP], 2],
  ["Screaming",  [ADJECTIVE, EFFECT, MAGICAL, SWAMP], 2],
  ["Poison",     [ADJECTIVE, EFFECT, MAGICAL, SWAMP], 2],
  ["Whispering", [ADJECTIVE, EFFECT, MAGICAL, SWAMP], 2],
  ["Cursed",     [ADJECTIVE, EFFECT, MAGICAL, SWAMP], 2],
  ["Haunted",    [ADJECTIVE, EFFECT, MAGICAL, SWAMP], 2],
  ["Withering",  [ADJECTIVE, EFFECT, MAGICAL, SWAMP], 2],
  ["Creeping",   [ADJECTIVE, EFFECT, MAGICAL, SWAMP], 2],
  ["Polluted",   [ADJECTIVE, EFFECT, MAGICAL, SWAMP], 2],
  ["Ghostly",    [ADJECTIVE, EFFECT, MAGICAL, SWAMP], 2],
  ["Caustic",    [ADJECTIVE, EFFECT, MAGICAL, SWAMP], 2],
  ["Boiling",    [ADJECTIVE, EFFECT, MAGICAL, SWAMP], 2],
  ["Primordial", [ADJECTIVE, EFFECT, MAGICAL, SWAMP], 2],
  ["Spectral",   [ADJECTIVE, EFFECT, MAGICAL, SWAMP], 2],
  // Hills
  ["Glowing",    [ADJECTIVE, EFFECT, MAGICAL, HILLS], 2],
  ["Hidden",     [ADJECTIVE, EFFECT, MAGICAL, HILLS], 2],
  ["Wandering",  [ADJECTIVE, EFFECT, MAGICAL, HILLS], 2],
  ["Endless",    [ADJECTIVE, EFFECT, MAGICAL, HILLS], 2],
  ["Drifting",   [ADJECTIVE, EFFECT, MAGICAL, HILLS], 2],
  ["Howling",    [ADJECTIVE, EFFECT, MAGICAL, HILLS], 2],
  ["Screaming",  [ADJECTIVE, EFFECT, MAGICAL, HILLS], 2],
  ["Whispering", [ADJECTIVE, EFFECT, MAGICAL, HILLS], 2],
  ["Frozen",     [ADJECTIVE, EFFECT, MAGICAL, HILLS], 2],
  ["Cursed",     [ADJECTIVE, EFFECT, MAGICAL, HILLS], 2],
  ["Haunted",    [ADJECTIVE, EFFECT, MAGICAL, HILLS], 2],
  ["Withering",  [ADJECTIVE, EFFECT, MAGICAL, HILLS], 2],
  ["Creeping",   [ADJECTIVE, EFFECT, MAGICAL, HILLS], 2],
  ["Hovering",   [ADJECTIVE, EFFECT, MAGICAL, HILLS], 2],
  ["Ghostly",    [ADJECTIVE, EFFECT, MAGICAL, HILLS], 2],
  ["Shifting",   [ADJECTIVE, EFFECT, MAGICAL, HILLS], 2],
  // Tower
  ["Clockwork",   [ADJECTIVE, EFFECT, MAGICAL, TOWER], 2],
  ["Glowing",     [ADJECTIVE, EFFECT, MAGICAL, TOWER], 2],
  ["Shimmering",  [ADJECTIVE, EFFECT, MAGICAL, TOWER], 2],
  ["Hidden",      [ADJECTIVE, EFFECT, MAGICAL, TOWER], 2],
  ["Secret",      [ADJECTIVE, EFFECT, MAGICAL, TOWER], 2],
  ["Invisible",   [ADJECTIVE, EFFECT, MAGICAL, TOWER], 1],
  ["Ethereal",    [ADJECTIVE, EFFECT, MAGICAL, TOWER], 2],
  ["Floating",    [ADJECTIVE, EFFECT, MAGICAL, TOWER], 2],
  ["Levitating",  [ADJECTIVE, EFFECT, MAGICAL, TOWER], 2],
  ["Prismatic",   [ADJECTIVE, EFFECT, MAGICAL, TOWER], 2],
  ["Wandering",   [ADJECTIVE, EFFECT, MAGICAL, TOWER], 2],
  ["Drifting",    [ADJECTIVE, EFFECT, MAGICAL, TOWER], 2],
  ["Blinking",    [ADJECTIVE, EFFECT, MAGICAL, TOWER], 2],
  ["Radiant",     [ADJECTIVE, EFFECT, MAGICAL, TOWER], 2],
  ["Howling",     [ADJECTIVE, EFFECT, MAGICAL, TOWER], 2],
  ["Screaming",   [ADJECTIVE, EFFECT, MAGICAL, TOWER], 2],
  ["Burning",     [ADJECTIVE, EFFECT, MAGICAL, TOWER], 2],
  ["Electric",    [ADJECTIVE, EFFECT, MAGICAL, TOWER], 2],
  ["Spinning",    [ADJECTIVE, EFFECT, MAGICAL, TOWER], 2],
  ["Secure",      [ADJECTIVE, EFFECT, MAGICAL, TOWER], 2],
  ["Locked",      [ADJECTIVE, EFFECT, MAGICAL, TOWER], 2],
  ["Inverted",    [ADJECTIVE, EFFECT, MAGICAL, TOWER], 1],
  ["Whispering",  [ADJECTIVE, EFFECT, MAGICAL, TOWER], 2],
  ["Frozen",      [ADJECTIVE, EFFECT, MAGICAL, TOWER], 2],
  ["Cursed",      [ADJECTIVE, EFFECT, MAGICAL, TOWER], 2],
  ["Haunted",     [ADJECTIVE, EFFECT, MAGICAL, TOWER], 2],
  ["Creeping",    [ADJECTIVE, EFFECT, MAGICAL, TOWER], 2],
  ["Luminous",    [ADJECTIVE, EFFECT, MAGICAL, TOWER], 2],
  ["Iridescent",  [ADJECTIVE, EFFECT, MAGICAL, TOWER], 2],
  ["Hovering",    [ADJECTIVE, EFFECT, MAGICAL, TOWER], 2],
  ["Phantasmal",  [ADJECTIVE, EFFECT, MAGICAL, TOWER], 2],
  ["Jeweled",     [ADJECTIVE, EFFECT, MAGICAL, TOWER], 2],
  ["Trapped",     [ADJECTIVE, EFFECT, MAGICAL, TOWER], 2],
  ["Ghostly",     [ADJECTIVE, EFFECT, MAGICAL, TOWER], 2],
  ["Spectral",    [ADJECTIVE, EFFECT, MAGICAL, TOWER], 2],
  ["Whirling",    [ADJECTIVE, EFFECT, MAGICAL, TOWER], 2],
  ["Spiraling",   [ADJECTIVE, EFFECT, MAGICAL, TOWER], 2],
  ["Concealed",   [ADJECTIVE, EFFECT, MAGICAL, TOWER], 2],
  // Ocean
  ["Shimmering", [ADJECTIVE, EFFECT, MAGICAL, OCEAN], 2],
  ["Ethereal",   [ADJECTIVE, EFFECT, MAGICAL, OCEAN], 2],
  ["Endless",    [ADJECTIVE, EFFECT, MAGICAL, OCEAN], 2],
  ["Drifting",   [ADJECTIVE, EFFECT, MAGICAL, OCEAN], 2],
  ["Howling",    [ADJECTIVE, EFFECT, MAGICAL, OCEAN], 2],
  ["Cursed",     [ADJECTIVE, EFFECT, MAGICAL, OCEAN], 2],
  ["Bottomless", [ADJECTIVE, EFFECT, MAGICAL, OCEAN], 2],
  ["Boiling",    [ADJECTIVE, EFFECT, MAGICAL, OCEAN], 2],
  // River / Lake
  ["Glowing",    [ADJECTIVE, EFFECT, MAGICAL, RIVER], 2],
  ["Shimmering", [ADJECTIVE, EFFECT, MAGICAL, RIVER], 2],
  ["Hidden",     [ADJECTIVE, EFFECT, MAGICAL, RIVER], 2],
  ["Prismatic",  [ADJECTIVE, EFFECT, MAGICAL, RIVER], 2],
  ["Screaming",  [ADJECTIVE, EFFECT, MAGICAL, RIVER], 2],
  ["Poison",     [ADJECTIVE, EFFECT, MAGICAL, RIVER], 2],
  ["Whispering", [ADJECTIVE, EFFECT, MAGICAL, RIVER], 2],
  ["Frozen",     [ADJECTIVE, EFFECT, MAGICAL, RIVER], 2],
  ["Cursed",     [ADJECTIVE, EFFECT, MAGICAL, RIVER], 2],
  ["Haunted",    [ADJECTIVE, EFFECT, MAGICAL, RIVER], 2],
  ["Luminous",   [ADJECTIVE, EFFECT, MAGICAL, RIVER], 2],
  ["Polluted",   [ADJECTIVE, EFFECT, MAGICAL, RIVER], 2],
  ["Iridescent", [ADJECTIVE, EFFECT, MAGICAL, RIVER], 2],
  ["Ghostly",    [ADJECTIVE, EFFECT, MAGICAL, RIVER], 2],
  ["Bottomless", [ADJECTIVE, EFFECT, MAGICAL, RIVER], 2],
  ["Caustic",    [ADJECTIVE, EFFECT, MAGICAL, RIVER], 2],
  ["Boiling",    [ADJECTIVE, EFFECT, MAGICAL, RIVER], 2],
  ["Wandering",  [ADJECTIVE, EFFECT, MAGICAL, RIVER], 2],
  ["Endless",    [ADJECTIVE, EFFECT, MAGICAL, RIVER], 2],
  ["Creeping",   [ADJECTIVE, EFFECT, MAGICAL, RIVER], 2],
  ["Polluted",   [ADJECTIVE, EFFECT, MAGICAL, RIVER], 2],
  // Cave
  ["Glowing",    [ADJECTIVE, EFFECT, MAGICAL, CAVE], 2],
  ["Shimmering", [ADJECTIVE, EFFECT, MAGICAL, CAVE], 2],
  ["Hidden",     [ADJECTIVE, EFFECT, MAGICAL, CAVE], 2],
  ["Secret",     [ADJECTIVE, EFFECT, MAGICAL, CAVE], 2],
  ["Endless",    [ADJECTIVE, EFFECT, MAGICAL, CAVE], 2],
  ["Howling",    [ADJECTIVE, EFFECT, MAGICAL, CAVE], 2],
  ["Screaming",  [ADJECTIVE, EFFECT, MAGICAL, CAVE], 2],
  ["Whispering", [ADJECTIVE, EFFECT, MAGICAL, CAVE], 2],
  ["Frozen",     [ADJECTIVE, EFFECT, MAGICAL, CAVE], 2],
  ["Colossal",   [ADJECTIVE, EFFECT, MAGICAL, CAVE], 2],
  ["Cursed",     [ADJECTIVE, EFFECT, MAGICAL, CAVE], 2],
  ["Haunted",    [ADJECTIVE, EFFECT, MAGICAL, CAVE], 2],
  ["Creeping",   [ADJECTIVE, EFFECT, MAGICAL, CAVE], 2],
  ["Luminous",   [ADJECTIVE, EFFECT, MAGICAL, CAVE], 2],
  ["Jeweled",    [ADJECTIVE, EFFECT, MAGICAL, CAVE], 2],
  ["Trapped",    [ADJECTIVE, EFFECT, MAGICAL, CAVE], 2],
  ["Ghostly",    [ADJECTIVE, EFFECT, MAGICAL, CAVE], 2],
  ["Bottomless", [ADJECTIVE, EFFECT, MAGICAL, CAVE], 2],
  ["Caustic",    [ADJECTIVE, EFFECT, MAGICAL, CAVE], 2],
  ["Concealed",  [ADJECTIVE, EFFECT, MAGICAL, CAVE], 2],
  // Mine
  ["Clockwork",  [ADJECTIVE, EFFECT, MAGICAL, MINE], 2],
  ["Glowing",    [ADJECTIVE, EFFECT, MAGICAL, MINE], 2],
  ["Shimmering", [ADJECTIVE, EFFECT, MAGICAL, MINE], 2],
  ["Hidden",     [ADJECTIVE, EFFECT, MAGICAL, MINE], 2],
  ["Secret",     [ADJECTIVE, EFFECT, MAGICAL, MINE], 2],
  ["Endless",    [ADJECTIVE, EFFECT, MAGICAL, MINE], 2],
  ["Radiant",    [ADJECTIVE, EFFECT, MAGICAL, MINE], 2],
  ["Howling",    [ADJECTIVE, EFFECT, MAGICAL, MINE], 2],
  ["Locked",     [ADJECTIVE, EFFECT, MAGICAL, MINE], 2],
  ["Whispering", [ADJECTIVE, EFFECT, MAGICAL, MINE], 2],
  ["Frozen",     [ADJECTIVE, EFFECT, MAGICAL, MINE], 2],
  ["Colossal",   [ADJECTIVE, EFFECT, MAGICAL, MINE], 2],
  ["Cursed",     [ADJECTIVE, EFFECT, MAGICAL, MINE], 2],
  ["Haunted",    [ADJECTIVE, EFFECT, MAGICAL, MINE], 2],
  ["Magnetic",   [ADJECTIVE, EFFECT, MAGICAL, MINE], 2],
  ["Luminous",   [ADJECTIVE, EFFECT, MAGICAL, MINE], 2],
  ["Polluted",   [ADJECTIVE, EFFECT, MAGICAL, MINE], 2],
  ["Jeweled",    [ADJECTIVE, EFFECT, MAGICAL, MINE], 2],
  ["Trapped",    [ADJECTIVE, EFFECT, MAGICAL, MINE], 2],
  ["Ghostly",    [ADJECTIVE, EFFECT, MAGICAL, MINE], 2],
  ["Caustic",    [ADJECTIVE, EFFECT, MAGICAL, MINE], 2],
  ["Concealed",  [ADJECTIVE, EFFECT, MAGICAL, MINE], 2],
  ["Exhausted",  [ADJECTIVE, EFFECT, MAGICAL, MINE], 2],
  ["Plundered",  [ADJECTIVE, EFFECT, MAGICAL, MINE], 2],
  // Temple
  ["Clockwork",  [ADJECTIVE, EFFECT, MAGICAL, TEMPLE], 2],
  ["Glowing",    [ADJECTIVE, EFFECT, MAGICAL, TEMPLE], 2],
  ["Shimmering", [ADJECTIVE, EFFECT, MAGICAL, TEMPLE], 2],
  ["Hidden",     [ADJECTIVE, EFFECT, MAGICAL, TEMPLE], 2],
  ["Secret",     [ADJECTIVE, EFFECT, MAGICAL, TEMPLE], 2],
  ["Floating",   [ADJECTIVE, EFFECT, MAGICAL, TEMPLE], 2],
  ["Levitating", [ADJECTIVE, EFFECT, MAGICAL, TEMPLE], 2],
  ["Radiant",    [ADJECTIVE, EFFECT, MAGICAL, TEMPLE], 2],
  ["Howling",    [ADJECTIVE, EFFECT, MAGICAL, TEMPLE], 2],
  ["Locked",     [ADJECTIVE, EFFECT, MAGICAL, TEMPLE], 2],
  ["Whispering", [ADJECTIVE, EFFECT, MAGICAL, TEMPLE], 2],
  ["Frozen",     [ADJECTIVE, EFFECT, MAGICAL, TEMPLE], 2],
  ["Colossal",   [ADJECTIVE, EFFECT, MAGICAL, TEMPLE], 2],
  ["Cursed",     [ADJECTIVE, EFFECT, MAGICAL, TEMPLE], 2],
  ["Haunted",    [ADJECTIVE, EFFECT, MAGICAL, TEMPLE], 2],
  ["Creeping",   [ADJECTIVE, EFFECT, MAGICAL, TEMPLE], 2],
  ["Luminous",   [ADJECTIVE, EFFECT, MAGICAL, TEMPLE], 2],
  ["Iridescent", [ADJECTIVE, EFFECT, MAGICAL, TEMPLE], 2],
  ["Hovering",   [ADJECTIVE, EFFECT, MAGICAL, TEMPLE], 2],
  ["Jeweled",    [ADJECTIVE, EFFECT, MAGICAL, TEMPLE], 2],
  ["Trapped",    [ADJECTIVE, EFFECT, MAGICAL, TEMPLE], 2],
  ["Ghostly",    [ADJECTIVE, EFFECT, MAGICAL, TEMPLE], 2],
  ["Whirling",   [ADJECTIVE, EFFECT, MAGICAL, TEMPLE], 2],
  ["Spiraling",  [ADJECTIVE, EFFECT, MAGICAL, TEMPLE], 2],
  ["Concealed",  [ADJECTIVE, EFFECT, MAGICAL, TEMPLE], 2],
  // Canyon
  ["Hidden",     [ADJECTIVE, EFFECT, MAGICAL, CANYON], 2],
  ["Secret",     [ADJECTIVE, EFFECT, MAGICAL, CANYON], 2],
  ["Howling",    [ADJECTIVE, EFFECT, MAGICAL, CANYON], 2],
  ["Screaming",  [ADJECTIVE, EFFECT, MAGICAL, CANYON], 2],
  ["Whispering", [ADJECTIVE, EFFECT, MAGICAL, CANYON], 2],
  ["Frozen",     [ADJECTIVE, EFFECT, MAGICAL, CANYON], 2],
  ["Colossal",   [ADJECTIVE, EFFECT, MAGICAL, CANYON], 2],
  ["Cursed",     [ADJECTIVE, EFFECT, MAGICAL, CANYON], 2],
  ["Haunted",    [ADJECTIVE, EFFECT, MAGICAL, CANYON], 2],
  ["Creeping",   [ADJECTIVE, EFFECT, MAGICAL, CANYON], 2],
  ["Luminous",   [ADJECTIVE, EFFECT, MAGICAL, CANYON], 2],
  ["Ghostly",    [ADJECTIVE, EFFECT, MAGICAL, CANYON], 2],
  ["Bottomless", [ADJECTIVE, EFFECT, MAGICAL, CANYON], 2],
  ["Concealed",  [ADJECTIVE, EFFECT, MAGICAL, CANYON], 2],
]

// PARTICIPLES

export const past_participle_adjective: TaggedItem[] = [
  ["Weeping",    [PARTICIPLE], 2],
  ["Sleeping",   [PARTICIPLE], 2],
  ["Gasping",    [PARTICIPLE], 2],
  ["Waning",     [PARTICIPLE], 2],
  ["Wailing",    [PARTICIPLE], 2],
  ["Screeching", [PARTICIPLE], 2],
  ["Glimmering", [PARTICIPLE], 2],
  ["Writhing",   [PARTICIPLE], 2],
  ["Dancing",    [PARTICIPLE], 2],
  ["Withering",  [PARTICIPLE], 2],
  ["Creeping",   [PARTICIPLE], 2],
  ["Glowing",    [PARTICIPLE], 2],
  ["Shimmering", [PARTICIPLE], 2],
  ["Floating",   [PARTICIPLE], 2],
  ["Levitating", [PARTICIPLE], 2],
  ["Wandering",  [PARTICIPLE], 2],
  ["Singing",    [PARTICIPLE], 2],
  ["Drifting",   [PARTICIPLE], 2],
  ["Blinking",   [PARTICIPLE], 2],
  ["Jumping",    [PARTICIPLE], 2],
  ["Howling",    [PARTICIPLE], 2],
  ["Screaming",  [PARTICIPLE], 2],
  ["Burning",    [PARTICIPLE], 2],
  ["Blazing",    [PARTICIPLE], 2],
  ["Spinning",   [PARTICIPLE], 2],
  ["Whispering", [PARTICIPLE], 2],
  ["Whirling",   [PARTICIPLE], 2],
  ["Flickering", [PARTICIPLE], 2],
  ["Spiraling",  [PARTICIPLE], 2],
  ["Shifting",   [PARTICIPLE], 2],
  ["Boiling",    [PARTICIPLE], 2],
  ["Blinding",   [PARTICIPLE], 2],
  ["Shrinking",  [PARTICIPLE], 2],
  ["Hovering",   [PARTICIPLE], 2],
  ["Festering",  [PARTICIPLE], 2],
  ["Sinking",    [PARTICIPLE], 2],
  ["Smoldering", [PARTICIPLE], 2],
  ["Leaking",    [PARTICIPLE], 2],
  ["Crumbling",  [PARTICIPLE], 2],
  ["Rotting",    [PARTICIPLE], 2],
  ["Squirming",  [PARTICIPLE], 2],
  ["Looming",    [PARTICIPLE], 2],
  ["Lurking",    [PARTICIPLE], 2],
]

export const tavern_participle: TaggedItem[] = [
  ...past_participle_adjective,
  ["Limping",    [PARTICIPLE, TAVERN], 2],
  ["Snorting",   [PARTICIPLE, TAVERN], 2],
  ["Stuttering", [PARTICIPLE, TAVERN], 2],
]

// SPECIAL ADJECTIVES — terrain or structure specific

export const bridge_special_adjective: TaggedItem[] = [
  ["Covered",        [ADJECTIVE, BRIDGE], 2],
  ["Suspension",     [ADJECTIVE, BRIDGE], 2],
  ["Rope",           [ADJECTIVE, BRIDGE], 2],
  ["Toll",           [ADJECTIVE, BRIDGE], 2],
  ["Log",            [ADJECTIVE, BRIDGE], 2],
  ["Fallen Tree",    [ADJECTIVE, BRIDGE], 2],
  ["Natural",        [ADJECTIVE, BRIDGE], 2],
  ["Gargoyle",       [ADJECTIVE, BRIDGE], 2],
  ["Chain",          [ADJECTIVE, BRIDGE], 2],
  ["Ironwork",       [ADJECTIVE, BRIDGE], 2],
  ["Arched",         [ADJECTIVE, BRIDGE], 2],
  ["Stepping Stone", [ADJECTIVE, BRIDGE], 2],
]

export const tower_special_adjective: TaggedItem[] = [
  ["Bell",    [ADJECTIVE, TOWER], 2],
  ["Watch",   [ADJECTIVE, TOWER], 2],
  ["Signal",  [ADJECTIVE, TOWER], 2],
  ["Lookout", [ADJECTIVE, TOWER], 2],
]

export const stone_special_adjective: TaggedItem[] = [
  ["Wedge",      [ADJECTIVE, STONE], 2],
  ["Standing",   [ADJECTIVE, STONE], 2],
  ["Chimney",    [ADJECTIVE, STONE], 2],
  ["Wart",       [ADJECTIVE, STONE], 2],
  ["Warp",       [ADJECTIVE, STONE], 2],
  ["Wrinkle",    [ADJECTIVE, STONE], 2],
  ["Riven",      [ADJECTIVE, STONE], 2],
  ["Whispering", [ADJECTIVE, STONE], 2],
  ["Grave",      [ADJECTIVE, STONE], 2],
  ["Engraved",   [ADJECTIVE, STONE], 2],
  ["Portal",     [ADJECTIVE, STONE], 2],
  ["Spinning",   [ADJECTIVE, STONE], 2],
  ["Singing",    [ADJECTIVE, STONE], 2],
  ["Skimming",   [ADJECTIVE, STONE], 2],
  ["Leaning",    [ADJECTIVE, STONE], 2],
  ["Lode",       [ADJECTIVE, STONE], 2],
  ["Lift",       [ADJECTIVE, STONE], 2],
  ["Rune",       [ADJECTIVE, STONE], 2],
  ["Trail",      [ADJECTIVE, STONE], 2],
  ["Grind",      [ADJECTIVE, STONE], 2],
  ["Skipping",   [ADJECTIVE, STONE], 2],
  ["Moon",       [ADJECTIVE, STONE], 2],
  ["Speaking",   [ADJECTIVE, STONE], 2],
  ["Slippery",   [ADJECTIVE, STONE], 2],
  ["Balanced",   [ADJECTIVE, STONE], 2],
  ["Lookout",    [ADJECTIVE, STONE], 2],
  ["Stovepipe",  [ADJECTIVE, STONE], 2],
  ["Notch",      [ADJECTIVE, STONE], 2],
  ["Dome",       [ADJECTIVE, STONE], 2],
  ["Needle",     [ADJECTIVE, STONE], 2],
  ["Pedestal",   [ADJECTIVE, STONE], 2],
  ["Bald",       [ADJECTIVE, STONE], 2],
  ["Mushroom",   [ADJECTIVE, STONE], 2],
  ["Crevisse",   [ADJECTIVE, STONE], 2],
  ["Weird",      [ADJECTIVE, STONE], 2],
  ["Weeping",    [ADJECTIVE, STONE], 2],
  ["Chatter",    [ADJECTIVE, STONE], 2],
  ["Beetle",     [ADJECTIVE, STONE], 2],
  ["Brim",       [ADJECTIVE, STONE], 2],
  ["Float",      [ADJECTIVE, STONE], 2],
  ["Field",      [ADJECTIVE, STONE], 2],
  ["Drip",       [ADJECTIVE, STONE], 2],
  ["Sun",        [ADJECTIVE, STONE], 2],
  ["Mud",        [ADJECTIVE, STONE], 2],
  ["Touch",      [ADJECTIVE, STONE], 2],
  ["Stink",      [ADJECTIVE, STONE], 2],
  ["Smoke",      [ADJECTIVE, STONE], 2],
  ["Boil",       [ADJECTIVE, STONE], 2],
  ["Drifting",   [ADJECTIVE, STONE], 2],
  ["Mill",       [ADJECTIVE, STONE], 2],
  ["Gate",       [ADJECTIVE, STONE], 2],
  ["Helix",      [ADJECTIVE, STONE], 2],
  ["Spire",      [ADJECTIVE, STONE], 2],
  ["Alter",      [ADJECTIVE, STONE], 2],
  ["Wind",       [ADJECTIVE, STONE], 2],
  ["Calendar",   [ADJECTIVE, STONE], 2],
  ["Clock",      [ADJECTIVE, STONE], 2],
]

export const district_special_adjective: TaggedItem[] = [
  ["Dock",      [ADJECTIVE, CITY], 2],
  ["High",      [ADJECTIVE, CITY], 2],
  ["Low",       [ADJECTIVE, CITY], 2],
  ["Lower",     [ADJECTIVE, CITY], 2],
  ["Jewel",     [ADJECTIVE, CITY], 2],
  ["Palace",    [ADJECTIVE, CITY], 2],
  ["Trade",     [ADJECTIVE, CITY], 2],
  ["Sea",       [ADJECTIVE, CITY], 2],
  ["Castle",    [ADJECTIVE, CITY], 2],
  ["River",     [ADJECTIVE, CITY], 2],
  ["Garden",    [ADJECTIVE, CITY], 2],
  ["Foreign",   [ADJECTIVE, CITY], 2],
  ["Thieves",   [ADJECTIVE, CITY], 2],
  ["Artisans",  [ADJECTIVE, CITY], 2],
  ["Slum",      [ADJECTIVE, CITY], 2],
  ["Park",      [ADJECTIVE, CITY], 2],
  ["Plaza",     [ADJECTIVE, CITY], 2],
  ["Temple",    [ADJECTIVE, CITY], 2],
  ["Noble",     [ADJECTIVE, CITY], 2],
  ["Uptown",    [ADJECTIVE, CITY], 2],
  ["Harbor",    [ADJECTIVE, CITY], 2],
  ["Festival",  [ADJECTIVE, CITY], 2],
  ["Market",    [ADJECTIVE, CITY], 2],
  ["Lantern",   [ADJECTIVE, CITY], 2],
  ["Shackles",  [ADJECTIVE, CITY], 2],
  ["Emerald",   [ADJECTIVE, CITY], 2],
  ["Crypt",     [ADJECTIVE, CITY], 2],
  ["Old",       [ADJECTIVE, CITY], 2],
  ["Night",     [ADJECTIVE, CITY], 2],
  ["Marble",    [ADJECTIVE, CITY], 2],
  ["Bellows",   [ADJECTIVE, CITY], 2],
  ["Cobbles",   [ADJECTIVE, CITY], 2],
]

// COMPOSITE ADJECTIVE POOLS

export const base_adjective: TaggedItem[] = [
  ...color,
  ...emotives,
  ...materials,
  ...conditions,
  ...effects,
  ...creatures,
]

export const natural_mountain_adjective: TaggedItem[] = [
  ...color,
  ...emotives,
  ...materials,
  ...filterByTag(MOUNTAIN, conditions),
  ...filterByTag(MOUNTAIN, effects),
  ...creatures,
]

export const natural_river_adjective: TaggedItem[] = [
  ...color,
  ...emotives,
  ...materials,
  ...filterByTag(RIVER, conditions),
  ...filterByTag(RIVER, effects),
  ...creatures,
]

export const natural_hills_adjective: TaggedItem[] = [
  ...color,
  ...emotives,
  ...materials,
  ...filterByTag(HILLS, conditions),
  ...filterByTag(HILLS, effects),
  ...creatures,
]

export const natural_woodlands_adjective: TaggedItem[] = [
  ...color,
  ...emotives,
  ...materials,
  ...filterByTag(FOREST, conditions),
  ...filterByTag(FOREST, effects),
  ...creatures,
]

export const natural_marshes_adjective: TaggedItem[] = [
  ...color,
  ...emotives,
  ...materials,
  ...filterByTag(SWAMP, conditions),
  ...filterByTag(SWAMP, effects),
  ...creatures,
]

export const natural_depression_adjective: TaggedItem[] = [
  ...color,
  ...emotives,
  ...materials,
  ...filterByTag(CANYON, conditions),
  ...filterByTag(CANYON, effects),
  ...creatures,
]

export const natural_underground_adjective: TaggedItem[] = [
  ...color,
  ...emotives,
  ...materials,
  ...filterByTag(CAVE, conditions),
  ...filterByTag(CAVE, effects),
  ...creatures,
]

export const natural_saltwater_adjective: TaggedItem[] = [
  ...color,
  ...emotives,
  ...filterByTag(OCEAN, materials),
  ...filterByTag(OCEAN, conditions),
  ...filterByTag(OCEAN, effects),
  ...creatures,
]

export const natural_stone_adjective: TaggedItem[] = [
  ...base_adjective,
  ...stone_special_adjective,
]

export const construction_fortification_adjective: TaggedItem[] = [
  ...color,
  ...emotives,
  ...materials,
  ...filterByTag(TOWER, conditions),
  ...filterByTag(TOWER, effects),
  ...creatures,
]

export const construction_religious_adjective: TaggedItem[] = [
  ...color,
  ...emotives,
  ...materials,
  ...filterByTag(TEMPLE, conditions),
  ...filterByTag(TEMPLE, effects),
  ...creatures,
]

export const construction_underground_adjective: TaggedItem[] = [
  ...color,
  ...emotives,
  ...materials,
  ...filterByTag(MINE, conditions),
  ...filterByTag(MINE, effects),
  ...creatures,
]

export const construction_bridge_adjective: TaggedItem[] = [
  ...base_adjective,
  ...bridge_special_adjective,
]

export const construction_tower_adjective: TaggedItem[] = [
  ...base_adjective,
  ...tower_special_adjective,
]

export const dungeon_room_adjective: TaggedItem[] = [
  ...dungeon_materials,
  ...dungeon_objects,
  ...dungeon_adjective,
  ...dungeon_bridge_adjective,
  ...dungeon_corridor_adjective,
  ...dungeon_portal_adjective,
  ...dungeon_stairway_adjective,
  ...dungeon_pit_adjective,
]

export const tomb_room_adjective: TaggedItem[] = [
  ...tomb_objects,
  ...tomb_adjective,
]

export const temple_room_adjective: TaggedItem[] = [
  ...temple_objects,
  ...temple_adjective,
]

export const cavern_room_adjective: TaggedItem[] = [
  ...cavern_materials,
  ...cavern_objects,
  ...cavern_adjective,
]

export const magical_room_adjective: TaggedItem[] = [
  ...magical_materials,
  ...magical_objects,
  ...magical_adjective,
]
