import { TaggedItem } from '../types/types'
import {
  NOUN, ADJECTIVE,
  DUNGEON, TOMB, TEMPLE, CAVE, UNDERGROUND, MAGICAL
} from './tags'

// TOMB

export const tomb_adjective: TaggedItem[] = [
  ["Empty",       [ADJECTIVE, TOMB], 3],
  ["False",       [ADJECTIVE, TOMB], 2],
  ["Burial",      [ADJECTIVE, TOMB], 3],
  ["Haunted",     [ADJECTIVE, TOMB], 2],
  ["Trapped",     [ADJECTIVE, TOMB], 2],
  ["Ceremonial",  [ADJECTIVE, TOMB], 2],
  ["Entry",       [ADJECTIVE, TOMB], 3],
  ["Sealed",      [ADJECTIVE, TOMB], 2],
  ["Upper",       [ADJECTIVE, TOMB], 2],
  ["Lower",       [ADJECTIVE, TOMB], 2],
]

export const tomb_objects: TaggedItem[] = [
  ["Sepulcher",        [NOUN, TOMB], 1],
  ["Bone",             [NOUN, TOMB], 3],
  ["Skeleton",         [NOUN, TOMB], 3],
  ["Darkness",         [NOUN, TOMB], 2],
  ["Skull",            [NOUN, TOMB], 3],
  ["Remains",          [NOUN, TOMB], 2],
  ["Offering",         [NOUN, TOMB], 2],
  ["Armored Skeleton", [NOUN, TOMB], 1],
  ["Buried Treasure",  [NOUN, TOMB], 1],
  ["Sleeping Kings",   [NOUN, TOMB], 1],
  ["Sarcophagus",      [NOUN, TOMB], 2],
  ["Pit",              [NOUN, TOMB], 3],
]

// TEMPLE

export const temple_adjective: TaggedItem[] = [
  ["Waiting",       [ADJECTIVE, TEMPLE], 2],
  ["Violet",        [ADJECTIVE, TEMPLE], 1],
  ["Torture",       [ADJECTIVE, TEMPLE], 1],
  ["Terraced",      [ADJECTIVE, TEMPLE], 2],
  ["Tapestry",      [ADJECTIVE, TEMPLE], 1],
  ["Storage",       [ADJECTIVE, TEMPLE], 2],
  ["Robing",        [ADJECTIVE, TEMPLE], 1],
  ["Reception",     [ADJECTIVE, TEMPLE], 2],
  ["Pillared",      [ADJECTIVE, TEMPLE], 2],
  ["Meditation",    [ADJECTIVE, TEMPLE], 2],
  ["Marble",        [ADJECTIVE, TEMPLE], 2],
  ["Large",         [ADJECTIVE, TEMPLE], 3],
  ["Inner",         [ADJECTIVE, TEMPLE], 3],
  ["Outer",         [ADJECTIVE, TEMPLE], 3],
  ["Vaulted",       [ADJECTIVE, TEMPLE], 2],
  ["Divination",    [ADJECTIVE, TEMPLE], 1],
  ["Domed",         [ADJECTIVE, TEMPLE], 2],
  ["Augury",        [ADJECTIVE, TEMPLE], 1],
  ["Audience",      [ADJECTIVE, TEMPLE], 2],
  ["Arched",        [ADJECTIVE, TEMPLE], 2],
  ["Abandoned",     [ADJECTIVE, TEMPLE], 2],
  ["Columned",      [ADJECTIVE, TEMPLE], 2],
  ["Ancestral",     [ADJECTIVE, TEMPLE], 1],
  ["Processional",  [ADJECTIVE, TEMPLE], 1],
]

export const temple_objects: TaggedItem[] = [
  ["Ziggarut",      [NOUN, TEMPLE], 1],
  ["Wine",          [NOUN, TEMPLE], 2],
  ["Treasure",      [NOUN, TEMPLE], 2],
  ["Stupa",         [NOUN, TEMPLE], 1],
  ["Statuary",      [NOUN, TEMPLE], 2],
  ["Statue",        [NOUN, TEMPLE], 3],
  ["Pyramid",       [NOUN, TEMPLE], 1],
  ["Pool",          [NOUN, TEMPLE], 2],
  ["Pipe Organ",    [NOUN, TEMPLE], 1],
  ["Obelisk",       [NOUN, TEMPLE], 1],
  ["Incense",       [NOUN, TEMPLE], 2],
  ["Idol",          [NOUN, TEMPLE], 2],
  ["Mosaic",        [NOUN, TEMPLE], 2],
  ["Dome",          [NOUN, TEMPLE], 2],
  ["Dolmen",        [NOUN, TEMPLE], 1],
  ["Distillery",    [NOUN, TEMPLE], 1],
  ["Silver Chains", [NOUN, TEMPLE], 1],
  ["Candle",        [NOUN, TEMPLE], 3],
  ["Arch",          [NOUN, TEMPLE], 2],
  ["Alter",         [NOUN, TEMPLE], 3],
  ["Hundred Candles",[NOUN, TEMPLE], 1],
]

export const temple_special_rooms: TaggedItem[] = [
  ["Vestibule",           [NOUN, TEMPLE], 2],
  ["Vestry",              [NOUN, TEMPLE], 1],
  ["Sanctuary",           [NOUN, TEMPLE], 3],
  ["Shrine",              [NOUN, TEMPLE], 3],
  ["Refectory",           [NOUN, TEMPLE], 1],
  ["Promenade",           [NOUN, TEMPLE], 1],
  ["Transept",            [NOUN, TEMPLE], 1],
  ["Offeratorium",        [NOUN, TEMPLE], 1],
  ["Office",              [NOUN, TEMPLE], 2],
  ["Oratorium",           [NOUN, TEMPLE], 1],
  ["Pavillion",           [NOUN, TEMPLE], 2],
  ["Nave",                [NOUN, TEMPLE], 2],
  ["Court",               [NOUN, TEMPLE], 2],
  ["Library",             [NOUN, TEMPLE], 2],
  ["Hall",                [NOUN, TEMPLE], 3],
  ["Sanctum",             [NOUN, TEMPLE], 2],
  ["Herbarium",           [NOUN, TEMPLE], 1],
  ["Foyer",               [NOUN, TEMPLE], 2],
  ["Chantry",             [NOUN, TEMPLE], 1],
  ["Choir Loft",          [NOUN, TEMPLE], 1],
  ["Balcony",             [NOUN, TEMPLE], 2],
  ["Beastiary",           [NOUN, TEMPLE], 1],
  ["Archives",            [NOUN, TEMPLE], 1],
  ["Annex",               [NOUN, TEMPLE], 2],
  ["Antechamber",         [NOUN, TEMPLE], 2],
  ["Apse",                [NOUN, TEMPLE], 1],
  ["Arcade (of Pillars)", [NOUN, TEMPLE], 1],
  ["Alcove",              [NOUN, TEMPLE], 2],
  ["Cloister",            [NOUN, TEMPLE], 1],
  ["Chapel",              [NOUN, TEMPLE], 2],
]

// CAVERNS

export const cavern_materials: TaggedItem[] = [
  ["Coral",      [ADJECTIVE, CAVE], 1],
  ["Algae",      [ADJECTIVE, CAVE], 2],
  ["Basalt",     [ADJECTIVE, CAVE], 2],
  ["Bone",       [ADJECTIVE, CAVE], 2],
  ["Carnelian",  [ADJECTIVE, CAVE], 1],
  ["Clay",       [ADJECTIVE, CAVE], 2],
  ["Crystal",    [ADJECTIVE, CAVE], 2],
  ["Ice",        [ADJECTIVE, CAVE], 2],
  ["Flowstone",  [ADJECTIVE, CAVE], 1],
  ["Fungus",     [ADJECTIVE, CAVE], 2],
  ["Gypsum",     [ADJECTIVE, CAVE], 1],
  ["Sand",       [ADJECTIVE, CAVE], 2],
  ["Slate",      [ADJECTIVE, CAVE], 1],
  ["Steam",      [ADJECTIVE, CAVE], 2],
  ["Water",      [ADJECTIVE, CAVE], 2],
]

export const cavern_objects: TaggedItem[] = [
  ["Minaret",      [NOUN, CAVE], 1],
  ["Waterfall",    [NOUN, CAVE], 2],
  ["Spring",       [NOUN, CAVE], 2],
  ["Bridge",       [NOUN, CAVE], 2],
  ["Artifact",     [NOUN, CAVE], 1],
  ["Bone",         [NOUN, CAVE], 3],
  ["Boulder",      [NOUN, CAVE], 2],
  ["Many Candles", [NOUN, CAVE], 1],
  ["Glowing Skull",[NOUN, CAVE], 1],
  ["Skull",        [NOUN, CAVE], 2],
  ["Corpse",       [NOUN, CAVE], 2],
  ["Cave Pearl",   [NOUN, CAVE], 1],
  ["Coffin",       [NOUN, CAVE], 2],
  ["Crystal",      [NOUN, CAVE], 2],
  ["Distillery",   [NOUN, CAVE], 1],
  ["Engraving",    [NOUN, CAVE], 2],
  ["Formation",    [NOUN, CAVE], 2],
  ["Gem",          [NOUN, CAVE], 1],
  ["Demon Idol",   [NOUN, CAVE], 1],
  ["Magic Pool",   [NOUN, CAVE], 1],
  ["Moat",         [NOUN, CAVE], 1],
  ["Pit",          [NOUN, CAVE], 2],
  ["Pool",         [NOUN, CAVE], 2],
  ["Ice Cube",     [NOUN, CAVE], 1],
  ["Rune",         [NOUN, CAVE], 1],
  ["Sewer",        [NOUN, CAVE], 1],
  ["Sinkhole",     [NOUN, CAVE], 1],
  ["Stream",       [NOUN, CAVE], 2],
  ["Trapdoor",     [NOUN, CAVE], 1],
  ["Volcano",      [NOUN, CAVE], 1],
  ["Weapon",       [NOUN, CAVE], 2],
]

export const cavern_adjective: TaggedItem[] = [
  ["Winding",          [ADJECTIVE, CAVE], 2],
  ["Wide",             [ADJECTIVE, CAVE], 3],
  ["Wet",              [ADJECTIVE, CAVE], 3],
  ["Water Filled",     [ADJECTIVE, CAVE], 2],
  ["Upper",            [ADJECTIVE, CAVE], 3],
  ["Splendid",         [ADJECTIVE, CAVE], 1],
  ["Narrow",           [ADJECTIVE, CAVE], 3],
  ["Monotonous",       [ADJECTIVE, CAVE], 1],
  ["Lower",            [ADJECTIVE, CAVE], 3],
  ["Inclined",         [ADJECTIVE, CAVE], 2],
  ["Gothic",           [ADJECTIVE, CAVE], 1],
  ["Forgotten",        [ADJECTIVE, CAVE], 2],
  ["Dark",             [ADJECTIVE, CAVE], 3],
  ["Collapsed",        [ADJECTIVE, CAVE], 2],
  ["Grinding",         [ADJECTIVE, CAVE], 1],
  ["Dripping",         [ADJECTIVE, CAVE], 2],
  ["Frostwork",        [ADJECTIVE, CAVE], 1],
  ["Arched",           [ADJECTIVE, CAVE], 2],
  ["Attic",            [ADJECTIVE, CAVE], 1],
  ["Blast",            [ADJECTIVE, CAVE], 1],
  ["Cathedral",        [ADJECTIVE, CAVE], 1],
  ["Charred and Burned",[ADJECTIVE, CAVE], 1],
  ["Communal",         [ADJECTIVE, CAVE], 2],
  ["Damp",             [ADJECTIVE, CAVE], 3],
  ["Deserted",         [ADJECTIVE, CAVE], 2],
  ["Dismal",           [ADJECTIVE, CAVE], 1],
  ["Secret",           [ADJECTIVE, CAVE], 2],
  ["Deep",             [ADJECTIVE, CAVE], 3],
  ["Domed",            [ADJECTIVE, CAVE], 1],
  ["Vaulted",          [ADJECTIVE, CAVE], 2],
  ["Dry",              [ADJECTIVE, CAVE], 2],
  ["Empty",            [ADJECTIVE, CAVE], 2],
  ["Engraved",         [ADJECTIVE, CAVE], 2],
  ["Entry",            [ADJECTIVE, CAVE], 3],
  ["Exit",             [ADJECTIVE, CAVE], 2],
  ["Fire",             [ADJECTIVE, CAVE], 2],
  ["Flooding",         [ADJECTIVE, CAVE], 2],
  ["Glittering",       [ADJECTIVE, CAVE], 1],
  ["Glowing",          [ADJECTIVE, CAVE], 2],
  ["Grey",             [ADJECTIVE, CAVE], 2],
  ["Guard",            [ADJECTIVE, CAVE], 2],
  ["Hidden",           [ADJECTIVE, CAVE], 2],
  ["Huge",             [ADJECTIVE, CAVE], 2],
  ["Vast",             [ADJECTIVE, CAVE], 2],
  ["Irregular",        [ADJECTIVE, CAVE], 2],
  ["Jagged",           [ADJECTIVE, CAVE], 2],
  ["Jeweled",          [ADJECTIVE, CAVE], 1],
  ["Littered",         [ADJECTIVE, CAVE], 2],
  ["Long",             [ADJECTIVE, CAVE], 3],
  ["Low Ceiling",      [ADJECTIVE, CAVE], 2],
  ["Misty",            [ADJECTIVE, CAVE], 2],
  ["Mudslide",         [ADJECTIVE, CAVE], 1],
  ["Pillared",         [ADJECTIVE, CAVE], 2],
  ["Rotunda",          [ADJECTIVE, CAVE], 1],
  ["Sealed",           [ADJECTIVE, CAVE], 2],
  ["Shattered",        [ADJECTIVE, CAVE], 2],
  ["Singing",          [ADJECTIVE, CAVE], 1],
  ["Slippery",         [ADJECTIVE, CAVE], 2],
  ["Small",            [ADJECTIVE, CAVE], 3],
  ["Smoke Filled",     [ADJECTIVE, CAVE], 2],
  ["Smooth",           [ADJECTIVE, CAVE], 2],
  ["Stinking",         [ADJECTIVE, CAVE], 2],
  ["Storage",          [ADJECTIVE, CAVE], 2],
  ["Sunken",           [ADJECTIVE, CAVE], 2],
  ["Terraced",         [ADJECTIVE, CAVE], 1],
  ["Wind",             [ADJECTIVE, CAVE], 2],
]

export const cavern_special_rooms: TaggedItem[] = [
  ["Culvert",   [NOUN, CAVE], 2],
  ["Catacombs", [NOUN, CAVE], 1],
  ["Rift",      [NOUN, CAVE], 2],
  ["Labyrinth", [NOUN, CAVE], 1],
  ["Crawlway",  [NOUN, CAVE], 2],
  ["Corkscrew", [NOUN, CAVE], 1],
  ["Alcove",    [NOUN, CAVE], 2],
  ["Antecavern",[NOUN, CAVE], 1],
  ["Barrow",    [NOUN, CAVE], 1],
  ["Cavity",    [NOUN, CAVE], 2],
  ["Chasm",     [NOUN, CAVE], 2],
  ["Crevasse",  [NOUN, CAVE], 1],
  ["Hollow",    [NOUN, CAVE], 2],
  ["Grotto",    [NOUN, CAVE], 2],
  ["Loft",      [NOUN, CAVE], 1],
  ["Attic",     [NOUN, CAVE], 1],
  ["Cellar",    [NOUN, CAVE], 2],
  ["Balcony",   [NOUN, CAVE], 1],
  ["Ballroom",  [NOUN, CAVE], 1],
  ["Ravine",    [NOUN, CAVE], 2],
  ["Sewers",    [NOUN, CAVE], 1],
  ["Gallery",   [NOUN, CAVE], 1],
]

export const cavern_room_unique: TaggedItem[] = [
  ["The Button Hole",             [NOUN, CAVE], 1],
  ["Rathole",                     [NOUN, CAVE], 2],
  ["Escape Tunnel",               [NOUN, CAVE], 2],
  ["Borehole",                    [NOUN, CAVE], 1],
  ["Belfry",                      [NOUN, CAVE], 1],
  ["Chandelier Ballroom",         [NOUN, CAVE], 1],
  ["Natural Bridge",              [NOUN, CAVE], 2],
  ["Virgin Forest",               [NOUN, CAVE], 1],
  ["Ammonia Cave (Bat Colony)",   [NOUN, CAVE], 1],
  ["Boneyard",                    [NOUN, CAVE], 2],
  ["Boulder Choke",               [NOUN, CAVE], 1],
  ["Boulder Heap",                [NOUN, CAVE], 1],
  ["Cave Warrens",                [NOUN, CAVE], 2],
  ["Cavern Barracks",             [NOUN, CAVE], 1],
  ["Cavern Hall",                 [NOUN, CAVE], 2],
  ["Cave Chamber",                [NOUN, CAVE], 2],
  ["Cavern Temple",               [NOUN, CAVE], 1],
  ["Coral Grove",                 [NOUN, CAVE], 1],
  ["Crystal Gardens",             [NOUN, CAVE], 1],
  ["Crystal Grotto",              [NOUN, CAVE], 1],
  ["Crystal Pool",                [NOUN, CAVE], 1],
  ["Death Valley",                [NOUN, CAVE], 1],
  ["Deep Sea Room",               [NOUN, CAVE], 1],
  ["Deep Secrets",                [NOUN, CAVE], 1],
  ["Devil's Ice Box",             [NOUN, CAVE], 1],
  ["Dismal Hollow",               [NOUN, CAVE], 2],
  ["Elfin Forest",                [NOUN, CAVE], 1],
  ["Fairy Grotto",                [NOUN, CAVE], 1],
  ["Firecaverns",                 [NOUN, CAVE], 1],
  ["Ghost Town",                  [NOUN, CAVE], 1],
  ["Giant's Hallway",             [NOUN, CAVE], 1],
  ["Glacier Way",                 [NOUN, CAVE], 1],
  ["Grand Entry",                 [NOUN, CAVE], 2],
  ["Great Beyond",                [NOUN, CAVE], 1],
  ["Helictite Hall",              [NOUN, CAVE], 1],
  ["Hidden Loft",                 [NOUN, CAVE], 1],
  ["Infernal Regions",            [NOUN, CAVE], 1],
  ["Jungle Room",                 [NOUN, CAVE], 1],
  ["Kitchen Cave",                [NOUN, CAVE], 1],
  ["Land of Awes",                [NOUN, CAVE], 1],
  ["Lava Pool",                   [NOUN, CAVE], 1],
  ["Lost World Cave",             [NOUN, CAVE], 1],
  ["Menagerie",                   [NOUN, CAVE], 1],
  ["Mummy's Niche",               [NOUN, CAVE], 1],
  ["Nirvana",                     [NOUN, CAVE], 1],
  ["North Rift",                  [NOUN, CAVE], 1],
  ["Oasis",                       [NOUN, CAVE], 2],
  ["Prison Cave",                 [NOUN, CAVE], 1],
  ["Rainbow Cavern",              [NOUN, CAVE], 1],
  ["Stalagmite Forest",           [NOUN, CAVE], 1],
  ["Storm Shelter",               [NOUN, CAVE], 1],
  ["Underground River",           [NOUN, CAVE], 2],
  ["Underground Lake",            [NOUN, CAVE], 1],
  ["Whale's Stomach",             [NOUN, CAVE], 1],
]

export const cavern_water_special_rooms: TaggedItem[] = [
  ["Waterfall", [NOUN, CAVE], 3],
  ["Spring",    [NOUN, CAVE], 2],
  ["Falls",     [NOUN, CAVE], 2],
]

export const cavern_portal_special_rooms: TaggedItem[] = [
  ["Keyhole", [NOUN, CAVE], 2],
]

export const cavern_unique: TaggedItem[] = [
  ...cavern_room_unique,
  ...cavern_water_special_rooms,
]

// DUNGEON

export const dungeon_materials: TaggedItem[] = [
  ["Teak",       [ADJECTIVE, DUNGEON], 1],
  ["Cedar",      [ADJECTIVE, DUNGEON], 1],
  ["Red Marble", [ADJECTIVE, DUNGEON], 1],
  ["Sand",       [ADJECTIVE, DUNGEON], 2],
  ["Steam",      [ADJECTIVE, DUNGEON], 2],
  ["Moss",       [ADJECTIVE, DUNGEON], 2],
  ["Lava",       [ADJECTIVE, DUNGEON], 1],
  ["Ice",        [ADJECTIVE, DUNGEON], 2],
  ["Granite",    [ADJECTIVE, DUNGEON], 2],
  ["Geode",      [ADJECTIVE, DUNGEON], 1],
  ["Dust",       [ADJECTIVE, DUNGEON], 3],
  ["Coal",       [ADJECTIVE, DUNGEON], 1],
  ["Amber",      [ADJECTIVE, DUNGEON], 1],
]

export const dungeon_objects: TaggedItem[] = [
  ["Well",             [NOUN, DUNGEON], 2],
  ["Hot Spring",       [NOUN, DUNGEON], 1],
  ["Mud Pit",          [NOUN, DUNGEON], 1],
  ["Vaulted Skylight", [NOUN, DUNGEON], 1],
  ["Sparkling Stone",  [NOUN, DUNGEON], 1],
  ["Boiler",           [NOUN, DUNGEON], 1],
  ["Spyhole",          [NOUN, DUNGEON], 1],
  ["Pit",              [NOUN, DUNGEON], 2],
  ["Rat",              [NOUN, DUNGEON], 2],
  ["Antler",           [NOUN, DUNGEON], 1],
  ["Winch",            [NOUN, DUNGEON], 1],
  ["Weapon",           [NOUN, DUNGEON], 2],
  ["Waterfall",        [NOUN, DUNGEON], 1],
  ["Sword",            [NOUN, DUNGEON], 2],
  ["Valve",            [NOUN, DUNGEON], 1],
  ["Trophy",           [NOUN, DUNGEON], 2],
  ["Treasure",         [NOUN, DUNGEON], 2],
  ["Trap",             [NOUN, DUNGEON], 2],
  ["Torch",            [NOUN, DUNGEON], 3],
  ["Throne",           [NOUN, DUNGEON], 2],
  ["Slippery Floor",   [NOUN, DUNGEON], 2],
  ["Rope",             [NOUN, DUNGEON], 2],
  ["Crowned Skull",    [NOUN, DUNGEON], 1],
  ["Refuse",           [NOUN, DUNGEON], 2],
  ["Quicksand",        [NOUN, DUNGEON], 1],
  ["Pump",             [NOUN, DUNGEON], 1],
  ["Provisions",       [NOUN, DUNGEON], 2],
  ["Pottery",          [NOUN, DUNGEON], 1],
  ["Moat",             [NOUN, DUNGEON], 1],
  ["Lodestone",        [NOUN, DUNGEON], 1],
  ["Ladder",           [NOUN, DUNGEON], 2],
  ["Junk",             [NOUN, DUNGEON], 2],
  ["Black Helm",       [NOUN, DUNGEON], 1],
  ["Garbage",          [NOUN, DUNGEON], 2],
  ["Crossbow",         [NOUN, DUNGEON], 2],
  ["Fountain",         [NOUN, DUNGEON], 2],
  ["Cube",             [NOUN, DUNGEON], 1],
  ["Compass Rose",     [NOUN, DUNGEON], 1],
  ["Cobweb",           [NOUN, DUNGEON], 2],
  ["Stone Head",       [NOUN, DUNGEON], 1],
  ["Barrel",           [NOUN, DUNGEON], 2],
  ["Ballistae",        [NOUN, DUNGEON], 1],
  ["Arsenal",          [NOUN, DUNGEON], 2],
  ["Water Clock",      [NOUN, DUNGEON], 1],
]

export const dungeon_adjective: TaggedItem[] = [
  ["Sewage",              [ADJECTIVE, DUNGEON], 2],
  ["Sundered",            [ADJECTIVE, DUNGEON], 1],
  ["Greased",             [ADJECTIVE, DUNGEON], 1],
  ["Muttering",           [ADJECTIVE, DUNGEON], 1],
  ["Unfinished",          [ADJECTIVE, DUNGEON], 2],
  ["Training",            [ADJECTIVE, DUNGEON], 2],
  ["Toll",                [ADJECTIVE, DUNGEON], 1],
  ["Timber",              [ADJECTIVE, DUNGEON], 2],
  ["Thieves",             [ADJECTIVE, DUNGEON], 1],
  ["Secret",              [ADJECTIVE, DUNGEON], 2],
  ["Rubble-Filled",       [ADJECTIVE, DUNGEON], 2],
  ["Round",               [ADJECTIVE, DUNGEON], 2],
  ["Rough Hewn",          [ADJECTIVE, DUNGEON], 2],
  ["Polished",            [ADJECTIVE, DUNGEON], 2],
  ["Partially Collapsed", [ADJECTIVE, DUNGEON], 2],
  ["Padlocked",           [ADJECTIVE, DUNGEON], 1],
  ["Mud-Filled",          [ADJECTIVE, DUNGEON], 2],
  ["Opulent",             [ADJECTIVE, DUNGEON], 1],
  ["Odd-Angled",          [ADJECTIVE, DUNGEON], 1],
  ["Misty",               [ADJECTIVE, DUNGEON], 2],
  ["Meeting",             [ADJECTIVE, DUNGEON], 2],
  ["Maintenance",         [ADJECTIVE, DUNGEON], 2],
  ["Loud",                [ADJECTIVE, DUNGEON], 2],
  ["Locked",              [ADJECTIVE, DUNGEON], 2],
  ["Littered",            [ADJECTIVE, DUNGEON], 2],
  ["Jumbled",             [ADJECTIVE, DUNGEON], 1],
  ["Inky",                [ADJECTIVE, DUNGEON], 1],
  ["Echo",                [ADJECTIVE, DUNGEON], 2],
  ["Guard",               [ADJECTIVE, DUNGEON], 3],
  ["Grim",                [ADJECTIVE, DUNGEON], 2],
  ["Grand",               [ADJECTIVE, DUNGEON], 2],
  ["Forsaken",            [ADJECTIVE, DUNGEON], 2],
  ["Forgotten",           [ADJECTIVE, DUNGEON], 2],
  ["Foggy",               [ADJECTIVE, DUNGEON], 2],
  ["Flooding",            [ADJECTIVE, DUNGEON], 2],
  ["Empty",               [ADJECTIVE, DUNGEON], 3],
  ["Earth-floored",       [ADJECTIVE, DUNGEON], 2],
  ["Dusty",               [ADJECTIVE, DUNGEON], 3],
  ["Moldy",               [ADJECTIVE, DUNGEON], 2],
  ["Drainage",            [ADJECTIVE, DUNGEON], 2],
  ["Deserted",            [ADJECTIVE, DUNGEON], 2],
  ["Damp",                [ADJECTIVE, DUNGEON], 3],
  ["Cool",                [ADJECTIVE, DUNGEON], 2],
  ["Common",              [ADJECTIVE, DUNGEON], 3],
  ["Collapsed",           [ADJECTIVE, DUNGEON], 2],
  ["Bricked Up",          [ADJECTIVE, DUNGEON], 1],
  ["Boarded Up",          [ADJECTIVE, DUNGEON], 1],
  ["Bloodstained",        [ADJECTIVE, DUNGEON], 2],
  ["Barred",              [ADJECTIVE, DUNGEON], 2],
  ["Banquet",             [ADJECTIVE, DUNGEON], 1],
  ["Audience",            [ADJECTIVE, DUNGEON], 2],
  ["Arched",              [ADJECTIVE, DUNGEON], 2],
]

export const dungeon_special_rooms: TaggedItem[] = [
  ["Oubliette",                 [NOUN, DUNGEON], 1],
  ["Maze",                      [NOUN, DUNGEON], 2],
  ["Cove",                      [NOUN, DUNGEON], 1],
  ["Cistern",                   [NOUN, DUNGEON], 2],
  ["Smithy",                    [NOUN, DUNGEON], 2],
  ["Forge",                     [NOUN, DUNGEON], 2],
  ["Wellroom",                  [NOUN, DUNGEON], 1],
  ["Storeroom",                 [NOUN, DUNGEON], 3],
  ["Ballroom",                  [NOUN, DUNGEON], 1],
  ["Bedchamber",                [NOUN, DUNGEON], 2],
  ["Compartment",               [NOUN, DUNGEON], 2],
  ["Prison",                    [NOUN, DUNGEON], 2],
  ["Pantry",                    [NOUN, DUNGEON], 2],
  ["Nursery",                   [NOUN, DUNGEON], 1],
  ["Elevator",                  [NOUN, DUNGEON], 1],
  ["Arena",                     [NOUN, DUNGEON], 2],
  ["Armory",                    [NOUN, DUNGEON], 2],
  ["Kennels",                   [NOUN, DUNGEON], 1],
  ["Niche",                     [NOUN, DUNGEON], 2],
  ["Dormitory",                 [NOUN, DUNGEON], 2],
  ["Recess",                    [NOUN, DUNGEON], 2],
  ["Scullery (Dish Washing Room)",[NOUN, DUNGEON], 1],
  ["Latrine",                   [NOUN, DUNGEON], 1],
  ["Kitchen",                   [NOUN, DUNGEON], 2],
  ["Coliseum",                  [NOUN, DUNGEON], 1],
  ["Cellar",                    [NOUN, DUNGEON], 2],
  ["Cesspool",                  [NOUN, DUNGEON], 1],
  ["Closet",                    [NOUN, DUNGEON], 2],
  ["Barracks",                  [NOUN, DUNGEON], 2],
  ["Barroom",                   [NOUN, DUNGEON], 2],
  ["Bank",                      [NOUN, DUNGEON], 1],
  ["Aquaduct",                  [NOUN, DUNGEON], 1],
  ["Snuggery",                  [NOUN, DUNGEON], 1],
]

export const dungeon_unique: TaggedItem[] = [
  ["Tight Squeeze",         [NOUN, DUNGEON], 2],
  ["Vent Shaft",            [NOUN, DUNGEON], 2],
  ["Swill Pit",             [NOUN, DUNGEON], 1],
  ["Mine Shaft",            [NOUN, DUNGEON], 2],
  ["Tool Shed",             [NOUN, DUNGEON], 2],
  ["Strong Room",           [NOUN, DUNGEON], 2],
  ["Boat Dock (Row Boat)",  [NOUN, DUNGEON], 1],
  ["Slippery Slide",        [NOUN, DUNGEON], 2],
  ["Shooting Gallery",      [NOUN, DUNGEON], 1],
  ["Dressing Room",         [NOUN, DUNGEON], 2],
  ["Dining Room",           [NOUN, DUNGEON], 2],
  ["Living Room",           [NOUN, DUNGEON], 2],
  ["Root Cellar",           [NOUN, DUNGEON], 2],
  ["Nursery Room",          [NOUN, DUNGEON], 1],
  ["Gas Chamber",           [NOUN, DUNGEON], 1],
  ["Food Storage",          [NOUN, DUNGEON], 2],
  ["Fuel Storage",          [NOUN, DUNGEON], 1],
  ["Oaken Cabinet",         [NOUN, DUNGEON], 1],
  ["Bridal Chamber",        [NOUN, DUNGEON], 1],
  ["Firing Range",          [NOUN, DUNGEON], 1],
  ["Linen Closet",          [NOUN, DUNGEON], 1],
  ["Harem/Seraglio",        [NOUN, DUNGEON], 1],
  ["Underground Bridge",    [NOUN, DUNGEON], 1],
]

export const dungeon_bridge_adjective: TaggedItem[] = [
  ["Collapsing", [ADJECTIVE, DUNGEON], 2],
  ["Rope",       [ADJECTIVE, DUNGEON], 2],
  ["Rotting",    [ADJECTIVE, DUNGEON], 2],
  ["Stone",      [ADJECTIVE, DUNGEON], 3],
]

export const dungeon_corridor_adjective: TaggedItem[] = [
  ["Blocked",   [ADJECTIVE, DUNGEON], 2],
  ["Cobweb",    [ADJECTIVE, DUNGEON], 2],
  ["Collapsed", [ADJECTIVE, DUNGEON], 2],
  ["Crooked",   [ADJECTIVE, DUNGEON], 2],
  ["Flooded",   [ADJECTIVE, DUNGEON], 2],
  ["Junction",  [ADJECTIVE, DUNGEON], 2],
  ["Plain",     [ADJECTIVE, DUNGEON], 3],
  ["Round",     [ADJECTIVE, DUNGEON], 2],
  ["Royal",     [ADJECTIVE, DUNGEON], 1],
  ["Trapped",   [ADJECTIVE, DUNGEON], 2],
  ["Verdigris", [ADJECTIVE, DUNGEON], 1],
]

export const dungeon_portal_adjective: TaggedItem[] = [
  ["Great Iron",   [ADJECTIVE, DUNGEON], 2],
  ["Heavy Barred", [ADJECTIVE, DUNGEON], 2],
  ["Reinforced",   [ADJECTIVE, DUNGEON], 2],
  ["Secret",       [ADJECTIVE, DUNGEON], 2],
  ["One-way",      [ADJECTIVE, DUNGEON], 1],
  ["Metal",        [ADJECTIVE, DUNGEON], 2],
  ["Stone",        [ADJECTIVE, DUNGEON], 3],
  ["Circular",     [ADJECTIVE, DUNGEON], 1],
  ["False",        [ADJECTIVE, DUNGEON], 2],
  ["Double",       [ADJECTIVE, DUNGEON], 2],
  ["Revolving",    [ADJECTIVE, DUNGEON], 1],
]

export const dungeon_stairway_adjective: TaggedItem[] = [
  ["Main",    [ADJECTIVE, DUNGEON], 3],
  ["Marble",  [ADJECTIVE, DUNGEON], 2],
  ["Moving",  [ADJECTIVE, DUNGEON], 1],
  ["Ruined",  [ADJECTIVE, DUNGEON], 2],
  ["Sinister",[ADJECTIVE, DUNGEON], 1],
  ["Trapped", [ADJECTIVE, DUNGEON], 2],
]

export const dungeon_pit_adjective: TaggedItem[] = [
  ["Circular",    [ADJECTIVE, DUNGEON], 2],
  ["Drainage",    [ADJECTIVE, DUNGEON], 2],
  ["Locking",     [ADJECTIVE, DUNGEON], 1],
  ["Flooding",    [ADJECTIVE, DUNGEON], 2],
  ["Spiked",      [ADJECTIVE, DUNGEON], 2],
  ["Spear",       [ADJECTIVE, DUNGEON], 2],
  ["Poison Spike",[ADJECTIVE, DUNGEON], 1],
  ["Teleporting", [ADJECTIVE, DUNGEON], 1],
  ["Crossbow",    [ADJECTIVE, DUNGEON], 1],
  ["Slime",       [ADJECTIVE, DUNGEON], 2],
  ["Gas",         [ADJECTIVE, DUNGEON], 2],
  ["Water Filled",[ADJECTIVE, DUNGEON], 2],
  ["Acid",        [ADJECTIVE, DUNGEON], 1],
  ["Sulfur",      [ADJECTIVE, DUNGEON], 1],
  ["Rat",         [ADJECTIVE, DUNGEON], 2],
  ["Snake",       [ADJECTIVE, DUNGEON], 2],
]

// MAGICAL

export const magical_unique: TaggedItem[] = [
  ["Underground Garden", [NOUN, MAGICAL], 1],
  ["Treasure Vault",     [NOUN, MAGICAL], 2],
  ["Wind Tunnel",        [NOUN, MAGICAL], 1],
  ["Storage Space",      [NOUN, MAGICAL], 2],
  ["Scenic Vista",       [NOUN, MAGICAL], 1],
  ["Fish Tank",          [NOUN, MAGICAL], 1],
  ["Echo Chamber",       [NOUN, MAGICAL], 1],
  ["Game Room",          [NOUN, MAGICAL], 1],
  ["Display Room",       [NOUN, MAGICAL], 1],
  ["Control Room",       [NOUN, MAGICAL], 1],
  ["Cloak Room",         [NOUN, MAGICAL], 2],
  ["Classroom",          [NOUN, MAGICAL], 1],
  ["Card Room",          [NOUN, MAGICAL], 1],
  ["Beam Room",          [NOUN, MAGICAL], 1],
  ["Council Chamber",    [NOUN, MAGICAL], 1],
  ["Curtain of Beads",   [NOUN, MAGICAL], 1],
  ["Art Studio",         [NOUN, MAGICAL], 1],
]

export const magical_materials: TaggedItem[] = [
  ["Jade",           [ADJECTIVE, MAGICAL], 2],
  ["Glass",          [ADJECTIVE, MAGICAL], 2],
  ["Crystal",        [ADJECTIVE, MAGICAL], 2],
  ["Marble and Gold",[ADJECTIVE, MAGICAL], 1],
  ["Mist",           [ADJECTIVE, MAGICAL], 2],
  ["Mithril",        [ADJECTIVE, MAGICAL], 1],
]

export const magical_objects: TaggedItem[] = [
  ["Floating Bones", [NOUN, MAGICAL], 1],
  ["Treasure",       [NOUN, MAGICAL], 2],
  ["Fountain",       [NOUN, MAGICAL], 2],
  ["Throne",         [NOUN, MAGICAL], 2],
  ["Tea",            [NOUN, MAGICAL], 1],
  ["Star",           [NOUN, MAGICAL], 1],
  ["Sphere",         [NOUN, MAGICAL], 2],
  ["Scroll",         [NOUN, MAGICAL], 2],
  ["Spell",          [NOUN, MAGICAL], 1],
  ["Rosette",        [NOUN, MAGICAL], 1],
  ["Green Glow",     [NOUN, MAGICAL], 1],
  ["Mirror",         [NOUN, MAGICAL], 2],
  ["Machine",        [NOUN, MAGICAL], 2],
  ["Lantern",        [NOUN, MAGICAL], 2],
  ["Key",            [NOUN, MAGICAL], 2],
  ["Jewelry",        [NOUN, MAGICAL], 2],
  ["Illusion",       [NOUN, MAGICAL], 1],
  ["Floating Hat",   [NOUN, MAGICAL], 1],
  ["Grim Statue",    [NOUN, MAGICAL], 1],
  ["Gem",            [NOUN, MAGICAL], 2],
  ["Gargoyle",       [NOUN, MAGICAL], 2],
  ["Talking Painting",[NOUN, MAGICAL], 1],
  ["Shield",         [NOUN, MAGICAL], 2],
  ["Painting",       [NOUN, MAGICAL], 2],
  ["Living Sculpture",[NOUN, MAGICAL], 1],
  ["Fungus",         [NOUN, MAGICAL], 1],
  ["Fresco",         [NOUN, MAGICAL], 1],
  ["Engraving",      [NOUN, MAGICAL], 2],
  ["Pedestal",       [NOUN, MAGICAL], 2],
  ["Compass",        [NOUN, MAGICAL], 1],
  ["Clock",          [NOUN, MAGICAL], 1],
  ["Cloak",          [NOUN, MAGICAL], 2],
  ["Talking Skull",  [NOUN, MAGICAL], 1],
  ["Floating Corpse",[NOUN, MAGICAL], 1],
  ["Dancing Swords", [NOUN, MAGICAL], 1],
  ["Sword",          [NOUN, MAGICAL], 2],
  ["Potion",         [NOUN, MAGICAL], 2],
  ["Portal",         [NOUN, MAGICAL], 2],
  ["Pool",           [NOUN, MAGICAL], 2],
  ["Map",            [NOUN, MAGICAL], 2],
  ["Lever",          [NOUN, MAGICAL], 2],
  ["Floating Skull", [NOUN, MAGICAL], 1],
  ["Eye",            [NOUN, MAGICAL], 2],
  ["Chest",          [NOUN, MAGICAL], 2],
  ["Cauldron",       [NOUN, MAGICAL], 2],
  ["Balloon",        [NOUN, MAGICAL], 1],
  ["Cage",           [NOUN, MAGICAL], 2],
  ["Artifact",       [NOUN, MAGICAL], 2],
  ["Armor",          [NOUN, MAGICAL], 2],
  ["Abacus",         [NOUN, MAGICAL], 1],
  ["Floating Candles",[NOUN, MAGICAL], 1],
  ["Guardian",       [NOUN, MAGICAL], 2],
]

export const magical_adjective: TaggedItem[] = [
  ["Wondrous",     [ADJECTIVE, MAGICAL], 2],
  ["Weird",        [ADJECTIVE, MAGICAL], 2],
  ["Viewing",      [ADJECTIVE, MAGICAL], 1],
  ["Tiny",         [ADJECTIVE, MAGICAL], 2],
  ["Terraced",     [ADJECTIVE, MAGICAL], 1],
  ["Teleportation",[ADJECTIVE, MAGICAL], 1],
  ["Sunken",       [ADJECTIVE, MAGICAL], 2],
  ["Summoning",    [ADJECTIVE, MAGICAL], 1],
  ["Striated",     [ADJECTIVE, MAGICAL], 1],
  ["Storage",      [ADJECTIVE, MAGICAL], 2],
  ["Stasis",       [ADJECTIVE, MAGICAL], 1],
  ["Spinning",     [ADJECTIVE, MAGICAL], 1],
  ["Smoking",      [ADJECTIVE, MAGICAL], 1],
  ["Secret",       [ADJECTIVE, MAGICAL], 2],
  ["Scrying",      [ADJECTIVE, MAGICAL], 1],
  ["Reflecting",   [ADJECTIVE, MAGICAL], 1],
  ["Radiation",    [ADJECTIVE, MAGICAL], 1],
  ["Pleasure",     [ADJECTIVE, MAGICAL], 1],
  ["Pearlescent",  [ADJECTIVE, MAGICAL], 1],
  ["Opulent",      [ADJECTIVE, MAGICAL], 1],
  ["Luxurious",    [ADJECTIVE, MAGICAL], 1],
  ["Locked",       [ADJECTIVE, MAGICAL], 2],
  ["Lavish",       [ADJECTIVE, MAGICAL], 1],
  ["Inner",        [ADJECTIVE, MAGICAL], 2],
  ["Elemental",    [ADJECTIVE, MAGICAL], 1],
  ["Domed",        [ADJECTIVE, MAGICAL], 1],
  ["Conjuring",    [ADJECTIVE, MAGICAL], 1],
  ["Purple",       [ADJECTIVE, MAGICAL], 1],
  ["Muraled",      [ADJECTIVE, MAGICAL], 1],
  ["Glowing",      [ADJECTIVE, MAGICAL], 2],
]

export const magical_special_rooms: TaggedItem[] = [
  ["Salon",      [NOUN, MAGICAL], 1],
  ["Registary",  [NOUN, MAGICAL], 1],
  ["Privy",      [NOUN, MAGICAL], 1],
  ["Planetarium",[NOUN, MAGICAL], 1],
  ["Museum",     [NOUN, MAGICAL], 2],
  ["Menagerie",  [NOUN, MAGICAL], 1],
  ["Lounge",     [NOUN, MAGICAL], 1],
  ["Librarium",  [NOUN, MAGICAL], 1],
  ["Laboratory", [NOUN, MAGICAL], 2],
  ["Workroom",   [NOUN, MAGICAL], 2],
  ["Sphere",     [NOUN, MAGICAL], 1],
  ["Greenhouse", [NOUN, MAGICAL], 1],
  ["Cubicle",    [NOUN, MAGICAL], 1],
  ["Closet",     [NOUN, MAGICAL], 2],
  ["Gallery",    [NOUN, MAGICAL], 2],
  ["Aviary",     [NOUN, MAGICAL], 1],
  ["Atrium",     [NOUN, MAGICAL], 1],
  ["Maze",       [NOUN, MAGICAL], 2],
  ["Beastiary",  [NOUN, MAGICAL], 1],
]
