import { TaggedItem, filterByTag, filterByAllTags } from '../types/types'
import {
  NOUN,
  MOUNTAIN, RIVER, FOREST, SWAMP, CAVE, DUNGEON, TEMPLE, TOMB, TAVERN,
  CITY, TOWER, FORTIFICATION, UNDERGROUND, OCEAN, HILLS, DESERT, CANYON,
  STONE, MINE, BRIDGE, MAGICAL,
  SHELTER, MECHANICAL, SECURITY, ARTIFACT,
  LEVEL, ROOM, NATION, DISTRICT,
} from './tags'
import {
  dungeon_special_rooms,
  temple_special_rooms,
  cavern_special_rooms,
  cavern_water_special_rooms,
  cavern_portal_special_rooms,
  magical_special_rooms,
} from './dungeon_rooms'

// CONSTRUCTION BASE

export const constructions: TaggedItem[] = [
  // Fortification
  ["Castle",      [NOUN, FORTIFICATION], 3],
  ["Citadel",     [NOUN, FORTIFICATION], 2],
  ["Fortress",    [NOUN, FORTIFICATION], 2],
  ["Stronghold",  [NOUN, FORTIFICATION], 2],
  ["Tower",       [NOUN, FORTIFICATION, TOWER], 3],
  ["Trench",      [NOUN, FORTIFICATION], 2],
  ["Outpost",     [NOUN, FORTIFICATION], 2],
  ["Encampment",  [NOUN, FORTIFICATION], 2],
  ["Minefield",   [NOUN, FORTIFICATION], 1],
  ["Keep",        [NOUN, FORTIFICATION], 3],
  ["Gate",        [NOUN, FORTIFICATION], 2],
  ["Wall",        [NOUN, FORTIFICATION], 2],
  ["Barrier",     [NOUN, FORTIFICATION], 2],
  ["Hold",        [NOUN, FORTIFICATION], 2],
  // Religious
  ["Monastary",    [NOUN, TEMPLE], 2],
  ["Temple",       [NOUN, TEMPLE], 3],
  ["Shrine",       [NOUN, TEMPLE], 3],
  ["Sanctuary",    [NOUN, TEMPLE], 2],
  ["Reliquary",    [NOUN, TEMPLE], 1],
  ["Abbey",        [NOUN, TEMPLE], 2],
  ["Cathedral",    [NOUN, TEMPLE], 2],
  ["Prayer Wheel", [NOUN, TEMPLE], 1],
  ["Alter",        [NOUN, TEMPLE], 2],
  ["Ziggarut",     [NOUN, TEMPLE], 1],
  ["Sanctum",      [NOUN, TEMPLE], 2],
  // Funerary
  ["Morgue",      [NOUN, TOMB], 2],
  ["Mortuary",    [NOUN, TOMB], 2],
  ["Mausoleum",   [NOUN, TOMB], 2],
  ["Graveyard",   [NOUN, TOMB], 3],
  ["Crypt",       [NOUN, TOMB], 3],
  ["Tomb",        [NOUN, TOMB], 3],
  ["Mound",       [NOUN, TOMB], 2],
  ["Barrow",      [NOUN, TOMB], 2],
  ["Pyramid",     [NOUN, TOMB], 1],
  ["Catacombs",   [NOUN, TOMB, UNDERGROUND], 2],
  ["Ossuary",     [NOUN, TOMB], 1],
  // Artifact / magical objects
  ["Obelisk",    [NOUN, ARTIFACT, MAGICAL], 2],
  ["Statue",     [NOUN, ARTIFACT], 2],
  ["Tome",       [NOUN, ARTIFACT, MAGICAL], 2],
  ["Monolith",   [NOUN, ARTIFACT], 2],
  ["Guardian",   [NOUN, ARTIFACT], 2],
  ["Forge",      [NOUN, ARTIFACT], 2],
  ["Bubble",     [NOUN, ARTIFACT, MAGICAL], 1],
  ["Cube",       [NOUN, ARTIFACT], 2],
  ["Helix",      [NOUN, ARTIFACT], 2],
  ["Dome",       [NOUN, ARTIFACT], 2],
  ["Vortex",     [NOUN, ARTIFACT, MAGICAL], 1],
  ["Spiral",     [NOUN, ARTIFACT], 2],
  ["Totem",      [NOUN, ARTIFACT], 2],
  ["Apparatus",  [NOUN, ARTIFACT], 2],
  ["Furnace",    [NOUN, ARTIFACT], 2],
  ["Circle",     [NOUN, ARTIFACT, MAGICAL], 2],
  ["Stele",      [NOUN, ARTIFACT], 1],
  ["Tablet",     [NOUN, ARTIFACT], 2],
  ["Visage",     [NOUN, ARTIFACT], 2],
  ["Arch",       [NOUN, ARTIFACT], 2],
  ["Sphere",     [NOUN, ARTIFACT, MAGICAL], 2],
  ["Box",        [NOUN, ARTIFACT], 2],
  ["Puzzle",     [NOUN, ARTIFACT], 2],
  ["Cauldron",   [NOUN, ARTIFACT, MAGICAL], 2],
  ["Fountain",   [NOUN, ARTIFACT], 2],
  ["Grid",       [NOUN, ARTIFACT], 2],
  ["Matrix",     [NOUN, ARTIFACT, MAGICAL], 1],
  ["Orb",        [NOUN, ARTIFACT, MAGICAL], 2],
  ["Shard",      [NOUN, ARTIFACT], 2],
  ["Piller",     [NOUN, ARTIFACT], 2],
  ["Relic",      [NOUN, ARTIFACT], 2],
  ["Anvil",      [NOUN, ARTIFACT], 2],
  ["Throne",     [NOUN, ARTIFACT], 2],
  // Underground
  ["Burrow",      [NOUN, UNDERGROUND, DUNGEON], 2],
  ["Dungeon",     [NOUN, UNDERGROUND, DUNGEON], 3],
  ["Tunnel",      [NOUN, UNDERGROUND, DUNGEON], 2],
  ["Catacombs",   [NOUN, UNDERGROUND, DUNGEON], 2],
  ["Sewer",       [NOUN, UNDERGROUND, DUNGEON], 2],
  ["Mine",        [NOUN, UNDERGROUND, MINE], 3],
  ["Pit",         [NOUN, UNDERGROUND, DUNGEON], 2],
  ["Maze",        [NOUN, UNDERGROUND, DUNGEON], 2],
  ["Excavation",  [NOUN, UNDERGROUND, DUNGEON], 2],
  ["Nest",        [NOUN, UNDERGROUND], 2],
  ["Lair",        [NOUN, UNDERGROUND], 2],
  ["Den",         [NOUN, UNDERGROUND], 2],
  ["Vault",       [NOUN, UNDERGROUND, DUNGEON], 2],
  ["Warren",      [NOUN, UNDERGROUND], 2],
  ["Cellar",      [NOUN, UNDERGROUND], 2],
  // Shelter
  ["Manor",    [NOUN, SHELTER], 2],
  ["Palace",   [NOUN, SHELTER, CITY], 2],
  ["Hall",     [NOUN, SHELTER], 2],
  ["Hive",     [NOUN, SHELTER], 2],
  ["Ruin",     [NOUN, SHELTER], 2],
  ["Library",  [NOUN, SHELTER], 2],
  ["Enclave",  [NOUN, SHELTER], 2],
  // Mechanical
  ["Observatory", [NOUN, MECHANICAL], 2],
  ["Windmill",    [NOUN, MECHANICAL], 2],
  ["Aquaduct",    [NOUN, MECHANICAL], 2],
  ["Lighthouse",  [NOUN, MECHANICAL], 2],
  ["Foundry",     [NOUN, MECHANICAL], 2],
  // Security
  ["Prison",   [NOUN, SECURITY], 2],
  ["Cage",     [NOUN, SECURITY], 2],
  ["Vault",    [NOUN, SECURITY], 2],
  ["Cache",    [NOUN, SECURITY], 2],
  ["Treasury", [NOUN, SECURITY], 2],
  // Misc traversal
  ["Bridge",   [NOUN, BRIDGE], 3],
  ["Stairway", [NOUN], 2],
  ["Road",     [NOUN], 2],
  ["Crossing", [NOUN], 2],
  ["Pass",     [NOUN, MOUNTAIN], 2],
  ["Trail",    [NOUN], 2],
  ["Causeway", [NOUN], 2],
  ["Landing",  [NOUN], 2],
  // Freshwater
  ["Well",    [NOUN, RIVER], 2],
  ["Cistern", [NOUN, RIVER], 2],
  // City
  ["City", [NOUN, CITY], 3],
  // Bridge
  ["Bridge",     [NOUN, BRIDGE], 3],
  ["Drawbridge", [NOUN, BRIDGE], 2],
  // Tower
  ["Tower", [NOUN, TOWER], 3],
  // Tavern
  ["Inn",      [NOUN, TAVERN], 3],
  ["Tavern",   [NOUN, TAVERN], 3],
  ["Alehouse", [NOUN, TAVERN], 2],
  ["Pub",      [NOUN, TAVERN], 2],
  ["Lodge",    [NOUN, TAVERN], 2],
]

export const dungeon: TaggedItem[] = [
  // Dungeon levels (large-scale areas)
  ["Eye",                [NOUN, DUNGEON, UNDERGROUND, LEVEL], 2],
  ["Atrium",             [NOUN, DUNGEON, UNDERGROUND, LEVEL], 2],
  ["Promenade",          [NOUN, DUNGEON, UNDERGROUND, LEVEL], 1],
  ["Core",               [NOUN, DUNGEON, UNDERGROUND, LEVEL], 2],
  ["Balcony",            [NOUN, DUNGEON, UNDERGROUND, LEVEL], 2],
  ["Cauldron",           [NOUN, DUNGEON, UNDERGROUND, LEVEL], 2],
  ["Garden",             [NOUN, DUNGEON, UNDERGROUND, LEVEL], 2],
  ["Pavillion",          [NOUN, DUNGEON, UNDERGROUND, LEVEL], 2],
  ["Arena",              [NOUN, DUNGEON, UNDERGROUND, LEVEL], 2],
  ["Foundry",            [NOUN, DUNGEON, UNDERGROUND, LEVEL], 2],
  ["Grid",               [NOUN, DUNGEON, UNDERGROUND, LEVEL], 2],
  ["Cube",               [NOUN, DUNGEON, UNDERGROUND, LEVEL], 2],
  ["Kitchens",           [NOUN, DUNGEON, UNDERGROUND, LEVEL], 2],
  ["Underground Lake",   [NOUN, DUNGEON, UNDERGROUND, LEVEL], 1],
  ["Underground Forest", [NOUN, DUNGEON, UNDERGROUND, LEVEL], 1],
  ["Underground City",   [NOUN, DUNGEON, UNDERGROUND, LEVEL], 1],
  ["Gallery",            [NOUN, DUNGEON, UNDERGROUND, LEVEL], 2],
  ["Collection",         [NOUN, DUNGEON, UNDERGROUND, LEVEL], 2],
  ["Underground Garden", [NOUN, DUNGEON, UNDERGROUND, LEVEL], 1],
  ["Maze",               [NOUN, DUNGEON, UNDERGROUND, LEVEL], 2],
  ["Labyrinth",          [NOUN, DUNGEON, UNDERGROUND, LEVEL], 2],
  ["Warrens",            [NOUN, DUNGEON, UNDERGROUND, LEVEL], 2],
  ["Barracks",           [NOUN, DUNGEON, UNDERGROUND, LEVEL], 2],
  ["Libraries",          [NOUN, DUNGEON, UNDERGROUND, LEVEL], 2],
  ["Catacombs",          [NOUN, DUNGEON, UNDERGROUND, LEVEL], 2],
  ["Sewers",             [NOUN, DUNGEON, UNDERGROUND, LEVEL], 2],
  ["Chasm",              [NOUN, DUNGEON, UNDERGROUND, LEVEL], 2],
  ["Prisons",            [NOUN, DUNGEON, UNDERGROUND, LEVEL], 2],
  ["Asylum",             [NOUN, DUNGEON, UNDERGROUND, LEVEL], 2],
  ["Mines",              [NOUN, DUNGEON, UNDERGROUND, LEVEL, MINE], 2],
  ["Caverns",            [NOUN, DUNGEON, UNDERGROUND, LEVEL, CAVE], 2],
  ["Tunnels",            [NOUN, DUNGEON, UNDERGROUND, LEVEL], 2],
  ["Laboratories",       [NOUN, DUNGEON, UNDERGROUND, LEVEL], 2],
  ["Museum",             [NOUN, DUNGEON, UNDERGROUND, LEVEL], 2],
  ["Baths",              [NOUN, DUNGEON, UNDERGROUND, LEVEL], 2],
  ["Wreckage",           [NOUN, DUNGEON, UNDERGROUND, LEVEL], 2],
  ["Hideout",            [NOUN, DUNGEON, UNDERGROUND, LEVEL], 2],
  ["Treasury",           [NOUN, DUNGEON, UNDERGROUND, LEVEL], 2],
  ["Vaults",             [NOUN, DUNGEON, UNDERGROUND, LEVEL], 2],
  ["Underground Citadel",[NOUN, DUNGEON, UNDERGROUND, LEVEL], 1],
  ["Cemetery",           [NOUN, DUNGEON, UNDERGROUND, LEVEL, TOMB], 2],
  ["Tombs",              [NOUN, DUNGEON, UNDERGROUND, LEVEL, TOMB], 2],
  ["Crypts",             [NOUN, DUNGEON, UNDERGROUND, LEVEL, TOMB], 2],
  ["Temple",             [NOUN, DUNGEON, UNDERGROUND, LEVEL, TEMPLE], 2],
  ["Ruins",              [NOUN, DUNGEON, UNDERGROUND, LEVEL], 2],
  ["Storerooms",         [NOUN, DUNGEON, UNDERGROUND, LEVEL], 2],
  ["Theater",            [NOUN, DUNGEON, UNDERGROUND, LEVEL], 2],
  ["Markets",            [NOUN, DUNGEON, UNDERGROUND, LEVEL], 2],
  ["Halls",              [NOUN, DUNGEON, UNDERGROUND, LEVEL], 2],
  ["Workshop",           [NOUN, DUNGEON, UNDERGROUND, LEVEL], 2],
  ["Pit",                [NOUN, DUNGEON, UNDERGROUND, LEVEL], 2],
  ["Sanctuary",          [NOUN, DUNGEON, UNDERGROUND, LEVEL], 2],
  ["Garrison",           [NOUN, DUNGEON, UNDERGROUND, LEVEL], 2],
  ["Repository",         [NOUN, DUNGEON, UNDERGROUND, LEVEL], 2],
  ["Grotto",             [NOUN, DUNGEON, UNDERGROUND, LEVEL], 2],
  ["Cavern",             [NOUN, DUNGEON, UNDERGROUND, LEVEL], 2],
  // Dungeon rooms (individual room types)
  ["Room",          [NOUN, DUNGEON, ROOM], 3],
  ["Chamber",       [NOUN, DUNGEON, ROOM], 3],
  ["Antechamber",   [NOUN, DUNGEON, ROOM], 2],
  ["Niche",         [NOUN, DUNGEON, ROOM], 2],
  ["Cell",          [NOUN, DUNGEON, ROOM], 2],
  ["Mine",          [NOUN, DUNGEON, ROOM, MINE], 2],
  ["Vault",         [NOUN, DUNGEON, ROOM], 2],
  ["Gallery",       [NOUN, DUNGEON, ROOM], 2],
  ["Staircase",        [NOUN, DUNGEON, ROOM], 2],
  ["Stairway",         [NOUN, DUNGEON, ROOM], 2],
  ["Ladder",           [NOUN, DUNGEON, ROOM], 2],
  ["Spiral Staircase", [NOUN, DUNGEON, ROOM], 2],
  ["Stairs",           [NOUN, DUNGEON, ROOM], 3],
  ["Escalator",        [NOUN, DUNGEON, ROOM], 1],
  ["Pit",     [NOUN, DUNGEON, ROOM], 2],
  ["Shaft",   [NOUN, DUNGEON, ROOM], 2],
  ["Culvert", [NOUN, DUNGEON, ROOM], 2],
  ["Pipe",    [NOUN, DUNGEON, ROOM], 2],
  ["Tube",    [NOUN, DUNGEON, ROOM], 2],
  ["Corridor",   [NOUN, DUNGEON, ROOM], 3],
  ["Hallway",    [NOUN, DUNGEON, ROOM], 3],
  ["Tunnel",     [NOUN, DUNGEON, ROOM], 2],
  ["Avenue",     [NOUN, DUNGEON, ROOM], 2],
  ["Passage",    [NOUN, DUNGEON, ROOM], 2],
  ["Serviceway", [NOUN, DUNGEON, ROOM], 1],
  ["Crawlway",   [NOUN, DUNGEON, ROOM], 2],
  ["Catwalk",    [NOUN, DUNGEON, ROOM], 2],
  ["Hall",       [NOUN, DUNGEON, ROOM], 2],
  ["Burrow",      [NOUN, DUNGEON, ROOM, UNDERGROUND], 2],
  ["Tunnel",      [NOUN, DUNGEON, ROOM, UNDERGROUND], 2],
  ["Catacombs",   [NOUN, DUNGEON, ROOM, UNDERGROUND], 2],
  ["Sewer",       [NOUN, DUNGEON, ROOM, UNDERGROUND], 2],
  ["Mine",        [NOUN, DUNGEON, ROOM, MINE], 2],
  ["Maze",        [NOUN, DUNGEON, ROOM], 2],
  ["Excavation",  [NOUN, DUNGEON, ROOM], 2],
  ["Nest",        [NOUN, DUNGEON, ROOM], 2],
  ["Lair",        [NOUN, DUNGEON, ROOM], 2],
  ["Den",         [NOUN, DUNGEON, ROOM], 2],
  ["Warren",      [NOUN, DUNGEON, ROOM], 2],
  ["Cellar",      [NOUN, DUNGEON, ROOM], 2],
  ["Labyrinth",   [NOUN, DUNGEON, ROOM], 2],
  ["Mausoleum",  [NOUN, TOMB, DUNGEON, ROOM], 2],
  ["Grave",      [NOUN, TOMB, DUNGEON, ROOM], 2],
  ["Crypt",      [NOUN, TOMB, DUNGEON, ROOM], 3],
  ["Tomb",       [NOUN, TOMB, DUNGEON, ROOM], 3],
  ["Barrow",     [NOUN, TOMB, DUNGEON, ROOM], 2],
  ["Ossuary",    [NOUN, TOMB, DUNGEON, ROOM], 1],
  ["Doorway",  [NOUN, DUNGEON, ROOM], 2],
  ["Door",     [NOUN, DUNGEON, ROOM], 2],
  ["Portal",   [NOUN, DUNGEON, ROOM], 2],
  ["Gate",     [NOUN, DUNGEON, ROOM], 2],
  ["Hatch",    [NOUN, DUNGEON, ROOM], 2],
  ["Archway",  [NOUN, DUNGEON, ROOM], 2],
  ["Curtain",  [NOUN, DUNGEON, ROOM], 2],
  ["Hatchway", [NOUN, DUNGEON, ROOM], 2],
  ["Valves",   [NOUN, DUNGEON, ROOM], 2],
  ["Pillar",   [NOUN, DUNGEON, ROOM], 2],
  ["Throne",   [NOUN, DUNGEON, ROOM], 2],
  ["Elevator", [NOUN, DUNGEON, ROOM], 1],
  // Special rooms (from dungeon_rooms.ts)
  ...dungeon_special_rooms,
]

// POLITICAL

export const political: TaggedItem[] = [
  ["Realm",         [NOUN, CITY, NATION], 2],
  ["Theocracy",     [NOUN, CITY, NATION], 1],
  ["Kingdom",       [NOUN, CITY, NATION], 3],
  ["Empire",        [NOUN, CITY, NATION], 2],
  ["Alliance",      [NOUN, CITY, NATION], 2],
  ["Duchy",         [NOUN, CITY, NATION], 2],
  ["Principality",  [NOUN, CITY, NATION], 1],
  ["Guild",         [NOUN, CITY, NATION], 2],
  ["Marches",       [NOUN, CITY, NATION], 2],
  ["Grand Duchy",   [NOUN, CITY, NATION], 1],
  ["Collective",    [NOUN, CITY, NATION], 2],
  ["Confederacy",   [NOUN, CITY, NATION], 2],
  ["Baronry",       [NOUN, CITY, NATION], 2],
  ["Colony",        [NOUN, CITY, NATION], 2],
  ["Federation",    [NOUN, CITY, NATION], 2],
  ["County",        [NOUN, CITY, NATION], 2],
  ["Dominion",      [NOUN, CITY, NATION], 2],
  ["Territory",     [NOUN, CITY, NATION], 2],
  ["Watch",         [NOUN, CITY, NATION], 2],
  ["Hold",          [NOUN, CITY, NATION], 2],
  ["Province",      [NOUN, CITY, NATION], 2],
  ["Union",         [NOUN, CITY, NATION], 2],
  ["League",        [NOUN, CITY, NATION], 2],
  ["Ward",     [NOUN, CITY, DISTRICT], 2],
  ["Quarter",  [NOUN, CITY, DISTRICT], 2],
  ["District", [NOUN, CITY, DISTRICT], 2],
  ["Market",   [NOUN, CITY, DISTRICT], 2],
]

export const tomb_room: TaggedItem[] = filterByAllTags([TOMB, ROOM], dungeon)

export const temple_room: TaggedItem[] = [
  ...filterByTag(ROOM, dungeon),
  ...temple_special_rooms,
]

export const cavern_room: TaggedItem[] = [
  ...cavern_special_rooms,
  ...cavern_water_special_rooms,
  ...cavern_portal_special_rooms,
]

export const magical_room: TaggedItem[] = [
  ...dungeon.filter(([_, tags]) => tags.includes(ROOM) && !tags.includes(TOMB)),
  ...magical_special_rooms,
]

// NATURAL BASE

export const naturals: TaggedItem[] = [
  // Woodlands
  ["Glade",   [NOUN, FOREST], 2],
  ["Grove",   [NOUN, FOREST], 2],
  ["Meadow",  [NOUN, FOREST], 2],
  ["Thicket", [NOUN, FOREST], 2],
  ["Briar",   [NOUN, FOREST], 2],
  ["Woods",   [NOUN, FOREST], 3],
  ["Forest",  [NOUN, FOREST], 3],
  ["Garden",  [NOUN, FOREST], 2],
  ["Tree",    [NOUN, FOREST], 2],
  // Marshes
  ["Swamp",    [NOUN, SWAMP], 3],
  ["Jungle",   [NOUN, SWAMP, FOREST], 2],
  ["Bog",      [NOUN, SWAMP], 3],
  ["Marsh",    [NOUN, SWAMP], 3],
  ["Quagmire", [NOUN, SWAMP], 2],
  ["Mire",     [NOUN, SWAMP], 2],
  ["Fen",      [NOUN, SWAMP], 2],
  ["Rot",      [NOUN, SWAMP], 2],
  // Underground / cave
  ["Grotto",   [NOUN, CAVE, UNDERGROUND], 2],
  ["Sinkhole", [NOUN, CAVE, UNDERGROUND], 2],
  ["Cavern",   [NOUN, CAVE, UNDERGROUND], 3],
  ["Cave",     [NOUN, CAVE, UNDERGROUND], 3],
  ["Hole",     [NOUN, CAVE, UNDERGROUND], 2],
  // Depression / canyon
  ["Chasm",   [NOUN, CANYON], 2],
  ["Fault",   [NOUN, CANYON], 2],
  ["Ravine",  [NOUN, CANYON], 2],
  ["Rift",    [NOUN, CANYON], 2],
  ["Gully",   [NOUN, CANYON], 2],
  ["Gorge",   [NOUN, CANYON], 2],
  ["Canyon",  [NOUN, CANYON], 3],
  ["Fissure", [NOUN, CANYON], 2],
  ["Crater",  [NOUN, CANYON], 2],
  ["Cliff",   [NOUN, CANYON], 2],
  ["Valley",  [NOUN, CANYON], 3],
  // Freshwater
  ["River",  [NOUN, RIVER], 3],
  ["Spring", [NOUN, RIVER], 2],
  ["Falls",  [NOUN, RIVER], 2],
  ["Creek",  [NOUN, RIVER], 2],
  ["Stream", [NOUN, RIVER], 2],
  ["Geyser", [NOUN, RIVER], 1],
  ["Pool",   [NOUN, RIVER], 2],
  ["Lake",   [NOUN, RIVER], 3],
  ["Pond",   [NOUN, RIVER], 2],
  ["Puddle", [NOUN, RIVER], 2],
  ["Basin",  [NOUN, RIVER], 2],
  ["Kettle", [NOUN, RIVER], 2],
  // Highlands
  ["Mesa",      [NOUN, MOUNTAIN], 2],
  ["Spire",     [NOUN, MOUNTAIN], 2],
  ["Summit",    [NOUN, MOUNTAIN], 2],
  ["Plateau",   [NOUN, MOUNTAIN], 2],
  ["Peak",      [NOUN, MOUNTAIN], 3],
  ["Pinnacle",  [NOUN, MOUNTAIN], 2],
  ["Mountains", [NOUN, MOUNTAIN], 3],
  // Stone
  ["Rock",     [NOUN, STONE], 2],
  ["Stone",    [NOUN, STONE], 2],
  ["Monolith", [NOUN, STONE], 2],
  // Saltwater
  ["Sea",       [NOUN, OCEAN], 3],
  ["Reef",      [NOUN, OCEAN], 2],
  ["Bay",       [NOUN, OCEAN], 2],
  ["Ocean",     [NOUN, OCEAN], 3],
  ["Whirlpool", [NOUN, OCEAN], 1],
  // Hills
  ["Hills", [NOUN, HILLS], 3],
  // Desert
  ["Desert", [NOUN, DESERT], 3],
  ["Dunes",  [NOUN, DESERT], 2],
  // Misc
  ["Barrens",  [NOUN], 2],
  ["Wastes",   [NOUN], 2],
  ["Island",   [NOUN], 2],
  ["Tundra",   [NOUN], 2],
  ["Moor",     [NOUN], 2],
  ["Plains",   [NOUN], 2],
  ["Volcano",  [NOUN, MOUNTAIN], 1],
  ["Glacier",  [NOUN, MOUNTAIN], 2],
  ["Blight",   [NOUN], 2],
]

export const base: TaggedItem[] = [
  ...constructions,
  ...naturals,
]

// Re-export combined aliases for backward compat with typeConfig
export const construction = constructions
export const natural = naturals
