import { TaggedItem } from '../types/types'
import { filterByTag } from '../types/types'
import {
  NOUN, ADJECTIVE, PREFIX, SUFFIX, POSSESSIVE, MAGICAL,
  EVIL, GOOD, MUNDANE,
  MOUNTAIN, FORTIFICATION, RIVER, FOREST, TOWN, TAVERN,
  PERSON, RULER, WARRIOR, RELIGIOUS, MAGICAL_PERSON,
  ENTERTAINER, WORKER,
} from './tags'

// PERSONS (possessives)

export const persons: TaggedItem[] = [
  // Magical
  ["Wizard",     [POSSESSIVE, MAGICAL_PERSON], 3],
  ["Sorceror",   [POSSESSIVE, MAGICAL_PERSON], 2],
  ["Apprentice", [POSSESSIVE, MAGICAL_PERSON], 2],
  ["Alchemist",  [POSSESSIVE, MAGICAL_PERSON], 2],
  ["Advisor",    [POSSESSIVE, MAGICAL_PERSON], 1],
  // Religious
  ["Druid",    [POSSESSIVE, RELIGIOUS], 2],
  ["Martyr",   [POSSESSIVE, RELIGIOUS], 2],
  ["Monk",     [POSSESSIVE, RELIGIOUS], 3],
  ["Templar",  [POSSESSIVE, RELIGIOUS], 2],
  ["Shamen",   [POSSESSIVE, RELIGIOUS], 2],
  ["Scribe",   [POSSESSIVE, RELIGIOUS], 2],
  ["Priest",   [POSSESSIVE, RELIGIOUS], 3],
  ["Adept",    [POSSESSIVE, RELIGIOUS], 2],
  ["Acolyte",  [POSSESSIVE, RELIGIOUS], 2],
  ["Scrivner", [POSSESSIVE, RELIGIOUS], 1],
  // Warrior
  ["Archer",   [POSSESSIVE, WARRIOR], 2],
  ["Guardian", [POSSESSIVE, WARRIOR], 2],
  ["Rogue",    [POSSESSIVE, WARRIOR], 2],
  // Worker
  ["Cook",     [POSSESSIVE, PERSON, WORKER], 2],
  ["Servant",  [POSSESSIVE, PERSON, WORKER], 2],
  ["Maid",     [POSSESSIVE, PERSON, WORKER], 2],
  ["Fletcher", [POSSESSIVE, PERSON, WORKER], 2],
  // Entertainer
  ["Minstrel", [POSSESSIVE, PERSON, ENTERTAINER], 2],
  ["Jester",   [POSSESSIVE, PERSON, ENTERTAINER], 2],
  // Ruler
  ["King",  [POSSESSIVE, RULER], 3],
  ["Queen", [POSSESSIVE, RULER], 3],
  ["Lord",  [POSSESSIVE, RULER], 3],
  ["Duke",  [POSSESSIVE, RULER], 2],
  // Misc
  ["Fidget",        [POSSESSIVE, PERSON], 2],
  ["Maggot",        [POSSESSIVE, PERSON], 2],
  ["Dead Man",      [POSSESSIVE, PERSON], 2],
  ["Hermit",        [POSSESSIVE, PERSON], 2],
  ["Fool",          [POSSESSIVE, PERSON], 2],
  ["Special Guest", [POSSESSIVE, PERSON], 1],
  ["Guest",         [POSSESSIVE, PERSON], 2],
]

export const possessive: TaggedItem[] = [...persons]

export const possessive_suffix: TaggedItem[] = [
  ["Crossing", [NOUN], 2],
  ["Gaunlet",  [NOUN], 2],
  ["Watch",    [NOUN], 2],
  ["Sorrow",   [NOUN], 2],
  ["Folly",    [NOUN], 2],
  ["Run",      [NOUN], 2],
]

export const relative: TaggedItem[] = [
  ["Greater",  [ADJECTIVE], 2],
  ["Lesser",   [ADJECTIVE], 2],
  ["Inner",    [ADJECTIVE], 2],
  ["Outer",    [ADJECTIVE], 2],
  ["Upper",    [ADJECTIVE], 2],
  ["Lower",    [ADJECTIVE], 2],
  ["Eastern",  [ADJECTIVE], 2],
  ["Western",  [ADJECTIVE], 2],
  ["Northern", [ADJECTIVE], 2],
  ["Southern", [ADJECTIVE], 2],
  ["Old",      [ADJECTIVE], 3],
  ["Elder",    [ADJECTIVE], 2],
  ["Far",      [ADJECTIVE], 2],
  ["Deep",     [ADJECTIVE], 2],
  ["High",     [ADJECTIVE], 2],
]

export const the: TaggedItem[] = [
  ["The", [ADJECTIVE], 1],
]

export const optional_adjective: TaggedItem[] = [
  ...relative,
  ...the,
]

// PREFIX / SUFFIX

export const prefixes: TaggedItem[] = [
  // Objects (inline from objects export below — share same items)
  ["Eye",      [NOUN], 2],
  ["Hand",     [NOUN], 2],
  ["Talon",    [NOUN], 2],
  ["Fang",     [NOUN], 2],
  ["Skull",    [NOUN], 2],
  ["Mind",     [NOUN], 2],
  ["Corpse",   [NOUN], 2],
  ["Glacier",  [NOUN], 2],
  ["Moon",     [NOUN, MAGICAL], 2],
  ["Sun",      [NOUN, MAGICAL], 2],
  ["Star",     [NOUN, MAGICAL], 2],
  ["Venom",    [NOUN], 2],
  ["Rune",     [NOUN, MAGICAL], 2],
  ["Shroud",   [NOUN], 2],
  ["Cloak",    [NOUN], 2],
  ["Glyph",    [NOUN, MAGICAL], 2],
  ["Sword",    [NOUN], 2],
  ["Thorn",    [NOUN], 2],
  ["Flame",    [NOUN], 2],
  ["Shadow",   [NOUN], 2],
  ["Fire",     [NOUN], 2],
  ["Lantern",  [NOUN], 2],
  ["Slime",    [NOUN], 2],
  ["Leaf",     [NOUN], 2],
  ["Chord",    [NOUN], 2],
  ["Chain",    [NOUN], 2],
  ["Talisman", [NOUN, MAGICAL], 2],
  ["Pentacle", [NOUN, MAGICAL], 2],
  ["Orb",      [NOUN, MAGICAL], 2],
  ["Sphere",   [NOUN, MAGICAL], 2],
  ["Egg",      [NOUN], 2],
  ["Candle",   [NOUN], 2],
  ["Lens",     [NOUN], 2],
  ["Shield",   [NOUN], 2],
  ["Jar",      [NOUN], 2],
  ["Urn",      [NOUN], 2],
  ["Spike",    [NOUN], 2],
  ["Gem",      [NOUN], 2],
  ["Rose",     [NOUN], 2],
  ["Junk",     [NOUN], 2],
  ["Void",     [NOUN, MAGICAL], 2],
  ["Glaive",   [NOUN], 1],
  // Good
  ["Soul",    [PREFIX, GOOD], 2],
  ["Star",    [PREFIX, GOOD], 2],
  ["Spell",   [PREFIX, GOOD], 2],
  ["Heart",   [PREFIX, GOOD], 2],
  ["Stone",   [PREFIX, GOOD], 2],
  ["Shard",   [PREFIX, GOOD], 2],
  ["Feather", [PREFIX, GOOD], 2],
  ["Far",     [PREFIX, GOOD], 2],
  ["Moon",    [PREFIX, GOOD], 2],
  ["Elder",   [PREFIX, GOOD], 2],
  ["Old",     [PREFIX, GOOD], 2],
  ["Storm",   [PREFIX, GOOD], 2],
  ["Rune",    [PREFIX, GOOD], 2],
  ["Dagger",  [PREFIX, GOOD], 2],
  ["Sigil",   [PREFIX, GOOD], 2],
  ["Mist",    [PREFIX, GOOD], 2],
  ["Wind",    [PREFIX, GOOD], 2],
  ["Moss",    [PREFIX, GOOD], 2],
  ["Well",    [PREFIX, GOOD], 2],
  ["Ever",    [PREFIX, GOOD], 2],
  ["Ember",   [PREFIX, GOOD], 2],
  // Evil
  ["Ash",     [PREFIX, EVIL], 2],
  ["Ashen",   [PREFIX, EVIL], 3],
  ["Bane",    [PREFIX, EVIL], 3],
  ["Bitter",  [PREFIX, EVIL], 2],
  ["Blight",  [PREFIX, EVIL], 3],
  ["Blood",   [PREFIX, EVIL], 2],
  ["Bone",    [PREFIX, EVIL], 2],
  ["Carrion", [PREFIX, EVIL], 1],
  ["Dark",    [PREFIX, EVIL], 3],
  ["Dead",    [PREFIX, EVIL], 2],
  ["Demon",   [PREFIX, EVIL], 2],
  ["Dire",    [PREFIX, EVIL], 2],
  ["Dirt",    [PREFIX, EVIL], 2],
  ["Doom",    [PREFIX, EVIL], 2],
  ["Dread",   [PREFIX, EVIL], 2],
  ["Fang",    [PREFIX, EVIL], 2],
  ["Fell",    [PREFIX, EVIL], 2],
  ["Fire",    [PREFIX, EVIL], 2],
  ["Frost",   [PREFIX, EVIL], 2],
  ["Gallow",  [PREFIX, EVIL], 1],
  ["Ghoul",   [PREFIX, EVIL], 2],
  ["Gloom",   [PREFIX, EVIL], 2],
  ["Gore",    [PREFIX, EVIL], 2],
  ["Grim",    [PREFIX, EVIL], 3],
  ["Guant",   [PREFIX, EVIL], 2],
  ["Hack",    [PREFIX, EVIL], 2],
  ["Havoc",   [PREFIX, EVIL], 2],
  ["Imp",     [PREFIX, EVIL], 2],
  ["Marrow",  [PREFIX, EVIL], 2],
  ["Mire",    [PREFIX, EVIL], 2],
  ["Murk",    [PREFIX, EVIL], 2],
  ["Plague",  [PREFIX, EVIL], 2],
  ["Raven",   [PREFIX, EVIL], 2],
  ["Riven",   [PREFIX, EVIL], 2],
  ["Rot",     [PREFIX, EVIL], 2],
  ["Sever",   [PREFIX, EVIL], 2],
  ["Shadow",  [PREFIX, EVIL], 3],
  ["Shiver",  [PREFIX, EVIL], 2],
  ["Spawn",   [PREFIX, EVIL], 2],
  ["Thorn",   [PREFIX, EVIL], 2],
  ["Torn",    [PREFIX, EVIL], 2],
  ["Winter",  [PREFIX, EVIL], 2],
  ["Woe",     [PREFIX, EVIL], 2],
  ["Wraith",  [PREFIX, EVIL], 3],
  ["Wyrm",    [PREFIX, EVIL], 2],
  ["Swarm",   [PREFIX, EVIL], 2],
  ["Witch",   [PREFIX, EVIL], 2],
  // Mundane
  ["Stump",   [PREFIX, MUNDANE], 2],
  ["Cricket", [PREFIX, MUNDANE], 2],
  ["Mouse",   [PREFIX, MUNDANE], 2],
  ["Thistle", [PREFIX, MUNDANE], 2],
  ["Cobble",  [PREFIX, MUNDANE], 2],
  ["Thatch",  [PREFIX, MUNDANE], 2],
  ["Puddle",  [PREFIX, MUNDANE], 2],
  ["Gnat",    [PREFIX, MUNDANE], 2],
  ["Moth",    [PREFIX, MUNDANE], 2],
  ["Owl",     [PREFIX, MUNDANE], 2],
  ["Grog",    [PREFIX, MUNDANE], 2],
  ["Farm",    [PREFIX, MUNDANE], 2],
  // Terrain
  ["Mount",  [PREFIX, MOUNTAIN], 3],
  ["Fort",   [PREFIX, FORTIFICATION], 3],
  ["Castle", [PREFIX, FORTIFICATION], 3],
]

export const suffixes: TaggedItem[] = [
  // Objects
  ["Eye",      [NOUN], 2],
  ["Hand",     [NOUN], 2],
  ["Talon",    [NOUN], 2],
  ["Fang",     [NOUN], 2],
  ["Skull",    [NOUN], 2],
  ["Mind",     [NOUN], 2],
  ["Corpse",   [NOUN], 2],
  ["Glacier",  [NOUN], 2],
  ["Moon",     [NOUN, MAGICAL], 2],
  ["Sun",      [NOUN, MAGICAL], 2],
  ["Star",     [NOUN, MAGICAL], 2],
  ["Venom",    [NOUN], 2],
  ["Rune",     [NOUN, MAGICAL], 2],
  ["Shroud",   [NOUN], 2],
  ["Cloak",    [NOUN], 2],
  ["Glyph",    [NOUN, MAGICAL], 2],
  ["Sword",    [NOUN], 2],
  ["Thorn",    [NOUN], 2],
  ["Flame",    [NOUN], 2],
  ["Shadow",   [NOUN], 2],
  ["Fire",     [NOUN], 2],
  ["Lantern",  [NOUN], 2],
  ["Slime",    [NOUN], 2],
  ["Leaf",     [NOUN], 2],
  ["Chord",    [NOUN], 2],
  ["Chain",    [NOUN], 2],
  ["Talisman", [NOUN, MAGICAL], 2],
  ["Pentacle", [NOUN, MAGICAL], 2],
  ["Orb",      [NOUN, MAGICAL], 2],
  ["Sphere",   [NOUN, MAGICAL], 2],
  ["Egg",      [NOUN], 2],
  ["Candle",   [NOUN], 2],
  ["Lens",     [NOUN], 2],
  ["Shield",   [NOUN], 2],
  ["Jar",      [NOUN], 2],
  ["Urn",      [NOUN], 2],
  ["Spike",    [NOUN], 2],
  ["Gem",      [NOUN], 2],
  ["Rose",     [NOUN], 2],
  ["Junk",     [NOUN], 2],
  ["Void",     [NOUN, MAGICAL], 2],
  ["Glaive",   [NOUN], 1],
  // Good prefix/suffix
  ["Soul",    [PREFIX, GOOD], 2],
  ["Star",    [PREFIX, GOOD], 2],
  ["Spell",   [PREFIX, GOOD], 2],
  ["Heart",   [PREFIX, GOOD], 2],
  ["Stone",   [PREFIX, GOOD], 2],
  ["Shard",   [PREFIX, GOOD], 2],
  ["Feather", [PREFIX, GOOD], 2],
  ["Far",     [PREFIX, GOOD], 2],
  ["Moon",    [PREFIX, GOOD], 2],
  ["Elder",   [PREFIX, GOOD], 2],
  ["Old",     [PREFIX, GOOD], 2],
  ["Storm",   [PREFIX, GOOD], 2],
  ["Rune",    [PREFIX, GOOD], 2],
  ["Dagger",  [PREFIX, GOOD], 2],
  ["Sigil",   [PREFIX, GOOD], 2],
  ["Mist",    [PREFIX, GOOD], 2],
  ["Wind",    [PREFIX, GOOD], 2],
  ["Moss",    [PREFIX, GOOD], 2],
  ["Well",    [PREFIX, GOOD], 2],
  ["Ever",    [PREFIX, GOOD], 2],
  ["Ember",   [PREFIX, GOOD], 2],
  ["Hand",   [SUFFIX, GOOD], 2],
  ["Shield", [SUFFIX, GOOD], 2],
  ["Song",   [SUFFIX, GOOD], 2],
  ["Spire",  [SUFFIX, GOOD], 2],
  ["Edge",   [SUFFIX, GOOD], 2],
  ["Warden", [SUFFIX, GOOD], 2],
  ["Stone",  [SUFFIX, GOOD], 2],
  ["Root",   [SUFFIX, GOOD], 2],
  ["Guard",  [SUFFIX, GOOD], 2],
  ["Water",  [SUFFIX, GOOD], 2],
  ["Ever",   [SUFFIX, GOOD], 2],
  ["Wind",   [SUFFIX, GOOD], 2],
  ["Forge",  [SUFFIX, GOOD], 2],
  ["Watch",  [SUFFIX, GOOD], 2],
  ["Hold",   [SUFFIX, GOOD], 2],
  // Evil prefix/suffix
  ["Ash",     [PREFIX, EVIL], 2],
  ["Ashen",   [PREFIX, EVIL], 3],
  ["Bane",    [PREFIX, EVIL], 3],
  ["Bitter",  [PREFIX, EVIL], 2],
  ["Blight",  [PREFIX, EVIL], 3],
  ["Blood",   [PREFIX, EVIL], 2],
  ["Bone",    [PREFIX, EVIL], 2],
  ["Carrion", [PREFIX, EVIL], 1],
  ["Dark",    [PREFIX, EVIL], 3],
  ["Dead",    [PREFIX, EVIL], 2],
  ["Demon",   [PREFIX, EVIL], 2],
  ["Dire",    [PREFIX, EVIL], 2],
  ["Dirt",    [PREFIX, EVIL], 2],
  ["Doom",    [PREFIX, EVIL], 2],
  ["Dread",   [PREFIX, EVIL], 2],
  ["Fang",    [PREFIX, EVIL], 2],
  ["Fell",    [PREFIX, EVIL], 2],
  ["Fire",    [PREFIX, EVIL], 2],
  ["Frost",   [PREFIX, EVIL], 2],
  ["Gallow",  [PREFIX, EVIL], 1],
  ["Ghoul",   [PREFIX, EVIL], 2],
  ["Gloom",   [PREFIX, EVIL], 2],
  ["Gore",    [PREFIX, EVIL], 2],
  ["Grim",    [PREFIX, EVIL], 3],
  ["Guant",   [PREFIX, EVIL], 2],
  ["Hack",    [PREFIX, EVIL], 2],
  ["Havoc",   [PREFIX, EVIL], 2],
  ["Imp",     [PREFIX, EVIL], 2],
  ["Marrow",  [PREFIX, EVIL], 2],
  ["Mire",    [PREFIX, EVIL], 2],
  ["Murk",    [PREFIX, EVIL], 2],
  ["Plague",  [PREFIX, EVIL], 2],
  ["Raven",   [PREFIX, EVIL], 2],
  ["Riven",   [PREFIX, EVIL], 2],
  ["Rot",     [PREFIX, EVIL], 2],
  ["Sever",   [PREFIX, EVIL], 2],
  ["Shadow",  [PREFIX, EVIL], 3],
  ["Shiver",  [PREFIX, EVIL], 2],
  ["Spawn",   [PREFIX, EVIL], 2],
  ["Thorn",   [PREFIX, EVIL], 2],
  ["Torn",    [PREFIX, EVIL], 2],
  ["Winter",  [PREFIX, EVIL], 2],
  ["Woe",     [PREFIX, EVIL], 2],
  ["Wraith",  [PREFIX, EVIL], 3],
  ["Wyrm",    [PREFIX, EVIL], 2],
  ["Swarm",   [PREFIX, EVIL], 2],
  ["Witch",   [PREFIX, EVIL], 2],
  ["Finger", [SUFFIX, EVIL], 2],
  ["Fist",   [SUFFIX, EVIL], 2],
  ["Talon",  [SUFFIX, EVIL], 2],
  ["Spawn",  [SUFFIX, EVIL], 2],
  ["Dark",   [SUFFIX, EVIL], 2],
  // Mundane prefix
  ["Stump",   [PREFIX, MUNDANE], 2],
  ["Cricket", [PREFIX, MUNDANE], 2],
  ["Mouse",   [PREFIX, MUNDANE], 2],
  ["Thistle", [PREFIX, MUNDANE], 2],
  ["Cobble",  [PREFIX, MUNDANE], 2],
  ["Thatch",  [PREFIX, MUNDANE], 2],
  ["Puddle",  [PREFIX, MUNDANE], 2],
  ["Gnat",    [PREFIX, MUNDANE], 2],
  ["Moth",    [PREFIX, MUNDANE], 2],
  ["Owl",     [PREFIX, MUNDANE], 2],
  ["Grog",    [PREFIX, MUNDANE], 2],
  ["Farm",    [PREFIX, MUNDANE], 2],
  // Terrain suffixes
  ["flow",   [SUFFIX, RIVER], 2],
  ["water",  [SUFFIX, RIVER], 2],
  ["tears",  [SUFFIX, RIVER], 2],
  ["blood",  [SUFFIX, RIVER], 2],
  ["wine",   [SUFFIX, RIVER], 2],
  ["mere",   [SUFFIX, RIVER], 2],
  ["ford",   [SUFFIX, RIVER], 2],
  ["falls",  [SUFFIX, RIVER], 2],
  ["meade",  [SUFFIX, RIVER], 2],
  ["grog",   [SUFFIX, RIVER], 2],
  ["spring", [SUFFIX, RIVER], 2],
  ["tide",   [SUFFIX, RIVER], 2],
  ["wash",   [SUFFIX, RIVER], 2],
  ["wood",   [SUFFIX, FOREST], 2],
  ["leaf",   [SUFFIX, FOREST], 2],
  ["root",   [SUFFIX, FOREST], 2],
  ["tree",   [SUFFIX, FOREST], 2],
  ["thorn",  [SUFFIX, FOREST], 2],
  ["willow", [SUFFIX, FOREST], 2],
  ["oak",    [SUFFIX, FOREST], 2],
  ["wort",   [SUFFIX, FOREST], 2],
  ["weed",   [SUFFIX, FOREST], 2],
  ["cedar",  [SUFFIX, FOREST], 2],
  ["bark",   [SUFFIX, FOREST], 2],
  ["wall",  [SUFFIX, MOUNTAIN], 2],
  ["stone", [SUFFIX, MOUNTAIN], 2],
  ["horn",  [SUFFIX, MOUNTAIN], 2],
  ["spur",  [SUFFIX, MOUNTAIN], 2],
  ["rock",  [SUFFIX, MOUNTAIN], 2],
  ["tooth", [SUFFIX, MOUNTAIN], 2],
  ["spine", [SUFFIX, MOUNTAIN], 2],
  ["teeth", [SUFFIX, MOUNTAIN], 2],
  ["talon", [SUFFIX, MOUNTAIN], 2],
  ["cap",   [SUFFIX, MOUNTAIN], 2],
  ["top",   [SUFFIX, MOUNTAIN], 2],
]

// ABSTRACTIONS

export const abstraction: TaggedItem[] = [
  ["Blight",         [NOUN], 2],
  ["Hate",           [NOUN], 2],
  ["Malice",         [NOUN], 2],
  ["Ire",            [NOUN], 2],
  ["Carnage",        [NOUN], 2],
  ["Envy",           [NOUN], 2],
  ["Truth",          [NOUN], 2],
  ["Knowledge",      [NOUN], 2],
  ["Discord",        [NOUN], 2],
  ["Dread",          [NOUN], 2],
  ["Lies",           [NOUN], 2],
  ["Weakness",       [NOUN], 2],
  ["Woe",            [NOUN], 2],
  ["Gore",           [NOUN], 2],
  ["Greed",          [NOUN], 2],
  ["Stench",         [NOUN], 2],
  ["Healing",        [NOUN], 2],
  ["Strength",       [NOUN], 2],
  ["Wisdom",         [NOUN], 2],
  ["Might",          [NOUN], 2],
  ["Remedy",         [NOUN], 2],
  ["Memory",         [NOUN], 2],
  ["Mana",           [NOUN], 2],
  ["Life",           [NOUN], 2],
  ["Lore",           [NOUN], 2],
  ["Regeneration",   [NOUN], 1],
  ["Summoning",      [NOUN], 2],
  ["Mercy",          [NOUN], 2],
  ["Perception",     [NOUN], 2],
  ["Vision",         [NOUN], 2],
  ["Protection",     [NOUN], 2],
  ["Balance",        [NOUN], 2],
  ["Storms",         [NOUN], 2],
  ["Tears",          [NOUN], 2],
  ["Steam",          [NOUN], 2],
  ["Gravity",        [NOUN], 1],
  ["Silence",        [NOUN], 2],
  ["Whisper",        [NOUN], 2],
  ["Sleep",          [NOUN], 2],
  ["Disruption",     [NOUN], 2],
  ["Magnetism",      [NOUN], 1],
  ["Eclipse",        [NOUN], 2],
  ["Zenith",         [NOUN], 1],
  ["Distortion",     [NOUN], 1],
  ["Eternal Return", [NOUN], 1],
  ["Merriment",      [NOUN], 2],
  ["Echo",           [NOUN], 2],
  ["Fatique",        [NOUN], 2],
]

// OBJECTS

export const objects: TaggedItem[] = [
  ["Eye",      [NOUN], 2],
  ["Hand",     [NOUN], 2],
  ["Talon",    [NOUN], 2],
  ["Fang",     [NOUN], 2],
  ["Skull",    [NOUN], 2],
  ["Mind",     [NOUN], 2],
  ["Corpse",   [NOUN], 2],
  ["Glacier",  [NOUN], 2],
  ["Moon",     [NOUN, MAGICAL], 2],
  ["Sun",      [NOUN, MAGICAL], 2],
  ["Star",     [NOUN, MAGICAL], 2],
  ["Venom",    [NOUN], 2],
  ["Rune",     [NOUN, MAGICAL], 2],
  ["Shroud",   [NOUN], 2],
  ["Cloak",    [NOUN], 2],
  ["Glyph",    [NOUN, MAGICAL], 2],
  ["Sword",    [NOUN], 2],
  ["Thorn",    [NOUN], 2],
  ["Flame",    [NOUN], 2],
  ["Shadow",   [NOUN], 2],
  ["Fire",     [NOUN], 2],
  ["Lantern",  [NOUN], 2],
  ["Slime",    [NOUN], 2],
  ["Leaf",     [NOUN], 2],
  ["Chord",    [NOUN], 2],
  ["Chain",    [NOUN], 2],
  ["Talisman", [NOUN, MAGICAL], 2],
  ["Pentacle", [NOUN, MAGICAL], 2],
  ["Orb",      [NOUN, MAGICAL], 2],
  ["Sphere",   [NOUN, MAGICAL], 2],
  ["Egg",      [NOUN], 2],
  ["Candle",   [NOUN], 2],
  ["Lens",     [NOUN], 2],
  ["Shield",   [NOUN], 2],
  ["Jar",      [NOUN], 2],
  ["Urn",      [NOUN], 2],
  ["Spike",    [NOUN], 2],
  ["Gem",      [NOUN], 2],
  ["Rose",     [NOUN], 2],
  ["Junk",     [NOUN], 2],
  ["Void",     [NOUN, MAGICAL], 2],
  ["Glaive",   [NOUN], 1],
]

export const tavern_objects: TaggedItem[] = [
  ...persons,
  ...objects,
]

// PREPOSITIONAL

export const prepositional_singular: TaggedItem[] = [
  ...abstraction,
]

export const prepositional_plural: TaggedItem[] = [
  ...objects,
]

export const tomb_prepositional: TaggedItem[] = [
  ...abstraction,
]

export const temple_prepositional: TaggedItem[] = [
  ...filterByTag(RELIGIOUS, persons),
  ...abstraction,
]

export const cavern_prepositional: TaggedItem[] = [
  ...abstraction,
]

export const dungeon_prepositional: TaggedItem[] = [
  ...persons,
  ...abstraction,
]

export const magical_prepositional: TaggedItem[] = [
  ...filterByTag(MAGICAL_PERSON, persons),
  ...abstraction,
]

export const suffix_town: TaggedItem[] = [
  // Town-specific suffixes
  ["well",    [SUFFIX, TOWN], 2],
  ["wall",    [SUFFIX, TOWN], 2],
  ["wich",    [SUFFIX, TOWN], 2],
  ["wold",    [SUFFIX, TOWN], 1],
  ["wald",    [SUFFIX, TOWN], 1],
  ["ton",     [SUFFIX, TOWN], 3],
  ["town",    [SUFFIX, TOWN], 3],
  ["glen",    [SUFFIX, TOWN], 2],
  ["heim",    [SUFFIX, TOWN], 2],
  ["wort",    [SUFFIX, TOWN], 1],
  ["ward",    [SUFFIX, TOWN], 2],
  ["ham",     [SUFFIX, TOWN], 2],
  ["berg",    [SUFFIX, TOWN], 2],
  ["gard",    [SUFFIX, TOWN], 1],
  ["watch",   [SUFFIX, TOWN], 2],
  ["port",    [SUFFIX, TOWN], 2],
  ["gate",    [SUFFIX, TOWN], 2],
  ["brair",   [SUFFIX, TOWN], 1],
  ["home",    [SUFFIX, TOWN], 2],
  ["holm",    [SUFFIX, TOWN], 2],
  ["haven",   [SUFFIX, TOWN], 2],
  ["shire",   [SUFFIX, TOWN], 2],
  ["keep",    [SUFFIX, TOWN], 2],
  ["stone",   [SUFFIX, TOWN], 2],
  ["heart",   [SUFFIX, TOWN], 2],
  ["hall",    [SUFFIX, TOWN], 2],
  ["bury",    [SUFFIX, TOWN], 2],
  ["falls",   [SUFFIX, TOWN], 2],
  ["ford",    [SUFFIX, TOWN], 2],
  ["helm",    [SUFFIX, TOWN], 2],
  ["mere",    [SUFFIX, TOWN], 2],
  ["mill",    [SUFFIX, TOWN], 2],
  ["hollow",  [SUFFIX, TOWN], 2],
  ["burrow",  [SUFFIX, TOWN], 2],
  ["barrow",  [SUFFIX, TOWN], 2],
  ["cliff",   [SUFFIX, TOWN], 2],
  ["guard",   [SUFFIX, TOWN], 2],
  ["water",   [SUFFIX, TOWN], 2],
  ["bluff",   [SUFFIX, TOWN], 2],
  ["dorf",    [SUFFIX, TOWN], 2],
  ["field",   [SUFFIX, TOWN], 2],
  ["fens",    [SUFFIX, TOWN], 2],
  ["bog",     [SUFFIX, TOWN], 2],
  ["moor",    [SUFFIX, TOWN], 2],
  ["delve",   [SUFFIX, TOWN], 2],
  ["wick",    [SUFFIX, TOWN], 2],
  ["wart",    [SUFFIX, TOWN], 1],
  ["moot",    [SUFFIX, TOWN], 1],
  ["dell",    [SUFFIX, TOWN], 2],
  ["fell",    [SUFFIX, TOWN], 2],
  ["minster", [SUFFIX, TOWN], 2],
  ["stein",   [SUFFIX, TOWN], 2],
  ["ville",   [SUFFIX, TOWN], 2],
  ["borough", [SUFFIX, TOWN], 2],
  ["vale",    [SUFFIX, TOWN], 2],
  ["dale",    [SUFFIX, TOWN], 2],
  ["end",     [SUFFIX, TOWN], 2],
  // General suffixes appended
  ...suffixes,
]

// TYPE LISTS — kept as string arrays for UI dropdown population

export const natural_type: string[] = [
  "natural_mountain",
  "natural_hills",
  "natural_river",
  "natural_freshwater",
  "natural_woodlands",
  "natural_highlands",
  "natural_saltwater",
  "natural_underground",
  "natural_depression",
  "natural_marshes",
  "natural_desert",
  "natural_misc",
  "natural_stone",
]

export const any_dungeon_type: string[] = [
  "tomb_room",
  "temple_room",
  "cavern_room",
  "magical_room",
  "dungeon_room",
]

export const construction_type: string[] = [
  "construction_underground",
  "construction_religious",
  "construction_fortification",
  "construction_funerary",
  "construction_artifact",
  "construction_shelter",
  "construction_mechanical",
  "construction_security",
  "construction_misc",
  "construction_freshwater",
  "construction_tower",
  "construction_bridge",
  "construction_tavern",
]

export const base_type: string[][] = [
  natural_type,
  construction_type,
]
