// AUTO-GENERATED by scripts/generateHexTileRotations.ts — do not edit manually

import type { TerrainType, HexDirection } from "../hexTerrain/types"

export type TileConfig = {
  src: string
  edges: Record<HexDirection, TerrainType>
}

export const TILES: TileConfig[] = [
  {
    src: "/hexTiles/five.svg",
    edges: {
      N: "forest",
      NE: "forest",
      SE: "forest",
      S: "forest",
      SW: "forest",
      NW: "plains"
    }
  },
  {
    src: "/hexTiles/five_coast_plains.svg",
    edges: {
      N: "plains",
      NE: "plains",
      SE: "plains",
      S: "plains",
      SW: "plains",
      NW: "coast"
    }
  },
  {
    src: "/hexTiles/five_coast_swamp.svg",
    edges: {
      N: "swamp",
      NE: "swamp",
      SE: "swamp",
      S: "swamp",
      SW: "swamp",
      NW: "coast"
    }
  },
  {
    src: "/hexTiles/five_forest_hills.svg",
    edges: {
      N: "hills",
      NE: "hills",
      SE: "hills",
      S: "hills",
      SW: "hills",
      NW: "forest"
    }
  },
  {
    src: "/hexTiles/five_forest_swamp.svg",
    edges: {
      N: "swamp",
      NE: "swamp",
      SE: "swamp",
      S: "swamp",
      SW: "swamp",
      NW: "forest"
    }
  },
  {
    src: "/hexTiles/five_hills_desert.svg",
    edges: {
      N: "desert",
      NE: "desert",
      SE: "desert",
      S: "desert",
      SW: "desert",
      NW: "hills"
    }
  },
  {
    src: "/hexTiles/five_hills_mountains.svg",
    edges: {
      N: "mountains",
      NE: "mountains",
      SE: "mountains",
      S: "mountains",
      SW: "mountains",
      NW: "hills"
    }
  },
  {
    src: "/hexTiles/five_ocean_coast.svg",
    edges: {
      N: "coast",
      NE: "coast",
      SE: "coast",
      S: "coast",
      SW: "coast",
      NW: "ocean"
    }
  },
  {
    src: "/hexTiles/five_plains_desert.svg",
    edges: {
      N: "desert",
      NE: "desert",
      SE: "desert",
      S: "desert",
      SW: "desert",
      NW: "plains"
    }
  },
  {
    src: "/hexTiles/five_plains_hills.svg",
    edges: {
      N: "hills",
      NE: "hills",
      SE: "hills",
      S: "hills",
      SW: "hills",
      NW: "plains"
    }
  },
  {
    src: "/hexTiles/five_plains_swamp.svg",
    edges: {
      N: "swamp",
      NE: "swamp",
      SE: "swamp",
      S: "swamp",
      SW: "swamp",
      NW: "plains"
    }
  },
  {
    src: "/hexTiles/four.svg",
    edges: {
      N: "plains",
      NE: "plains",
      SE: "plains",
      S: "plains",
      SW: "plains",
      NW: "plains"
    }
  },
  {
    src: "/hexTiles/four_coast_plains.svg",
    edges: {
      N: "coast",
      NE: "coast",
      SE: "coast",
      S: "coast",
      SW: "coast",
      NW: "coast"
    }
  },
  {
    src: "/hexTiles/four_coast_swamp.svg",
    edges: {
      N: "coast",
      NE: "coast",
      SE: "coast",
      S: "coast",
      SW: "coast",
      NW: "coast"
    }
  },
  {
    src: "/hexTiles/four_forest_hills.svg",
    edges: {
      N: "forest",
      NE: "forest",
      SE: "forest",
      S: "forest",
      SW: "forest",
      NW: "forest"
    }
  },
  {
    src: "/hexTiles/four_forest_swamp.svg",
    edges: {
      N: "forest",
      NE: "forest",
      SE: "forest",
      S: "forest",
      SW: "forest",
      NW: "forest"
    }
  },
  {
    src: "/hexTiles/four_hills_desert.svg",
    edges: {
      N: "hills",
      NE: "hills",
      SE: "hills",
      S: "hills",
      SW: "hills",
      NW: "hills"
    }
  },
  {
    src: "/hexTiles/four_hills_mountains.svg",
    edges: {
      N: "hills",
      NE: "hills",
      SE: "hills",
      S: "hills",
      SW: "hills",
      NW: "hills"
    }
  },
  {
    src: "/hexTiles/four_ocean_coast.svg",
    edges: {
      N: "ocean",
      NE: "ocean",
      SE: "ocean",
      S: "ocean",
      SW: "ocean",
      NW: "ocean"
    }
  },
  {
    src: "/hexTiles/four_plains_desert.svg",
    edges: {
      N: "plains",
      NE: "plains",
      SE: "plains",
      S: "plains",
      SW: "plains",
      NW: "plains"
    }
  },
  {
    src: "/hexTiles/four_plains_hills.svg",
    edges: {
      N: "plains",
      NE: "plains",
      SE: "plains",
      S: "plains",
      SW: "plains",
      NW: "plains"
    }
  },
  {
    src: "/hexTiles/four_plains_swamp.svg",
    edges: {
      N: "plains",
      NE: "plains",
      SE: "plains",
      S: "plains",
      SW: "plains",
      NW: "plains"
    }
  },
  {
    src: "/hexTiles/one.svg",
    edges: {
      N: "plains",
      NE: "forest",
      SE: "plains",
      S: "plains",
      SW: "plains",
      NW: "plains"
    }
  },
  {
    src: "/hexTiles/one_coast_plains.svg",
    edges: {
      N: "coast",
      NE: "plains",
      SE: "coast",
      S: "coast",
      SW: "coast",
      NW: "coast"
    }
  },
  {
    src: "/hexTiles/one_coast_swamp.svg",
    edges: {
      N: "coast",
      NE: "swamp",
      SE: "coast",
      S: "coast",
      SW: "coast",
      NW: "coast"
    }
  },
  {
    src: "/hexTiles/one_forest_hills.svg",
    edges: {
      N: "forest",
      NE: "hills",
      SE: "forest",
      S: "forest",
      SW: "forest",
      NW: "forest"
    }
  },
  {
    src: "/hexTiles/one_forest_swamp.svg",
    edges: {
      N: "forest",
      NE: "swamp",
      SE: "forest",
      S: "forest",
      SW: "forest",
      NW: "forest"
    }
  },
  {
    src: "/hexTiles/one_hills_desert.svg",
    edges: {
      N: "hills",
      NE: "desert",
      SE: "hills",
      S: "hills",
      SW: "hills",
      NW: "hills"
    }
  },
  {
    src: "/hexTiles/one_hills_mountains.svg",
    edges: {
      N: "hills",
      NE: "mountains",
      SE: "hills",
      S: "hills",
      SW: "hills",
      NW: "hills"
    }
  },
  {
    src: "/hexTiles/one_ocean_coast.svg",
    edges: {
      N: "ocean",
      NE: "coast",
      SE: "ocean",
      S: "ocean",
      SW: "ocean",
      NW: "ocean"
    }
  },
  {
    src: "/hexTiles/one_plains_desert.svg",
    edges: {
      N: "plains",
      NE: "desert",
      SE: "plains",
      S: "plains",
      SW: "plains",
      NW: "plains"
    }
  },
  {
    src: "/hexTiles/one_plains_hills.svg",
    edges: {
      N: "plains",
      NE: "hills",
      SE: "plains",
      S: "plains",
      SW: "plains",
      NW: "plains"
    }
  },
  {
    src: "/hexTiles/one_plains_swamp.svg",
    edges: {
      N: "plains",
      NE: "swamp",
      SE: "plains",
      S: "plains",
      SW: "plains",
      NW: "plains"
    }
  },
  {
    src: "/hexTiles/six.svg",
    edges: {
      N: "forest",
      NE: "forest",
      SE: "forest",
      S: "forest",
      SW: "forest",
      NW: "forest"
    }
  },
  {
    src: "/hexTiles/six_coast_plains.svg",
    edges: {
      N: "plains",
      NE: "plains",
      SE: "plains",
      S: "plains",
      SW: "plains",
      NW: "plains"
    }
  },
  {
    src: "/hexTiles/six_coast_swamp.svg",
    edges: {
      N: "swamp",
      NE: "swamp",
      SE: "swamp",
      S: "swamp",
      SW: "swamp",
      NW: "swamp"
    }
  },
  {
    src: "/hexTiles/six_forest_hills.svg",
    edges: {
      N: "hills",
      NE: "hills",
      SE: "hills",
      S: "hills",
      SW: "hills",
      NW: "hills"
    }
  },
  {
    src: "/hexTiles/six_forest_swamp.svg",
    edges: {
      N: "swamp",
      NE: "swamp",
      SE: "swamp",
      S: "swamp",
      SW: "swamp",
      NW: "swamp"
    }
  },
  {
    src: "/hexTiles/six_hills_desert.svg",
    edges: {
      N: "desert",
      NE: "desert",
      SE: "desert",
      S: "desert",
      SW: "desert",
      NW: "desert"
    }
  },
  {
    src: "/hexTiles/six_hills_mountains.svg",
    edges: {
      N: "mountains",
      NE: "mountains",
      SE: "mountains",
      S: "mountains",
      SW: "mountains",
      NW: "mountains"
    }
  },
  {
    src: "/hexTiles/six_ocean_coast.svg",
    edges: {
      N: "coast",
      NE: "coast",
      SE: "coast",
      S: "coast",
      SW: "coast",
      NW: "coast"
    }
  },
  {
    src: "/hexTiles/six_plains_desert.svg",
    edges: {
      N: "desert",
      NE: "desert",
      SE: "desert",
      S: "desert",
      SW: "desert",
      NW: "desert"
    }
  },
  {
    src: "/hexTiles/six_plains_hills.svg",
    edges: {
      N: "hills",
      NE: "hills",
      SE: "hills",
      S: "hills",
      SW: "hills",
      NW: "hills"
    }
  },
  {
    src: "/hexTiles/six_plains_swamp.svg",
    edges: {
      N: "swamp",
      NE: "swamp",
      SE: "swamp",
      S: "swamp",
      SW: "swamp",
      NW: "swamp"
    }
  },
  {
    src: "/hexTiles/solid_coast.svg",
    edges: {
      N: "coast",
      NE: "coast",
      SE: "coast",
      S: "coast",
      SW: "coast",
      NW: "coast"
    }
  },
  {
    src: "/hexTiles/solid_desert.svg",
    edges: {
      N: "desert",
      NE: "desert",
      SE: "desert",
      S: "desert",
      SW: "desert",
      NW: "desert"
    }
  },
  {
    src: "/hexTiles/solid_forest.svg",
    edges: {
      N: "forest",
      NE: "forest",
      SE: "forest",
      S: "forest",
      SW: "forest",
      NW: "forest"
    }
  },
  {
    src: "/hexTiles/solid_hills.svg",
    edges: {
      N: "hills",
      NE: "hills",
      SE: "hills",
      S: "hills",
      SW: "hills",
      NW: "hills"
    }
  },
  {
    src: "/hexTiles/solid_mountains.svg",
    edges: {
      N: "mountains",
      NE: "mountains",
      SE: "mountains",
      S: "mountains",
      SW: "mountains",
      NW: "mountains"
    }
  },
  {
    src: "/hexTiles/solid_ocean.svg",
    edges: {
      N: "ocean",
      NE: "ocean",
      SE: "ocean",
      S: "ocean",
      SW: "ocean",
      NW: "ocean"
    }
  },
  {
    src: "/hexTiles/solid_plains.svg",
    edges: {
      N: "plains",
      NE: "plains",
      SE: "plains",
      S: "plains",
      SW: "plains",
      NW: "plains"
    }
  },
  {
    src: "/hexTiles/solid_swamp.svg",
    edges: {
      N: "swamp",
      NE: "swamp",
      SE: "swamp",
      S: "swamp",
      SW: "swamp",
      NW: "swamp"
    }
  },
  {
    src: "/hexTiles/test_transition.svg",
    edges: {
      N: "forest",
      NE: "plains",
      SE: "plains",
      S: "plains",
      SW: "forest",
      NW: "forest"
    }
  },
  {
    src: "/hexTiles/test_transition_coast_plains.svg",
    edges: {
      N: "plains",
      NE: "coast",
      SE: "coast",
      S: "coast",
      SW: "plains",
      NW: "plains"
    }
  },
  {
    src: "/hexTiles/test_transition_coast_swamp.svg",
    edges: {
      N: "swamp",
      NE: "coast",
      SE: "coast",
      S: "coast",
      SW: "swamp",
      NW: "swamp"
    }
  },
  {
    src: "/hexTiles/test_transition_forest_hills.svg",
    edges: {
      N: "hills",
      NE: "forest",
      SE: "forest",
      S: "forest",
      SW: "hills",
      NW: "hills"
    }
  },
  {
    src: "/hexTiles/test_transition_forest_swamp.svg",
    edges: {
      N: "swamp",
      NE: "forest",
      SE: "forest",
      S: "forest",
      SW: "swamp",
      NW: "swamp"
    }
  },
  {
    src: "/hexTiles/test_transition_hills_desert.svg",
    edges: {
      N: "desert",
      NE: "hills",
      SE: "hills",
      S: "hills",
      SW: "desert",
      NW: "desert"
    }
  },
  {
    src: "/hexTiles/test_transition_hills_mountains.svg",
    edges: {
      N: "mountains",
      NE: "hills",
      SE: "hills",
      S: "hills",
      SW: "mountains",
      NW: "mountains"
    }
  },
  {
    src: "/hexTiles/test_transition_ocean_coast.svg",
    edges: {
      N: "coast",
      NE: "ocean",
      SE: "ocean",
      S: "ocean",
      SW: "coast",
      NW: "coast"
    }
  },
  {
    src: "/hexTiles/test_transition_plains_desert.svg",
    edges: {
      N: "desert",
      NE: "plains",
      SE: "plains",
      S: "plains",
      SW: "desert",
      NW: "desert"
    }
  },
  {
    src: "/hexTiles/test_transition_plains_hills.svg",
    edges: {
      N: "hills",
      NE: "plains",
      SE: "plains",
      S: "plains",
      SW: "hills",
      NW: "hills"
    }
  },
  {
    src: "/hexTiles/test_transition_plains_swamp.svg",
    edges: {
      N: "swamp",
      NE: "plains",
      SE: "plains",
      S: "plains",
      SW: "swamp",
      NW: "swamp"
    }
  },
  {
    src: "/hexTiles/three.svg",
    edges: {
      N: "plains",
      NE: "plains",
      SE: "forest",
      S: "plains",
      SW: "plains",
      NW: "plains"
    }
  },
  {
    src: "/hexTiles/three_coast_plains.svg",
    edges: {
      N: "coast",
      NE: "coast",
      SE: "plains",
      S: "coast",
      SW: "coast",
      NW: "coast"
    }
  },
  {
    src: "/hexTiles/three_coast_swamp.svg",
    edges: {
      N: "coast",
      NE: "coast",
      SE: "swamp",
      S: "coast",
      SW: "coast",
      NW: "coast"
    }
  },
  {
    src: "/hexTiles/three_forest_hills.svg",
    edges: {
      N: "forest",
      NE: "forest",
      SE: "hills",
      S: "forest",
      SW: "forest",
      NW: "forest"
    }
  },
  {
    src: "/hexTiles/three_forest_swamp.svg",
    edges: {
      N: "forest",
      NE: "forest",
      SE: "swamp",
      S: "forest",
      SW: "forest",
      NW: "forest"
    }
  },
  {
    src: "/hexTiles/three_hills_desert.svg",
    edges: {
      N: "hills",
      NE: "hills",
      SE: "desert",
      S: "hills",
      SW: "hills",
      NW: "hills"
    }
  },
  {
    src: "/hexTiles/three_hills_mountains.svg",
    edges: {
      N: "hills",
      NE: "hills",
      SE: "mountains",
      S: "hills",
      SW: "hills",
      NW: "hills"
    }
  },
  {
    src: "/hexTiles/three_ocean_coast.svg",
    edges: {
      N: "ocean",
      NE: "ocean",
      SE: "coast",
      S: "ocean",
      SW: "ocean",
      NW: "ocean"
    }
  },
  {
    src: "/hexTiles/three_plains_desert.svg",
    edges: {
      N: "plains",
      NE: "plains",
      SE: "desert",
      S: "plains",
      SW: "plains",
      NW: "plains"
    }
  },
  {
    src: "/hexTiles/three_plains_hills.svg",
    edges: {
      N: "plains",
      NE: "plains",
      SE: "hills",
      S: "plains",
      SW: "plains",
      NW: "plains"
    }
  },
  {
    src: "/hexTiles/three_plains_swamp.svg",
    edges: {
      N: "plains",
      NE: "plains",
      SE: "swamp",
      S: "plains",
      SW: "plains",
      NW: "plains"
    }
  },
  {
    src: "/hexTiles/two.svg",
    edges: {
      N: "plains",
      NE: "plains",
      SE: "plains",
      S: "plains",
      SW: "plains",
      NW: "plains"
    }
  },
  {
    src: "/hexTiles/two_coast_plains.svg",
    edges: {
      N: "coast",
      NE: "coast",
      SE: "coast",
      S: "coast",
      SW: "coast",
      NW: "coast"
    }
  },
  {
    src: "/hexTiles/two_coast_swamp.svg",
    edges: {
      N: "coast",
      NE: "coast",
      SE: "coast",
      S: "coast",
      SW: "coast",
      NW: "coast"
    }
  },
  {
    src: "/hexTiles/two_forest_hills.svg",
    edges: {
      N: "forest",
      NE: "forest",
      SE: "forest",
      S: "forest",
      SW: "forest",
      NW: "forest"
    }
  },
  {
    src: "/hexTiles/two_forest_swamp.svg",
    edges: {
      N: "forest",
      NE: "forest",
      SE: "forest",
      S: "forest",
      SW: "forest",
      NW: "forest"
    }
  },
  {
    src: "/hexTiles/two_hills_desert.svg",
    edges: {
      N: "hills",
      NE: "hills",
      SE: "hills",
      S: "hills",
      SW: "hills",
      NW: "hills"
    }
  },
  {
    src: "/hexTiles/two_hills_mountains.svg",
    edges: {
      N: "hills",
      NE: "hills",
      SE: "hills",
      S: "hills",
      SW: "hills",
      NW: "hills"
    }
  },
  {
    src: "/hexTiles/two_ocean_coast.svg",
    edges: {
      N: "ocean",
      NE: "ocean",
      SE: "ocean",
      S: "ocean",
      SW: "ocean",
      NW: "ocean"
    }
  },
  {
    src: "/hexTiles/two_plains_desert.svg",
    edges: {
      N: "plains",
      NE: "plains",
      SE: "plains",
      S: "plains",
      SW: "plains",
      NW: "plains"
    }
  },
  {
    src: "/hexTiles/two_plains_hills.svg",
    edges: {
      N: "plains",
      NE: "plains",
      SE: "plains",
      S: "plains",
      SW: "plains",
      NW: "plains"
    }
  },
  {
    src: "/hexTiles/two_plains_swamp.svg",
    edges: {
      N: "plains",
      NE: "plains",
      SE: "plains",
      S: "plains",
      SW: "plains",
      NW: "plains"
    }
  },
  {
    src: "/hexTiles/five_r060.svg",
    edges: {
      N: "plains",
      NE: "forest",
      SE: "forest",
      S: "forest",
      SW: "forest",
      NW: "forest"
    }
  },
  {
    src: "/hexTiles/five_r120.svg",
    edges: {
      N: "forest",
      NE: "plains",
      SE: "forest",
      S: "forest",
      SW: "forest",
      NW: "forest"
    }
  },
  {
    src: "/hexTiles/five_r180.svg",
    edges: {
      N: "forest",
      NE: "forest",
      SE: "plains",
      S: "forest",
      SW: "forest",
      NW: "forest"
    }
  },
  {
    src: "/hexTiles/five_r240.svg",
    edges: {
      N: "forest",
      NE: "forest",
      SE: "forest",
      S: "plains",
      SW: "forest",
      NW: "forest"
    }
  },
  {
    src: "/hexTiles/five_r300.svg",
    edges: {
      N: "forest",
      NE: "forest",
      SE: "forest",
      S: "forest",
      SW: "plains",
      NW: "forest"
    }
  },
  {
    src: "/hexTiles/five_coast_plains_r060.svg",
    edges: {
      N: "coast",
      NE: "plains",
      SE: "plains",
      S: "plains",
      SW: "plains",
      NW: "plains"
    }
  },
  {
    src: "/hexTiles/five_coast_plains_r120.svg",
    edges: {
      N: "plains",
      NE: "coast",
      SE: "plains",
      S: "plains",
      SW: "plains",
      NW: "plains"
    }
  },
  {
    src: "/hexTiles/five_coast_plains_r180.svg",
    edges: {
      N: "plains",
      NE: "plains",
      SE: "coast",
      S: "plains",
      SW: "plains",
      NW: "plains"
    }
  },
  {
    src: "/hexTiles/five_coast_plains_r240.svg",
    edges: {
      N: "plains",
      NE: "plains",
      SE: "plains",
      S: "coast",
      SW: "plains",
      NW: "plains"
    }
  },
  {
    src: "/hexTiles/five_coast_plains_r300.svg",
    edges: {
      N: "plains",
      NE: "plains",
      SE: "plains",
      S: "plains",
      SW: "coast",
      NW: "plains"
    }
  },
  {
    src: "/hexTiles/five_coast_swamp_r060.svg",
    edges: {
      N: "coast",
      NE: "swamp",
      SE: "swamp",
      S: "swamp",
      SW: "swamp",
      NW: "swamp"
    }
  },
  {
    src: "/hexTiles/five_coast_swamp_r120.svg",
    edges: {
      N: "swamp",
      NE: "coast",
      SE: "swamp",
      S: "swamp",
      SW: "swamp",
      NW: "swamp"
    }
  },
  {
    src: "/hexTiles/five_coast_swamp_r180.svg",
    edges: {
      N: "swamp",
      NE: "swamp",
      SE: "coast",
      S: "swamp",
      SW: "swamp",
      NW: "swamp"
    }
  },
  {
    src: "/hexTiles/five_coast_swamp_r240.svg",
    edges: {
      N: "swamp",
      NE: "swamp",
      SE: "swamp",
      S: "coast",
      SW: "swamp",
      NW: "swamp"
    }
  },
  {
    src: "/hexTiles/five_coast_swamp_r300.svg",
    edges: {
      N: "swamp",
      NE: "swamp",
      SE: "swamp",
      S: "swamp",
      SW: "coast",
      NW: "swamp"
    }
  },
  {
    src: "/hexTiles/five_forest_hills_r060.svg",
    edges: {
      N: "forest",
      NE: "hills",
      SE: "hills",
      S: "hills",
      SW: "hills",
      NW: "hills"
    }
  },
  {
    src: "/hexTiles/five_forest_hills_r120.svg",
    edges: {
      N: "hills",
      NE: "forest",
      SE: "hills",
      S: "hills",
      SW: "hills",
      NW: "hills"
    }
  },
  {
    src: "/hexTiles/five_forest_hills_r180.svg",
    edges: {
      N: "hills",
      NE: "hills",
      SE: "forest",
      S: "hills",
      SW: "hills",
      NW: "hills"
    }
  },
  {
    src: "/hexTiles/five_forest_hills_r240.svg",
    edges: {
      N: "hills",
      NE: "hills",
      SE: "hills",
      S: "forest",
      SW: "hills",
      NW: "hills"
    }
  },
  {
    src: "/hexTiles/five_forest_hills_r300.svg",
    edges: {
      N: "hills",
      NE: "hills",
      SE: "hills",
      S: "hills",
      SW: "forest",
      NW: "hills"
    }
  },
  {
    src: "/hexTiles/five_forest_swamp_r060.svg",
    edges: {
      N: "forest",
      NE: "swamp",
      SE: "swamp",
      S: "swamp",
      SW: "swamp",
      NW: "swamp"
    }
  },
  {
    src: "/hexTiles/five_forest_swamp_r120.svg",
    edges: {
      N: "swamp",
      NE: "forest",
      SE: "swamp",
      S: "swamp",
      SW: "swamp",
      NW: "swamp"
    }
  },
  {
    src: "/hexTiles/five_forest_swamp_r180.svg",
    edges: {
      N: "swamp",
      NE: "swamp",
      SE: "forest",
      S: "swamp",
      SW: "swamp",
      NW: "swamp"
    }
  },
  {
    src: "/hexTiles/five_forest_swamp_r240.svg",
    edges: {
      N: "swamp",
      NE: "swamp",
      SE: "swamp",
      S: "forest",
      SW: "swamp",
      NW: "swamp"
    }
  },
  {
    src: "/hexTiles/five_forest_swamp_r300.svg",
    edges: {
      N: "swamp",
      NE: "swamp",
      SE: "swamp",
      S: "swamp",
      SW: "forest",
      NW: "swamp"
    }
  },
  {
    src: "/hexTiles/five_hills_desert_r060.svg",
    edges: {
      N: "hills",
      NE: "desert",
      SE: "desert",
      S: "desert",
      SW: "desert",
      NW: "desert"
    }
  },
  {
    src: "/hexTiles/five_hills_desert_r120.svg",
    edges: {
      N: "desert",
      NE: "hills",
      SE: "desert",
      S: "desert",
      SW: "desert",
      NW: "desert"
    }
  },
  {
    src: "/hexTiles/five_hills_desert_r180.svg",
    edges: {
      N: "desert",
      NE: "desert",
      SE: "hills",
      S: "desert",
      SW: "desert",
      NW: "desert"
    }
  },
  {
    src: "/hexTiles/five_hills_desert_r240.svg",
    edges: {
      N: "desert",
      NE: "desert",
      SE: "desert",
      S: "hills",
      SW: "desert",
      NW: "desert"
    }
  },
  {
    src: "/hexTiles/five_hills_desert_r300.svg",
    edges: {
      N: "desert",
      NE: "desert",
      SE: "desert",
      S: "desert",
      SW: "hills",
      NW: "desert"
    }
  },
  {
    src: "/hexTiles/five_hills_mountains_r060.svg",
    edges: {
      N: "hills",
      NE: "mountains",
      SE: "mountains",
      S: "mountains",
      SW: "mountains",
      NW: "mountains"
    }
  },
  {
    src: "/hexTiles/five_hills_mountains_r120.svg",
    edges: {
      N: "mountains",
      NE: "hills",
      SE: "mountains",
      S: "mountains",
      SW: "mountains",
      NW: "mountains"
    }
  },
  {
    src: "/hexTiles/five_hills_mountains_r180.svg",
    edges: {
      N: "mountains",
      NE: "mountains",
      SE: "hills",
      S: "mountains",
      SW: "mountains",
      NW: "mountains"
    }
  },
  {
    src: "/hexTiles/five_hills_mountains_r240.svg",
    edges: {
      N: "mountains",
      NE: "mountains",
      SE: "mountains",
      S: "hills",
      SW: "mountains",
      NW: "mountains"
    }
  },
  {
    src: "/hexTiles/five_hills_mountains_r300.svg",
    edges: {
      N: "mountains",
      NE: "mountains",
      SE: "mountains",
      S: "mountains",
      SW: "hills",
      NW: "mountains"
    }
  },
  {
    src: "/hexTiles/five_ocean_coast_r060.svg",
    edges: {
      N: "ocean",
      NE: "coast",
      SE: "coast",
      S: "coast",
      SW: "coast",
      NW: "coast"
    }
  },
  {
    src: "/hexTiles/five_ocean_coast_r120.svg",
    edges: {
      N: "coast",
      NE: "ocean",
      SE: "coast",
      S: "coast",
      SW: "coast",
      NW: "coast"
    }
  },
  {
    src: "/hexTiles/five_ocean_coast_r180.svg",
    edges: {
      N: "coast",
      NE: "coast",
      SE: "ocean",
      S: "coast",
      SW: "coast",
      NW: "coast"
    }
  },
  {
    src: "/hexTiles/five_ocean_coast_r240.svg",
    edges: {
      N: "coast",
      NE: "coast",
      SE: "coast",
      S: "ocean",
      SW: "coast",
      NW: "coast"
    }
  },
  {
    src: "/hexTiles/five_ocean_coast_r300.svg",
    edges: {
      N: "coast",
      NE: "coast",
      SE: "coast",
      S: "coast",
      SW: "ocean",
      NW: "coast"
    }
  },
  {
    src: "/hexTiles/five_plains_desert_r060.svg",
    edges: {
      N: "plains",
      NE: "desert",
      SE: "desert",
      S: "desert",
      SW: "desert",
      NW: "desert"
    }
  },
  {
    src: "/hexTiles/five_plains_desert_r120.svg",
    edges: {
      N: "desert",
      NE: "plains",
      SE: "desert",
      S: "desert",
      SW: "desert",
      NW: "desert"
    }
  },
  {
    src: "/hexTiles/five_plains_desert_r180.svg",
    edges: {
      N: "desert",
      NE: "desert",
      SE: "plains",
      S: "desert",
      SW: "desert",
      NW: "desert"
    }
  },
  {
    src: "/hexTiles/five_plains_desert_r240.svg",
    edges: {
      N: "desert",
      NE: "desert",
      SE: "desert",
      S: "plains",
      SW: "desert",
      NW: "desert"
    }
  },
  {
    src: "/hexTiles/five_plains_desert_r300.svg",
    edges: {
      N: "desert",
      NE: "desert",
      SE: "desert",
      S: "desert",
      SW: "plains",
      NW: "desert"
    }
  },
  {
    src: "/hexTiles/five_plains_hills_r060.svg",
    edges: {
      N: "plains",
      NE: "hills",
      SE: "hills",
      S: "hills",
      SW: "hills",
      NW: "hills"
    }
  },
  {
    src: "/hexTiles/five_plains_hills_r120.svg",
    edges: {
      N: "hills",
      NE: "plains",
      SE: "hills",
      S: "hills",
      SW: "hills",
      NW: "hills"
    }
  },
  {
    src: "/hexTiles/five_plains_hills_r180.svg",
    edges: {
      N: "hills",
      NE: "hills",
      SE: "plains",
      S: "hills",
      SW: "hills",
      NW: "hills"
    }
  },
  {
    src: "/hexTiles/five_plains_hills_r240.svg",
    edges: {
      N: "hills",
      NE: "hills",
      SE: "hills",
      S: "plains",
      SW: "hills",
      NW: "hills"
    }
  },
  {
    src: "/hexTiles/five_plains_hills_r300.svg",
    edges: {
      N: "hills",
      NE: "hills",
      SE: "hills",
      S: "hills",
      SW: "plains",
      NW: "hills"
    }
  },
  {
    src: "/hexTiles/five_plains_swamp_r060.svg",
    edges: {
      N: "plains",
      NE: "swamp",
      SE: "swamp",
      S: "swamp",
      SW: "swamp",
      NW: "swamp"
    }
  },
  {
    src: "/hexTiles/five_plains_swamp_r120.svg",
    edges: {
      N: "swamp",
      NE: "plains",
      SE: "swamp",
      S: "swamp",
      SW: "swamp",
      NW: "swamp"
    }
  },
  {
    src: "/hexTiles/five_plains_swamp_r180.svg",
    edges: {
      N: "swamp",
      NE: "swamp",
      SE: "plains",
      S: "swamp",
      SW: "swamp",
      NW: "swamp"
    }
  },
  {
    src: "/hexTiles/five_plains_swamp_r240.svg",
    edges: {
      N: "swamp",
      NE: "swamp",
      SE: "swamp",
      S: "plains",
      SW: "swamp",
      NW: "swamp"
    }
  },
  {
    src: "/hexTiles/five_plains_swamp_r300.svg",
    edges: {
      N: "swamp",
      NE: "swamp",
      SE: "swamp",
      S: "swamp",
      SW: "plains",
      NW: "swamp"
    }
  },
  {
    src: "/hexTiles/one_r120.svg",
    edges: {
      N: "plains",
      NE: "plains",
      SE: "plains",
      S: "forest",
      SW: "plains",
      NW: "plains"
    }
  },
  {
    src: "/hexTiles/one_r180.svg",
    edges: {
      N: "plains",
      NE: "plains",
      SE: "plains",
      S: "plains",
      SW: "forest",
      NW: "plains"
    }
  },
  {
    src: "/hexTiles/one_r240.svg",
    edges: {
      N: "plains",
      NE: "plains",
      SE: "plains",
      S: "plains",
      SW: "plains",
      NW: "forest"
    }
  },
  {
    src: "/hexTiles/one_r300.svg",
    edges: {
      N: "forest",
      NE: "plains",
      SE: "plains",
      S: "plains",
      SW: "plains",
      NW: "plains"
    }
  },
  {
    src: "/hexTiles/one_coast_plains_r120.svg",
    edges: {
      N: "coast",
      NE: "coast",
      SE: "coast",
      S: "plains",
      SW: "coast",
      NW: "coast"
    }
  },
  {
    src: "/hexTiles/one_coast_plains_r180.svg",
    edges: {
      N: "coast",
      NE: "coast",
      SE: "coast",
      S: "coast",
      SW: "plains",
      NW: "coast"
    }
  },
  {
    src: "/hexTiles/one_coast_plains_r240.svg",
    edges: {
      N: "coast",
      NE: "coast",
      SE: "coast",
      S: "coast",
      SW: "coast",
      NW: "plains"
    }
  },
  {
    src: "/hexTiles/one_coast_plains_r300.svg",
    edges: {
      N: "plains",
      NE: "coast",
      SE: "coast",
      S: "coast",
      SW: "coast",
      NW: "coast"
    }
  },
  {
    src: "/hexTiles/one_coast_swamp_r120.svg",
    edges: {
      N: "coast",
      NE: "coast",
      SE: "coast",
      S: "swamp",
      SW: "coast",
      NW: "coast"
    }
  },
  {
    src: "/hexTiles/one_coast_swamp_r180.svg",
    edges: {
      N: "coast",
      NE: "coast",
      SE: "coast",
      S: "coast",
      SW: "swamp",
      NW: "coast"
    }
  },
  {
    src: "/hexTiles/one_coast_swamp_r240.svg",
    edges: {
      N: "coast",
      NE: "coast",
      SE: "coast",
      S: "coast",
      SW: "coast",
      NW: "swamp"
    }
  },
  {
    src: "/hexTiles/one_coast_swamp_r300.svg",
    edges: {
      N: "swamp",
      NE: "coast",
      SE: "coast",
      S: "coast",
      SW: "coast",
      NW: "coast"
    }
  },
  {
    src: "/hexTiles/one_forest_hills_r120.svg",
    edges: {
      N: "forest",
      NE: "forest",
      SE: "forest",
      S: "hills",
      SW: "forest",
      NW: "forest"
    }
  },
  {
    src: "/hexTiles/one_forest_hills_r180.svg",
    edges: {
      N: "forest",
      NE: "forest",
      SE: "forest",
      S: "forest",
      SW: "hills",
      NW: "forest"
    }
  },
  {
    src: "/hexTiles/one_forest_hills_r240.svg",
    edges: {
      N: "forest",
      NE: "forest",
      SE: "forest",
      S: "forest",
      SW: "forest",
      NW: "hills"
    }
  },
  {
    src: "/hexTiles/one_forest_hills_r300.svg",
    edges: {
      N: "hills",
      NE: "forest",
      SE: "forest",
      S: "forest",
      SW: "forest",
      NW: "forest"
    }
  },
  {
    src: "/hexTiles/one_forest_swamp_r120.svg",
    edges: {
      N: "forest",
      NE: "forest",
      SE: "forest",
      S: "swamp",
      SW: "forest",
      NW: "forest"
    }
  },
  {
    src: "/hexTiles/one_forest_swamp_r180.svg",
    edges: {
      N: "forest",
      NE: "forest",
      SE: "forest",
      S: "forest",
      SW: "swamp",
      NW: "forest"
    }
  },
  {
    src: "/hexTiles/one_forest_swamp_r240.svg",
    edges: {
      N: "forest",
      NE: "forest",
      SE: "forest",
      S: "forest",
      SW: "forest",
      NW: "swamp"
    }
  },
  {
    src: "/hexTiles/one_forest_swamp_r300.svg",
    edges: {
      N: "swamp",
      NE: "forest",
      SE: "forest",
      S: "forest",
      SW: "forest",
      NW: "forest"
    }
  },
  {
    src: "/hexTiles/one_hills_desert_r120.svg",
    edges: {
      N: "hills",
      NE: "hills",
      SE: "hills",
      S: "desert",
      SW: "hills",
      NW: "hills"
    }
  },
  {
    src: "/hexTiles/one_hills_desert_r180.svg",
    edges: {
      N: "hills",
      NE: "hills",
      SE: "hills",
      S: "hills",
      SW: "desert",
      NW: "hills"
    }
  },
  {
    src: "/hexTiles/one_hills_desert_r240.svg",
    edges: {
      N: "hills",
      NE: "hills",
      SE: "hills",
      S: "hills",
      SW: "hills",
      NW: "desert"
    }
  },
  {
    src: "/hexTiles/one_hills_desert_r300.svg",
    edges: {
      N: "desert",
      NE: "hills",
      SE: "hills",
      S: "hills",
      SW: "hills",
      NW: "hills"
    }
  },
  {
    src: "/hexTiles/one_hills_mountains_r120.svg",
    edges: {
      N: "hills",
      NE: "hills",
      SE: "hills",
      S: "mountains",
      SW: "hills",
      NW: "hills"
    }
  },
  {
    src: "/hexTiles/one_hills_mountains_r180.svg",
    edges: {
      N: "hills",
      NE: "hills",
      SE: "hills",
      S: "hills",
      SW: "mountains",
      NW: "hills"
    }
  },
  {
    src: "/hexTiles/one_hills_mountains_r240.svg",
    edges: {
      N: "hills",
      NE: "hills",
      SE: "hills",
      S: "hills",
      SW: "hills",
      NW: "mountains"
    }
  },
  {
    src: "/hexTiles/one_hills_mountains_r300.svg",
    edges: {
      N: "mountains",
      NE: "hills",
      SE: "hills",
      S: "hills",
      SW: "hills",
      NW: "hills"
    }
  },
  {
    src: "/hexTiles/one_ocean_coast_r120.svg",
    edges: {
      N: "ocean",
      NE: "ocean",
      SE: "ocean",
      S: "coast",
      SW: "ocean",
      NW: "ocean"
    }
  },
  {
    src: "/hexTiles/one_ocean_coast_r180.svg",
    edges: {
      N: "ocean",
      NE: "ocean",
      SE: "ocean",
      S: "ocean",
      SW: "coast",
      NW: "ocean"
    }
  },
  {
    src: "/hexTiles/one_ocean_coast_r240.svg",
    edges: {
      N: "ocean",
      NE: "ocean",
      SE: "ocean",
      S: "ocean",
      SW: "ocean",
      NW: "coast"
    }
  },
  {
    src: "/hexTiles/one_ocean_coast_r300.svg",
    edges: {
      N: "coast",
      NE: "ocean",
      SE: "ocean",
      S: "ocean",
      SW: "ocean",
      NW: "ocean"
    }
  },
  {
    src: "/hexTiles/one_plains_desert_r120.svg",
    edges: {
      N: "plains",
      NE: "plains",
      SE: "plains",
      S: "desert",
      SW: "plains",
      NW: "plains"
    }
  },
  {
    src: "/hexTiles/one_plains_desert_r180.svg",
    edges: {
      N: "plains",
      NE: "plains",
      SE: "plains",
      S: "plains",
      SW: "desert",
      NW: "plains"
    }
  },
  {
    src: "/hexTiles/one_plains_desert_r240.svg",
    edges: {
      N: "plains",
      NE: "plains",
      SE: "plains",
      S: "plains",
      SW: "plains",
      NW: "desert"
    }
  },
  {
    src: "/hexTiles/one_plains_desert_r300.svg",
    edges: {
      N: "desert",
      NE: "plains",
      SE: "plains",
      S: "plains",
      SW: "plains",
      NW: "plains"
    }
  },
  {
    src: "/hexTiles/one_plains_hills_r120.svg",
    edges: {
      N: "plains",
      NE: "plains",
      SE: "plains",
      S: "hills",
      SW: "plains",
      NW: "plains"
    }
  },
  {
    src: "/hexTiles/one_plains_hills_r180.svg",
    edges: {
      N: "plains",
      NE: "plains",
      SE: "plains",
      S: "plains",
      SW: "hills",
      NW: "plains"
    }
  },
  {
    src: "/hexTiles/one_plains_hills_r240.svg",
    edges: {
      N: "plains",
      NE: "plains",
      SE: "plains",
      S: "plains",
      SW: "plains",
      NW: "hills"
    }
  },
  {
    src: "/hexTiles/one_plains_hills_r300.svg",
    edges: {
      N: "hills",
      NE: "plains",
      SE: "plains",
      S: "plains",
      SW: "plains",
      NW: "plains"
    }
  },
  {
    src: "/hexTiles/one_plains_swamp_r120.svg",
    edges: {
      N: "plains",
      NE: "plains",
      SE: "plains",
      S: "swamp",
      SW: "plains",
      NW: "plains"
    }
  },
  {
    src: "/hexTiles/one_plains_swamp_r180.svg",
    edges: {
      N: "plains",
      NE: "plains",
      SE: "plains",
      S: "plains",
      SW: "swamp",
      NW: "plains"
    }
  },
  {
    src: "/hexTiles/one_plains_swamp_r240.svg",
    edges: {
      N: "plains",
      NE: "plains",
      SE: "plains",
      S: "plains",
      SW: "plains",
      NW: "swamp"
    }
  },
  {
    src: "/hexTiles/one_plains_swamp_r300.svg",
    edges: {
      N: "swamp",
      NE: "plains",
      SE: "plains",
      S: "plains",
      SW: "plains",
      NW: "plains"
    }
  },
  {
    src: "/hexTiles/test_transition_r060.svg",
    edges: {
      N: "forest",
      NE: "forest",
      SE: "plains",
      S: "plains",
      SW: "plains",
      NW: "forest"
    }
  },
  {
    src: "/hexTiles/test_transition_r120.svg",
    edges: {
      N: "forest",
      NE: "forest",
      SE: "forest",
      S: "plains",
      SW: "plains",
      NW: "plains"
    }
  },
  {
    src: "/hexTiles/test_transition_r180.svg",
    edges: {
      N: "plains",
      NE: "forest",
      SE: "forest",
      S: "forest",
      SW: "plains",
      NW: "plains"
    }
  },
  {
    src: "/hexTiles/test_transition_r240.svg",
    edges: {
      N: "plains",
      NE: "plains",
      SE: "forest",
      S: "forest",
      SW: "forest",
      NW: "plains"
    }
  },
  {
    src: "/hexTiles/test_transition_r300.svg",
    edges: {
      N: "plains",
      NE: "plains",
      SE: "plains",
      S: "forest",
      SW: "forest",
      NW: "forest"
    }
  },
  {
    src: "/hexTiles/test_transition_coast_plains_r060.svg",
    edges: {
      N: "plains",
      NE: "plains",
      SE: "coast",
      S: "coast",
      SW: "coast",
      NW: "plains"
    }
  },
  {
    src: "/hexTiles/test_transition_coast_plains_r120.svg",
    edges: {
      N: "plains",
      NE: "plains",
      SE: "plains",
      S: "coast",
      SW: "coast",
      NW: "coast"
    }
  },
  {
    src: "/hexTiles/test_transition_coast_plains_r180.svg",
    edges: {
      N: "coast",
      NE: "plains",
      SE: "plains",
      S: "plains",
      SW: "coast",
      NW: "coast"
    }
  },
  {
    src: "/hexTiles/test_transition_coast_plains_r240.svg",
    edges: {
      N: "coast",
      NE: "coast",
      SE: "plains",
      S: "plains",
      SW: "plains",
      NW: "coast"
    }
  },
  {
    src: "/hexTiles/test_transition_coast_plains_r300.svg",
    edges: {
      N: "coast",
      NE: "coast",
      SE: "coast",
      S: "plains",
      SW: "plains",
      NW: "plains"
    }
  },
  {
    src: "/hexTiles/test_transition_coast_swamp_r060.svg",
    edges: {
      N: "swamp",
      NE: "swamp",
      SE: "coast",
      S: "coast",
      SW: "coast",
      NW: "swamp"
    }
  },
  {
    src: "/hexTiles/test_transition_coast_swamp_r120.svg",
    edges: {
      N: "swamp",
      NE: "swamp",
      SE: "swamp",
      S: "coast",
      SW: "coast",
      NW: "coast"
    }
  },
  {
    src: "/hexTiles/test_transition_coast_swamp_r180.svg",
    edges: {
      N: "coast",
      NE: "swamp",
      SE: "swamp",
      S: "swamp",
      SW: "coast",
      NW: "coast"
    }
  },
  {
    src: "/hexTiles/test_transition_coast_swamp_r240.svg",
    edges: {
      N: "coast",
      NE: "coast",
      SE: "swamp",
      S: "swamp",
      SW: "swamp",
      NW: "coast"
    }
  },
  {
    src: "/hexTiles/test_transition_coast_swamp_r300.svg",
    edges: {
      N: "coast",
      NE: "coast",
      SE: "coast",
      S: "swamp",
      SW: "swamp",
      NW: "swamp"
    }
  },
  {
    src: "/hexTiles/test_transition_forest_hills_r060.svg",
    edges: {
      N: "hills",
      NE: "hills",
      SE: "forest",
      S: "forest",
      SW: "forest",
      NW: "hills"
    }
  },
  {
    src: "/hexTiles/test_transition_forest_hills_r120.svg",
    edges: {
      N: "hills",
      NE: "hills",
      SE: "hills",
      S: "forest",
      SW: "forest",
      NW: "forest"
    }
  },
  {
    src: "/hexTiles/test_transition_forest_hills_r180.svg",
    edges: {
      N: "forest",
      NE: "hills",
      SE: "hills",
      S: "hills",
      SW: "forest",
      NW: "forest"
    }
  },
  {
    src: "/hexTiles/test_transition_forest_hills_r240.svg",
    edges: {
      N: "forest",
      NE: "forest",
      SE: "hills",
      S: "hills",
      SW: "hills",
      NW: "forest"
    }
  },
  {
    src: "/hexTiles/test_transition_forest_hills_r300.svg",
    edges: {
      N: "forest",
      NE: "forest",
      SE: "forest",
      S: "hills",
      SW: "hills",
      NW: "hills"
    }
  },
  {
    src: "/hexTiles/test_transition_forest_swamp_r060.svg",
    edges: {
      N: "swamp",
      NE: "swamp",
      SE: "forest",
      S: "forest",
      SW: "forest",
      NW: "swamp"
    }
  },
  {
    src: "/hexTiles/test_transition_forest_swamp_r120.svg",
    edges: {
      N: "swamp",
      NE: "swamp",
      SE: "swamp",
      S: "forest",
      SW: "forest",
      NW: "forest"
    }
  },
  {
    src: "/hexTiles/test_transition_forest_swamp_r180.svg",
    edges: {
      N: "forest",
      NE: "swamp",
      SE: "swamp",
      S: "swamp",
      SW: "forest",
      NW: "forest"
    }
  },
  {
    src: "/hexTiles/test_transition_forest_swamp_r240.svg",
    edges: {
      N: "forest",
      NE: "forest",
      SE: "swamp",
      S: "swamp",
      SW: "swamp",
      NW: "forest"
    }
  },
  {
    src: "/hexTiles/test_transition_forest_swamp_r300.svg",
    edges: {
      N: "forest",
      NE: "forest",
      SE: "forest",
      S: "swamp",
      SW: "swamp",
      NW: "swamp"
    }
  },
  {
    src: "/hexTiles/test_transition_hills_desert_r060.svg",
    edges: {
      N: "desert",
      NE: "desert",
      SE: "hills",
      S: "hills",
      SW: "hills",
      NW: "desert"
    }
  },
  {
    src: "/hexTiles/test_transition_hills_desert_r120.svg",
    edges: {
      N: "desert",
      NE: "desert",
      SE: "desert",
      S: "hills",
      SW: "hills",
      NW: "hills"
    }
  },
  {
    src: "/hexTiles/test_transition_hills_desert_r180.svg",
    edges: {
      N: "hills",
      NE: "desert",
      SE: "desert",
      S: "desert",
      SW: "hills",
      NW: "hills"
    }
  },
  {
    src: "/hexTiles/test_transition_hills_desert_r240.svg",
    edges: {
      N: "hills",
      NE: "hills",
      SE: "desert",
      S: "desert",
      SW: "desert",
      NW: "hills"
    }
  },
  {
    src: "/hexTiles/test_transition_hills_desert_r300.svg",
    edges: {
      N: "hills",
      NE: "hills",
      SE: "hills",
      S: "desert",
      SW: "desert",
      NW: "desert"
    }
  },
  {
    src: "/hexTiles/test_transition_hills_mountains_r060.svg",
    edges: {
      N: "mountains",
      NE: "mountains",
      SE: "hills",
      S: "hills",
      SW: "hills",
      NW: "mountains"
    }
  },
  {
    src: "/hexTiles/test_transition_hills_mountains_r120.svg",
    edges: {
      N: "mountains",
      NE: "mountains",
      SE: "mountains",
      S: "hills",
      SW: "hills",
      NW: "hills"
    }
  },
  {
    src: "/hexTiles/test_transition_hills_mountains_r180.svg",
    edges: {
      N: "hills",
      NE: "mountains",
      SE: "mountains",
      S: "mountains",
      SW: "hills",
      NW: "hills"
    }
  },
  {
    src: "/hexTiles/test_transition_hills_mountains_r240.svg",
    edges: {
      N: "hills",
      NE: "hills",
      SE: "mountains",
      S: "mountains",
      SW: "mountains",
      NW: "hills"
    }
  },
  {
    src: "/hexTiles/test_transition_hills_mountains_r300.svg",
    edges: {
      N: "hills",
      NE: "hills",
      SE: "hills",
      S: "mountains",
      SW: "mountains",
      NW: "mountains"
    }
  },
  {
    src: "/hexTiles/test_transition_ocean_coast_r060.svg",
    edges: {
      N: "coast",
      NE: "coast",
      SE: "ocean",
      S: "ocean",
      SW: "ocean",
      NW: "coast"
    }
  },
  {
    src: "/hexTiles/test_transition_ocean_coast_r120.svg",
    edges: {
      N: "coast",
      NE: "coast",
      SE: "coast",
      S: "ocean",
      SW: "ocean",
      NW: "ocean"
    }
  },
  {
    src: "/hexTiles/test_transition_ocean_coast_r180.svg",
    edges: {
      N: "ocean",
      NE: "coast",
      SE: "coast",
      S: "coast",
      SW: "ocean",
      NW: "ocean"
    }
  },
  {
    src: "/hexTiles/test_transition_ocean_coast_r240.svg",
    edges: {
      N: "ocean",
      NE: "ocean",
      SE: "coast",
      S: "coast",
      SW: "coast",
      NW: "ocean"
    }
  },
  {
    src: "/hexTiles/test_transition_ocean_coast_r300.svg",
    edges: {
      N: "ocean",
      NE: "ocean",
      SE: "ocean",
      S: "coast",
      SW: "coast",
      NW: "coast"
    }
  },
  {
    src: "/hexTiles/test_transition_plains_desert_r060.svg",
    edges: {
      N: "desert",
      NE: "desert",
      SE: "plains",
      S: "plains",
      SW: "plains",
      NW: "desert"
    }
  },
  {
    src: "/hexTiles/test_transition_plains_desert_r120.svg",
    edges: {
      N: "desert",
      NE: "desert",
      SE: "desert",
      S: "plains",
      SW: "plains",
      NW: "plains"
    }
  },
  {
    src: "/hexTiles/test_transition_plains_desert_r180.svg",
    edges: {
      N: "plains",
      NE: "desert",
      SE: "desert",
      S: "desert",
      SW: "plains",
      NW: "plains"
    }
  },
  {
    src: "/hexTiles/test_transition_plains_desert_r240.svg",
    edges: {
      N: "plains",
      NE: "plains",
      SE: "desert",
      S: "desert",
      SW: "desert",
      NW: "plains"
    }
  },
  {
    src: "/hexTiles/test_transition_plains_desert_r300.svg",
    edges: {
      N: "plains",
      NE: "plains",
      SE: "plains",
      S: "desert",
      SW: "desert",
      NW: "desert"
    }
  },
  {
    src: "/hexTiles/test_transition_plains_hills_r060.svg",
    edges: {
      N: "hills",
      NE: "hills",
      SE: "plains",
      S: "plains",
      SW: "plains",
      NW: "hills"
    }
  },
  {
    src: "/hexTiles/test_transition_plains_hills_r120.svg",
    edges: {
      N: "hills",
      NE: "hills",
      SE: "hills",
      S: "plains",
      SW: "plains",
      NW: "plains"
    }
  },
  {
    src: "/hexTiles/test_transition_plains_hills_r180.svg",
    edges: {
      N: "plains",
      NE: "hills",
      SE: "hills",
      S: "hills",
      SW: "plains",
      NW: "plains"
    }
  },
  {
    src: "/hexTiles/test_transition_plains_hills_r240.svg",
    edges: {
      N: "plains",
      NE: "plains",
      SE: "hills",
      S: "hills",
      SW: "hills",
      NW: "plains"
    }
  },
  {
    src: "/hexTiles/test_transition_plains_hills_r300.svg",
    edges: {
      N: "plains",
      NE: "plains",
      SE: "plains",
      S: "hills",
      SW: "hills",
      NW: "hills"
    }
  },
  {
    src: "/hexTiles/test_transition_plains_swamp_r060.svg",
    edges: {
      N: "swamp",
      NE: "swamp",
      SE: "plains",
      S: "plains",
      SW: "plains",
      NW: "swamp"
    }
  },
  {
    src: "/hexTiles/test_transition_plains_swamp_r120.svg",
    edges: {
      N: "swamp",
      NE: "swamp",
      SE: "swamp",
      S: "plains",
      SW: "plains",
      NW: "plains"
    }
  },
  {
    src: "/hexTiles/test_transition_plains_swamp_r180.svg",
    edges: {
      N: "plains",
      NE: "swamp",
      SE: "swamp",
      S: "swamp",
      SW: "plains",
      NW: "plains"
    }
  },
  {
    src: "/hexTiles/test_transition_plains_swamp_r240.svg",
    edges: {
      N: "plains",
      NE: "plains",
      SE: "swamp",
      S: "swamp",
      SW: "swamp",
      NW: "plains"
    }
  },
  {
    src: "/hexTiles/test_transition_plains_swamp_r300.svg",
    edges: {
      N: "plains",
      NE: "plains",
      SE: "plains",
      S: "swamp",
      SW: "swamp",
      NW: "swamp"
    }
  }
]
