// AUTO-GENERATED by scripts/generateDungeonTiles.ts — do not edit manually.
// Per-material fine-grid trim tiles + door tiles. Trim index scheme (see bitmask.ts):
//   orthogonal sides N=1 E=2 S=4 W=8 → 1..15; outer corners NE=16 SE=17 SW=18 NW=19.
// Index 0 unused. Swap real art by replacing the SVGs (same names) or editing here.

export const TRIM_WALL: string[] = [
  "",
  "/dungeonTiles/wall_trim_1.svg",
  "/dungeonTiles/wall_trim_2.svg",
  "/dungeonTiles/wall_trim_3.svg",
  "/dungeonTiles/wall_trim_4.svg",
  "/dungeonTiles/wall_trim_5.svg",
  "/dungeonTiles/wall_trim_6.svg",
  "/dungeonTiles/wall_trim_7.svg",
  "/dungeonTiles/wall_trim_8.svg",
  "/dungeonTiles/wall_trim_9.svg",
  "/dungeonTiles/wall_trim_10.svg",
  "/dungeonTiles/wall_trim_11.svg",
  "/dungeonTiles/wall_trim_12.svg",
  "/dungeonTiles/wall_trim_13.svg",
  "/dungeonTiles/wall_trim_14.svg",
  "/dungeonTiles/wall_trim_15.svg",
  "/dungeonTiles/wall_trim_16.svg",
  "/dungeonTiles/wall_trim_17.svg",
  "/dungeonTiles/wall_trim_18.svg",
  "/dungeonTiles/wall_trim_19.svg",
]

export const TRIM_WATER: string[] = [
  "",
  "/dungeonTiles/water_trim_1.svg",
  "/dungeonTiles/water_trim_2.svg",
  "/dungeonTiles/water_trim_3.svg",
  "/dungeonTiles/water_trim_4.svg",
  "/dungeonTiles/water_trim_5.svg",
  "/dungeonTiles/water_trim_6.svg",
  "/dungeonTiles/water_trim_7.svg",
  "/dungeonTiles/water_trim_8.svg",
  "/dungeonTiles/water_trim_9.svg",
  "/dungeonTiles/water_trim_10.svg",
  "/dungeonTiles/water_trim_11.svg",
  "/dungeonTiles/water_trim_12.svg",
  "/dungeonTiles/water_trim_13.svg",
  "/dungeonTiles/water_trim_14.svg",
  "/dungeonTiles/water_trim_15.svg",
  "/dungeonTiles/water_trim_16.svg",
  "/dungeonTiles/water_trim_17.svg",
  "/dungeonTiles/water_trim_18.svg",
  "/dungeonTiles/water_trim_19.svg",
]

export const DOOR_TILES = { n: "/dungeonTiles/door_n.svg", s: "/dungeonTiles/door_s.svg", e: "/dungeonTiles/door_e.svg", w: "/dungeonTiles/door_w.svg" }

export const PILLAR_TILE = "/dungeonTiles/pillar.svg"

export const STAIR_TILES = { n: "/dungeonTiles/stairs_n.svg", s: "/dungeonTiles/stairs_s.svg", e: "/dungeonTiles/stairs_e.svg", w: "/dungeonTiles/stairs_w.svg" }

export const PORTAL_TILES = { entrance: "/dungeonTiles/portal_entrance.svg", exit: "/dungeonTiles/portal_exit.svg" }

// Rounded room-corner tiles (overlay above base, below wall-detail), keyed by the outer corner
// rounded off (nw/ne/se/sw). ROUND_CORNER = the wall-colour bite (transparent inside the arc).
export const ROUND_CORNER_TILES = { nw: "/dungeonTiles/round_corner_nw.svg", ne: "/dungeonTiles/round_corner_ne.svg", se: "/dungeonTiles/round_corner_se.svg", sw: "/dungeonTiles/round_corner_sw.svg" }

// Arc-lip tiles, nested [orient][radius] (radius 1..4 — stroke width scales so the lip stays ~constant).
export const ROUND_TRIM_TILES = {
  nw: { 1: "/dungeonTiles/round_trim_nw_r1.svg", 2: "/dungeonTiles/round_trim_nw_r2.svg", 3: "/dungeonTiles/round_trim_nw_r3.svg", 4: "/dungeonTiles/round_trim_nw_r4.svg" },
  ne: { 1: "/dungeonTiles/round_trim_ne_r1.svg", 2: "/dungeonTiles/round_trim_ne_r2.svg", 3: "/dungeonTiles/round_trim_ne_r3.svg", 4: "/dungeonTiles/round_trim_ne_r4.svg" },
  se: { 1: "/dungeonTiles/round_trim_se_r1.svg", 2: "/dungeonTiles/round_trim_se_r2.svg", 3: "/dungeonTiles/round_trim_se_r3.svg", 4: "/dungeonTiles/round_trim_se_r4.svg" },
  sw: { 1: "/dungeonTiles/round_trim_sw_r1.svg", 2: "/dungeonTiles/round_trim_sw_r2.svg", 3: "/dungeonTiles/round_trim_sw_r3.svg", 4: "/dungeonTiles/round_trim_sw_r4.svg" },
}
