import { readdirSync, writeFileSync } from "node:fs"
import { join, extname } from "node:path"
import { detectCorners, CORNER_NAMES, ROOT } from "./detectHexTiles.js"
import type { HexCorner, TerrainType } from "./detectHexTiles.js"

// Generates a corner-based tile config for the Hex Transitions refactor.
// Every SVG in public/hexTiles/ (sources + rotations, all already on disk) is
// rasterized and sampled at its 6 corners — no pair-collapsing — so the config
// carries the full transition information corner matching needs.

const tilesDir = join(ROOT, "public/hexTiles")
const outPath  = join(ROOT, "src/refactorHexTransitions/tileConfig.ts")

const files = readdirSync(tilesDir)
  .filter(f => extname(f) === ".svg")
  .sort()

if (files.length === 0) {
  console.log("No SVG tiles found in public/hexTiles/")
  process.exit(0)
}

const tiles: Array<{ src: string; corners: Record<HexCorner, TerrainType> }> = []
let failed = 0

for (const file of files) {
  const corners = detectCorners(join(tilesDir, file))
  if (!corners) { console.error(`  SKIP: ${file} (detection failed)`); failed++; continue }
  tiles.push({ src: `/hexTiles/${file}`, corners })
  console.log(`  ${file}: [${CORNER_NAMES.map(c => corners[c]).join(",")}]`)
}

const entries = tiles.map(({ src, corners }) => {
  const cornerLines = CORNER_NAMES.map(c => `      ${c}: "${corners[c]}"`).join(",\n")
  return `  {\n    src: "${src}",\n    corners: {\n${cornerLines}\n    }\n  }`
})

const output = `\
// AUTO-GENERATED by scripts/generateHexTransitionsConfig.ts — do not edit manually

import type { TerrainType, HexCorner } from "./types"

export type TileConfig = {
  src: string
  corners: Record<HexCorner, TerrainType>
}

export const TILES: TileConfig[] = [
${entries.join(",\n")}
]
`

writeFileSync(outPath, output, "utf-8")
console.log(`\nDone: ${tiles.length} tile(s) → src/refactorHexTransitions/tileConfig.ts${failed ? ` (${failed} failed)` : ""}`)
