import { writeFileSync, mkdirSync, readdirSync, rmSync } from "node:fs"
import { join, dirname } from "node:path"
import { fileURLToPath } from "node:url"
import { TRIM_STYLE } from "../src/refactorGeomorphs/geomorph-dungeon/materials.js"

// Generates PLACEHOLDER wall-detail "trim" tiles (per material) + door tiles for
// the multi-material dungeon geomorph. The detail layer is a fine sub-grid; a
// floor sub-cell touching an edge-material renders a trim lip that bumps into the
// room. Index scheme (see bitmask.ts, must stay in sync):
//   orthogonal sides  N=1 E=2 S=4 W=8  → index 1..15
//   outer corners (diagonal-only)  NE=16 SE=17 SW=18 NW=19
// Straight edges fill the sub-cell (prominent strips); outer corners fill one
// 50×50 quadrant (small nubs). Room-facing sides get a lighter bevel.
//
// Real art later: replace public/dungeonTiles/<name>_trim_<n>.svg / door_*.svg
// (same names, SVG or PNG) or edit the generated manifest — no app-code change.

const __dirname = dirname(fileURLToPath(import.meta.url))
const ROOT = join(__dirname, "..")
const OUT_DIR = join(ROOT, "public/dungeonTiles")
const CONFIG_PATH = join(ROOT, "src/refactorGeomorphs/geomorph-dungeon/tileConfig.ts")

const V = 100 // tile viewBox
const BW = 22 // bevel strip width

const rect = (x: number, y: number, w: number, h: number, fill: string) =>
  `<rect x="${x}" y="${y}" width="${w}" height="${h}" fill="${fill}"/>`

function orthoTile(mask: number, body: string, bevel: string): string {
  const parts = [rect(0, 0, V, V, body)]
  if (mask & 1) parts.push(rect(0, V - BW, V, BW, bevel)) // wall N → bevel S
  if (mask & 2) parts.push(rect(0, 0, BW, V, bevel))      // wall E → bevel W
  if (mask & 4) parts.push(rect(0, 0, V, BW, bevel))      // wall S → bevel N
  if (mask & 8) parts.push(rect(V - BW, 0, BW, V, bevel)) // wall W → bevel E
  return parts.join("\n  ")
}

function cornerTile(index: number, body: string, bevel: string): string {
  const H = V / 2
  const map: Record<number, [number, number]> = {
    16: [H, 0], 17: [H, H], 18: [0, H], 19: [0, 0], // NE, SE, SW, NW quadrant origin
  }
  const [qx, qy] = map[index]
  const innerX = qx === 0 ? H - BW : H
  const innerY = qy === 0 ? H - BW : H
  return [
    rect(qx, qy, H, H, body),
    rect(innerX, qy, BW, H, bevel),
    rect(qx, innerY, H, BW, bevel),
  ].join("\n  ")
}

const wrap = (inner: string) =>
  `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${V} ${V}">\n  ${inner}\n</svg>\n`

// Door: a plain brown line (top-down door leaf), flush to one edge of the cell so
// it aligns with the wall at the room threshold. ~8px thick (wall-detail size).
function doorTile(edge: "n" | "s" | "e" | "w"): string {
  const DOOR = "#8a5a2b", T = 24
  const r = {
    n: rect(0, 0, V, T, DOOR),
    s: rect(0, V - T, V, T, DOOR),
    w: rect(0, 0, T, V, DOOR),
    e: rect(V - T, 0, T, V, DOOR),
  }[edge]
  return wrap(r)
}

// Pillar: a stone dot (rendered at S/2, centered on a base-grid vertex).
function pillarTile(): string {
  return wrap(`<circle cx="${V / 2}" cy="${V / 2}" r="46" fill="#6b7280" stroke="#3a3f4b" stroke-width="6"/>`)
}

mkdirSync(OUT_DIR, { recursive: true })
for (const f of readdirSync(OUT_DIR)) {
  if (/^(corner_|trim_|wall_trim_|water_trim_|door_|pillar)/.test(f)) rmSync(join(OUT_DIR, f))
}

// Per-material trim sets (index 0 unused).
const trimArrays: Record<string, string[]> = {}
for (const name of Object.keys(TRIM_STYLE) as ("wall" | "water")[]) {
  const { body, bevel } = TRIM_STYLE[name]
  const srcs: string[] = new Array(20).fill("")
  for (let i = 1; i <= 19; i++) {
    const inner = i <= 15 ? orthoTile(i, body, bevel) : cornerTile(i, body, bevel)
    const file = `${name}_trim_${i}.svg`
    writeFileSync(join(OUT_DIR, file), wrap(inner), "utf-8")
    srcs[i] = `/dungeonTiles/${file}`
  }
  trimArrays[name] = srcs
}

// Door tiles — one per edge (line flush to that edge).
for (const edge of ["n", "s", "e", "w"] as const) {
  writeFileSync(join(OUT_DIR, `door_${edge}.svg`), doorTile(edge), "utf-8")
}

// Pillar tile.
writeFileSync(join(OUT_DIR, "pillar.svg"), pillarTile(), "utf-8")

const arrLiteral = (a: string[]) => `[\n${a.map(s => `  "${s}",`).join("\n")}\n]`
const config = `// AUTO-GENERATED by scripts/generateDungeonTiles.ts — do not edit manually.
// Per-material fine-grid trim tiles + door tiles. Trim index scheme (see bitmask.ts):
//   orthogonal sides N=1 E=2 S=4 W=8 → 1..15; outer corners NE=16 SE=17 SW=18 NW=19.
// Index 0 unused. Swap real art by replacing the SVGs (same names) or editing here.

export const TRIM_WALL: string[] = ${arrLiteral(trimArrays.wall)}

export const TRIM_WATER: string[] = ${arrLiteral(trimArrays.water)}

export const DOOR_TILES = { n: "/dungeonTiles/door_n.svg", s: "/dungeonTiles/door_s.svg", e: "/dungeonTiles/door_e.svg", w: "/dungeonTiles/door_w.svg" }

export const PILLAR_TILE = "/dungeonTiles/pillar.svg"
`
mkdirSync(dirname(CONFIG_PATH), { recursive: true })
writeFileSync(CONFIG_PATH, config, "utf-8")

console.log("Done: wall+water trim (19 each) + 4 door tiles + pillar → public/dungeonTiles/ + tileConfig.ts")
