// AUTO-GENERATED by scripts/generateDungeonTiles.ts — do not edit manually.
// Per-material fine-grid trim tiles + door tiles. Trim index scheme (see bitmask.ts):
//   orthogonal sides N=1 E=2 S=4 W=8 → 1..15; outer corners NE=16 SE=17 SW=18 NW=19.
// Index 0 unused. Swap real art by replacing the SVGs (same names) or editing here.

export const TRIM_WALL: string[] = [
  "",
  "/dungeonTiles/wall_trim_1.svg",
  "/dungeonTiles/wall_trim_2.svg",
  "/dungeonTiles/wall_trim_3.svg",
  "/dungeonTiles/wall_trim_4.svg",
  "/dungeonTiles/wall_trim_5.svg",
  "/dungeonTiles/wall_trim_6.svg",
  "/dungeonTiles/wall_trim_7.svg",
  "/dungeonTiles/wall_trim_8.svg",
  "/dungeonTiles/wall_trim_9.svg",
  "/dungeonTiles/wall_trim_10.svg",
  "/dungeonTiles/wall_trim_11.svg",
  "/dungeonTiles/wall_trim_12.svg",
  "/dungeonTiles/wall_trim_13.svg",
  "/dungeonTiles/wall_trim_14.svg",
  "/dungeonTiles/wall_trim_15.svg",
  "/dungeonTiles/wall_trim_16.svg",
  "/dungeonTiles/wall_trim_17.svg",
  "/dungeonTiles/wall_trim_18.svg",
  "/dungeonTiles/wall_trim_19.svg",
]

export const TRIM_WATER: string[] = [
  "",
  "/dungeonTiles/water_trim_1.svg",
  "/dungeonTiles/water_trim_2.svg",
  "/dungeonTiles/water_trim_3.svg",
  "/dungeonTiles/water_trim_4.svg",
  "/dungeonTiles/water_trim_5.svg",
  "/dungeonTiles/water_trim_6.svg",
  "/dungeonTiles/water_trim_7.svg",
  "/dungeonTiles/water_trim_8.svg",
  "/dungeonTiles/water_trim_9.svg",
  "/dungeonTiles/water_trim_10.svg",
  "/dungeonTiles/water_trim_11.svg",
  "/dungeonTiles/water_trim_12.svg",
  "/dungeonTiles/water_trim_13.svg",
  "/dungeonTiles/water_trim_14.svg",
  "/dungeonTiles/water_trim_15.svg",
  "/dungeonTiles/water_trim_16.svg",
  "/dungeonTiles/water_trim_17.svg",
  "/dungeonTiles/water_trim_18.svg",
  "/dungeonTiles/water_trim_19.svg",
]

export const DOOR_TILES = { n: "/dungeonTiles/door_n.svg", s: "/dungeonTiles/door_s.svg", e: "/dungeonTiles/door_e.svg", w: "/dungeonTiles/door_w.svg" }

export const PILLAR_TILE = "/dungeonTiles/pillar.svg"
