import { Alignment, Gender } from "../../character/Character";
import { MaterialGroup } from "../../names/enums";

export enum Tags {
    Creature = 'creature',
    Underground = 'underground',
    Undead = 'undead',
    Material = 'material',
}

const {
    Creature,
    Underground,
    Undead,
    Material,
} = Tags

export enum age {
    New = 'new',
    Old = 'old',
    Ancient = 'ancient'
}

export enum Condition {
    Damaged = 'damaged'
}

const { Metal, Wood, Mineral, Stone, Gem } = MaterialGroup
const { Evil, Good, Neutral } = Alignment

export const creature_underground = [
    ['Troglodyte', [Creature, Underground], 1],
    ['Drow', [Creature, Underground], 1],
    ['Carrion Crawler', [Creature, Underground], 1],
    ['Piercer', [Creature, Underground], 1]
];

export const creature_undead = [
    ['Skeleton', [Creature, Undead], 1],
    ['Zombie', [Creature, Undead], 1],
    ['Ghoul', [Creature, Undead], 1],
    ['Ghost', [Creature, Undead], 1],
    ['Wight', [Creature, Undead], 1],
    ['Wraith', [Creature, Undead], 1],
    ['Spectre', [Creature, Undead], 1]
];

export const creature_humanoid = [
    ['Dwarf', [], 1],
    ['Elf', [], 1],
    ['Gnome', [], 1],
    ['Halfing', [], 1],
    ['Drow', [], 1]
];

export const creature_goblinoid = [
    ['Troll', [], 1],
    ['Ogre', [], 1],
    ['Gnoll', [], 1],
    ['Bugbear', [], 1],
    ['Hobgoblin', [], 1],
    ['Orc', [], 1],
    ['Goblin', [], 1],
    ['Kobold', [], 1],
    ['Cyclops', [], 1],
    ['Minotaur', [], 1],
    ['Troglodyte', [], 1]
];

export const creature_animal = [
    ['Rat', [], 1],
    ['Raven', [], 1],
    ['Frog', [], 1],
    ['Serpent', [], 1],
    ['Leech', [], 1],
    ['Bat', [], 1],
    ['Bear', [], 1]
];

export const creature_insect = [
    ['Spider', [], 1],
    ['Ant', [], 1]
];

export const creature_medium = [
    ['Gargoyle', [], 1],
    ['Golem', [], 1],
    ['Demon', [], 1],
    ['Devil', [], 1],
    ['Carrion Crawler', [], 1]
];

export const creature_large = [
    ['Dragon', [], 1],
    ['Wyrm', [], 1],
    ['Sphinx', [], 1],
    ['Hydra', [], 1],
    ['Griffon', [], 1],
    ['Giant', [], 1]
];

export const creature_small = [
    ['Imp', [], 1],
    ['Spore', [], 1],
    ['Stirge', [], 1],
    ['Piercer', [], 1]
];



// COLORS
export const color = [
    ['Azure', [], 1],
    ['Cobalt', [], 1],
    ['Verdigris', [], 1],
    ['Pale', [], 1],
    ['Dark', [], 1],
    ['Dim', [], 1],
    ['Umber', [], 1],
    ['Amber', [], 1],
    ['Burgundy', [], 1],
    ['Crimson', [], 1],
    ['Ocher', [], 1],
    ['Rainbow', [], 1],
    ['Magenta', [], 1],
    ['Cyan', [], 1],
    ['Gray', [], 1],
    ['Black', [], 1],
    ['White', [], 1],
    ['Red', [], 1],
    ['Blue', [], 1],
    ['Green', [], 1],
    ['Orange', [], 1],
    ['Violet', [], 1],
    ['Yellow', [], 1],
    ['Sepia', [], 1],
    ['Cerulean', [], 1],
    ['Alizerin', [], 1],
    ['Ebon', [], 1],
    ['Veridian', [], 1],
    ['Dun', [], 1]
];

// EMOTIVE
export const emotive_evil = [
    ['Creepy', [Evil], 1],
    ['Vile', [Evil], 1],
    ['Cursed', [Evil], 1],
    ['Toxic', [Evil], 1],
    ['Noxious', [Evil], 1],
    ['Putrid', [Evil], 1],
    ['Pitch Black', [Evil], 1],
    ['Desecrated', [Evil], 1],
    ['Awful', [Evil], 1],
    ['Demonic', [Evil], 1],
    ['Infernal', [Evil], 1],
    ['Dire', [Evil], 1],
    ['Grim', [Evil], 1],
    ['Rancid', [Evil], 1],
    ['Foul', [Evil], 1],
    ['Dreary', [Evil], 1],
    ['Abyssal', [Evil], 1],
    ['Corrupted', [Evil], 1],
    ['Contaminated', [Evil], 1],
    ['Diabolic', [Evil], 1],
    ['Cruel', [Evil], 1],
    ['Wretched', [Evil], 1],
    ['Fetid', [Evil], 1],
    ['Unnatural', [Evil], 1],
    ['Infested', [Evil], 1],
    ['Sinister', [Evil], 1],
    ['Suspicious', [Evil], 1],
    ['Defiled', [Evil], 1],
    ['Insidious', [Evil], 1],
    ['Blackflame', [Evil], 1],
    ['Dismal', [Evil], 1],
    ['Gloomy', [Evil], 1],
    ['Murky', [Evil], 1]
];


export const emotive_good = [
    ['Celestial', [Good], 1],
    ['Holy', [Good], 1],
    ['Sacred', [Good], 1],
    ['Consecrated', [Good], 1],
    ['Pure', [Good], 1],
    ['Great', [Good], 1],
    ['Angelic', [Good], 1],
    ['Regal', [Good], 1],
    ['Heraldic', [Good], 1],
    ['Imperial', [Good], 1],
    ['Royal', [Good], 1],
    ['Blessed', [Good], 1],
    ['Ancestral', [Good], 1],
    ['Mystic', [Good], 1],
    ['Tranquil', [Good], 1]
];


export const emotive_neutral = [
    ['Weird', [Neutral], 1],
    ['Mysterious', [Neutral], 1],
    ['Cryptic', [Neutral], 1],
    ['Lunar', [Neutral], 1],
    ['Elder', [Neutral], 1],
    ['Fey', [Neutral], 1],
    ['Eldritch', [Neutral], 1],
    ['Lonely', [Neutral], 1],
    ['Strange', [Neutral], 1],
    ['Wondrous', [Neutral], 1],
    ['Arcane', [Neutral], 1],
    ['Enchanted', [Neutral], 1],
    ['Eerie', [Neutral], 1],
    ['Quiet', [Neutral], 1],
    ['Obscure', [Neutral], 1],
    ['Disenchanted', [Neutral], 1],
    ['Ingenious', [Neutral], 1]
];


// MATERIAL

export const material_misc = [
    ['Alabaster', [Material], 1],
    ['Bone', [Material], 1],
    ['Dung', [Material], 1],
    ['Sand', [Material], 1],
    ['Salt', [Material], 1],
    ['Glass', [Material], 1],
    ['Brimstone', [Material], 1],
    ['Sulphur', [Material], 1],
    ['Brine', [Material], 1],
    ['Ambergris', [Material], 1],
    ['Fungal', [Material], 1],
    ['Mud', [Material], 1],
    ['Pitch', [Material], 1],
    ['Sludge', [Material], 1],
    ['Parchment', [Material], 1],
    ['Woven', [Material], 1],
    ['Silk', [Material], 1],
    ['Wax', [Material], 1],
    ['Brick', [Material], 1],
    ['Ash', [Material], 1],
    ['Thatch', [Material], 1],
    ['Tar', [Material], 1],
    ['Porcelain', [Material], 1],
    ['Leather', [Material], 1],
    ['Slag', [Material], 1],
    ['Shale', [Material], 1],
    ['Coal', [Material], 1],
    ['Plaster', [Material], 1],
    ['Clay', [Material], 1],
    ['Straw', [Material], 1],
    ['Tephra', [Material], 1],
    ['Charcoal', [Material], 1],
    ['Lotus', [Material], 1],
    ['Papyrus', [Material], 1],
    ['Muck', [Material], 1],
    ['Steam', [Material], 1],
    ['Smog', [Material], 1],
    ['Blood', [Material], 1],
    ['Fog', [Material], 1],
    ['Ice', [Material], 1]
];

export const saltwater_material = [
    ['Salt', [], 1],
    ['Glass', [], 1],
    ['Blood', [], 1],
    ['Fog', [], 1],
    ['Brine', [], 1],
    ['Ice', [], 1],
    ['Silver', [], 1],
    ['Emerald', [], 1],
    ['Jade', [], 1],
    ['Onyx', [], 1],
    ['Ruby', [], 1],
    ['Topaz', [], 1],
    ['Crystal', [], 1],
    ['Sapphire', [], 1],
    ['Amethyst', [], 1],
    ['Coral', [], 1],
    ['Ivory', [], 1],
    ['Turquoise', [], 1],
    ['Opal', [], 1]
];

export const material_stone = [
    ['Obsidian', [Material, Stone], 1],
    ['Granite', [Material, Stone], 1],
    ['Marble', [Material, Stone], 1],
    ['Flint', [Material, Stone], 1],
    ['Flowstone', [Material, Stone], 1],
    ['Limestone', [Material, Stone], 1],
    ['Sandstone', [Material, Stone], 1],
    ['Basalt', [Material, Stone], 1],
    ['Concrete', [Material, Stone], 1],
    ['Igneous', [Material, Stone], 1],
    ['Greenstone', [Material, Stone], 1]
];

export const material_metal = [
    ['Brass', [Material, Metal], 1],
    ['Copper', [Material, Metal], 1],
    ['Iron', [Material, Metal], 1],
    ['Silver', [Material, Metal], 1],
    ['Mithril', [Material, Metal], 1],
    ['Platinum', [Material, Metal], 1],
    ['Bronze', [Material, Metal], 1],
    ['Steel', [Material, Metal], 1],
    ['Gold', [Material, Metal], 1],
    ['Lead', [Material, Metal], 1],
    ['Alloy', [Material, Metal], 1],
    ['Adamantite', [Material, Metal], 1]
];

export const material_gemstone = [
    ['Emerald', [Material, Gem], 1],
    ['Jade', [Material, Gem], 1],
    ['Onyx', [Material, Gem], 1],
    ['Ruby', [Material, Gem], 1],
    ['Topaz', [Material, Gem], 1],
    ['Crystal', [Material, Gem], 1],
    ['Sapphire', [Material, Gem], 1],
    ['Amethyst', [Material, Gem], 1],
    ['Garnet', [Material, Gem], 1],
    ['Coral', [Material, Gem], 1],
    ['Beryl', [Material, Gem], 1],
    ['Lapis', [Material, Gem], 1],
    ['Ivory', [Material, Gem], 1],
    ['Turquoise', [Material, Gem], 1],
    ['Ambergris', [Material, Gem], 1],
    ['Opal', [Material, Gem], 1],
    ['Greenstone', [Material, Gem], 1],
    ['Bloodstone', [Material, Gem], 1]
];

export const material_wood = [
    ['Oaken', [Material, Wood], 1],
    ['Cedar', [Material, Wood], 1],
    ['Ash', [Material, Wood], 1],
    ['Wooden', [Material, Wood], 1],
    ['Redwood', [Material, Wood], 1],
    ['Mahogany', [Material, Wood], 1]
];


// CONDITION & EFFECT

export const mountain_condition = [
    ['Grand', [], 1],
    ['Pristine', [], 1],
    ['Terraced', [], 1],
    ['Shattered', [], 1],
    ['Broken', [], 1],
    ['Fallen', [], 1],
    ['Crumbling', [], 1],
    ['Splintered', [], 1],
    ['Worn', [], 1],
    ['Collapsed', [], 1],
    ['Scorched', [], 1],
    ['Unstable', [], 1],
    ['Weathered', [], 1],
    ['Warped', [], 1],
    ['Rusty', [], 1],
    ['Sunken', [], 1],
    ['Tangled', [], 1],
    ['Twisted', [], 1],
    ['Tarnished', [], 1],
    ['Sinking', [], 1],
    ['Smoldering', [], 1],
    ['Odious', [], 1],
    ['Moldy', [], 1],
    ['Eroded', [], 1],
    ['Overgrown', [], 1],
    ['Lost', [], 1],
    ['Ancient', [], 1],
    ['Bald', [], 1],
    ['Hollow', [], 1],
    ['Forgotten', [], 1],
    ['Jagged', [], 1],
    ['Cloudy', [], 1],
    ['Foggy', [], 1],
    ['Wrinkled', [], 1],
    ['Mossy', [], 1],
    ['Drifting', [], 1],
    ['Looming', [], 1],
    ['Lurking', [], 1],
    ['Remote', [], 1],
    ['Barbed', [], 1],
    ['Shrouded', [], 1],
    ['Thermal', [], 1],
    ['Crested', [], 1],
    ['Spined', [], 1],
    ['Serrated', [], 1],
    ['Forsaken', [], 1],
    ['Dormant', [], 1]
];

export const mountain_effect = [
    ['Glowing', [], 1],
    ['Shimmering', [], 1],
    ['Levitating', [], 1],
    ['Wandering', [], 1],
    ['Endless', [], 1],
    ['Drifting', [], 1],
    ['Radiant', [], 1],
    ['Howling', [], 1],
    ['Screaming', [], 1],
    ['Inverted', [], 1],
    ['Whispering', [], 1],
    ['Frozen', [], 1],
    ['Colossal', [], 1],
    ['Cursed', [], 1],
    ['Haunted', [], 1],
    ['Withering', [], 1],
    ['Creeping', [], 1],
    ['Magnetic', [], 1],
    ['Luminous', [], 1],
    ['Irridescent', [], 1],
    ['Jeweled', [], 1],
    ['Ghostly', [], 1],
    ['Caustic', [], 1],
    ['Shifting', [], 1],
    ['Whirling', [], 1],
    ['Spiraling', [], 1]
];


export const forest_condition = [
    ['Pristine', [], 1],
    ['Shattered', [], 1],
    ['Fallen', [], 1],
    ['Splintered', [], 1],
    ['Scorched', [], 1],
    ['Decayed', [], 1],
    ['Warped', [], 1],
    ['Rotting', [], 1],
    ['Sunken', [], 1],
    ['Tangled', [], 1],
    ['Twisted', [], 1],
    ['Tarnished', [], 1],
    ['Sinking', [], 1],
    ['Smoldering', [], 1],
    ['Flooded', [], 1],
    ['Moldy', [], 1],
    ['Eroded', [], 1],
    ['Overgrown', [], 1],
    ['Lost', [], 1],
    ['Mottled', [], 1],
    ['Ancient', [], 1],
    ['Forgotten', [], 1],
    ['Abandoned', [], 1],
    ['Jagged', [], 1],
    ['Cloudy', [], 1],
    ['Foggy', [], 1],
    ['Mossy', [], 1],
    ['Barbed', [], 1],
    ['Shrouded', [], 1],
    ['Spined', [], 1],
    ['Serrated', [], 1],
    ['Forsaken', [], 1],
    ['Nocturnal', [], 1]
];

export const forest_effect = [
    ['Shimmering', [], 1],
    ['Hidden', [], 1],
    ['Ethereal', [], 1],
    ['Floating', [], 1],
    ['Wandering', [], 1],
    ['Endless', [], 1],
    ['Howling', [], 1],
    ['Screaming', [], 1],
    ['Poison', [], 1],
    ['Whispering', [], 1],
    ['Frozen', [], 1],
    ['Cursed', [], 1],
    ['Haunted', [], 1],
    ['Withering', [], 1],
    ['Creeping', [], 1],
    ['Luminous', [], 1],
    ['Polluted', [], 1],
    ['Phantasmal', [], 1],
    ['Ghostly', [], 1],
    ['Primordial', [], 1],
    ['Spectral', [], 1]
];

export const swamp_condition = [
    ['Decayed', [], 1],
    ['Rotting', [], 1],
    ['Sunken', [], 1],
    ['Tangled', [], 1],
    ['Twisted', [], 1],
    ['Sinking', [], 1],
    ['Smoldering', [], 1],
    ['Flooded', [], 1],
    ['Odious', [], 1],
    ['Moldy', [], 1],
    ['Overgrown', [], 1],
    ['Drained', [], 1],
    ['Lost', [], 1],
    ['Ancient', [], 1],
    ['Forgotten', [], 1],
    ['Foggy', [], 1],
    ['Veiled', [], 1],
    ['Mossy', [], 1],
    ['Slippery', [], 1],
    ['Remote', [], 1],
    ['Dry', [], 1],
    ['Squirming', [], 1],
    ['Shrouded', [], 1],
    ['Shallow', [], 1],
    ['Forsaken', [], 1],
    ['Nocturnal', [], 1],

    ['Peat', [], 1],
    ['Pitch', [], 1],
    ['Mud', [], 1],
    ['Sludge', [], 1],
    ['Muddy', [], 1],
    ['Stump', [], 1]
];

export const swamp_effect = [
    ['Glowing', [], 1],
    ['Shimmering', [], 1],
    ['Endless', [], 1],
    ['Howling', [], 1],
    ['Screaming', [], 1],
    ['Poison', [], 1],
    ['Whispering', [], 1],
    ['Cursed', [], 1],
    ['Haunted', [], 1],
    ['Withering', [], 1],
    ['Creeping', [], 1],
    ['Polluted', [], 1],
    ['Ghostly', [], 1],
    ['Caustic', [], 1],
    ['Boiling', [], 1],
    ['Primordial', [], 1],
    ['Spectral', [], 1]
];

export const hills_condition = [
    ['Terraced', [], 1],
    ['Crumbling', [], 1],
    ['Splintered', [], 1],
    ['Worn', [], 1],
    ['Scorched', [], 1],
    ['Decayed', [], 1],
    ['Weathered', [], 1],
    ['Rotting', [], 1],
    ['Sunken', [], 1],
    ['Twisted', [], 1],
    ['Sinking', [], 1],
    ['Smoldering', [], 1],
    ['Moldy', [], 1],
    ['Eroded', [], 1],
    ['Overgrown', [], 1],
    ['Dusty', [], 1],
    ['Lost', [], 1],
    ['Bald', [], 1],
    ['Hollow', [], 1],
    ['Forgotten', [], 1],
    ['Jagged', [], 1],
    ['Foggy', [], 1],
    ['Wrinkled', [], 1],
    ['Mossy', [], 1],
    ['Slippery', [], 1],
    ['Remote', [], 1],
    ['Dry', [], 1],
    ['Shrouded', [], 1],
    ['Crested', [], 1],
    ['Forsaken', [], 1]
];

export const hills_effect = [
    ['Glowing', [], 1],
    ['Hidden', [], 1],
    ['Wandering', [], 1],
    ['Endless', [], 1],
    ['Drifting', [], 1],
    ['Howling', [], 1],
    ['Screaming', [], 1],
    ['Whispering', [], 1],
    ['Frozen', [], 1],
    ['Cursed', [], 1],
    ['Haunted', [], 1],
    ['Withering', [], 1],
    ['Creeping', [], 1],
    ['Hovering', [], 1],
    ['Ghostly', [], 1],
    ['Shifting', [], 1]
];

export const tower_condition = [
    ['Grand', [], 1],
    ['Ornate', [], 1],
    ['Engraved', [], 1],
    ['Warded', [], 1],
    ['Concentric', [], 1],
    ['Gilded', [], 1],
    ['Sealed', [], 1],
    ['Shattered', [], 1],
    ['Broken', [], 1],
    ['Fallen', [], 1],
    ['Crumbling', [], 1],
    ['Splintered', [], 1],
    ['Collapsed', [], 1],
    ['Scorched', [], 1],
    ['Decayed', [], 1],
    ['Weathered', [], 1],
    ['Warped', [], 1],
    ['Rotting', [], 1],
    ['Rusty', [], 1],
    ['Sunken', [], 1],
    ['Tangled', [], 1],
    ['Twisted', [], 1],
    ['Tarnished', [], 1],
    ['Sinking', [], 1],
    ['Smoldering', [], 1],
    ['Flooded', [], 1],
    ['Pilfered', [], 1],
    ['Moldy', [], 1],
    ['Rusting', [], 1],
    ['Dusty', [], 1],
    ['Lost', [], 1],
    ['Ancient', [], 1],
    ['Forgotten', [], 1],
    ['Abandoned', [], 1],
    ['Jagged', [], 1],
    ['Unfinished', [], 1],
    ['Renovated', [], 1],
    ['Repaired', [], 1],
    ['Foggy', [], 1],
    ['Veiled', [], 1],
    ['Rebuilt', [], 1],
    ['Mossy', [], 1],
    ['Drifting', [], 1],
    ['Looming', [], 1],
    ['Remote', [], 1],
    ['Barbed', [], 1],
    ['Shrouded', [], 1],
    ['Crested', [], 1],
    ['Spined', [], 1],
    ['Spiked', [], 1],
    ['Serrated', [], 1],
    ['Scaled', [], 1],
    ['Forsaken', [], 1],
    ['Cyclopean', [], 1]
];

export const tower_effect = [
    ['Clockwork', [], 1],
    ['Glowing', [], 1],
    ['Shimmering', [], 1],
    ['Hidden', [], 1],
    ['Secret', [], 1],
    ['Invisible', [], 1],
    ['Ethereal', [], 1],
    ['Floating', [], 1],
    ['Levitating', [], 1],
    ['Prismatic', [], 1],
    ['Wandering', [], 1],
    ['Drifting', [], 1],
    ['Blinking', [], 1],
    ['Radiant', [], 1],
    ['Howling', [], 1],
    ['Screaming', [], 1],
    ['Burning', [], 1],
    ['Electric', [], 1],
    ['Spinning', [], 1],
    ['Secure', [], 1],
    ['Locked', [], 1],
    ['Inverted', [], 1],
    ['Whispering', [], 1],
    ['Frozen', [], 1],
    ['Cursed', [], 1],
    ['Haunted', [], 1],
    ['Creeping', [], 1],
    ['Luminous', [], 1],
    ['Iridescent', [], 1],
    ['Hovering', [], 1],
    ['Phantasmal', [], 1],
    ['Jeweled', [], 1],
    ['Trapped', [], 1],
    ['Ghostly', [], 1],
    ['Spectral', [], 1],
    ['Whirling', [], 1],
    ['Spiraling', [], 1],
    ['Concealed', [], 1]
];

export const ocean_condition = [
    ['Sunken', [], 1],
    ['Squirming', [], 1],
    ['Shallow', [], 1]
];

export const ocean_effect = [
    ['Shimmering', [], 1],
    ['Ethereal', [], 1],
    ['Endless', [], 1],
    ['Drifting', [], 1],
    ['Howling', [], 1],
    ['Cursed', [], 1],
    ['Bottomless', [], 1],
    ['Boiling', [], 1]
];

export const lake_condition = [
    ['Pristine', [], 1],
    ['Rotting', [], 1],
    ['Sunken', [], 1],
    ['Sinking', [], 1],
    ['Smoldering', [], 1],
    ['Flooded', [], 1],
    ['Moldy', [], 1],
    ['Eroded', [], 1],
    ['Overgrown', [], 1],
    ['Lost', [], 1],
    ['Forgotten', [], 1],
    ['Foggy', [], 1],
    ['Veiled', [], 1],
    ['Mossy', [], 1],
    ['Remote', [], 1],
    ['Dry', [], 1],
    ['Shrouded', [], 1],
    ['Thermal', [], 1],

    ['Shallow', [], 1],
    ['Forsaken', [], 1]
];

export const lake_effect = [
    ['Glowing', [], 1],
    ['Shimmering', [], 1],
    ['Hidden', [], 1],
    ['Prismatic', [], 1],
    ['Screaming', [], 1],
    ['Poison', [], 1],
    ['Whispering', [], 1],
    ['Frozen', [], 1],
    ['Cursed', [], 1],
    ['Haunted', [], 1],
    ['Luminous', [], 1],
    ['Polluted', [], 1],
    ['Iridescent', [], 1],
    ['Ghostly', [], 1],
    ['Bottomless', [], 1],
    ['Caustic', [], 1],
    ['Boiling', [], 1]
];

export const cave_condition = [
    ['Grand', [], 1],
    ['Pristine', [], 1],
    ['Terraced', [], 1],
    ['Sealed', [], 1],
    ['Fallen', [], 1],
    ['Crumbling', [], 1],
    ['Worn', [], 1],
    ['Collapsed', [], 1],
    ['Scorched', [], 1],
    ['Unstable', [], 1],
    ['Defaced', [], 1],
    ['Weathered', [], 1],
    ['Warped', [], 1],
    ['Rotting', [], 1],
    ['Rusty', [], 1],
    ['Sunken', [], 1],
    ['Twisted', [], 1],
    ['Sinking', [], 1],
    ['Smoldering', [], 1],
    ['Flooded', [], 1],
    ['Moldy', [], 1],
    ['Eroded', [], 1],
    ['Rusting', [], 1],
    ['Overgrown', [], 1],
    ['Leaking', [], 1],
    ['Drained', [], 1],
    ['Dusty', [], 1],
    ['Lost', [], 1],
    ['Forgotten', [], 1],
    ['Abandoned', [], 1],
    ['Foggy', [], 1],
    ['Speckled', [], 1],
    ['Veiled', [], 1],
    ['Mossy', [], 1],
    ['Slippery', [], 1],
    ['Remote', [], 1],
    ['Dry', [], 1],
    ['Shrouded', [], 1],
    ['Thermal', [], 1],
    ['Shallow', [], 1],
    ['Forsaken', [], 1]
];

export const cave_effect = [
    ['Glowing', [], 1],
    ['Shimmering', [], 1],
    ['Hidden', [], 1],
    ['Secret', [], 1],
    ['Endless', [], 1],
    ['Howling', [], 1],
    ['Screaming', [], 1],
    ['Whispering', [], 1],
    ['Frozen', [], 1],
    ['Colossal', [], 1],
    ['Cursed', [], 1],
    ['Haunted', [], 1],
    ['Creeping', [], 1],
    ['Luminous', [], 1],
    ['Jeweled', [], 1],
    ['Trapped', [], 1],
    ['Ghostly', [], 1],
    ['Bottomless', [], 1],
    ['Caustic', [], 1],
    ['Concealed', [], 1]
];

export const mine_condition = [
    ['Sealed', [], 1],
    ['Crumbling', [], 1],
    ['Collapsed', [], 1],
    ['Scorched', [], 1],
    ['Unstable', [], 1],
    ['Decayed', [], 1],
    ['Defaced', [], 1],
    ['Rotting', [], 1],
    ['Sunken', [], 1],
    ['Twisted', [], 1],
    ['Sinking', [], 1],
    ['Smoldering', [], 1],
    ['Flooded', [], 1],
    ['Moldy', [], 1],
    ['Overgrown', [], 1],
    ['Leaking', [], 1],
    ['Dusty', [], 1],
    ['Lost', [], 1],
    ['Ancient', [], 1],
    ['Forgotten', [], 1],
    ['Abandoned', [], 1],
    ['Unfinished', [], 1],
    ['Renovated', [], 1],
    ['Repaired', [], 1],
    ['Veiled', [], 1],
    ['Slippery', [], 1],
    ['Remote', [], 1],
    ['Dry', [], 1],
    ['False', [], 1],
    ['Shrouded', [], 1],
    ['Shallow', [], 1],
    ['Forsaken', [], 1]
];

export const mine_effect = [
    ['Clockwork', [], 1],
    ['Glowing', [], 1],
    ['Shimmering', [], 1],
    ['Hidden', [], 1],
    ['Secret', [], 1],
    ['Endless', [], 1],
    ['Radiant', [], 1],
    ['Howling', [], 1],
    ['Locked', [], 1],
    ['Whispering', [], 1],
    ['Frozen', [], 1],
    ['Colossal', [], 1],
    ['Cursed', [], 1],
    ['Haunted', [], 1],
    ['Magnetic', [], 1],
    ['Luminous', [], 1],
    ['Polluted', [], 1],
    ['Jeweled', [], 1],
    ['Trapped', [], 1],
    ['Ghostly', [], 1],
    ['Caustic', [], 1],
    ['Concealed', [], 1],

    ['Exhausted', [], 1],
    ['Plundered', [], 1]
];

export const river_condition = [
    ['Grand', [], 1],
    ['Pristine', [], 1],
    ['Warped', [], 1],
    ['Rotting', [], 1],
    ['Sunken', [], 1],
    ['Twisted', [], 1],
    ['Sinking', [], 1],
    ['Flooded', [], 1],
    ['Moldy', [], 1],
    ['Eroded', [], 1],
    ['Overgrown', [], 1],
    ['Drained', [], 1],
    ['Lost', [], 1],
    ['Foggy', [], 1],
    ['Veiled', [], 1],
    ['Mossy', [], 1],
    ['Drifting', [], 1],
    ['Remote', [], 1],
    ['Dry', [], 1],
    ['Squirming', [], 1],
    ['Shrouded', [], 1],
    ['Shallow', [], 1],
    ['Forsaken', [], 1]
];

export const river_effect = [
    ['Shimmering', [], 1],
    ['Wandering', [], 1],
    ['Endless', [], 1],
    ['Poison', [], 1],
    ['Whispering', [], 1],
    ['Frozen', [], 1],
    ['Cursed', [], 1],
    ['Haunted', [], 1],
    ['Creeping', [], 1],
    ['Polluted', [], 1],
    ['Caustic', [], 1],
    ['Boiling', [], 1]
];

export const temple_condition = [
    ['Grand', [], 1],
    ['Ornate', [], 1],
    ['Engraved', [], 1],
    ['Gilded', [], 1],
    ['Sealed', [], 1],
    ['Shattered', [], 1],
    ['Broken', [], 1],
    ['Fallen', [], 1],
    ['Crumbling', [], 1],
    ['Splintered', [], 1],
    ['Collapsed', [], 1],
    ['Scorched', [], 1],
    ['Decayed', [], 1],
    ['Defaced', [], 1],
    ['Weathered', [], 1],
    ['Warped', [], 1],
    ['Rotting', [], 1],
    ['Rusty', [], 1],
    ['Sunken', [], 1],
    ['Tangled', [], 1],
    ['Twisted', [], 1],
    ['Tarnished', [], 1],
    ['Sinking', [], 1],
    ['Smoldering', [], 1],
    ['Flooded', [], 1],
    ['Moldy', [], 1],
    ['Rusting', [], 1],
    ['Overgrown', [], 1],
    ['Lost', [], 1],
    ['Ancient', [], 1],
    ['Forgotten', [], 1],
    ['Abandoned', [], 1],
    ['Unfinished', [], 1],
    ['Renovated', [], 1],
    ['Repaired', [], 1],
    ['Veiled', [], 1],
    ['Rebuilt', [], 1],
    ['Remote', [], 1],
    ['Shrouded', [], 1],
    ['Forsaken', [], 1]
];

export const temple_effect = [
    ['Clockwork', [], 1],
    ['Glowing', [], 1],
    ['Shimmering', [], 1],
    ['Hidden', [], 1],
    ['Secret', [], 1],
    ['Floating', [], 1],
    ['Levitating', [], 1],
    ['Radiant', [], 1],
    ['Howling', [], 1],
    ['Locked', [], 1],
    ['Whispering', [], 1],
    ['Frozen', [], 1],
    ['Colossal', [], 1],
    ['Cursed', [], 1],
    ['Haunted', [], 1],
    ['Creeping', [], 1],
    ['Luminous', [], 1],
    ['Iridescent', [], 1],
    ['Hovering', [], 1],
    ['Jeweled', [], 1],
    ['Trapped', [], 1],
    ['Ghostly', [], 1],
    ['Whirling', [], 1],
    ['Spiraling', [], 1],
    ['Concealed', [], 1]
];

export const canyon_condition = [
    ['Crumbling', [], 1],
    ['Weathered', [], 1],
    ['Rotting', [], 1],
    ['Rusty', [], 1],
    ['Sunken', [], 1],
    ['Twisted', [], 1],
    ['Sinking', [], 1],
    ['Smoldering', [], 1],
    ['Flooded', [], 1],
    ['Moldy', [], 1],
    ['Eroded', [], 1],
    ['Overgrown', [], 1],
    ['Dusty', [], 1],
    ['Lost', [], 1],
    ['Forgotten', [], 1],
    ['Veiled', [], 1],
    ['Mossy', [], 1],
    ['Slippery', [], 1],
    ['Remote', [], 1],
    ['Dry', [], 1],
    ['Shrouded', [], 1],
    ['Shallow', [], 1],
    ['Forsaken', [], 1]
];

export const canyon_effect = [
    ['Hidden', [], 1],
    ['Secret', [], 1],
    ['Howling', [], 1],
    ['Screaming', [], 1],
    ['Whispering', [], 1],
    ['Frozen', [], 1],
    ['Colossal', [], 1],
    ['Cursed', [], 1],
    ['Haunted', [], 1],
    ['Creeping', [], 1],
    ['Luminous', [], 1],
    ['Ghostly', [], 1],
    ['Bottomless', [], 1],
    ['Concealed', [], 1]
];


export const condition_construction = [
    ['Unfinished', [], 1],
    ['Renovated', [], 1],
    ['Repaired', [], 1],
    ['Abandoned', [], 1],
    ['Rebuilt', [], 1],
    ['Sealed', [], 1],
    ['Concentric', [], 1],
    ['Terraced', [], 1],
    ['Geometric', [], 1],
    ['Gilded', [], 1],
    ['Ornate', [], 1],
    ['Engraved', [], 1],
    ['Warded', [], 1],
    ['Sturdy', [], 1]
];

export const condition_misc = [
    ['Dusty', [], 1],
    ['Lost', [], 1],
    ['Mottled', [], 1],
    ['Ancient', [], 1],
    ['Bald', [], 1],
    ['Hollow', [], 1],
    ['Balanced', [], 1],
    ['Forgotten', [], 1],
    ['Abandoned', [], 1],
    ['Jagged', [], 1],
    ['Dull', [], 1],
    ['Viscous', [], 1],
    ['Cloudy', [], 1],
    ['Greasy', [], 1],
    ['Unfinished', [], 1],
    ['Renovated', [], 1],
    ['Repaired', [], 1],
    ['Foggy', [], 1],
    ['Speckled', [], 1],
    ['Wrinkled', [], 1],
    ['Veiled', [], 1],
    ['Rebuilt', [], 1],
    ['Mossy', [], 1],
    ['Slippery', [], 1],
    ['Drifting', [], 1],
    ['Looming', [], 1],
    ['Lurking', [], 1],
    ['Remote', [], 1],
    ['Dry', [], 1],
    ['Squirming', [], 1],
    ['False ', [], 1],
    ['Barbed', [], 1],
    ['Shrouded', [], 1],
    ['Thermal', [], 1],
    ['Crested', [], 1],
    ['Spined', [], 1],
    ['Spiked', [], 1],
    ['Serrated', [], 1],
    ['Scaled', [], 1],
    ['Shallow', [], 1],
    ['Forsaken', [], 1],
    ['Dormant', [], 1],
    ['Nocturnal', [], 1],
    ['Cyclopean', [], 1]
];

export const condition_excellent = [
    ['Fine', [], 1],
    ['Grand', [], 1],
    ['Pristine', [], 1],
    ['Ornate', [], 1],
    ['Engraved', [], 1],
    ['Warded', [], 1],
    ['Sturdy', [], 1],
    ['Bright', [], 1],
    ['Concentric', [], 1],
    ['Terraced', [], 1],
    ['Geometric', [], 1],
    ['Gilded', [], 1],
    ['Sealed', [], 1]
];

export const condition_broken = [
    ['Shattered', [], 1],
    ['Broken', [], 1],
    ['Fallen', [], 1],
    ['Crumbling', [], 1],
    ['Flawed', [], 1],
    ['Faulty', [], 1],
    ['Splintered', [], 1],
    ['Chipped', [], 1],
    ['Worn', [], 1],
    ['Collapsed', [], 1],
    ['Scorched', [], 1],
    ['Unstable', [], 1],
    ['Decayed', [], 1],
    ['Defaced', [], 1],
    ['Weathered', [], 1],
    ['Warped', [], 1],
    ['Rotting', [], 1],
    ['Rusty', [], 1],
    ['Sunken', [], 1],
    ['Tangled', [], 1],
    ['Twisted', [], 1],
    ['Tarnished', [], 1],
    ['Sinking', [], 1],
    ['Smoldering', [], 1],
    ['Flooded', [], 1],
    ['Pilfered', [], 1],
    ['Odious', [], 1],
    ['Moldy', [], 1],
    ['Eroded', [], 1],
    ['Rusting', [], 1],
    ['Overgrown', [], 1],
    ['Leaking', [], 1],
    ['Drained', [], 1]
];

export const effect = [
    ['Clockwork', [], 1],
    ['Glowing', [], 1],
    ['Shimmering', [], 1],
    ['Hidden', [], 1],
    ['Secret', [], 1],
    ['Invisible', [], 1],
    ['Ethereal', [], 1],
    ['Floating', [], 1],
    ['Levitating', [], 1],
    ['Prismatic', [], 1],
    ['Wandering', [], 1],
    ['Singing', [], 1],
    ['Endless', [], 1],
    ['Drifting', [], 1],
    ['Blinking', [], 1],
    ['Jumping', [], 1],
    ['Radiant', [], 1],
    ['Giant', [], 1],
    ['Howling', [], 1],
    ['Screaming', [], 1],
    ['Chromatic', [], 1],
    ['Burning', [], 1],
    ['Blazing', [], 1],
    ['Charged', [], 1],
    ['Fiery', [], 1],
    ['Electric', [], 1],
    ['Acidic', [], 1],
    ['Poison', [], 1],
    ['Spinning', [], 1],
    ['Secure', [], 1],
    ['Locked', [], 1],
    ['Inverted', [], 1],
    ['Whispering', [], 1],
    ['Corrosive', [], 1],
    ['Frozen', [], 1],
    ['Colossal', [], 1],
    ['Cursed', [], 1],
    ['Haunted', [], 1],
    ['Dancing', [], 1],
    ['Withering', [], 1],
    ['Creeping', [], 1],
    ['Magnetic', [], 1],
    ['Albino', [], 1],
    ['Luminous', [], 1],
    ['Molten', [], 1],
    ['Polluted', [], 1],
    ['Iridescent', [], 1],
    ['Hovering', [], 1],
    ['Phantasmal', [], 1],
    ['Jeweled', [], 1],
    ['Trapped', [], 1],
    ['Voltaic', [], 1],
    ['Psionic', [], 1],
    ['Masterwork', [], 1],
    ['Temporal', [], 1],
    ['Ghostly', [], 1],
    ['Shrinking', [], 1],
    ['Bottomless', [], 1],
    ['Blinding', [], 1],
    ['Caustic', [], 1],
    ['Boiling', [], 1],
    ['Primordial', [], 1],
    ['Eternal', [], 1],
    ['Animated', [], 1],
    ['Spectral', [], 1],
    ['Shifting', [], 1],
    ['Hypnotic', [], 1],
    ['Explosive', [], 1],
    ['Blurry', [], 1],
    ['Shrunken', [], 1],
    ['Whirling', [], 1],
    ['Flickering', [], 1],
    ['Spiraling', [], 1],
    ['Concealed', [], 1]
];

export const past_participle_adjective = [
    ['Weeping', [], 1],
    ['Sleeping', [], 1],
    ['Gasping', [], 1],
    ['Waning', [], 1],
    ['Wailing', [], 1],
    ['Screeching', [], 1],
    ['Glimmering', [], 1],
    ['Writhing', [], 1],
    ['Dancing', [], 1],
    ['Withering', [], 1],
    ['Creeping', [], 1],
    ['Glowing', [], 1],
    ['Shimmering', [], 1],
    ['Floating', [], 1],
    ['Levitating', [], 1],
    ['Wandering', [], 1],
    ['Singing', [], 1],
    ['Drifting', [], 1],
    ['Blinking', [], 1],
    ['Jumping', [], 1],
    ['Howling', [], 1],
    ['Screaming', [], 1],
    ['Burning', [], 1],
    ['Blazing', [], 1],
    ['Spinning', [], 1],
    ['Whispering', [], 1],
    ['Whirling', [], 1],
    ['Flickering', [], 1],
    ['Spiraling', [], 1],
    ['Shifting', [], 1],
    ['Boiling', [], 1],
    ['Blinding', [], 1],
    ['Shrinking', [], 1],
    ['Hovering', [], 1],
    ['Festering', [], 1],
    ['Sinking', [], 1],
    ['Smoldering', [], 1],
    ['Leaking', [], 1],
    ['Crumbling', [], 1],
    ['Rotting', [], 1],
    ['Squirming', [], 1],
    ['Drifting', [], 1],
    ['Looming', [], 1],
    ['Lurking', [], 1]
];

export const tavern_participle_adjective = [
    ['Limping', [], 1],
    ['Snorting', [], 1],
    ['Stuttering', [], 1]
];


export const addtional_adjective = [
    ['Crystalline', [], 1],
    ['Glacial', [], 1],
    ['infernal', [], 1],
    ['Elysian', [], 1],
    ['Arcadian', [], 1],
    ['Shattered', [], 1],
    ['Opaque', [], 1],
    ['Smooth', [], 1],
    ['Chilled', [], 1],
    ['Cryptic', [], 1],
    ['Obscure', [], 1],
    ['Lucid', [], 1],
    ['Reinfornced', [], 1],
    ['Ruined', [], 1],
    ['Damaged', [], 1],
    ['Decomposed', [], 1],
    ['Stitched', [], 1],
    ['Preserved', [], 1],
    ['Polished', [], 1],
    ['Fractured', [], 1],
    ['Poisonous', [], 1],
    ['Toxic', [], 1],
    ['Ashen', [], 1],
    ['Forlorn', [], 1],
    ['Dismal', [], 1],
    ['Bleak', [], 1],
    ['Sacramental', [], 1],
    ['Solar', [], 1],
    ['Lunar', [], 1],
    ['Primal', [], 1],
    ['Sacrificial', [], 1],
    ['Malevolent', [], 1],
    ['Fetid', [], 1],
    ['Imperial', [], 1],
    ['Empyrean', [], 1],
    ['Murky', [], 1],
    ['Elemental', [], 1],
    ['Decrepit', [], 1],
    ['Fermented', [], 1],
    ['Abysmal', [], 1],
    ['Erudite', [], 1],
    ['Termagant', [], 1],
    ['Unmarked', [], 1],
    ['Infested', [], 1],
    ['Derelict', [], 1],
    ['Toadstool', [], 1],
    ['Arcane', [], 1],
    ['Lone', [], 1],
    ['Lonely', [], 1],
    ['Seven', [], 1],
    ['Ten', [], 1],
    ['Twelve', [], 1],
    ['Fouled', [], 1],
    ['Festering', [], 1],
    ['Whispering', [], 1],
    ['Vast', [], 1],
    ['Cloven', [], 1]
];

export const bridge_special_adjective = [
    ['Covered', [], 1],
    ['Suspension', [], 1],
    ['Rope', [], 1],
    ['Toll', [], 1],
    ['Log', [], 1],
    ['Fallen Tree', [], 1],
    ['Natural', [], 1],
    ['Gargoyle', [], 1],
    ['Chain', [], 1],
    ['Ironwork', [], 1],
    ['Arched', [], 1],
    ['Stepping Stone', [], 1]
];

export const tower_special_adjective = [
    ['Bell', [], 1],
    ['Watch', [], 1],
    ['Signal', [], 1],
    ['Lookout', [], 1]
];


export const dungeon_level_connection = [
    ['Stairs', [], 1],
    ['Spiral Stairs', [], 1],
    ['Elevator', [], 1],
    ['Sloping Passage', [], 1],
    ['Teleporter', [], 1],
    ['Pit', [], 1],
    ['Slide', [], 1],
    ['Ladder', [], 1]
];

export const stone_special_adjective = [
    ['Wedge', [], 1],
    ['Standing', [], 1],
    ['Chimney', [], 1],
    ['Wart', [], 1],
    ['Warp', [], 1],
    ['Wrinkle', [], 1],
    ['Riven', [], 1],
    ['Whispering', [], 1],
    ['Grave', [], 1],
    ['Engraved', [], 1],
    ['Portal', [], 1],
    ['Spinning', [], 1],
    ['Singing', [], 1],
    ['Skimming', [], 1],
    ['Leaning', [], 1],
    ['Lode', [], 1],
    ['Lift', [], 1],
    ['Rune', [], 1],
    ['Trail', [], 1],
    ['Grind', [], 1],
    ['Skipping', [], 1],
    ['Moon', [], 1],
    ['Speaking', [], 1],
    ['Slippery', [], 1],
    ['Balanced', [], 1],
    ['Lookout', [], 1],
    ['Stovepipe', [], 1],
    ['Notch', [], 1],
    ['Dome', [], 1],
    ['Needle', [], 1],
    ['Pedestal', [], 1],
    ['Bald', [], 1],
    ['Mushroom', [], 1],
    ['Crevisse', [], 1],
    ['Weird', [], 1],
    ['Weeping', [], 1],
    ['Chatter', [], 1],
    ['Beetle', [], 1],
    ['Brim', [], 1],
    ['Float', [], 1],
    ['Field', [], 1],
    ['Drip', [], 1],
    ['Sun', [], 1],
    ['Mud', [], 1],
    ['Touch', [], 1],
    ['Stink', [], 1],
    ['Smoke', [], 1],
    ['Boil', [], 1],
    ['Drifting', [], 1],
    ['Mill', [], 1],
    ['Gate', [], 1],
    ['Helix', [], 1],
    ['Spire', [], 1],
    ['Alter', [], 1],
    ['Wind', [], 1],
    ['Calendar', [], 1],
    ['Clock', [], 1],
    ['Moon', [], 1]
];

export const district_special_adjective = [
    ['Dock', [], 1],
    ['High', [], 1],
    ['Low', [], 1],
    ['Lower', [], 1],
    ['Jewel', [], 1],
    ['Palace', [], 1],
    ['Trade', [], 1],
    ['Sea', [], 1],
    ['Castle', [], 1],
    ['River', [], 1],
    ['Garden', [], 1],
    ['Foreign', [], 1],
    ['Thieves', [], 1],
    ['Artisans', [], 1],
    ['Slum', [], 1],
    ['Park', [], 1],
    ['Plaza', [], 1],
    ['Temple', [], 1],
    ['Noble', [], 1],
    ['Uptown', [], 1],
    ['Harbor', [], 1],
    ['Festival', [], 1],
    ['Market', [], 1],
    ['Lantern', [], 1],
    ['Shackles', [], 1],
    ['Emerald', [], 1],
    ['Crypt', [], 1],
    ['Old', [], 1],
    ['Night', [], 1],
    ['Marble', [], 1],
    ['Bellows', [], 1],
    ['Cobbles', [], 1]
];

