export const getRandom = (n: number) => Math.floor(Math.random() * n)
export const getRandomV2 = (n: number) => Math.ceil(Math.random() * n)
export const d6 = (): number => getRandom(6)
export const d6x3 = (): number => getRandomV2(6) + getRandomV2(6) + getRandomV2(6)
export const d4 = (): number => getRandom(4)
export const d8 = (): number => getRandom(8)
export const d10 = (): number => getRandom(10)
export const d12 = (): number => getRandom(12)
export const d20 = (): number => getRandom(20)
export const uuid = (): string => crypto.randomUUID()