// AUTO-GENERATED by scripts/generateDungeonTiles.ts — do not edit manually.
// Cave skin (Idea 7): rounded concave corner tiles (a few radii). Apse/alcove variety = wall bays.

// Corner tiles (vertex marching-squares, cave skin): a VARIETY of concave fillet shapes per
// orientation. Page.tsx selects one at random per corner (seeded by cell position) for an organic,
// non-repeating silhouette.
export const CAVE_CORNER_VARIANTS: Record<"nw" | "ne" | "se" | "sw", string[]> = {
  nw: [
  "/dungeonTiles/cave_corner_nw_0.svg",
  "/dungeonTiles/cave_corner_nw_1.svg",
  "/dungeonTiles/cave_corner_nw_2.svg",
  "/dungeonTiles/cave_corner_nw_3.svg",
],
  ne: [
  "/dungeonTiles/cave_corner_ne_0.svg",
  "/dungeonTiles/cave_corner_ne_1.svg",
  "/dungeonTiles/cave_corner_ne_2.svg",
  "/dungeonTiles/cave_corner_ne_3.svg",
],
  se: [
  "/dungeonTiles/cave_corner_se_0.svg",
  "/dungeonTiles/cave_corner_se_1.svg",
  "/dungeonTiles/cave_corner_se_2.svg",
  "/dungeonTiles/cave_corner_se_3.svg",
],
  sw: [
  "/dungeonTiles/cave_corner_sw_0.svg",
  "/dungeonTiles/cave_corner_sw_1.svg",
  "/dungeonTiles/cave_corner_sw_2.svg",
  "/dungeonTiles/cave_corner_sw_3.svg",
],
}

// 1-cell pocket (dome) tiles — a smooth half-circle for a floor cell walled on 3 sides, keyed by the
// open side. Used instead of two corner tiles (which would make an asymmetrical pointed arch).
export const CAVE_POCKET: Record<"n" | "s" | "e" | "w", string> = {
  n: "/dungeonTiles/cave_pocket_n.svg", s: "/dungeonTiles/cave_pocket_s.svg",
  e: "/dungeonTiles/cave_pocket_e.svg", w: "/dungeonTiles/cave_pocket_w.svg",
}
