// A dungeon room modeled as a config OBJECT on core/config (design target: map as a view of the
// generated object tree). Feature-side (owns the RoomProfile → tags mapping); core stays generic.
//
// Step 8: the room's semantic content is generated by a Config whose rules read the room's GenContext
// (the dungeon root ⊕ the room's profile tags). Today the only property is `name` (via core/naming),
// so this is behavior-PRESERVING — the name rule calls the same roomName with the same tags/rng. It
// establishes the pattern: richer content (themed label, description, contents) becomes more rules
// reading the same context, and a dungeon-level theme flows down through the root context.

import type { Rng } from "../../core/rng"
import { type GenContext, childContext } from "../../core/model"
import { createItem, type Config, type ItemRecord } from "../../core/config"
import { roomName } from "../../core/naming"
import type { RoomProfile } from "./types"
import { profileToTags } from "./roomTags"

const DUNGEON_ID = "dungeon" // the root object's id (rooms are its children in the tree)

export type RoomObject = {
  name: string
}

export const roomConfig: Config<RoomObject> = {
  name: { updater: (_item, ctx, rng) => roomName(ctx.tags, rng) },
}

// Build a room as a config object: its context inherits the dungeon root's tags and adds the room's
// own profile tags. Returns the ItemRecord (typed properties + tree metadata: id + parentId).
export function buildRoomObject(profile: RoomProfile, root: GenContext, rng: Rng, num: number): ItemRecord<RoomObject> {
  const ctx = childContext(root, profileToTags(profile))
  return createItem("room", roomConfig, ctx, rng, { id: `room-${num}`, parentId: DUNGEON_ID })
}
