
export enum Epithets {
    Epithet = 'Epithet',
    Personality = 'Personality',
    Demonic = 'Demonic',
    Good = 'Good',
    Dominion = 'Dominion',
    Animal = 'Animal',
    Negative = 'Negative',
    Positive = 'Positive',
    Draconic = 'Draconic',
}

const {
    Epithet,
    Personality,
    Demonic,
    Good,
    Dominion,
    Animal,
    Negative,
    Positive,
    Draconic
} = Epithets

const bigList = [
    ["Aardvark", [Epithet, Animal, Positive], 1],
    ["Abrupt", [Epithet, Personality], 1],
    ["Absentminded", [Epithet, Personality], 1],
    ["Adamant", [Epithet, Good], 1],
    ["Adapter", [Epithet, Demonic], 1],
    ["Adder", [Epithet, Animal, Negative], 1],
    ["Addict", [Epithet, Personality], 1],
    ["Admirable", [Epithet, Good], 1],
    ["Adventurous", [Epithet, Personality], 1],
    ["Adviser", [Epithet, Good], 1],
    ["Affable", [Epithet, Personality], 1],
    ["Affected", [Epithet, Personality], 1],
    ["Aggressive", [Epithet, Personality], 1],
    ["Agreeable", [Epithet, Personality], 1],
    ["Alert", [Epithet, Personality], 1],
    ["Alligator", [Epithet, Animal, Negative], 1],
    ["Aloof", [Epithet, Personality], 1],
    ["Altruistic", [Epithet, Good], 1],
    ["Altruistic", [Epithet, Personality], 1],
    ["Ambiguous", [Epithet, Personality], 1],
    ["Ambitious", [Epithet, Personality], 1],
    ["Amiable", [Epithet, Personality], 1],
    ["Amphibian", [Epithet, Animal, Negative], 1],
    ["Anaconda", [Epithet, Animal, Negative], 1],
    ["Angelic", [Epithet, Good], 1],
    ["Ant", [Epithet, Animal, Negative], 1],
    ["Anteater", [Epithet, Animal, Positive], 1],
    ["Antelope", [Epithet, Animal, Positive], 1],
    ["Apathetic", [Epithet, Personality], 1],
    ["Ape", [Epithet, Animal, Negative], 1],
    ["Ape", [Epithet, Animal, Positive], 1],
    ["Apologetic", [Epithet, Personality], 1],
    ["Armadillo", [Epithet, Animal, Positive], 1],
    ["Armored", [Epithet, Demonic], 1],
    ["Arrogant", [Epithet, Personality], 1],
    ["Artistic", [Epithet, Personality], 1],
    ["Asp", [Epithet, Animal, Negative], 1],
    ["Assailer", [Epithet, Demonic], 1],
    ["Audacious", [Epithet, Personality], 1],
    ["Austere", [Epithet, Personality], 1],
    ["Awkward", [Epithet, Personality], 1],
    ["Baboon", [Epithet, Animal, Positive], 1],
    ["Badger", [Epithet, Animal, Positive], 1],
    ["Barracuda", [Epithet, Animal, Negative], 1],
    ["Basilisk", [Epithet, Animal, Negative], 1],
    ["Bat", [Epithet, Animal, Negative], 1],
    ["Batrachian", [Epithet, Animal, Negative], 1],
    ["Bear", [Epithet, Animal, Negative], 1],
    ["Bear", [Epithet, Animal, Positive], 1],
    ["Beaver", [Epithet, Animal, Positive], 1],
    ["Beetle", [Epithet, Animal, Negative], 1],
    ["Beetle", [Epithet, Animal, Negative], 1],
    ["Belligerent", [Epithet, Personality], 1],
    ["Beloved", [Epithet, Good], 1],
    ["Beneficent", [Epithet, Good], 1],
    ["Benevolent", [Epithet, Good], 1],
    ["Benign", [Epithet, Good], 1],
    ["Binder", [Epithet, Demonic], 1],
    ["Bison", [Epithet, Animal, Positive], 1],
    ["Biter", [Epithet, Demonic], 1],
    ["Black Widow", [Epithet, Animal, Negative], 1],
    ["Blackbird", [Epithet, Animal, Negative], 1],
    ["Blameless", [Epithet, Good], 1],
    ["Blessed", [Epithet, Good], 1],
    ["Boar", [Epithet, Animal, Negative], 1],
    ["Boastful", [Epithet, Draconic], 1],
    ["Boastful", [Epithet, Personality], 1],
    ["Bold", [Epithet, Good], 1],
    ["Bold", [Epithet, Personality], 1],
    ["Bombarder", [Epithet, Demonic], 1],
    ["Boor", [Epithet, Personality], 1],
    ["Brash", [Epithet, Draconic], 1],
    ["Brash", [Epithet, Personality], 1],
    ["Brave", [Epithet, Good], 1],
    ["Brave", [Epithet, Personality], 1],
    ["Breaker", [Epithet, Demonic], 1],
    ["Breeder", [Epithet, Demonic], 1],
    ["Brilliant", [Epithet, Personality], 1],
    ["Bug", [Epithet, Animal, Negative], 1],
    ["Bull", [Epithet, Animal, Positive], 1],
    ["Burier", [Epithet, Demonic], 1],
    ["Burner", [Epithet, Demonic], 1],
    ["Butterfly", [Epithet, Animal, Positive], 1],
    ["Cackler", [Epithet, Demonic], 1],
    ["Cajoler", [Epithet, Demonic], 1],
    ["Calculating", [Epithet, Personality], 1],
    ["Callous", [Epithet, Personality], 1],
    ["Calm", [Epithet, Personality], 1],
    ["Camel", [Epithet, Animal, Positive], 1],
    ["Canary", [Epithet, Animal, Positive], 1],
    ["Capricious", [Epithet, Personality], 1],
    ["Capturer", [Epithet, Demonic], 1],
    ["Carefree", [Epithet, Personality], 1],
    ["Careful", [Epithet, Personality], 1],
    ["Careless", [Epithet, Personality], 1],
    ["Cat", [Epithet, Animal, Positive], 1],
    ["Caustic", [Epithet, Personality], 1],
    ["Cauterizer", [Epithet, Demonic], 1],
    ["Cautious", [Epithet, Personality], 1],
    ["Centipede", [Epithet, Animal, Negative], 1],
    ["Chameleon", [Epithet, Animal, Negative], 1],
    ["Chameleon", [Epithet, Animal, Positive], 1],
    ["Changer", [Epithet, Demonic], 1],
    ["Charismatic", [Epithet, Personality], 1],
    ["Charitable", [Epithet, Good], 1],
    ["Chaste", [Epithet, Personality], 1],
    ["Cheerful", [Epithet, Personality], 1],
    ["Cheetah", [Epithet, Animal, Positive], 1],
    ["Chivalrous", [Epithet, Personality], 1],
    ["Clam", [Epithet, Animal, Positive], 1],
    ["Claw", [Epithet, Demonic], 1],
    ["Clever", [Epithet, Personality], 1],
    ["Clumsy", [Epithet, Personality], 1],
    ["Coarse", [Epithet, Personality], 1],
    ["Coaxer", [Epithet, Demonic], 1],
    ["Cobra", [Epithet, Animal, Negative], 1],
    ["Cockatrice", [Epithet, Animal, Negative], 1],
    ["Cockroach", [Epithet, Animal, Negative], 1],
    ["Coercer", [Epithet, Demonic], 1],
    ["Cold", [Epithet, Draconic], 1],
    ["Cold", [Epithet, Personality], 1],
    ["Collapser", [Epithet, Demonic], 1],
    ["Combustor", [Epithet, Demonic], 1],
    ["Compassionate", [Epithet, Good], 1],
    ["Compassionate", [Epithet, Good], 1],
    ["Compassionate", [Epithet, Personality], 1],
    ["Competent", [Epithet, Personality], 1],
    ["Composed", [Epithet, Personality], 1],
    ["Conceited", [Epithet, Draconic], 1],
    ["Conceited", [Epithet, Personality], 1],
    ["Condescending", [Epithet, Personality], 1],
    ["Confident", [Epithet, Personality], 1],
    ["Congenial", [Epithet, Personality], 1],
    ["Conscientious", [Epithet, Personality], 1],
    ["Consecrated", [Epithet, Good], 1],
    ["Considerate", [Epithet, Personality], 1],
    ["Constrainer", [Epithet, Demonic], 1],
    ["Constrainer", [Epithet, Good], 1],
    ["Constrictor", [Epithet, Demonic], 1],
    ["Contrarian", [Epithet, Personality], 1],
    ["Counselor", [Epithet, Good], 1],
    ["Courageous", [Epithet, Good], 1],
    ["Courageous", [Epithet, Personality], 1],
    ["Courteous", [Epithet, Personality], 1],
    ["Courtly", [Epithet, Draconic], 1],
    ["Covetous", [Epithet, Draconic], 1],
    ["Covetous", [Epithet, Personality], 1],
    ["Coward", [Epithet, Personality], 1],
    ["Cowardly", [Epithet, Draconic], 1],
    ["Crab", [Epithet, Animal, Negative], 1],
    ["Crafty", [Epithet, Personality], 1],
    ["Crocodile", [Epithet, Animal, Negative], 1],
    ["Crow", [Epithet, Animal, Negative], 1],
    ["Cruel", [Epithet, Draconic], 1],
    ["Cruel", [Epithet, Personality], 1],
    ["Cultured", [Epithet, Personality], 1],
    ["Cunning", [Epithet, Draconic], 1],
    ["Curious", [Epithet, Personality], 1],
    ["Curse-Bringer", [Epithet, Demonic], 1],
    ["Curse-Maker", [Epithet, Demonic], 1],
    ["Curse-Weaver", [Epithet, Demonic], 1],
    ["Cursed", [Epithet, Demonic], 1],
    ["Cynical", [Epithet, Personality], 1],
    ["Dainty", [Epithet, Personality], 1],
    ["Daring", [Epithet, Personality], 1],
    ["Dark-Bringer", [Epithet, Demonic], 1],
    ["Dark", [Epithet, Demonic], 1],
    ["Dark", [Epithet, Draconic], 1],
    ["Death-Bringer", [Epithet, Demonic], 1],
    ["Decayer", [Epithet, Demonic], 1],
    ["Deceitful", [Epithet, Draconic], 1],
    ["Deceitful", [Epithet, Personality], 1],
    ["Deceiver", [Epithet, Demonic], 1],
    ["Decisive", [Epithet, Personality], 1],
    ["Decorous", [Epithet, Personality], 1],
    ["Dedicated", [Epithet, Good], 1],
    ["Deer", [Epithet, Animal, Positive], 1],
    ["Defender", [Epithet, Good], 1],
    ["Defiant", [Epithet, Personality], 1],
    ["Delayer", [Epithet, Demonic], 1],
    ["Deliberate", [Epithet, Personality], 1],
    ["Delicate", [Epithet, Personality], 1],
    ["Deliverer", [Epithet, Good], 1],
    ["Delver", [Epithet, Demonic], 1],
    ["Demon", [Epithet, Demonic], 1],
    ["Descender", [Epithet, Demonic], 1],
    ["Despoiler", [Epithet, Demonic], 1],
    ["Despondent", [Epithet, Personality], 1],
    ["Destroyer", [Epithet, Demonic], 1],
    ["Determined", [Epithet, Personality], 1],
    ["Devious", [Epithet, Draconic], 1],
    ["Devious", [Epithet, Personality], 1],
    ["Devoted", [Epithet, Good], 1],
    ["Devotional", [Epithet, Good], 1],
    ["Devout", [Epithet, Good], 1],
    ["Dignified", [Epithet, Personality], 1],
    ["Diligent", [Epithet, Personality], 1],
    ["Discerner", [Epithet, Demonic], 1],
    ["Discerning", [Epithet, Personality], 1],
    ["Disciplined", [Epithet, Personality], 1],
    ["Discreet", [Epithet, Personality], 1],
    ["Disease-Bringer", [Epithet, Demonic], 1],
    ["Disenchanter", [Epithet, Demonic], 1],
    ["Dishonest", [Epithet, Personality], 1],
    ["Disloyal", [Epithet, Personality], 1],
    ["Displacer", [Epithet, Demonic], 1],
    ["Dissuader", [Epithet, Demonic], 1],
    ["Distant", [Epithet, Personality], 1],
    ["Distraught", [Epithet, Personality], 1],
    ["Distrustful", [Epithet, Personality], 1],
    ["Divine", [Epithet, Good], 1],
    ["Doe", [Epithet, Animal, Positive], 1],
    ["Dogmatic", [Epithet, Personality], 1],
    ["Doubter", [Epithet, Personality], 1],
    ["Dove", [Epithet, Animal, Positive], 1],
    ["Draconian", [Epithet, Personality], 1],
    ["Dragonfly", [Epithet, Animal, Positive], 1],
    ["Dramatic", [Epithet, Personality], 1],
    ["Dreamer", [Epithet, Draconic], 1],
    ["Dreamer", [Epithet, Personality], 1],
    ["Drummer", [Epithet, Demonic], 1],
    ["Dryad", [Epithet, Animal, Positive], 1],
    ["Dubious", [Epithet, Personality], 1],
    ["Duck", [Epithet, Animal, Positive], 1],
    ["Dull", [Epithet, Personality], 1],
    ["Dutiful", [Epithet, Personality], 1],
    ["Dynamic", [Epithet, Personality], 1],
    ["Eagle", [Epithet, Animal, Positive], 1],
    ["Earthworm", [Epithet, Animal, Negative], 1],
    ["Earwig", [Epithet, Animal, Negative], 1],
    ["Eccentric", [Epithet, Personality], 1],
    ["Eel", [Epithet, Animal, Negative], 1],
    ["Elephant", [Epithet, Animal, Positive], 1],
    ["Elk", [Epithet, Animal, Positive], 1],
    ["Eloquent", [Epithet, Personality], 1],
    ["Emancipator", [Epithet, Good], 1],
    ["Embittered", [Epithet, Personality], 1],
    ["Eminent", [Epithet, Personality], 1],
    ["Empathetic", [Epithet, Personality], 1],
    ["Emu", [Epithet, Animal, Positive], 1],
    ["Enchanter", [Epithet, Demonic], 1],
    ["Energetic", [Epithet, Personality], 1],
    ["Engaging", [Epithet, Personality], 1],
    ["Enigmatic", [Epithet, Personality], 1],
    ["Enkindler", [Epithet, Demonic], 1],
    ["Enslaver", [Epithet, Demonic], 1],
    ["Entangler", [Epithet, Demonic], 1],
    ["Enthusiast", [Epithet, Personality], 1],
    ["Enticer", [Epithet, Demonic], 1],
    ["Enticer", [Epithet, Demonic], 1],
    ["Erratic", [Epithet, Personality], 1],
    ["Ethical", [Epithet, Personality], 1],
    ["Evasive", [Epithet, Personality], 1],
    ["Exacting", [Epithet, Personality], 1],
    ["Examiner", [Epithet, Demonic], 1],
    ["Excessive", [Epithet, Personality], 1],
    ["Exemplary", [Epithet, Good], 1],
    ["Extravagant", [Epithet, Personality], 1],
    ["Exuberant", [Epithet, Personality], 1],
    ["Fair", [Epithet, Good], 1],
    ["Fair", [Epithet, Personality], 1],
    ["Faithful", [Epithet, Good], 1],
    ["Faithful", [Epithet, Personality], 1],
    ["Faithless", [Epithet, Personality], 1],
    ["Famine-Bringer", [Epithet, Demonic], 1],
    ["Fanatical", [Epithet, Personality], 1],
    ["Fatalistic", [Epithet, Personality], 1],
    ["Fearful", [Epithet, Personality], 1],
    ["Fearless", [Epithet, Personality], 1],
    ["Ferocious", [Epithet, Draconic], 1],
    ["Ferocious", [Epithet, Personality], 1],
    ["Ferret", [Epithet, Animal, Negative], 1],
    ["Fetcher", [Epithet, Demonic], 1],
    ["Fey", [Epithet, Animal, Positive], 1],
    ["Fiery", [Epithet, Draconic], 1],
    ["Fiery", [Epithet, Personality], 1],
    ["Finder", [Epithet, Demonic], 1],
    ["Finder", [Epithet, Good], 1],
    ["Fish", [Epithet, Animal, Negative], 1],
    ["Flamboyant", [Epithet, Personality], 1],
    ["Flamingo", [Epithet, Animal, Positive], 1],
    ["Flippant", [Epithet, Personality], 1],
    ["Fly", [Epithet, Animal, Negative], 1],
    ["Follower", [Epithet, Demonic], 1],
    ["Foolish", [Epithet, Draconic], 1],
    ["Foolish", [Epithet, Personality], 1],
    ["Forager", [Epithet, Demonic], 1],
    ["Forceful", [Epithet, Personality], 1],
    ["Forgetful", [Epithet, Personality], 1],
    ["Foul", [Epithet, Draconic], 1],
    ["Fox", [Epithet, Animal, Negative], 1],
    ["Fox", [Epithet, Animal, Positive], 1],
    ["Fretful", [Epithet, Personality], 1],
    ["Frog", [Epithet, Animal, Negative], 1],
    ["Frugal", [Epithet, Personality], 1],
    ["Furtive", [Epithet, Personality], 1],
    ["Fussy", [Epithet, Personality], 1],
    ["Gallant", [Epithet, Good], 1],
    ["Garrulous", [Epithet, Personality], 1],
    ["Gaudy", [Epithet, Personality], 1],
    ["Gazelle", [Epithet, Animal, Positive], 1],
    ["Gazer", [Epithet, Demonic], 1],
    ["Generous", [Epithet, Good], 1],
    ["Generous", [Epithet, Personality], 1],
    ["Genial", [Epithet, Personality], 1],
    ["Gentle", [Epithet, Good], 1],
    ["Gentle", [Epithet, Personality], 1],
    ["Ghastly", [Epithet, Demonic], 1],
    ["Giraffe", [Epithet, Animal, Positive], 1],
    ["Gloomy", [Epithet, Draconic], 1],
    ["Gloomy", [Epithet, Personality], 1],
    ["Goat", [Epithet, Animal, Negative], 1],
    ["Goat", [Epithet, Animal, Positive], 1],
    ["Goblin", [Epithet, Animal, Negative], 1],
    ["Good", [Epithet, Good], 1],
    ["Goose", [Epithet, Animal, Positive], 1],
    ["Gorgon", [Epithet, Animal, Negative], 1],
    ["Goshawk", [Epithet, Animal, Negative], 1],
    ["Graceful", [Epithet, Personality], 1],
    ["Gracious", [Epithet, Good], 1],
    ["Gracious", [Epithet, Personality], 1],
    ["Grandiose", [Epithet, Personality], 1],
    ["Greedy", [Epithet, Draconic], 1],
    ["Greedy", [Epithet, Personality], 1],
    ["Gregarious", [Epithet, Personality], 1],
    ["Greyhound", [Epithet, Animal, Positive], 1],
    ["Grim", [Epithet, Demonic], 1],
    ["Grim", [Epithet, Good], 1],
    ["Grub", [Epithet, Animal, Negative], 1],
    ["Gruff", [Epithet, Personality], 1],
    ["Gryphon", [Epithet, Animal, Positive], 1],
    ["Guarded", [Epithet, Personality], 1],
    ["Gullible", [Epithet, Personality], 1],
    ["Hallowed", [Epithet, Good], 1],
    ["Harbinger", [Epithet, Demonic], 1],
    ["Hardworking", [Epithet, Personality], 1],
    ["Hare", [Epithet, Animal, Positive], 1],
    ["Harried", [Epithet, Personality], 1],
    ["Harrier", [Epithet, Demonic], 1],
    ["Harsh", [Epithet, Draconic], 1],
    ["Harsh", [Epithet, Personality], 1],
    ["Hart", [Epithet, Animal, Positive], 1],
    ["Hateful", [Epithet, Draconic], 1],
    ["Haughty", [Epithet, Draconic], 1],
    ["Haughty", [Epithet, Personality], 1],
    ["Haunter", [Epithet, Demonic], 1],
    ["Hawk", [Epithet, Animal, Negative], 1],
    ["Hawk", [Epithet, Animal, Positive], 1],
    ["Heartless", [Epithet, Draconic], 1],
    ["Heartless", [Epithet, Personality], 1],
    ["Hedgehog", [Epithet, Animal, Positive], 1],
    ["Hedonistic", [Epithet, Personality], 1],
    ["Heroic", [Epithet, Good], 1],
    ["Hesitant", [Epithet, Personality], 1],
    ["Hippogriff", [Epithet, Animal, Positive], 1],
    ["Hippopotamus", [Epithet, Animal, Positive], 1],
    ["Hog", [Epithet, Animal, Negative], 1],
    ["Holy", [Epithet, Good], 1],
    ["Honest", [Epithet, Personality], 1],
    ["Honorable", [Epithet, Good], 1],
    ["Honorable", [Epithet, Personality], 1],
    ["Hornet", [Epithet, Animal, Negative], 1],
    ["Horrid", [Epithet, Draconic], 1],
    ["Horrific", [Epithet, Demonic], 1],
    ["Horror", [Epithet, Demonic], 1],
    ["Horse", [Epithet, Animal, Positive], 1],
    ["Hospitable", [Epithet, Personality], 1],
    ["Hostile", [Epithet, Personality], 1],
    ["Hothead", [Epithet, Personality], 1],
    ["Hound", [Epithet, Animal, Negative], 1],
    ["Hound", [Epithet, Animal, Positive], 1],
    ["Howler", [Epithet, Demonic], 1],
    ["Humble", [Epithet, Good], 1],
    ["Humble", [Epithet, Personality], 1],
    ["Hummingbird", [Epithet, Animal, Positive], 1],
    ["Hunter", [Epithet, Demonic], 1],
    ["Hydra", [Epithet, Animal, Negative], 1],
    ["Hyena", [Epithet, Animal, Negative], 1],
    ["Ibex", [Epithet, Animal, Positive], 1],
    ["Igniter", [Epithet, Demonic], 1],
    ["Iguana", [Epithet, Animal, Positive], 1],
    ["Immodest", [Epithet, Personality], 1],
    ["Impala", [Epithet, Animal, Positive], 1],
    ["Impartial", [Epithet, Good], 1],
    ["Impartial", [Epithet, Personality], 1],
    ["Impatient", [Epithet, Personality], 1],
    ["Implacable", [Epithet, Good], 1],
    ["Implanter", [Epithet, Demonic], 1],
    ["Impolite", [Epithet, Personality], 1],
    ["Impractical", [Epithet, Personality], 1],
    ["Impulsive", [Epithet, Personality], 1],
    ["Inciter", [Epithet, Demonic], 1],
    ["Incoherent", [Epithet, Personality], 1],
    ["Incompetent", [Epithet, Personality], 1],
    ["Inconsiderate", [Epithet, Personality], 1],
    ["Inconsistent", [Epithet, Personality], 1],
    ["Indecisive", [Epithet, Personality], 1],
    ["Indenturer", [Epithet, Demonic], 1],
    ["Indifferent", [Epithet, Personality], 1],
    ["Indiscrete", [Epithet, Personality], 1],
    ["Indolent", [Epithet, Draconic], 1],
    ["Indolent", [Epithet, Personality], 1],
    ["Industrious", [Epithet, Personality], 1],
    ["Inevitable", [Epithet, Demonic], 1],
    ["Inexorable", [Epithet, Good], 1],
    ["Inflexible", [Epithet, Personality], 1],
    ["Influencer", [Epithet, Demonic], 1],
    ["Inimical", [Epithet, Demonic], 1],
    ["Innocent", [Epithet, Personality], 1],
    ["Inquisitive", [Epithet, Personality], 1],
    ["Insane", [Epithet, Personality], 1],
    ["Insecure", [Epithet, Personality], 1],
    ["Insensitive", [Epithet, Personality], 1],
    ["Insightful", [Epithet, Personality], 1],
    ["Insincere", [Epithet, Personality], 1],
    ["Insipid", [Epithet, Personality], 1],
    ["Inspirer", [Epithet, Good], 1],
    ["Intelligent", [Epithet, Personality], 1],
    ["Intense", [Epithet, Personality], 1],
    ["Interloper", [Epithet, Demonic], 1],
    ["Interposer", [Epithet, Demonic], 1],
    ["Intimidating", [Epithet, Personality], 1],
    ["Intolerant", [Epithet, Personality], 1],
    ["Intrepid", [Epithet, Personality], 1],
    ["Introspective", [Epithet, Personality], 1],
    ["Introverted", [Epithet, Personality], 1],
    ["Intruder", [Epithet, Demonic], 1],
    ["Intuitive", [Epithet, Personality], 1],
    ["Invader", [Epithet, Demonic], 1],
    ["Inventive", [Epithet, Personality], 1],
    ["Irascible", [Epithet, Draconic], 1],
    ["Irresolute", [Epithet, Personality], 1],
    ["Irresponsible", [Epithet, Personality], 1],
    ["Irreverent", [Epithet, Personality], 1],
    ["Irritable", [Epithet, Personality], 1],
    ["Irritating", [Epithet, Personality], 1],
    ["Jackal", [Epithet, Animal, Negative], 1],
    ["Jaded", [Epithet, Personality], 1],
    ["Jaguar", [Epithet, Animal, Negative], 1],
    ["Jangler", [Epithet, Demonic], 1],
    ["Jealous", [Epithet, Personality], 1],
    ["Jolly", [Epithet, Personality], 1],
    ["Jovial", [Epithet, Personality], 1],
    ["Just", [Epithet, Good], 1],
    ["Keen", [Epithet, Personality], 1],
    ["Kestrel", [Epithet, Animal, Positive], 1],
    ["Kind", [Epithet, Good], 1],
    ["Kindhearted", [Epithet, Personality], 1],
    ["Kindler", [Epithet, Demonic], 1],
    ["Kindly", [Epithet, Good], 1],
    ["Knowledgeable", [Epithet, Personality], 1],
    ["Lamb", [Epithet, Animal, Positive], 1],
    ["Languid", [Epithet, Personality], 1],
    ["Laugher", [Epithet, Demonic], 1],
    ["Lawful", [Epithet, Good], 1],
    ["Lemur", [Epithet, Animal, Positive], 1],
    ["Lenient", [Epithet, Good], 1],
    ["Leopard", [Epithet, Animal, Negative], 1],
    ["Leopard", [Epithet, Animal, Positive], 1],
    ["Lethargic", [Epithet, Personality], 1],
    ["Levelheaded", [Epithet, Personality], 1],
    ["Liar", [Epithet, Personality], 1],
    ["Liberator", [Epithet, Good], 1],
    ["Limper", [Epithet, Demonic], 1],
    ["Lion", [Epithet, Animal, Positive], 1],
    ["List", [Epithet, Demonic], 1],
    ["Lively", [Epithet, Personality], 1],
    ["Lizard", [Epithet, Animal, Negative], 1],
    ["Logical", [Epithet, Personality], 1],
    ["Looter", [Epithet, Demonic], 1],
    ["Lordly", [Epithet, Personality], 1],
    ["Loud", [Epithet, Personality], 1],
    ["Lovable", [Epithet, Personality], 1],
    ["Loving", [Epithet, Personality], 1],
    ["Loyal", [Epithet, Personality], 1],
    ["Lunatic", [Epithet, Personality], 1],
    ["Lynx", [Epithet, Animal, Positive], 1],
    ["Mad", [Epithet, Demonic], 1],
    ["Mad", [Epithet, Personality], 1],
    ["Maggot", [Epithet, Animal, Negative], 1],
    ["Majestic", [Epithet, Good], 1],
    ["Maker", [Epithet, Demonic], 1],
    ["Malicious", [Epithet, Draconic], 1],
    ["Malicious", [Epithet, Personality], 1],
    ["Manipulative", [Epithet, Draconic], 1],
    ["Manipulative", [Epithet, Personality], 1],
    ["Mannerly", [Epithet, Personality], 1],
    ["Manticore", [Epithet, Animal, Negative], 1],
    ["Marauder", [Epithet, Demonic], 1],
    ["Mastiff", [Epithet, Animal, Positive], 1],
    ["Mean", [Epithet, Personality], 1],
    ["Meddler", [Epithet, Demonic], 1],
    ["Meek", [Epithet, Personality], 1],
    ["Melancholy", [Epithet, Personality], 1],
    ["Melter", [Epithet, Demonic], 1],
    ["Merciful", [Epithet, Good], 1],
    ["Merciful", [Epithet, Personality], 1],
    ["Mercurial", [Epithet, Personality], 1],
    ["Meticulous", [Epithet, Personality], 1],
    ["Mild", [Epithet, Good], 1],
    ["Mild", [Epithet, Personality], 1],
    ["Mimic", [Epithet, Animal, Negative], 1],
    ["Minder", [Epithet, Demonic], 1],
    ["Mischievous", [Epithet, Personality], 1],
    ["Miserly", [Epithet, Draconic], 1],
    ["Miserly", [Epithet, Personality], 1],
    ["Modest", [Epithet, Personality], 1],
    ["Mole", [Epithet, Animal, Negative], 1],
    ["Mole", [Epithet, Animal, Positive], 1],
    ["Mongoose", [Epithet, Animal, Positive], 1],
    ["Monkey", [Epithet, Animal, Negative], 1],
    ["Monkey", [Epithet, Animal, Positive], 1],
    ["Moody", [Epithet, Personality], 1],
    ["Moose", [Epithet, Animal, Positive], 1],
    ["Moral", [Epithet, Good], 1],
    ["Moth", [Epithet, Animal, Negative], 1],
    ["Mouse", [Epithet, Animal, Negative], 1],
    ["Mouse", [Epithet, Animal, Positive], 1],
    ["Mule", [Epithet, Animal, Positive], 1],
    ["Mushroom", [Epithet, Animal, Negative], 1],
    ["Muskrat", [Epithet, Animal, Positive], 1],
    ["Mysterious", [Epithet, Personality], 1],
    ["Negligent", [Epithet, Personality], 1],
    ["Nervous", [Epithet, Personality], 1],
    ["Neurotic", [Epithet, Personality], 1],
    ["Newt", [Epithet, Animal, Negative], 1],
    ["Newt", [Epithet, Animal, Positive], 1],
    ["Noble", [Epithet, Personality], 1],
    ["Obliging", [Epithet, Personality], 1],
    ["Obnoxious", [Epithet, Personality], 1],
    ["Obsequious", [Epithet, Personality], 1],
    ["Observant", [Epithet, Personality], 1],
    ["Observer", [Epithet, Demonic], 1],
    ["Obstinate", [Epithet, Personality], 1],
    ["Ocelot", [Epithet, Animal, Positive], 1],
    ["Octopus", [Epithet, Animal, Negative], 1],
    ["Octopus", [Epithet, Animal, Positive], 1],
    ["Odd", [Epithet, Personality], 1],
    ["Odious", [Epithet, Personality], 1],
    ["One", [Epithet, Demonic], 1],
    ["One", [Epithet, Demonic], 1],
    ["Opossum", [Epithet, Animal, Positive], 1],
    ["Ostentatious", [Epithet, Personality], 1],
    ["Ostrich", [Epithet, Animal, Positive], 1],
    ["Otter", [Epithet, Animal, Positive], 1],
    ["Outgoing", [Epithet, Personality], 1],
    ["Outrageous", [Epithet, Personality], 1],
    ["Outspoken", [Epithet, Personality], 1],
    ["Overbearing", [Epithet, Personality], 1],
    ["Owl", [Epithet, Animal, Positive], 1],
    ["Ox", [Epithet, Animal, Positive], 1],
    ["Pacifist", [Epithet, Personality], 1],
    ["Panther", [Epithet, Animal, Negative], 1],
    ["Panther", [Epithet, Animal, Positive], 1],
    ["Parakeet", [Epithet, Animal, Positive], 1],
    ["Parrot", [Epithet, Animal, Negative], 1],
    ["Parrot", [Epithet, Animal, Positive], 1],
    ["Passionate", [Epithet, Personality], 1],
    ["Passive", [Epithet, Personality], 1],
    ["Patient", [Epithet, Personality], 1],
    ["Peaceful", [Epithet, Personality], 1],
    ["Peacock", [Epithet, Animal, Negative], 1],
    ["Peacock", [Epithet, Animal, Positive], 1],
    ["Pegasus", [Epithet, Animal, Positive], 1],
    ["Pelican", [Epithet, Animal, Positive], 1],
    ["Persevering", [Epithet, Personality], 1],
    ["Persistent", [Epithet, Personality], 1],
    ["Persuader", [Epithet, Demonic], 1],
    ["Persuasive", [Epithet, Personality], 1],
    ["Perverse", [Epithet, Personality], 1],
    ["Pessimist", [Epithet, Personality], 1],
    ["Petty", [Epithet, Personality], 1],
    ["Petulant", [Epithet, Personality], 1],
    ["Pheasant", [Epithet, Animal, Positive], 1],
    ["Philanthropist", [Epithet, Personality], 1],
    ["Piercer", [Epithet, Demonic], 1],
    ["Pig", [Epithet, Animal, Negative], 1],
    ["Pigeon", [Epithet, Animal, Positive], 1],
    ["Pillager", [Epithet, Demonic], 1],
    ["Pious", [Epithet, Good], 1],
    ["Pious", [Epithet, Personality], 1],
    ["Placid", [Epithet, Personality], 1],
    ["Pleasant", [Epithet, Personality], 1],
    ["Plunderer", [Epithet, Demonic], 1],
    ["Poisoned", [Epithet, Demonic], 1],
    ["Poisoner", [Epithet, Demonic], 1],
    ["Polymorpher", [Epithet, Demonic], 1],
    ["Pompous", [Epithet, Personality], 1],
    ["Popular", [Epithet, Personality], 1],
    ["Porcupine", [Epithet, Animal, Negative], 1],
    ["Porcupine", [Epithet, Animal, Positive], 1],
    ["Possessive", [Epithet, Personality], 1],
    ["Praiseworthy", [Epithet, Good], 1],
    ["Preserver", [Epithet, Good], 1],
    ["Pretentious", [Epithet, Personality], 1],
    ["Profane", [Epithet, Draconic], 1],
    ["Profane", [Epithet, Personality], 1],
    ["Protector", [Epithet, Good], 1],
    ["Protector", [Epithet, Good], 1],
    ["Proud", [Epithet, Draconic], 1],
    ["Proud", [Epithet, Personality], 1],
    ["Prowler", [Epithet, Demonic], 1],
    ["Prudent", [Epithet, Personality], 1],
    ["Pure", [Epithet, Good], 1],
    ["Pursuer", [Epithet, Demonic], 1],
    ["Pursuer", [Epithet, Good], 1],
    ["Python", [Epithet, Animal, Negative], 1],
    ["Quail", [Epithet, Animal, Positive], 1],
    ["Quarrelsome", [Epithet, Personality], 1],
    ["Questioner", [Epithet, Demonic], 1],
    ["Quick", [Epithet, Personality], 1],
    ["Quiet", [Epithet, Personality], 1],
    ["Rabbit", [Epithet, Animal, Positive], 1],
    ["Raccoon", [Epithet, Animal, Positive], 1],
    ["Raider", [Epithet, Demonic], 1],
    ["Ram", [Epithet, Animal, Negative], 1],
    ["Ram", [Epithet, Animal, Positive], 1],
    ["Ransacker", [Epithet, Demonic], 1],
    ["Rash", [Epithet, Draconic], 1],
    ["Rash", [Epithet, Personality], 1],
    ["Rat", [Epithet, Animal, Negative], 1],
    ["Reckless", [Epithet, Draconic], 1],
    ["Reckless", [Epithet, Personality], 1],
    ["Reclusive", [Epithet, Draconic], 1],
    ["Reclusive", [Epithet, Personality], 1],
    ["Recoverer", [Epithet, Good], 1],
    ["Redeemer", [Epithet, Good], 1],
    ["Refined", [Epithet, Personality], 1],
    ["Reformer", [Epithet, Good], 1],
    ["Reindeer", [Epithet, Animal, Positive], 1],
    ["Releaser", [Epithet, Good], 1],
    ["Reluctant", [Epithet, Personality], 1],
    ["Remaker", [Epithet, Demonic], 1],
    ["Reptile", [Epithet, Animal, Negative], 1],
    ["Rescuer", [Epithet, Good], 1],
    ["Resentful", [Epithet, Personality], 1],
    ["Resolute", [Epithet, Good], 1],
    ["Resolute", [Epithet, Good], 1],
    ["Resolute", [Epithet, Personality], 1],
    ["Resolver", [Epithet, Good], 1],
    ["Resourceful", [Epithet, Personality], 1],
    ["Respectful", [Epithet, Personality], 1],
    ["Restless", [Epithet, Personality], 1],
    ["Restrainer", [Epithet, Demonic], 1],
    ["Revered", [Epithet, Good], 1],
    ["Rhinoceros", [Epithet, Animal, Negative], 1],
    ["Rhinoceros", [Epithet, Animal, Positive], 1],
    ["Righteous", [Epithet, Good], 1],
    ["Righteous", [Epithet, Personality], 1],
    ["Roach", [Epithet, Animal, Negative], 1],
    ["Robber", [Epithet, Demonic], 1],
    ["Rodent", [Epithet, Animal, Negative], 1],
    ["Rooster", [Epithet, Animal, Negative], 1],
    ["Rooster", [Epithet, Animal, Positive], 1],
    ["Rude", [Epithet, Personality], 1],
    ["Ruthless", [Epithet, Personality], 1],
    ["Sad", [Epithet, Personality], 1],
    ["Sage", [Epithet, Personality], 1],
    ["Saintly", [Epithet, Good], 1],
    ["Saintly", [Epithet, Personality], 1],
    ["Salamander", [Epithet, Animal, Negative], 1],
    ["Salamander", [Epithet, Animal, Positive], 1],
    ["Sanctified", [Epithet, Good], 1],
    ["Sanctified", [Epithet, Good], 1],
    ["Sanctimonious", [Epithet, Personality], 1],
    ["Satyr", [Epithet, Animal, Positive], 1],
    ["Scarab", [Epithet, Animal, Negative], 1],
    ["Scatterbrained", [Epithet, Personality], 1],
    ["Scheming", [Epithet, Draconic], 1],
    ["Scheming", [Epithet, Personality], 1],
    ["Scorcher", [Epithet, Demonic], 1],
    ["Scornful", [Epithet, Draconic], 1],
    ["Scornful", [Epithet, Personality], 1],
    ["Scourge", [Epithet, Demonic], 1],
    ["Scourger", [Epithet, Demonic], 1],
    ["Scratcher", [Epithet, Demonic], 1],
    ["Scrupulous", [Epithet, Good], 1],
    ["Scrutinizer", [Epithet, Demonic], 1],
    ["Scrutinizer", [Epithet, Demonic], 1],
    ["Scryer", [Epithet, Demonic], 1],
    ["Seal", [Epithet, Animal, Positive], 1],
    ["Secretive", [Epithet, Draconic], 1],
    ["Secretive", [Epithet, Personality], 1],
    ["Sedate", [Epithet, Personality], 1],
    ["Seeker", [Epithet, Demonic], 1],
    ["Seizer", [Epithet, Demonic], 1],
    ["Selfish", [Epithet, Draconic], 1],
    ["Selfish", [Epithet, Personality], 1],
    ["Selfless", [Epithet, Personality], 1],
    ["Sentimental", [Epithet, Personality], 1],
    ["Serene", [Epithet, Personality], 1],
    ["Serious", [Epithet, Personality], 1],
    ["Serpent", [Epithet, Animal, Negative], 1],
    ["Serpentine", [Epithet, Animal, Negative], 1],
    ["Shadow", [Epithet, Demonic], 1],
    ["Shallow", [Epithet, Personality], 1],
    ["Shameless", [Epithet, Personality], 1],
    ["Shapeshifter", [Epithet, Demonic], 1],
    ["Shark", [Epithet, Animal, Negative], 1],
    ["Sharp-Tongued", [Epithet, Personality], 1],
    ["Sharp-Witted", [Epithet, Personality], 1],
    ["Shatterer", [Epithet, Demonic], 1],
    ["Sheep", [Epithet, Animal, Positive], 1],
    ["Shifter", [Epithet, Demonic], 1],
    ["Shifty", [Epithet, Personality], 1],
    ["Shrew", [Epithet, Animal, Negative], 1],
    ["Shrewd", [Epithet, Personality], 1],
    ["Shrieker", [Epithet, Demonic], 1],
    ["Shrike", [Epithet, Animal, Negative], 1],
    ["Shriveler", [Epithet, Demonic], 1],
    ["Shy", [Epithet, Personality], 1],
    ["Sickly", [Epithet, Personality], 1],
    ["Sickness-Bringer", [Epithet, Demonic], 1],
    ["Silent", [Epithet, Personality], 1],
    ["Sin-Bringer", [Epithet, Demonic], 1],
    ["Sincere", [Epithet, Good], 1],
    ["Sincere", [Epithet, Personality], 1],
    ["Skillful", [Epithet, Personality], 1],
    ["Skunk", [Epithet, Animal, Negative], 1],
    ["Slayer", [Epithet, Demonic], 1],
    ["Slime", [Epithet, Animal, Negative], 1],
    ["Slow", [Epithet, Personality], 1],
    ["Slug", [Epithet, Animal, Negative], 1],
    ["Sly", [Epithet, Personality], 1],
    ["Snail", [Epithet, Animal, Negative], 1],
    ["Snake", [Epithet, Animal, Negative], 1],
    ["Sneaky", [Epithet, Personality], 1],
    ["Sociable", [Epithet, Personality], 1],
    ["Soft-Spoken", [Epithet, Personality], 1],
    ["Solitary", [Epithet, Personality], 1],
    ["Sour", [Epithet, Personality], 1],
    ["Sparrow", [Epithet, Animal, Positive], 1],
    ["Spendthrift", [Epithet, Personality], 1],
    ["Spider", [Epithet, Animal, Negative], 1],
    ["Spined", [Epithet, Demonic], 1],
    ["Spiritual", [Epithet, Good], 1],
    ["Spiteful", [Epithet, Personality], 1],
    ["Spoiled", [Epithet, Personality], 1],
    ["Squeamish", [Epithet, Personality], 1],
    ["Stag", [Epithet, Animal, Positive], 1],
    ["Stalker", [Epithet, Demonic], 1],
    ["Stately", [Epithet, Personality], 1],
    ["Steadfast", [Epithet, Personality], 1],
    ["Stern", [Epithet, Personality], 1],
    ["Stingy", [Epithet, Personality], 1],
    ["Stolid", [Epithet, Personality], 1],
    ["Strange", [Epithet, Personality], 1],
    ["Strict", [Epithet, Good], 1],
    ["Strict", [Epithet, Personality], 1],
    ["Strident", [Epithet, Personality], 1],
    ["Stringent", [Epithet, Good], 1],
    ["Strong", [Epithet, Personality], 1],
    ["Stubborn", [Epithet, Personality], 1],
    ["Studious", [Epithet, Personality], 1],
    ["Sublime", [Epithet, Good], 1],
    ["Succinct", [Epithet, Personality], 1],
    ["Sulky", [Epithet, Personality], 1],
    ["Sullen", [Epithet, Personality], 1],
    ["Superstitious", [Epithet, Personality], 1],
    ["Surly", [Epithet, Personality], 1],
    ["Suspicious", [Epithet, Personality], 1],
    ["Sustainer", [Epithet, Good], 1],
    ["Sweet", [Epithet, Personality], 1],
    ["Sylph", [Epithet, Animal, Positive], 1],
    ["Sympathetic", [Epithet, Personality], 1],
    ["Taciturn", [Epithet, Personality], 1],
    ["Tactful", [Epithet, Personality], 1],
    ["Tactless", [Epithet, Personality], 1],
    ["Taker", [Epithet, Demonic], 1],
    ["Talented", [Epithet, Personality], 1],
    ["Talkative", [Epithet, Personality], 1],
    ["Talon", [Epithet, Demonic], 1],
    ["Tamperer", [Epithet, Demonic], 1],
    ["Tangler", [Epithet, Demonic], 1],
    ["Tarantula", [Epithet, Animal, Negative], 1],
    ["Tardy", [Epithet, Personality], 1],
    ["Tasteless", [Epithet, Personality], 1],
    ["Temperamental", [Epithet, Personality], 1],
    ["Temperate", [Epithet, Personality], 1],
    ["Tempter", [Epithet, Demonic], 1],
    ["Tenacious", [Epithet, Personality], 1],
    ["Tense", [Epithet, Personality], 1],
    ["Thorough", [Epithet, Personality], 1],
    ["Thoughtful", [Epithet, Personality], 1],
    ["Thoughtless", [Epithet, Personality], 1],
    ["Threatening", [Epithet, Personality], 1],
    ["Thrifty", [Epithet, Personality], 1],
    ["Thrush", [Epithet, Animal, Positive], 1],
    ["Tiger", [Epithet, Animal, Negative], 1],
    ["Timid", [Epithet, Personality], 1],
    ["Tireless", [Epithet, Personality], 1],
    ["Tiresome", [Epithet, Personality], 1],
    ["Toad", [Epithet, Animal, Negative], 1],
    ["Toadstool", [Epithet, Animal, Negative], 1],
    ["Tolerant", [Epithet, Personality], 1],
    ["Tormentor", [Epithet, Demonic], 1],
    ["Trapper", [Epithet, Demonic], 1],
    ["Trapper", [Epithet, Demonic], 1],
    ["Traveler", [Epithet, Demonic], 1],
    ["Troll", [Epithet, Animal, Negative], 1],
    ["Troubled", [Epithet, Personality], 1],
    ["Truculent", [Epithet, Personality], 1],
    ["True", [Epithet, Good], 1],
    ["Trusting", [Epithet, Personality], 1],
    ["Trustworthy", [Epithet, Personality], 1],
    ["Turtle", [Epithet, Animal, Positive], 1],
    ["Twister", [Epithet, Demonic], 1],
    ["Unappreciative", [Epithet, Personality], 1],
    ["Unassuming", [Epithet, Personality], 1],
    ["Unbending", [Epithet, Good], 1],
    ["Unconventional", [Epithet, Personality], 1],
    ["Uncooperative", [Epithet, Personality], 1],
    ["Uncoordinated", [Epithet, Personality], 1],
    ["Uncouth", [Epithet, Personality], 1],
    ["Undependable", [Epithet, Personality], 1],
    ["Understanding", [Epithet, Personality], 1],
    ["Undeviating", [Epithet, Good], 1],
    ["Undisciplined", [Epithet, Personality], 1],
    ["Unearther", [Epithet, Demonic], 1],
    ["Unerring", [Epithet, Demonic], 1],
    ["Unfeeling", [Epithet, Personality], 1],
    ["Unflinching", [Epithet, Good], 1],
    ["Unfocused", [Epithet, Personality], 1],
    ["Unforgiving", [Epithet, Personality], 1],
    ["Unfriendly", [Epithet, Personality], 1],
    ["Ungrateful", [Epithet, Personality], 1],
    ["Unhealthy", [Epithet, Demonic], 1],
    ["Unhelpful", [Epithet, Personality], 1],
    ["Unicorn", [Epithet, Animal, Positive], 1],
    ["Uninhibited", [Epithet, Personality], 1],
    ["Unkind", [Epithet, Personality], 1],
    ["Unmaker", [Epithet, Demonic], 1],
    ["Unminder", [Epithet, Demonic], 1],
    ["Unraveler", [Epithet, Demonic], 1],
    ["Unruly", [Epithet, Personality], 1],
    ["Unscrupulous", [Epithet, Personality], 1],
    ["Unselfish", [Epithet, Personality], 1],
    ["Unsympathetic", [Epithet, Personality], 1],
    ["Untainted", [Epithet, Good], 1],
    ["Untrustworthy", [Epithet, Personality], 1],
    ["Unwilling", [Epithet, Personality], 1],
    ["Unwise", [Epithet, Personality], 1],
    ["Unyielding", [Epithet, Good], 1],
    ["Upright", [Epithet, Good], 1],
    ["Vain", [Epithet, Personality], 1],
    ["Valiant", [Epithet, Good], 1],
    ["Valiant", [Epithet, Personality], 1],
    ["Valorous", [Epithet, Good], 1],
    ["Vengeful", [Epithet, Personality], 1],
    ["Venomous", [Epithet, Personality], 1],
    ["Verbose", [Epithet, Personality], 1],
    ["Vicious", [Epithet, Draconic], 1],
    ["Vile", [Epithet, Draconic], 1],
    ["Vindictive", [Epithet, Personality], 1],
    ["Viper", [Epithet, Animal, Negative], 1],
    ["Virtuous", [Epithet, Good], 1],
    ["Virtuous", [Epithet, Good], 1],
    ["Virtuous", [Epithet, Personality], 1],
    ["Volatile", [Epithet, Personality], 1],
    ["Vulture", [Epithet, Animal, Negative], 1],
    ["Walrus", [Epithet, Animal, Positive], 1],
    ["Wanderer", [Epithet, Demonic], 1],
    ["War-Bringer", [Epithet, Demonic], 1],
    ["War-Maker", [Epithet, Demonic], 1],
    ["War-Weaver", [Epithet, Demonic], 1],
    ["Warlike", [Epithet, Personality], 1],
    ["Warper", [Epithet, Demonic], 1],
    ["Warthog", [Epithet, Animal, Negative], 1],
    ["Wary", [Epithet, Personality], 1],
    ["Wasp", [Epithet, Animal, Negative], 1],
    ["Waster", [Epithet, Demonic], 1],
    ["Watcher", [Epithet, Good], 1],
    ["Waylayer", [Epithet, Demonic], 1],
    ["Weary", [Epithet, Personality], 1],
    ["Weasel", [Epithet, Animal, Negative], 1],
    ["Web-Weaver", [Epithet, Demonic], 1],
    ["Well-born", [Epithet, Good], 1],
    ["Whimsical", [Epithet, Personality], 1],
    ["Willed", [Epithet, Personality], 1],
    ["Winnower", [Epithet, Demonic], 1],
    ["Winnower", [Epithet, Good], 1],
    ["Wise", [Epithet, Good], 1],
    ["Wise", [Epithet, Personality], 1],
    ["Witherer", [Epithet, Demonic], 1],
    ["Wolf", [Epithet, Animal, Negative], 1],
    ["Wolverine", [Epithet, Animal, Negative], 1],
    ["Worm", [Epithet, Animal, Negative], 1],
    ["Worm", [Epithet, Demonic], 1],
    ["Worthy", [Epithet, Good], 1],
    ["Wraith", [Epithet, Animal, Negative], 1],
    ["Wyrm", [Epithet, Animal, Negative], 1],
    ["Xenophobic", [Epithet, Personality], 1],
    ["Yak", [Epithet, Animal, Positive], 1],
]

// DOMINION EPITHETS
// A dominion epithet refers to something the person controls

// Table 28-14: Dominion Epithet Introduction

const DominionTemplates = [
    `Master (or Mistress) of`,
    `Lord (or Lady) of`,
    `King (or Queen) of`,
]

// Table 28-15: Evil Dominion Epithets

const DominionList = [
    ["Chaos", [Epithet, Dominion], 1],
    ["Scorching", [Epithet, Dominion], 1],
    ["Binding", [Epithet, Dominion], 1],
    ["Scratching", [Epithet, Dominion], 1],
    ["Biting", [Epithet, Dominion], 1],
    ["Scrutiny", [Epithet, Dominion], 1],
    ["Breaking", [Epithet, Dominion], 1],
    ["Scrying", [Epithet, Dominion], 1],
    ["Burial", [Epithet, Dominion], 1],
    ["Seeking", [Epithet, Dominion], 1],
    ["Burning", [Epithet, Dominion], 1],
    ["Seizing", [Epithet, Dominion], 1],
    ["Cackling", [Epithet, Dominion], 1],
    ["Shadows", [Epithet, Dominion], 1],
    ["Cajolement", [Epithet, Dominion], 1],
    ["Shapeshifting", [Epithet, Dominion], 1],
    ["Claws", [Epithet, Dominion], 1],
    ["Shrieking", [Epithet, Dominion], 1],
    ["Collapse", [Epithet, Dominion], 1],
    ["Shriveling", [Epithet, Dominion], 1],
    ["Fire", [Epithet, Dominion], 1],
    ["Sickness", [Epithet, Dominion], 1],
    ["Flame", [Epithet, Dominion], 1],
    ["Sins", [Epithet, Dominion], 1],
    ["Constraint", [Epithet, Dominion], 1],
    ["Stalking", [Epithet, Dominion], 1],
    ["Curses", [Epithet, Dominion], 1],
    ["Taking", [Epithet, Dominion], 1],
    ["Darkness", [Epithet, Dominion], 1],
    ["Slaying", [Epithet, Dominion], 1],
    ["Death", [Epithet, Dominion], 1],
    ["Talons", [Epithet, Dominion], 1],
    ["Decay", [Epithet, Dominion], 1],
    ["Entanglement", [Epithet, Dominion], 1],
    ["Deceit", [Epithet, Dominion], 1],
    ["Tangling", [Epithet, Dominion], 1],
    ["Imposture", [Epithet, Dominion], 1],
    ["Temptation", [Epithet, Dominion], 1],
    ["Descent", [Epithet, Dominion], 1],
    ["Tempting", [Epithet, Dominion], 1],
    ["Despoilment", [Epithet, Dominion], 1],
    ["Torment", [Epithet, Dominion], 1],
    ["Destruction", [Epithet, Dominion], 1],
    ["Traps", [Epithet, Dominion], 1],
    ["Disease", [Epithet, Dominion], 1],
    ["The Unearthed", [Epithet, Dominion], 1],
    ["Displacement", [Epithet, Dominion], 1],
    ["The Unhealthy", [Epithet, Dominion], 1],
    ["Dissuasion", [Epithet, Dominion], 1],
    ["Unmaking", [Epithet, Dominion], 1],
    ["Famine", [Epithet, Dominion], 1],
    ["Unraveling", [Epithet, Dominion], 1],
    ["Ghouls", [Epithet, Dominion], 1],
    ["War", [Epithet, Dominion], 1],
    ["Ghasts", [Epithet, Dominion], 1],
    ["Warfare", [Epithet, Dominion], 1],
    ["Wraiths", [Epithet, Dominion], 1],
    ["Waste", [Epithet, Dominion], 1],
    ["Wights", [Epithet, Dominion], 1],
    ["Waylaying", [Epithet, Dominion], 1],
    ["Specters", [Epithet, Dominion], 1],
    ["Ambush", [Epithet, Dominion], 1],
    ["Zombies", [Epithet, Dominion], 1],
    ["Winnowing", [Epithet, Dominion], 1],
    ["Skeletons", [Epithet, Dominion], 1],
    ["Withering", [Epithet, Dominion], 1],
    ["Haunting", [Epithet, Dominion], 1],
    ["Beak", [Epithet, Dominion], 1],
    ["Horror", [Epithet, Dominion], 1],
    ["Blight", [Epithet, Dominion], 1],
    ["Howling", [Epithet, Dominion], 1],
    ["Enfeeblement", [Epithet, Dominion], 1],
    ["Hunting", [Epithet, Dominion], 1],
    ["Weakness", [Epithet, Dominion], 1],
    ["Invasions", [Epithet, Dominion], 1],
    ["Plague", [Epithet, Dominion], 1],
    ["Loot", [Epithet, Dominion], 1],
    ["Fever", [Epithet, Dominion], 1],
    ["Pillage", [Epithet, Dominion], 1],
    ["Winter", [Epithet, Dominion], 1],
    ["Madness", [Epithet, Dominion], 1],
    ["Cold", [Epithet, Dominion], 1],
    ["Marauders", [Epithet, Dominion], 1],
    ["Screams", [Epithet, Dominion], 1],
    ["Meddling", [Epithet, Dominion], 1],
    ["Forgery", [Epithet, Dominion], 1],
    ["Persuasion", [Epithet, Dominion], 1],
    ["Murder", [Epithet, Dominion], 1],
    ["Piercing", [Epithet, Dominion], 1],
    ["Assassins", [Epithet, Dominion], 1],
    ["Plundering", [Epithet, Dominion], 1],
    ["Thieves", [Epithet, Dominion], 1],
    ["Plunder", [Epithet, Dominion], 1],
    ["Witchery", [Epithet, Dominion], 1],
    ["Poison", [Epithet, Dominion], 1],
    ["Witchcraft", [Epithet, Dominion], 1],
    ["Pursuit", [Epithet, Dominion], 1],
    ["Lies", [Epithet, Dominion], 1],
    ["Raids", [Epithet, Dominion], 1],
    ["Carrion", [Epithet, Dominion], 1],
]

