// AUTO-GENERATED by scripts/generateHexTransitionsConfig.ts — do not edit manually

import type { TerrainType, HexCorner } from "./types"

export type TileConfig = {
  src: string
  corners: Record<HexCorner, TerrainType>
}

export const TILES: TileConfig[] = [
  {
    src: "/hexTiles/five.svg",
    corners: {
      TR: "forest",
      R: "forest",
      BR: "forest",
      BL: "forest",
      L: "plains",
      TL: "plains"
    }
  },
  {
    src: "/hexTiles/five_coast_plains.svg",
    corners: {
      TR: "plains",
      R: "plains",
      BR: "plains",
      BL: "plains",
      L: "coast",
      TL: "coast"
    }
  },
  {
    src: "/hexTiles/five_coast_plains_r060.svg",
    corners: {
      TR: "coast",
      R: "plains",
      BR: "plains",
      BL: "plains",
      L: "plains",
      TL: "coast"
    }
  },
  {
    src: "/hexTiles/five_coast_plains_r120.svg",
    corners: {
      TR: "coast",
      R: "coast",
      BR: "plains",
      BL: "plains",
      L: "plains",
      TL: "plains"
    }
  },
  {
    src: "/hexTiles/five_coast_plains_r180.svg",
    corners: {
      TR: "plains",
      R: "coast",
      BR: "coast",
      BL: "plains",
      L: "plains",
      TL: "plains"
    }
  },
  {
    src: "/hexTiles/five_coast_plains_r240.svg",
    corners: {
      TR: "plains",
      R: "plains",
      BR: "coast",
      BL: "coast",
      L: "plains",
      TL: "plains"
    }
  },
  {
    src: "/hexTiles/five_coast_plains_r300.svg",
    corners: {
      TR: "plains",
      R: "plains",
      BR: "plains",
      BL: "coast",
      L: "coast",
      TL: "plains"
    }
  },
  {
    src: "/hexTiles/five_coast_swamp.svg",
    corners: {
      TR: "swamp",
      R: "swamp",
      BR: "swamp",
      BL: "swamp",
      L: "coast",
      TL: "coast"
    }
  },
  {
    src: "/hexTiles/five_coast_swamp_r060.svg",
    corners: {
      TR: "coast",
      R: "swamp",
      BR: "swamp",
      BL: "swamp",
      L: "swamp",
      TL: "coast"
    }
  },
  {
    src: "/hexTiles/five_coast_swamp_r120.svg",
    corners: {
      TR: "coast",
      R: "coast",
      BR: "swamp",
      BL: "swamp",
      L: "swamp",
      TL: "swamp"
    }
  },
  {
    src: "/hexTiles/five_coast_swamp_r180.svg",
    corners: {
      TR: "swamp",
      R: "coast",
      BR: "coast",
      BL: "swamp",
      L: "swamp",
      TL: "swamp"
    }
  },
  {
    src: "/hexTiles/five_coast_swamp_r240.svg",
    corners: {
      TR: "swamp",
      R: "swamp",
      BR: "coast",
      BL: "coast",
      L: "swamp",
      TL: "swamp"
    }
  },
  {
    src: "/hexTiles/five_coast_swamp_r300.svg",
    corners: {
      TR: "swamp",
      R: "swamp",
      BR: "swamp",
      BL: "coast",
      L: "coast",
      TL: "swamp"
    }
  },
  {
    src: "/hexTiles/five_forest_hills.svg",
    corners: {
      TR: "hills",
      R: "hills",
      BR: "hills",
      BL: "hills",
      L: "forest",
      TL: "forest"
    }
  },
  {
    src: "/hexTiles/five_forest_hills_r060.svg",
    corners: {
      TR: "forest",
      R: "hills",
      BR: "hills",
      BL: "hills",
      L: "hills",
      TL: "forest"
    }
  },
  {
    src: "/hexTiles/five_forest_hills_r120.svg",
    corners: {
      TR: "forest",
      R: "forest",
      BR: "hills",
      BL: "hills",
      L: "hills",
      TL: "hills"
    }
  },
  {
    src: "/hexTiles/five_forest_hills_r180.svg",
    corners: {
      TR: "hills",
      R: "forest",
      BR: "forest",
      BL: "hills",
      L: "hills",
      TL: "hills"
    }
  },
  {
    src: "/hexTiles/five_forest_hills_r240.svg",
    corners: {
      TR: "hills",
      R: "hills",
      BR: "forest",
      BL: "forest",
      L: "hills",
      TL: "hills"
    }
  },
  {
    src: "/hexTiles/five_forest_hills_r300.svg",
    corners: {
      TR: "hills",
      R: "hills",
      BR: "hills",
      BL: "forest",
      L: "forest",
      TL: "hills"
    }
  },
  {
    src: "/hexTiles/five_forest_swamp.svg",
    corners: {
      TR: "swamp",
      R: "swamp",
      BR: "swamp",
      BL: "swamp",
      L: "forest",
      TL: "forest"
    }
  },
  {
    src: "/hexTiles/five_forest_swamp_r060.svg",
    corners: {
      TR: "forest",
      R: "swamp",
      BR: "swamp",
      BL: "swamp",
      L: "swamp",
      TL: "forest"
    }
  },
  {
    src: "/hexTiles/five_forest_swamp_r120.svg",
    corners: {
      TR: "forest",
      R: "forest",
      BR: "swamp",
      BL: "swamp",
      L: "swamp",
      TL: "swamp"
    }
  },
  {
    src: "/hexTiles/five_forest_swamp_r180.svg",
    corners: {
      TR: "swamp",
      R: "forest",
      BR: "forest",
      BL: "swamp",
      L: "swamp",
      TL: "swamp"
    }
  },
  {
    src: "/hexTiles/five_forest_swamp_r240.svg",
    corners: {
      TR: "swamp",
      R: "swamp",
      BR: "forest",
      BL: "forest",
      L: "swamp",
      TL: "swamp"
    }
  },
  {
    src: "/hexTiles/five_forest_swamp_r300.svg",
    corners: {
      TR: "swamp",
      R: "swamp",
      BR: "swamp",
      BL: "forest",
      L: "forest",
      TL: "swamp"
    }
  },
  {
    src: "/hexTiles/five_hills_desert.svg",
    corners: {
      TR: "desert",
      R: "desert",
      BR: "desert",
      BL: "desert",
      L: "hills",
      TL: "hills"
    }
  },
  {
    src: "/hexTiles/five_hills_desert_r060.svg",
    corners: {
      TR: "hills",
      R: "desert",
      BR: "desert",
      BL: "desert",
      L: "desert",
      TL: "hills"
    }
  },
  {
    src: "/hexTiles/five_hills_desert_r120.svg",
    corners: {
      TR: "hills",
      R: "hills",
      BR: "desert",
      BL: "desert",
      L: "desert",
      TL: "desert"
    }
  },
  {
    src: "/hexTiles/five_hills_desert_r180.svg",
    corners: {
      TR: "desert",
      R: "hills",
      BR: "hills",
      BL: "desert",
      L: "desert",
      TL: "desert"
    }
  },
  {
    src: "/hexTiles/five_hills_desert_r240.svg",
    corners: {
      TR: "desert",
      R: "desert",
      BR: "hills",
      BL: "hills",
      L: "desert",
      TL: "desert"
    }
  },
  {
    src: "/hexTiles/five_hills_desert_r300.svg",
    corners: {
      TR: "desert",
      R: "desert",
      BR: "desert",
      BL: "hills",
      L: "hills",
      TL: "desert"
    }
  },
  {
    src: "/hexTiles/five_hills_mountains.svg",
    corners: {
      TR: "mountains",
      R: "mountains",
      BR: "mountains",
      BL: "mountains",
      L: "hills",
      TL: "hills"
    }
  },
  {
    src: "/hexTiles/five_hills_mountains_r060.svg",
    corners: {
      TR: "hills",
      R: "mountains",
      BR: "mountains",
      BL: "mountains",
      L: "mountains",
      TL: "hills"
    }
  },
  {
    src: "/hexTiles/five_hills_mountains_r120.svg",
    corners: {
      TR: "hills",
      R: "hills",
      BR: "mountains",
      BL: "mountains",
      L: "mountains",
      TL: "mountains"
    }
  },
  {
    src: "/hexTiles/five_hills_mountains_r180.svg",
    corners: {
      TR: "mountains",
      R: "hills",
      BR: "hills",
      BL: "mountains",
      L: "mountains",
      TL: "mountains"
    }
  },
  {
    src: "/hexTiles/five_hills_mountains_r240.svg",
    corners: {
      TR: "mountains",
      R: "mountains",
      BR: "hills",
      BL: "hills",
      L: "mountains",
      TL: "mountains"
    }
  },
  {
    src: "/hexTiles/five_hills_mountains_r300.svg",
    corners: {
      TR: "mountains",
      R: "mountains",
      BR: "mountains",
      BL: "hills",
      L: "hills",
      TL: "mountains"
    }
  },
  {
    src: "/hexTiles/five_ocean_coast.svg",
    corners: {
      TR: "coast",
      R: "coast",
      BR: "coast",
      BL: "coast",
      L: "ocean",
      TL: "ocean"
    }
  },
  {
    src: "/hexTiles/five_ocean_coast_r060.svg",
    corners: {
      TR: "ocean",
      R: "coast",
      BR: "coast",
      BL: "coast",
      L: "coast",
      TL: "ocean"
    }
  },
  {
    src: "/hexTiles/five_ocean_coast_r120.svg",
    corners: {
      TR: "ocean",
      R: "ocean",
      BR: "coast",
      BL: "coast",
      L: "coast",
      TL: "coast"
    }
  },
  {
    src: "/hexTiles/five_ocean_coast_r180.svg",
    corners: {
      TR: "coast",
      R: "ocean",
      BR: "ocean",
      BL: "coast",
      L: "coast",
      TL: "coast"
    }
  },
  {
    src: "/hexTiles/five_ocean_coast_r240.svg",
    corners: {
      TR: "coast",
      R: "coast",
      BR: "ocean",
      BL: "ocean",
      L: "coast",
      TL: "coast"
    }
  },
  {
    src: "/hexTiles/five_ocean_coast_r300.svg",
    corners: {
      TR: "coast",
      R: "coast",
      BR: "coast",
      BL: "ocean",
      L: "ocean",
      TL: "coast"
    }
  },
  {
    src: "/hexTiles/five_plains_desert.svg",
    corners: {
      TR: "desert",
      R: "desert",
      BR: "desert",
      BL: "desert",
      L: "plains",
      TL: "plains"
    }
  },
  {
    src: "/hexTiles/five_plains_desert_r060.svg",
    corners: {
      TR: "plains",
      R: "desert",
      BR: "desert",
      BL: "desert",
      L: "desert",
      TL: "plains"
    }
  },
  {
    src: "/hexTiles/five_plains_desert_r120.svg",
    corners: {
      TR: "plains",
      R: "plains",
      BR: "desert",
      BL: "desert",
      L: "desert",
      TL: "desert"
    }
  },
  {
    src: "/hexTiles/five_plains_desert_r180.svg",
    corners: {
      TR: "desert",
      R: "plains",
      BR: "plains",
      BL: "desert",
      L: "desert",
      TL: "desert"
    }
  },
  {
    src: "/hexTiles/five_plains_desert_r240.svg",
    corners: {
      TR: "desert",
      R: "desert",
      BR: "plains",
      BL: "plains",
      L: "desert",
      TL: "desert"
    }
  },
  {
    src: "/hexTiles/five_plains_desert_r300.svg",
    corners: {
      TR: "desert",
      R: "desert",
      BR: "desert",
      BL: "plains",
      L: "plains",
      TL: "desert"
    }
  },
  {
    src: "/hexTiles/five_plains_hills.svg",
    corners: {
      TR: "hills",
      R: "hills",
      BR: "hills",
      BL: "hills",
      L: "plains",
      TL: "plains"
    }
  },
  {
    src: "/hexTiles/five_plains_hills_r060.svg",
    corners: {
      TR: "plains",
      R: "hills",
      BR: "hills",
      BL: "hills",
      L: "hills",
      TL: "plains"
    }
  },
  {
    src: "/hexTiles/five_plains_hills_r120.svg",
    corners: {
      TR: "plains",
      R: "plains",
      BR: "hills",
      BL: "hills",
      L: "hills",
      TL: "hills"
    }
  },
  {
    src: "/hexTiles/five_plains_hills_r180.svg",
    corners: {
      TR: "hills",
      R: "plains",
      BR: "plains",
      BL: "hills",
      L: "hills",
      TL: "hills"
    }
  },
  {
    src: "/hexTiles/five_plains_hills_r240.svg",
    corners: {
      TR: "hills",
      R: "hills",
      BR: "plains",
      BL: "plains",
      L: "hills",
      TL: "hills"
    }
  },
  {
    src: "/hexTiles/five_plains_hills_r300.svg",
    corners: {
      TR: "hills",
      R: "hills",
      BR: "hills",
      BL: "plains",
      L: "plains",
      TL: "hills"
    }
  },
  {
    src: "/hexTiles/five_plains_swamp.svg",
    corners: {
      TR: "swamp",
      R: "swamp",
      BR: "swamp",
      BL: "swamp",
      L: "plains",
      TL: "plains"
    }
  },
  {
    src: "/hexTiles/five_plains_swamp_r060.svg",
    corners: {
      TR: "plains",
      R: "swamp",
      BR: "swamp",
      BL: "swamp",
      L: "swamp",
      TL: "plains"
    }
  },
  {
    src: "/hexTiles/five_plains_swamp_r120.svg",
    corners: {
      TR: "plains",
      R: "plains",
      BR: "swamp",
      BL: "swamp",
      L: "swamp",
      TL: "swamp"
    }
  },
  {
    src: "/hexTiles/five_plains_swamp_r180.svg",
    corners: {
      TR: "swamp",
      R: "plains",
      BR: "plains",
      BL: "swamp",
      L: "swamp",
      TL: "swamp"
    }
  },
  {
    src: "/hexTiles/five_plains_swamp_r240.svg",
    corners: {
      TR: "swamp",
      R: "swamp",
      BR: "plains",
      BL: "plains",
      L: "swamp",
      TL: "swamp"
    }
  },
  {
    src: "/hexTiles/five_plains_swamp_r300.svg",
    corners: {
      TR: "swamp",
      R: "swamp",
      BR: "swamp",
      BL: "plains",
      L: "plains",
      TL: "swamp"
    }
  },
  {
    src: "/hexTiles/five_r060.svg",
    corners: {
      TR: "plains",
      R: "forest",
      BR: "forest",
      BL: "forest",
      L: "forest",
      TL: "plains"
    }
  },
  {
    src: "/hexTiles/five_r120.svg",
    corners: {
      TR: "plains",
      R: "plains",
      BR: "forest",
      BL: "forest",
      L: "forest",
      TL: "forest"
    }
  },
  {
    src: "/hexTiles/five_r180.svg",
    corners: {
      TR: "forest",
      R: "plains",
      BR: "plains",
      BL: "forest",
      L: "forest",
      TL: "forest"
    }
  },
  {
    src: "/hexTiles/five_r240.svg",
    corners: {
      TR: "forest",
      R: "forest",
      BR: "plains",
      BL: "plains",
      L: "forest",
      TL: "forest"
    }
  },
  {
    src: "/hexTiles/five_r300.svg",
    corners: {
      TR: "forest",
      R: "forest",
      BR: "forest",
      BL: "plains",
      L: "plains",
      TL: "forest"
    }
  },
  {
    src: "/hexTiles/four.svg",
    corners: {
      TR: "plains",
      R: "plains",
      BR: "forest",
      BL: "plains",
      L: "plains",
      TL: "plains"
    }
  },
  {
    src: "/hexTiles/four_coast_plains.svg",
    corners: {
      TR: "coast",
      R: "coast",
      BR: "plains",
      BL: "coast",
      L: "coast",
      TL: "coast"
    }
  },
  {
    src: "/hexTiles/four_coast_swamp.svg",
    corners: {
      TR: "coast",
      R: "coast",
      BR: "swamp",
      BL: "coast",
      L: "coast",
      TL: "coast"
    }
  },
  {
    src: "/hexTiles/four_forest_hills.svg",
    corners: {
      TR: "forest",
      R: "forest",
      BR: "hills",
      BL: "forest",
      L: "forest",
      TL: "forest"
    }
  },
  {
    src: "/hexTiles/four_forest_swamp.svg",
    corners: {
      TR: "forest",
      R: "forest",
      BR: "swamp",
      BL: "forest",
      L: "forest",
      TL: "forest"
    }
  },
  {
    src: "/hexTiles/four_hills_desert.svg",
    corners: {
      TR: "hills",
      R: "hills",
      BR: "desert",
      BL: "hills",
      L: "hills",
      TL: "hills"
    }
  },
  {
    src: "/hexTiles/four_hills_mountains.svg",
    corners: {
      TR: "hills",
      R: "hills",
      BR: "mountains",
      BL: "hills",
      L: "hills",
      TL: "hills"
    }
  },
  {
    src: "/hexTiles/four_ocean_coast.svg",
    corners: {
      TR: "ocean",
      R: "ocean",
      BR: "coast",
      BL: "ocean",
      L: "ocean",
      TL: "ocean"
    }
  },
  {
    src: "/hexTiles/four_plains_desert.svg",
    corners: {
      TR: "plains",
      R: "plains",
      BR: "desert",
      BL: "plains",
      L: "plains",
      TL: "plains"
    }
  },
  {
    src: "/hexTiles/four_plains_hills.svg",
    corners: {
      TR: "plains",
      R: "plains",
      BR: "hills",
      BL: "plains",
      L: "plains",
      TL: "plains"
    }
  },
  {
    src: "/hexTiles/four_plains_swamp.svg",
    corners: {
      TR: "plains",
      R: "plains",
      BR: "swamp",
      BL: "plains",
      L: "plains",
      TL: "plains"
    }
  },
  {
    src: "/hexTiles/one.svg",
    corners: {
      TR: "forest",
      R: "forest",
      BR: "plains",
      BL: "plains",
      L: "plains",
      TL: "plains"
    }
  },
  {
    src: "/hexTiles/one_coast_plains.svg",
    corners: {
      TR: "plains",
      R: "plains",
      BR: "coast",
      BL: "coast",
      L: "coast",
      TL: "coast"
    }
  },
  {
    src: "/hexTiles/one_coast_plains_r120.svg",
    corners: {
      TR: "coast",
      R: "coast",
      BR: "plains",
      BL: "plains",
      L: "coast",
      TL: "coast"
    }
  },
  {
    src: "/hexTiles/one_coast_plains_r180.svg",
    corners: {
      TR: "coast",
      R: "coast",
      BR: "coast",
      BL: "plains",
      L: "plains",
      TL: "coast"
    }
  },
  {
    src: "/hexTiles/one_coast_plains_r240.svg",
    corners: {
      TR: "coast",
      R: "coast",
      BR: "coast",
      BL: "coast",
      L: "plains",
      TL: "plains"
    }
  },
  {
    src: "/hexTiles/one_coast_plains_r300.svg",
    corners: {
      TR: "plains",
      R: "coast",
      BR: "coast",
      BL: "coast",
      L: "coast",
      TL: "plains"
    }
  },
  {
    src: "/hexTiles/one_coast_swamp.svg",
    corners: {
      TR: "swamp",
      R: "swamp",
      BR: "coast",
      BL: "coast",
      L: "coast",
      TL: "coast"
    }
  },
  {
    src: "/hexTiles/one_coast_swamp_r120.svg",
    corners: {
      TR: "coast",
      R: "coast",
      BR: "swamp",
      BL: "swamp",
      L: "coast",
      TL: "coast"
    }
  },
  {
    src: "/hexTiles/one_coast_swamp_r180.svg",
    corners: {
      TR: "coast",
      R: "coast",
      BR: "coast",
      BL: "swamp",
      L: "swamp",
      TL: "coast"
    }
  },
  {
    src: "/hexTiles/one_coast_swamp_r240.svg",
    corners: {
      TR: "coast",
      R: "coast",
      BR: "coast",
      BL: "coast",
      L: "swamp",
      TL: "swamp"
    }
  },
  {
    src: "/hexTiles/one_coast_swamp_r300.svg",
    corners: {
      TR: "swamp",
      R: "coast",
      BR: "coast",
      BL: "coast",
      L: "coast",
      TL: "swamp"
    }
  },
  {
    src: "/hexTiles/one_forest_hills.svg",
    corners: {
      TR: "hills",
      R: "hills",
      BR: "forest",
      BL: "forest",
      L: "forest",
      TL: "forest"
    }
  },
  {
    src: "/hexTiles/one_forest_hills_r120.svg",
    corners: {
      TR: "forest",
      R: "forest",
      BR: "hills",
      BL: "hills",
      L: "forest",
      TL: "forest"
    }
  },
  {
    src: "/hexTiles/one_forest_hills_r180.svg",
    corners: {
      TR: "forest",
      R: "forest",
      BR: "forest",
      BL: "hills",
      L: "hills",
      TL: "forest"
    }
  },
  {
    src: "/hexTiles/one_forest_hills_r240.svg",
    corners: {
      TR: "forest",
      R: "forest",
      BR: "forest",
      BL: "forest",
      L: "hills",
      TL: "hills"
    }
  },
  {
    src: "/hexTiles/one_forest_hills_r300.svg",
    corners: {
      TR: "hills",
      R: "forest",
      BR: "forest",
      BL: "forest",
      L: "forest",
      TL: "hills"
    }
  },
  {
    src: "/hexTiles/one_forest_swamp.svg",
    corners: {
      TR: "swamp",
      R: "swamp",
      BR: "forest",
      BL: "forest",
      L: "forest",
      TL: "forest"
    }
  },
  {
    src: "/hexTiles/one_forest_swamp_r120.svg",
    corners: {
      TR: "forest",
      R: "forest",
      BR: "swamp",
      BL: "swamp",
      L: "forest",
      TL: "forest"
    }
  },
  {
    src: "/hexTiles/one_forest_swamp_r180.svg",
    corners: {
      TR: "forest",
      R: "forest",
      BR: "forest",
      BL: "swamp",
      L: "swamp",
      TL: "forest"
    }
  },
  {
    src: "/hexTiles/one_forest_swamp_r240.svg",
    corners: {
      TR: "forest",
      R: "forest",
      BR: "forest",
      BL: "forest",
      L: "swamp",
      TL: "swamp"
    }
  },
  {
    src: "/hexTiles/one_forest_swamp_r300.svg",
    corners: {
      TR: "swamp",
      R: "forest",
      BR: "forest",
      BL: "forest",
      L: "forest",
      TL: "swamp"
    }
  },
  {
    src: "/hexTiles/one_hills_desert.svg",
    corners: {
      TR: "desert",
      R: "desert",
      BR: "hills",
      BL: "hills",
      L: "hills",
      TL: "hills"
    }
  },
  {
    src: "/hexTiles/one_hills_desert_r120.svg",
    corners: {
      TR: "hills",
      R: "hills",
      BR: "desert",
      BL: "desert",
      L: "hills",
      TL: "hills"
    }
  },
  {
    src: "/hexTiles/one_hills_desert_r180.svg",
    corners: {
      TR: "hills",
      R: "hills",
      BR: "hills",
      BL: "desert",
      L: "desert",
      TL: "hills"
    }
  },
  {
    src: "/hexTiles/one_hills_desert_r240.svg",
    corners: {
      TR: "hills",
      R: "hills",
      BR: "hills",
      BL: "hills",
      L: "desert",
      TL: "desert"
    }
  },
  {
    src: "/hexTiles/one_hills_desert_r300.svg",
    corners: {
      TR: "desert",
      R: "hills",
      BR: "hills",
      BL: "hills",
      L: "hills",
      TL: "desert"
    }
  },
  {
    src: "/hexTiles/one_hills_mountains.svg",
    corners: {
      TR: "mountains",
      R: "mountains",
      BR: "hills",
      BL: "hills",
      L: "hills",
      TL: "hills"
    }
  },
  {
    src: "/hexTiles/one_hills_mountains_r120.svg",
    corners: {
      TR: "hills",
      R: "hills",
      BR: "mountains",
      BL: "mountains",
      L: "hills",
      TL: "hills"
    }
  },
  {
    src: "/hexTiles/one_hills_mountains_r180.svg",
    corners: {
      TR: "hills",
      R: "hills",
      BR: "hills",
      BL: "mountains",
      L: "mountains",
      TL: "hills"
    }
  },
  {
    src: "/hexTiles/one_hills_mountains_r240.svg",
    corners: {
      TR: "hills",
      R: "hills",
      BR: "hills",
      BL: "hills",
      L: "mountains",
      TL: "mountains"
    }
  },
  {
    src: "/hexTiles/one_hills_mountains_r300.svg",
    corners: {
      TR: "mountains",
      R: "hills",
      BR: "hills",
      BL: "hills",
      L: "hills",
      TL: "mountains"
    }
  },
  {
    src: "/hexTiles/one_ocean_coast.svg",
    corners: {
      TR: "coast",
      R: "coast",
      BR: "ocean",
      BL: "ocean",
      L: "ocean",
      TL: "ocean"
    }
  },
  {
    src: "/hexTiles/one_ocean_coast_r120.svg",
    corners: {
      TR: "ocean",
      R: "ocean",
      BR: "coast",
      BL: "coast",
      L: "ocean",
      TL: "ocean"
    }
  },
  {
    src: "/hexTiles/one_ocean_coast_r180.svg",
    corners: {
      TR: "ocean",
      R: "ocean",
      BR: "ocean",
      BL: "coast",
      L: "coast",
      TL: "ocean"
    }
  },
  {
    src: "/hexTiles/one_ocean_coast_r240.svg",
    corners: {
      TR: "ocean",
      R: "ocean",
      BR: "ocean",
      BL: "ocean",
      L: "coast",
      TL: "coast"
    }
  },
  {
    src: "/hexTiles/one_ocean_coast_r300.svg",
    corners: {
      TR: "coast",
      R: "ocean",
      BR: "ocean",
      BL: "ocean",
      L: "ocean",
      TL: "coast"
    }
  },
  {
    src: "/hexTiles/one_plains_desert.svg",
    corners: {
      TR: "desert",
      R: "desert",
      BR: "plains",
      BL: "plains",
      L: "plains",
      TL: "plains"
    }
  },
  {
    src: "/hexTiles/one_plains_desert_r120.svg",
    corners: {
      TR: "plains",
      R: "plains",
      BR: "desert",
      BL: "desert",
      L: "plains",
      TL: "plains"
    }
  },
  {
    src: "/hexTiles/one_plains_desert_r180.svg",
    corners: {
      TR: "plains",
      R: "plains",
      BR: "plains",
      BL: "desert",
      L: "desert",
      TL: "plains"
    }
  },
  {
    src: "/hexTiles/one_plains_desert_r240.svg",
    corners: {
      TR: "plains",
      R: "plains",
      BR: "plains",
      BL: "plains",
      L: "desert",
      TL: "desert"
    }
  },
  {
    src: "/hexTiles/one_plains_desert_r300.svg",
    corners: {
      TR: "desert",
      R: "plains",
      BR: "plains",
      BL: "plains",
      L: "plains",
      TL: "desert"
    }
  },
  {
    src: "/hexTiles/one_plains_hills.svg",
    corners: {
      TR: "hills",
      R: "hills",
      BR: "plains",
      BL: "plains",
      L: "plains",
      TL: "plains"
    }
  },
  {
    src: "/hexTiles/one_plains_hills_r120.svg",
    corners: {
      TR: "plains",
      R: "plains",
      BR: "hills",
      BL: "hills",
      L: "plains",
      TL: "plains"
    }
  },
  {
    src: "/hexTiles/one_plains_hills_r180.svg",
    corners: {
      TR: "plains",
      R: "plains",
      BR: "plains",
      BL: "hills",
      L: "hills",
      TL: "plains"
    }
  },
  {
    src: "/hexTiles/one_plains_hills_r240.svg",
    corners: {
      TR: "plains",
      R: "plains",
      BR: "plains",
      BL: "plains",
      L: "hills",
      TL: "hills"
    }
  },
  {
    src: "/hexTiles/one_plains_hills_r300.svg",
    corners: {
      TR: "hills",
      R: "plains",
      BR: "plains",
      BL: "plains",
      L: "plains",
      TL: "hills"
    }
  },
  {
    src: "/hexTiles/one_plains_swamp.svg",
    corners: {
      TR: "swamp",
      R: "swamp",
      BR: "plains",
      BL: "plains",
      L: "plains",
      TL: "plains"
    }
  },
  {
    src: "/hexTiles/one_plains_swamp_r120.svg",
    corners: {
      TR: "plains",
      R: "plains",
      BR: "swamp",
      BL: "swamp",
      L: "plains",
      TL: "plains"
    }
  },
  {
    src: "/hexTiles/one_plains_swamp_r180.svg",
    corners: {
      TR: "plains",
      R: "plains",
      BR: "plains",
      BL: "swamp",
      L: "swamp",
      TL: "plains"
    }
  },
  {
    src: "/hexTiles/one_plains_swamp_r240.svg",
    corners: {
      TR: "plains",
      R: "plains",
      BR: "plains",
      BL: "plains",
      L: "swamp",
      TL: "swamp"
    }
  },
  {
    src: "/hexTiles/one_plains_swamp_r300.svg",
    corners: {
      TR: "swamp",
      R: "plains",
      BR: "plains",
      BL: "plains",
      L: "plains",
      TL: "swamp"
    }
  },
  {
    src: "/hexTiles/one_r120.svg",
    corners: {
      TR: "plains",
      R: "plains",
      BR: "forest",
      BL: "forest",
      L: "plains",
      TL: "plains"
    }
  },
  {
    src: "/hexTiles/one_r180.svg",
    corners: {
      TR: "plains",
      R: "plains",
      BR: "plains",
      BL: "forest",
      L: "forest",
      TL: "plains"
    }
  },
  {
    src: "/hexTiles/one_r240.svg",
    corners: {
      TR: "plains",
      R: "plains",
      BR: "plains",
      BL: "plains",
      L: "forest",
      TL: "forest"
    }
  },
  {
    src: "/hexTiles/one_r300.svg",
    corners: {
      TR: "forest",
      R: "plains",
      BR: "plains",
      BL: "plains",
      L: "plains",
      TL: "forest"
    }
  },
  {
    src: "/hexTiles/six.svg",
    corners: {
      TR: "forest",
      R: "forest",
      BR: "forest",
      BL: "forest",
      L: "forest",
      TL: "plains"
    }
  },
  {
    src: "/hexTiles/six_coast_plains.svg",
    corners: {
      TR: "plains",
      R: "plains",
      BR: "plains",
      BL: "plains",
      L: "plains",
      TL: "coast"
    }
  },
  {
    src: "/hexTiles/six_coast_swamp.svg",
    corners: {
      TR: "swamp",
      R: "swamp",
      BR: "swamp",
      BL: "swamp",
      L: "swamp",
      TL: "coast"
    }
  },
  {
    src: "/hexTiles/six_forest_hills.svg",
    corners: {
      TR: "hills",
      R: "hills",
      BR: "hills",
      BL: "hills",
      L: "hills",
      TL: "forest"
    }
  },
  {
    src: "/hexTiles/six_forest_swamp.svg",
    corners: {
      TR: "swamp",
      R: "swamp",
      BR: "swamp",
      BL: "swamp",
      L: "swamp",
      TL: "forest"
    }
  },
  {
    src: "/hexTiles/six_hills_desert.svg",
    corners: {
      TR: "desert",
      R: "desert",
      BR: "desert",
      BL: "desert",
      L: "desert",
      TL: "hills"
    }
  },
  {
    src: "/hexTiles/six_hills_mountains.svg",
    corners: {
      TR: "mountains",
      R: "mountains",
      BR: "mountains",
      BL: "mountains",
      L: "mountains",
      TL: "hills"
    }
  },
  {
    src: "/hexTiles/six_ocean_coast.svg",
    corners: {
      TR: "coast",
      R: "coast",
      BR: "coast",
      BL: "coast",
      L: "coast",
      TL: "ocean"
    }
  },
  {
    src: "/hexTiles/six_plains_desert.svg",
    corners: {
      TR: "desert",
      R: "desert",
      BR: "desert",
      BL: "desert",
      L: "desert",
      TL: "plains"
    }
  },
  {
    src: "/hexTiles/six_plains_hills.svg",
    corners: {
      TR: "hills",
      R: "hills",
      BR: "hills",
      BL: "hills",
      L: "hills",
      TL: "plains"
    }
  },
  {
    src: "/hexTiles/six_plains_swamp.svg",
    corners: {
      TR: "swamp",
      R: "swamp",
      BR: "swamp",
      BL: "swamp",
      L: "swamp",
      TL: "plains"
    }
  },
  {
    src: "/hexTiles/solid_coast.svg",
    corners: {
      TR: "coast",
      R: "coast",
      BR: "coast",
      BL: "coast",
      L: "coast",
      TL: "coast"
    }
  },
  {
    src: "/hexTiles/solid_desert.svg",
    corners: {
      TR: "desert",
      R: "desert",
      BR: "desert",
      BL: "desert",
      L: "desert",
      TL: "desert"
    }
  },
  {
    src: "/hexTiles/solid_forest.svg",
    corners: {
      TR: "forest",
      R: "forest",
      BR: "forest",
      BL: "forest",
      L: "forest",
      TL: "forest"
    }
  },
  {
    src: "/hexTiles/solid_hills.svg",
    corners: {
      TR: "hills",
      R: "hills",
      BR: "hills",
      BL: "hills",
      L: "hills",
      TL: "hills"
    }
  },
  {
    src: "/hexTiles/solid_mountains.svg",
    corners: {
      TR: "mountains",
      R: "mountains",
      BR: "mountains",
      BL: "mountains",
      L: "mountains",
      TL: "mountains"
    }
  },
  {
    src: "/hexTiles/solid_ocean.svg",
    corners: {
      TR: "ocean",
      R: "ocean",
      BR: "ocean",
      BL: "ocean",
      L: "ocean",
      TL: "ocean"
    }
  },
  {
    src: "/hexTiles/solid_plains.svg",
    corners: {
      TR: "plains",
      R: "plains",
      BR: "plains",
      BL: "plains",
      L: "plains",
      TL: "plains"
    }
  },
  {
    src: "/hexTiles/solid_swamp.svg",
    corners: {
      TR: "swamp",
      R: "swamp",
      BR: "swamp",
      BL: "swamp",
      L: "swamp",
      TL: "swamp"
    }
  },
  {
    src: "/hexTiles/test_transition.svg",
    corners: {
      TR: "plains",
      R: "plains",
      BR: "plains",
      BL: "forest",
      L: "forest",
      TL: "forest"
    }
  },
  {
    src: "/hexTiles/test_transition_coast_plains.svg",
    corners: {
      TR: "coast",
      R: "coast",
      BR: "coast",
      BL: "plains",
      L: "plains",
      TL: "plains"
    }
  },
  {
    src: "/hexTiles/test_transition_coast_plains_r060.svg",
    corners: {
      TR: "plains",
      R: "coast",
      BR: "coast",
      BL: "coast",
      L: "plains",
      TL: "plains"
    }
  },
  {
    src: "/hexTiles/test_transition_coast_plains_r120.svg",
    corners: {
      TR: "plains",
      R: "plains",
      BR: "coast",
      BL: "coast",
      L: "coast",
      TL: "plains"
    }
  },
  {
    src: "/hexTiles/test_transition_coast_plains_r180.svg",
    corners: {
      TR: "plains",
      R: "plains",
      BR: "plains",
      BL: "coast",
      L: "coast",
      TL: "coast"
    }
  },
  {
    src: "/hexTiles/test_transition_coast_plains_r240.svg",
    corners: {
      TR: "coast",
      R: "plains",
      BR: "plains",
      BL: "plains",
      L: "coast",
      TL: "coast"
    }
  },
  {
    src: "/hexTiles/test_transition_coast_plains_r300.svg",
    corners: {
      TR: "coast",
      R: "coast",
      BR: "plains",
      BL: "plains",
      L: "plains",
      TL: "coast"
    }
  },
  {
    src: "/hexTiles/test_transition_coast_swamp.svg",
    corners: {
      TR: "coast",
      R: "coast",
      BR: "coast",
      BL: "swamp",
      L: "swamp",
      TL: "swamp"
    }
  },
  {
    src: "/hexTiles/test_transition_coast_swamp_r060.svg",
    corners: {
      TR: "swamp",
      R: "coast",
      BR: "coast",
      BL: "coast",
      L: "swamp",
      TL: "swamp"
    }
  },
  {
    src: "/hexTiles/test_transition_coast_swamp_r120.svg",
    corners: {
      TR: "swamp",
      R: "swamp",
      BR: "coast",
      BL: "coast",
      L: "coast",
      TL: "swamp"
    }
  },
  {
    src: "/hexTiles/test_transition_coast_swamp_r180.svg",
    corners: {
      TR: "swamp",
      R: "swamp",
      BR: "swamp",
      BL: "coast",
      L: "coast",
      TL: "coast"
    }
  },
  {
    src: "/hexTiles/test_transition_coast_swamp_r240.svg",
    corners: {
      TR: "coast",
      R: "swamp",
      BR: "swamp",
      BL: "swamp",
      L: "coast",
      TL: "coast"
    }
  },
  {
    src: "/hexTiles/test_transition_coast_swamp_r300.svg",
    corners: {
      TR: "coast",
      R: "coast",
      BR: "swamp",
      BL: "swamp",
      L: "swamp",
      TL: "coast"
    }
  },
  {
    src: "/hexTiles/test_transition_forest_hills.svg",
    corners: {
      TR: "forest",
      R: "forest",
      BR: "forest",
      BL: "hills",
      L: "hills",
      TL: "hills"
    }
  },
  {
    src: "/hexTiles/test_transition_forest_hills_r060.svg",
    corners: {
      TR: "hills",
      R: "forest",
      BR: "forest",
      BL: "forest",
      L: "hills",
      TL: "hills"
    }
  },
  {
    src: "/hexTiles/test_transition_forest_hills_r120.svg",
    corners: {
      TR: "hills",
      R: "hills",
      BR: "forest",
      BL: "forest",
      L: "forest",
      TL: "hills"
    }
  },
  {
    src: "/hexTiles/test_transition_forest_hills_r180.svg",
    corners: {
      TR: "hills",
      R: "hills",
      BR: "hills",
      BL: "forest",
      L: "forest",
      TL: "forest"
    }
  },
  {
    src: "/hexTiles/test_transition_forest_hills_r240.svg",
    corners: {
      TR: "forest",
      R: "hills",
      BR: "hills",
      BL: "hills",
      L: "forest",
      TL: "forest"
    }
  },
  {
    src: "/hexTiles/test_transition_forest_hills_r300.svg",
    corners: {
      TR: "forest",
      R: "forest",
      BR: "hills",
      BL: "hills",
      L: "hills",
      TL: "forest"
    }
  },
  {
    src: "/hexTiles/test_transition_forest_swamp.svg",
    corners: {
      TR: "forest",
      R: "forest",
      BR: "forest",
      BL: "swamp",
      L: "swamp",
      TL: "swamp"
    }
  },
  {
    src: "/hexTiles/test_transition_forest_swamp_r060.svg",
    corners: {
      TR: "swamp",
      R: "forest",
      BR: "forest",
      BL: "forest",
      L: "swamp",
      TL: "swamp"
    }
  },
  {
    src: "/hexTiles/test_transition_forest_swamp_r120.svg",
    corners: {
      TR: "swamp",
      R: "swamp",
      BR: "forest",
      BL: "forest",
      L: "forest",
      TL: "swamp"
    }
  },
  {
    src: "/hexTiles/test_transition_forest_swamp_r180.svg",
    corners: {
      TR: "swamp",
      R: "swamp",
      BR: "swamp",
      BL: "forest",
      L: "forest",
      TL: "forest"
    }
  },
  {
    src: "/hexTiles/test_transition_forest_swamp_r240.svg",
    corners: {
      TR: "forest",
      R: "swamp",
      BR: "swamp",
      BL: "swamp",
      L: "forest",
      TL: "forest"
    }
  },
  {
    src: "/hexTiles/test_transition_forest_swamp_r300.svg",
    corners: {
      TR: "forest",
      R: "forest",
      BR: "swamp",
      BL: "swamp",
      L: "swamp",
      TL: "forest"
    }
  },
  {
    src: "/hexTiles/test_transition_hills_desert.svg",
    corners: {
      TR: "hills",
      R: "hills",
      BR: "hills",
      BL: "desert",
      L: "desert",
      TL: "desert"
    }
  },
  {
    src: "/hexTiles/test_transition_hills_desert_r060.svg",
    corners: {
      TR: "desert",
      R: "hills",
      BR: "hills",
      BL: "hills",
      L: "desert",
      TL: "desert"
    }
  },
  {
    src: "/hexTiles/test_transition_hills_desert_r120.svg",
    corners: {
      TR: "desert",
      R: "desert",
      BR: "hills",
      BL: "hills",
      L: "hills",
      TL: "desert"
    }
  },
  {
    src: "/hexTiles/test_transition_hills_desert_r180.svg",
    corners: {
      TR: "desert",
      R: "desert",
      BR: "desert",
      BL: "hills",
      L: "hills",
      TL: "hills"
    }
  },
  {
    src: "/hexTiles/test_transition_hills_desert_r240.svg",
    corners: {
      TR: "hills",
      R: "desert",
      BR: "desert",
      BL: "desert",
      L: "hills",
      TL: "hills"
    }
  },
  {
    src: "/hexTiles/test_transition_hills_desert_r300.svg",
    corners: {
      TR: "hills",
      R: "hills",
      BR: "desert",
      BL: "desert",
      L: "desert",
      TL: "hills"
    }
  },
  {
    src: "/hexTiles/test_transition_hills_mountains.svg",
    corners: {
      TR: "hills",
      R: "hills",
      BR: "hills",
      BL: "mountains",
      L: "mountains",
      TL: "mountains"
    }
  },
  {
    src: "/hexTiles/test_transition_hills_mountains_r060.svg",
    corners: {
      TR: "mountains",
      R: "hills",
      BR: "hills",
      BL: "hills",
      L: "mountains",
      TL: "mountains"
    }
  },
  {
    src: "/hexTiles/test_transition_hills_mountains_r120.svg",
    corners: {
      TR: "mountains",
      R: "mountains",
      BR: "hills",
      BL: "hills",
      L: "hills",
      TL: "mountains"
    }
  },
  {
    src: "/hexTiles/test_transition_hills_mountains_r180.svg",
    corners: {
      TR: "mountains",
      R: "mountains",
      BR: "mountains",
      BL: "hills",
      L: "hills",
      TL: "hills"
    }
  },
  {
    src: "/hexTiles/test_transition_hills_mountains_r240.svg",
    corners: {
      TR: "hills",
      R: "mountains",
      BR: "mountains",
      BL: "mountains",
      L: "hills",
      TL: "hills"
    }
  },
  {
    src: "/hexTiles/test_transition_hills_mountains_r300.svg",
    corners: {
      TR: "hills",
      R: "hills",
      BR: "mountains",
      BL: "mountains",
      L: "mountains",
      TL: "hills"
    }
  },
  {
    src: "/hexTiles/test_transition_ocean_coast.svg",
    corners: {
      TR: "ocean",
      R: "ocean",
      BR: "ocean",
      BL: "coast",
      L: "coast",
      TL: "coast"
    }
  },
  {
    src: "/hexTiles/test_transition_ocean_coast_r060.svg",
    corners: {
      TR: "coast",
      R: "ocean",
      BR: "ocean",
      BL: "ocean",
      L: "coast",
      TL: "coast"
    }
  },
  {
    src: "/hexTiles/test_transition_ocean_coast_r120.svg",
    corners: {
      TR: "coast",
      R: "coast",
      BR: "ocean",
      BL: "ocean",
      L: "ocean",
      TL: "coast"
    }
  },
  {
    src: "/hexTiles/test_transition_ocean_coast_r180.svg",
    corners: {
      TR: "coast",
      R: "coast",
      BR: "coast",
      BL: "ocean",
      L: "ocean",
      TL: "ocean"
    }
  },
  {
    src: "/hexTiles/test_transition_ocean_coast_r240.svg",
    corners: {
      TR: "ocean",
      R: "coast",
      BR: "coast",
      BL: "coast",
      L: "ocean",
      TL: "ocean"
    }
  },
  {
    src: "/hexTiles/test_transition_ocean_coast_r300.svg",
    corners: {
      TR: "ocean",
      R: "ocean",
      BR: "coast",
      BL: "coast",
      L: "coast",
      TL: "ocean"
    }
  },
  {
    src: "/hexTiles/test_transition_plains_desert.svg",
    corners: {
      TR: "plains",
      R: "plains",
      BR: "plains",
      BL: "desert",
      L: "desert",
      TL: "desert"
    }
  },
  {
    src: "/hexTiles/test_transition_plains_desert_r060.svg",
    corners: {
      TR: "desert",
      R: "plains",
      BR: "plains",
      BL: "plains",
      L: "desert",
      TL: "desert"
    }
  },
  {
    src: "/hexTiles/test_transition_plains_desert_r120.svg",
    corners: {
      TR: "desert",
      R: "desert",
      BR: "plains",
      BL: "plains",
      L: "plains",
      TL: "desert"
    }
  },
  {
    src: "/hexTiles/test_transition_plains_desert_r180.svg",
    corners: {
      TR: "desert",
      R: "desert",
      BR: "desert",
      BL: "plains",
      L: "plains",
      TL: "plains"
    }
  },
  {
    src: "/hexTiles/test_transition_plains_desert_r240.svg",
    corners: {
      TR: "plains",
      R: "desert",
      BR: "desert",
      BL: "desert",
      L: "plains",
      TL: "plains"
    }
  },
  {
    src: "/hexTiles/test_transition_plains_desert_r300.svg",
    corners: {
      TR: "plains",
      R: "plains",
      BR: "desert",
      BL: "desert",
      L: "desert",
      TL: "plains"
    }
  },
  {
    src: "/hexTiles/test_transition_plains_hills.svg",
    corners: {
      TR: "plains",
      R: "plains",
      BR: "plains",
      BL: "hills",
      L: "hills",
      TL: "hills"
    }
  },
  {
    src: "/hexTiles/test_transition_plains_hills_r060.svg",
    corners: {
      TR: "hills",
      R: "plains",
      BR: "plains",
      BL: "plains",
      L: "hills",
      TL: "hills"
    }
  },
  {
    src: "/hexTiles/test_transition_plains_hills_r120.svg",
    corners: {
      TR: "hills",
      R: "hills",
      BR: "plains",
      BL: "plains",
      L: "plains",
      TL: "hills"
    }
  },
  {
    src: "/hexTiles/test_transition_plains_hills_r180.svg",
    corners: {
      TR: "hills",
      R: "hills",
      BR: "hills",
      BL: "plains",
      L: "plains",
      TL: "plains"
    }
  },
  {
    src: "/hexTiles/test_transition_plains_hills_r240.svg",
    corners: {
      TR: "plains",
      R: "hills",
      BR: "hills",
      BL: "hills",
      L: "plains",
      TL: "plains"
    }
  },
  {
    src: "/hexTiles/test_transition_plains_hills_r300.svg",
    corners: {
      TR: "plains",
      R: "plains",
      BR: "hills",
      BL: "hills",
      L: "hills",
      TL: "plains"
    }
  },
  {
    src: "/hexTiles/test_transition_plains_swamp.svg",
    corners: {
      TR: "plains",
      R: "plains",
      BR: "plains",
      BL: "swamp",
      L: "swamp",
      TL: "swamp"
    }
  },
  {
    src: "/hexTiles/test_transition_plains_swamp_r060.svg",
    corners: {
      TR: "swamp",
      R: "plains",
      BR: "plains",
      BL: "plains",
      L: "swamp",
      TL: "swamp"
    }
  },
  {
    src: "/hexTiles/test_transition_plains_swamp_r120.svg",
    corners: {
      TR: "swamp",
      R: "swamp",
      BR: "plains",
      BL: "plains",
      L: "plains",
      TL: "swamp"
    }
  },
  {
    src: "/hexTiles/test_transition_plains_swamp_r180.svg",
    corners: {
      TR: "swamp",
      R: "swamp",
      BR: "swamp",
      BL: "plains",
      L: "plains",
      TL: "plains"
    }
  },
  {
    src: "/hexTiles/test_transition_plains_swamp_r240.svg",
    corners: {
      TR: "plains",
      R: "swamp",
      BR: "swamp",
      BL: "swamp",
      L: "plains",
      TL: "plains"
    }
  },
  {
    src: "/hexTiles/test_transition_plains_swamp_r300.svg",
    corners: {
      TR: "plains",
      R: "plains",
      BR: "swamp",
      BL: "swamp",
      L: "swamp",
      TL: "plains"
    }
  },
  {
    src: "/hexTiles/test_transition_r060.svg",
    corners: {
      TR: "forest",
      R: "plains",
      BR: "plains",
      BL: "plains",
      L: "forest",
      TL: "forest"
    }
  },
  {
    src: "/hexTiles/test_transition_r120.svg",
    corners: {
      TR: "forest",
      R: "forest",
      BR: "plains",
      BL: "plains",
      L: "plains",
      TL: "forest"
    }
  },
  {
    src: "/hexTiles/test_transition_r180.svg",
    corners: {
      TR: "forest",
      R: "forest",
      BR: "forest",
      BL: "plains",
      L: "plains",
      TL: "plains"
    }
  },
  {
    src: "/hexTiles/test_transition_r240.svg",
    corners: {
      TR: "plains",
      R: "forest",
      BR: "forest",
      BL: "forest",
      L: "plains",
      TL: "plains"
    }
  },
  {
    src: "/hexTiles/test_transition_r300.svg",
    corners: {
      TR: "plains",
      R: "plains",
      BR: "forest",
      BL: "forest",
      L: "forest",
      TL: "plains"
    }
  },
  {
    src: "/hexTiles/three.svg",
    corners: {
      TR: "plains",
      R: "forest",
      BR: "forest",
      BL: "plains",
      L: "plains",
      TL: "plains"
    }
  },
  {
    src: "/hexTiles/three_coast_plains.svg",
    corners: {
      TR: "coast",
      R: "plains",
      BR: "plains",
      BL: "coast",
      L: "coast",
      TL: "coast"
    }
  },
  {
    src: "/hexTiles/three_coast_swamp.svg",
    corners: {
      TR: "coast",
      R: "swamp",
      BR: "swamp",
      BL: "coast",
      L: "coast",
      TL: "coast"
    }
  },
  {
    src: "/hexTiles/three_forest_hills.svg",
    corners: {
      TR: "forest",
      R: "hills",
      BR: "hills",
      BL: "forest",
      L: "forest",
      TL: "forest"
    }
  },
  {
    src: "/hexTiles/three_forest_swamp.svg",
    corners: {
      TR: "forest",
      R: "swamp",
      BR: "swamp",
      BL: "forest",
      L: "forest",
      TL: "forest"
    }
  },
  {
    src: "/hexTiles/three_hills_desert.svg",
    corners: {
      TR: "hills",
      R: "desert",
      BR: "desert",
      BL: "hills",
      L: "hills",
      TL: "hills"
    }
  },
  {
    src: "/hexTiles/three_hills_mountains.svg",
    corners: {
      TR: "hills",
      R: "mountains",
      BR: "mountains",
      BL: "hills",
      L: "hills",
      TL: "hills"
    }
  },
  {
    src: "/hexTiles/three_ocean_coast.svg",
    corners: {
      TR: "ocean",
      R: "coast",
      BR: "coast",
      BL: "ocean",
      L: "ocean",
      TL: "ocean"
    }
  },
  {
    src: "/hexTiles/three_plains_desert.svg",
    corners: {
      TR: "plains",
      R: "desert",
      BR: "desert",
      BL: "plains",
      L: "plains",
      TL: "plains"
    }
  },
  {
    src: "/hexTiles/three_plains_hills.svg",
    corners: {
      TR: "plains",
      R: "hills",
      BR: "hills",
      BL: "plains",
      L: "plains",
      TL: "plains"
    }
  },
  {
    src: "/hexTiles/three_plains_swamp.svg",
    corners: {
      TR: "plains",
      R: "swamp",
      BR: "swamp",
      BL: "plains",
      L: "plains",
      TL: "plains"
    }
  },
  {
    src: "/hexTiles/two.svg",
    corners: {
      TR: "plains",
      R: "plains",
      BR: "plains",
      BL: "plains",
      L: "plains",
      TL: "plains"
    }
  },
  {
    src: "/hexTiles/two_coast_plains.svg",
    corners: {
      TR: "coast",
      R: "coast",
      BR: "coast",
      BL: "coast",
      L: "coast",
      TL: "coast"
    }
  },
  {
    src: "/hexTiles/two_coast_swamp.svg",
    corners: {
      TR: "coast",
      R: "coast",
      BR: "coast",
      BL: "coast",
      L: "coast",
      TL: "coast"
    }
  },
  {
    src: "/hexTiles/two_forest_hills.svg",
    corners: {
      TR: "forest",
      R: "forest",
      BR: "forest",
      BL: "forest",
      L: "forest",
      TL: "forest"
    }
  },
  {
    src: "/hexTiles/two_forest_swamp.svg",
    corners: {
      TR: "forest",
      R: "forest",
      BR: "forest",
      BL: "forest",
      L: "forest",
      TL: "forest"
    }
  },
  {
    src: "/hexTiles/two_hills_desert.svg",
    corners: {
      TR: "hills",
      R: "hills",
      BR: "hills",
      BL: "hills",
      L: "hills",
      TL: "hills"
    }
  },
  {
    src: "/hexTiles/two_hills_mountains.svg",
    corners: {
      TR: "hills",
      R: "hills",
      BR: "hills",
      BL: "hills",
      L: "hills",
      TL: "hills"
    }
  },
  {
    src: "/hexTiles/two_ocean_coast.svg",
    corners: {
      TR: "ocean",
      R: "ocean",
      BR: "ocean",
      BL: "ocean",
      L: "ocean",
      TL: "ocean"
    }
  },
  {
    src: "/hexTiles/two_plains_desert.svg",
    corners: {
      TR: "plains",
      R: "plains",
      BR: "plains",
      BL: "plains",
      L: "plains",
      TL: "plains"
    }
  },
  {
    src: "/hexTiles/two_plains_hills.svg",
    corners: {
      TR: "plains",
      R: "plains",
      BR: "plains",
      BL: "plains",
      L: "plains",
      TL: "plains"
    }
  },
  {
    src: "/hexTiles/two_plains_swamp.svg",
    corners: {
      TR: "plains",
      R: "plains",
      BR: "plains",
      BL: "plains",
      L: "plains",
      TL: "plains"
    }
  }
]
